src/ununpack/agent/ununpack_globals.h
Newer libmagic versions return a new mimetype application/jar which was not detected so far.
As a result uploaded Jar files were not unpacked.
=> fix detection of jar files on newer distributions

src/nomos/agent/STRINGS.in
In some regexp libraries implementations syntax "... |)" is not valid
and lead to errors similar to shown below:
$ nomossa *.c
Compile failed, regex #1679
regex = "open cascade (technology |)public licen[cs]e"
FATAL nomos_regex.c.49: regcomp failure: empty (sub)expression
$
This was reported few years back in defect #5907 and fixed for
majority of cases in commit 0885a419.
This commit fixes issue re-introduced by commit 8f2a3b9a.
=> Fix non-portable regexp syntax

src/decider/agent_tests/Functional/schedulerTest.php, src/deciderjob/agent_tests/Functional/schedulerTest.php, src/lib/php/Test/TestAbstractDb.php, src/lib/php/libschema.php, src/reuser/agent_tests/Functional/schedulerTest.php, src/www/ui/core-schema.dat
In some circumstances, after a lib-schema update tables and sequences are left in an inconsistent state. See for example issue  #431 
To avoid inconsistencies reset all sequences to the maximum value they have in the referencing column.
=> set sequences current values after a schema update

.gitignore, src/Makefile, src/lib/php/Dao/TreeDao.php, src/lib/php/Dao/UploadDao.php, src/lib/php/Dao/test/TreeDaoTest.php, src/lib/php/Dao/test/UploadDaoTest.php, src/lib/php/Proxy/LicenseViewProxy.php, src/lib/php/Proxy/test/LicenseViewProxyTest.php, src/phpunit.xml, src/spdx2/Makefile, src/spdx2/agent/Makefile, src/spdx2/agent/services.php, src/spdx2/agent/spdx2.php, src/spdx2/agent/template/spdx-document.xml.twig, src/spdx2/agent/template/spdx-file.xml.twig, src/spdx2/agent/template/spdx-package.xml.twig, src/spdx2/agent/version.php.in, src/spdx2/agent_tests/Functional/Makefile, src/spdx2/agent_tests/Functional/SchedulerTestRunner.php, src/spdx2/agent_tests/Functional/SchedulerTestRunnerCli.php, src/spdx2/agent_tests/Functional/fo_report.sql, src/spdx2/agent_tests/Functional/schedulerTest.php, src/spdx2/agent_tests/Makefile, src/spdx2/spdx2.conf, src/spdx2/ui/Makefile, src/spdx2/ui/SpdxTwoAgentPlugin.php, src/spdx2/ui/SpdxTwoGeneratorUi.php, src/www/ui/ajax-showjobs.php
This generates an SPDX v2.0 rdf report.
The SPDXTools-v2.0.0 (http://spdx.org/sites/spdx/files/SPDXTools-v2.0.0.zip) can be used to transform the report into other formats.
The test in spdx2/agent_tests/Functional/schedulerTest.php uses this official tool for verifying one generated rdf report.
=> generate SPDX v2.0 rdf report

src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/list.php
copyright agent Show files without licenses
shows the same content as All option
due to filter typo.
=> copyright filter error correction

src/wget_agent/agent/wget_agent.c
this bug was introduced by myself in the pull request #532
* this solution may cause problems due to word splitting.
* for bash there would be a [better solution](http://stackoverflow.com/questions/17510339/how-can-i-force-bash-to-expand-a-variable-to-pass-it-as-an-argument) using arrays.
=> repair bug, which prevents wildcards from working in wget_agent

src/lib/php/Test/TestLiteDb.php, src/lib/php/tests/test_common_license_file.php
On the vagrant machine the values 
```
$this->logFileName = dirname(dirname(dirname(dirname(dirname(__FILE__))))) . 'db.sqlite.log';
```
get evaluated to **"/vagrantdb.sqlite.log"**, and the corresponding tests fail due to write permission problems.
With this fix they are evaluated to **"/vagrant/db.sqlite.log"** (but i think there is no cleaning mechanism, which would delete this file)
=> repair paths of log-files

install/fossinit.php
* the scheme is equivalent to version 2.6.3.3
* this value is displayed under `/?mod=foconfig`
This pull request is mentioned in #550
update other version strings from `trunk` to `3.0.0`, for example in
* `/VERSION`
* `/VERSIONSTRING`
* `/variable.list`
=> Write correct version of DB-scheme to DB

src/buckets/ui/ui-buckets.php, src/composer.json, src/copyright/ui/CopyrightView.php, src/copyright/ui/EccView.php, src/copyright/ui/Xpview.php, src/copyright/ui/oneshot.php, src/lib/php/Plugin/DefaultPlugin.php, src/lib/php/Plugin/FO_Plugin.php, src/lib/php/Plugin/test/DefaultPluginTest.php, src/lib/php/UI/Component/MicroMenu.php, src/lib/php/common-menu.php, src/lib/php/services.xml.in, src/nomos/ui/agent-nomos-once.php, src/www/ui/ui-browse-license.php, src/www/ui/ui-clearing-view.php, src/www/ui/ui-view-info.php, src/www/ui/ui-view.php
This hopfully makes the micromenu more usable. For example some file viewing plugins do not contain the format part and the order of the items is not the same in all cases.
This PR sets the micromenu `View` to be used for all views showing file contents (e. g. View, Copyright, Audit) and the micromenu `View-Meta` to be used for views showing meta-information of a file.
Currently in the `View` case:
> One-Shot Copyright/Email/URL | One-Shot License   •   Info | View | Audit | Copyright/Email/Url/Author | ECC | Bucket   •   Hex | Text | Formatted   •   Refresh
And in the `View-Meta` case:
> One-Shot Copyright/Email/URL | One-Shot License   •   Info | View | Audit | Copyright/Email/Url/Author | ECC   •   Refresh
Basically, the view settings are missing here.
The menu generating code inside …
=> uniform and fixed micromenu

src/ununpack/agent/traverse.c
extraneous parentheses caused build error when using clang:
https://travis-ci.org/fossology/fossology/jobs/93645065
=> fix(ununpack): remove extraneous parentheses

src/www/ui/core-auth.php, src/www/ui/page/HomePage.php
`$_SERVER['SERVER_PROTOCOL']` does not reliably provide a means for inferring the use of HTTPS. `$_SERVER['HTTPS']` is set on many web servers if HTTPS is being used, so check that first.
This fixes #580
=> [#580] improved protocol inference

src/cli/cp2foss.php, src/cli/fo_bucket_list.php, src/cli/fo_import_licenses.php, src/cli/fo_nomos_license_list.php, src/cli/fo_usergroup.php, src/cli/fossupload_status.php
The usage message from some command line tools print extra spaces at the end, which indents the next prompt. For example:
root@1055d6e47489:/# fo_nomos_license_list -h
Usage: fo_nomos_license_list
-u upload id        :: upload id
-t uploadtree id    :: uploadtree id
-c sysconfdir       :: Specify the directory for the system configuration
--username username :: username
--password password :: password
--container         :: include container or not, 1: yes, 0: no (default)
-x                  :: do not show files which have unuseful license 'No_license_found' or no license
-X excluding        :: Exclude files containing [free text] in the path.
'mac/' should exclude all files in the mac directory.
'mac' and it should exclude all files in any directory containing the substring 'mac'
'/mac' …
=> Remove extra spaces from the end of usage messages

src/delagent/agent/delagent.c, src/delagent/agent/delagent.h, src/delagent/agent/util.c
#271 :: a none permission user can get an upload list via /delagent -f  
#272 :: any user who is not the owner can delete any upload via /delagent -U  :: fixed with only owners and group admins can delete the upload now.
=> ./delagent fixes #271 and #272

src/www/ui/ui-download.php
* use `$filename` and replace all critical chars (__'%'__,__'/'__,__'\\'__) with __'_'__ to create a `$filenameFallback`
* closes #589
=> fix(ui-download): add $filenameFallback solve #589

CONTRIBUTING.md, README.md
makes the following wiki Page obsolete:
- https://github.com/fossology/fossology/wiki/Reporting-bugs
This closes #22
=> feat(CONTRIBUTING.md): create initial CONTRIBUTING.md

src/www/ui/page/UploadSrvPage.php
Just replace array bracket syntax by `array(...)`
this closes #604
=> fix(ui): repair error, which emerges in PHP <= 5.4

src/lib/php/common-auth.php
The `read_permission` function used by command line tools does not sanitize inputs before using them in SQL statements. This change uses the DbManager class instead, passing the inputs as parameters. This does not change any functionality; it only removes this SQL injection vulnerability. Style reflects usage in other parts of the file.
=> fix(security) SQL injection vulnerability in read_permission

src/cli/fossupload_status.php
Currently the usage information is coded but never printed. If --uploadId is not
provided, the error 'no uploadId supplied' is printed and the program exits. With
this change, usage is printed after this error, and also if the --help flag is used.
=> fossupload_status print usage on error or --help

src/www/ui/admin-dashboard.php
Bug introduced in cf2a177f7f731f35e8587bec2e4f1cbe5a251edd. This is breaking the Dashboard page.
Tested on version `3.0.0-167-ge9e4a36`
=> fix(dashboard): missing $this-> in method call

Vagrantfile, src/cli/Makefile, src/cli/fo_monk_license_list.php, src/cli/fo_ninka_license_list.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Dao/test/LicenseDaoTest.php, src/www/ui/template/ui-license-list-form.html.twig, src/www/ui/ui-license-list.php
This PR introduces many new features to the **license-list** UI and CLI.
It now looks like
and grants access to many options which were previously only reachable from the cli, i.e.
* excluding of files using a simple pattern and
* ecluding of subfolders.
One is now also able to choose which agents to include. (Previously only Nomos was used)
For the CLI there were also two new commands `fo_monk_license_list` and `fo_ninka_license_list` introduced (They all could simply be combined to a single command line tool).
All interfaces use a common function `getLicensesPerFileNameForAgentId` in **LicenseDao.php** (Previously there were two different implementations in **fo_nomos_lisense_list.php** and **ui-license-list.php**).
the old implementation took:
```
real    0m9.492s
user    0m0.070s
sys …
```
=> feature(license-list): improve UI and allow more agents

src/composer.lock
Since composer has problems with the dist-download it is falling back to git checkout of speciffic commits which created some, since in the repo https://github.com/symfony/config they have rewritten the history, i.e.
https://github.com/symfony/config/commit/b5063937fab6fdfb7bacc00bc8c0cd7ee0c50070
has become
https://github.com/symfony/config/commit/0ca496cbe208fc37c4cf3415ebb3056e0963115b
See discussion in #649
=> fix(composer): replace hash with correct one

.travis.yml
Some travis tests fail, since there is a call of `apt-get install -qq ...` in the setup, which takes more than 10 minutes but does not generate any output.
This fix splits the command in smaller batches.
--
It could have been enough to split it in two batches. Another solution would be to increase the verbosity level of `apt-get` or increase the timeout.
=> Fix(travis): `apt-get install -qq ...` times out

Makefile.conf, src/lib/php/Dao/JobDao.php, src/lib/php/Dao/ShowJobsDao.php, src/scheduler/agent/database.c, src/www/ui/ajax-showjobs.php, src/www/ui/async/AjaxFileBrowser.php, src/www/ui/scripts/job-queue-poll.js, src/www/ui/showjobs.php, src/www/ui/template/ui-showjobs-jobqueue-row.html.twig
For users without admin permissions the geeky scan details was broken in some cases, i.e. it looked like
visit as read-write user the url
<pre>
http://localhost:8081/repo/?mod=showjobs&<b>upload=-1</b>&job=49
</pre>
for a valid `jobId`.
the hotfix was to remove the part `upload=-1` from the url.
=> Dev/fix showjobs for `&upload=-1` in the url

src/cli/cp2foss.php
Two SQL queries in the cp2foss utility insert variables into the SQL string, which creates an SQL injection vulnerability. This PR converts those queries into prepared statements using DbManager. SELECT * has also been replaced with SELECT <fields> for efficiency.
=> fix(security) cp2foss SQL injection vulnerability

src/phpunit.xml, src/spdx2/agent/Makefile, src/spdx2/agent/spdx2.php, src/spdx2/agent/spdx2utils.php, src/spdx2/agent/template/spdx2tv-file.twig, src/spdx2/agent/template/spdx2tv-package.twig, src/spdx2/agent_tests/Unit/Makefile, src/spdx2/agent_tests/Unit/spdx2utilTest.php
The `OR`s and `AND`s in tag:value were flipped
=> fix(SPDX2): use implodedLicenses in tagValue format

Dockerfile, README.md, docker-entrypoint.sh, install/db/dbcreate.in, install/docker-compose.yml, utils/fo-installdeps
This change adds the posibilitiy to build a Docker Image out of Fossology.
It allows the execution as standalone container (combined database) or
connection against an external database instance as used by the Docker compose setup.
Signed-off-by: Roger Meier <r.meier@siemens.com>
Signed-off-by: Fabio Huser <fabio.huser@siemens.com>
Tested-by: Maximilian Huber <maximilian.huber@tngtech.com>
Tested-by: Pascal Bach <pascal.bach@siemens.com>
=> feat(docker): add Dockerfile and Docker compose setup

src/www/ui/showjobs.php
RW users were not able to see the list of jobs. The code always took the path through the action-permission check and RW did not have permissions for job number `-1`. Since this exited the function, some critical values of `$this->vars` were not set.
=> fix(showjobs): permission test left function to early

install/db/licenseref.sql, src/lib/php/Dao/LicenseDao.php, src/lib/php/Data/License.php, src/spdx2/agent/spdx2.php, src/spdx2/agent/spdx2utils.php, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2-file.xml.twig, src/spdx2/agent/template/spdx2-package.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig, src/spdx2/agent/template/spdx2tv-file.twig, src/spdx2/agent_tests/Functional/schedulerTest.php, src/spdx2/agent_tests/Unit/spdx2utilTest.php, src/www/ui/admin-license-file.php, src/www/ui/core-schema.dat, src/www/ui/template/admin_license-upload_form.html.twig
This is an improve based on the branch "contrib/spdx-license-status" by @shaheemazmalmmd, which was the head for the PR #705.
This substitutes #705, and adds the improvements from https://github.com/siemens/fossology/pull/12.
=> feature(spdx2): allow licenses to be spdx compatible and adapt the templates

src/lib/php/common-sysconfig.php
Creating the Postgres driver inline causes warnings to be logged in PHP7. Storing the object in a variable and passing a reference to that variable fixes this.
Closes #715.
=> Set Postgres driver using variable reference

src/www/ui/admin-dashboard.php
These missing quotes cause this warning to be printed to apache2/error.log whenever the Dashboard page is loaded:
```
==> /var/log/apache2/error.log <==
[Sat Dec 03 05:16:30.994315 2016] [:error] [pid 176] [client 192.168.99.1:51693] PHP Notice:  Use of undefined constant server - assumed 'server' in /usr/local/share/fossology/www/ui/admin-dashboard.php on line 153, referer: https://docker.localhost/?mod=showjobs&allusers=1
```
=> Missing quotes around string literal

src/copyright/agent/regexConfProvider.cc
Fixes issue where a pointer to a local variable is being returned from the `getRegexValue` function, causing an invalid regex to be passed to the copyright agent, triggering an infinite loop and agent crash after memory exhaustion.
Fixes #717
=> fix(copyright): invalid pointer to regex

README.md
The given port in the readme is wrong.
The URL path is not easy to fine, same goes for default user and password.
So this information is updates/addes.
=> Fix docker usage information

src/phpunit-bootstrap.php
Currently all Travis-builds fail,.
As a quickfix, this adds a fallback in `phpunit-bootstrap.php` which might work in all cases.
=> fix(test): phpunit-bootstrap doesn't find Hamcrest

install/fo-apache.conf, install/src-install-apache-example.conf, pbconf/Vagrantfile
Cleaning up the final version of the vagrant test file in pbconf for
testing and developing package builds after it worked for centos7. In
addition fixing configuration for Apache httpd 2.4 and leaving config for 2.2 as comment
for this PR 734 there is now an updated vagrant file which creates a centos7 machine and creates the packages for the same. Currently there are the following open issues with the created packages:
* apache 2.4 config must be adapated [1], which is also covered by this PR 734 
* SELinux setting for the file in /var/cache is wrong
* It would require ninka, otherwise fossology-ninka (and other parts of fossology) will not work. Work around with uninstalling or not installing fossology-ninka
* The time zone must be set for PHP. This is an issue which I have not seen …
=> feat(packaging): vagrant test file and config for httpd 2.4

Vagrantfile, src/lib/php/Dao/AgentDao.php, src/lib/php/Dao/TreeDao.php, src/lib/php/Dao/UserDao.php, src/lib/php/Dao/test/TreeDaoTest.php, src/spdx2/Makefile, src/spdx2/agent/spdx2.php, src/spdx2/agent/spdx2utils.php, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2-file.xml.twig, src/spdx2/agent/template/spdx2-package.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig, src/spdx2/agent/template/spdx2tv-file.twig, src/spdx2/agent/template/spdx2tv-package.twig, src/spdx2/agent_tests/Functional/schedulerTest.php, src/spdx2/agent_tests/Unit/spdx2utilTest.php
This PR fixes the following bugs in spdx2 (in order):
- **only print extracted texts of `LicenseRef-` licenses**
other license texts are given by the SPDX license list
- **in spdx all hashes should be lowercase**
- **only show organization key if not empty**
- **show clearnames of scanners with versions in spdx result**
- **move tag `Releationship` below the package information**
only in tag-value applicable
- **spdx file did not contain scanner findings**
this was a major bug introduced by myself
- **fix bug in template caused by missing if statement**
- **path names should not contain prefix**
in fossology our paths of files look like `example.zip/example/LICENSE` but in the SPDX file one has to strip of the prefix, i.e. only have `example/LICENSE`
there is still the advanced problem of …
=> This PR fixes a list of SPDX compatibility bugs

Dockerfile, Vagrantfile, pbconf/Vagrantfile, pbconf/fossology/deb/rules, pbconf/fossology/rpm/fossology.spec, src/Makefile, utils/fo-installdeps, utils/install_composer.sh
this pull request
- undos the changes to the composer placement introduced in #701
- adds the option to pass the environmental variable `COMPOSER_PHAR` to
`src/Makefile` to allow placing the composer.phar at arbitrary places
- this fixes the source installation, i.e. the documentation was not up
to date
- this fixes the problems with `vagrant up` (see #732)
- this fixes the problems with `docker-compose build`
as discussed in #731
closes #732
=> fix(make): do not place composer at `/tmp/composer/composer`

pbconf/fossology.pb
Use a specific package name corresponding to the real package name for EPEL
instead of a generic one whose verification was then failing.
=> Fix EPEL dependency

.travis.yml
PHPUnit 6.0 is not supported on PHP 5.6
=> (chore)travis php7.1, phpunit5 for php56

install/fossinit.php, src/lib/php/libschema.php
The following warnings are printed during fo-postinstall:
```
PHP Notice:  Only variables should be passed by reference in /usr/local/share/fossology/lib/php/libschema.php on line 1080
PHP Notice:  Only variables should be passed by reference in /usr/local/lib/fossology/fossinit.php on line 135
```
This PR fixes those warnings. Tested on latest commit 37eb354d9d45114700c3801bdaa8348c40aea0f7
=> fix(fo-postinstall): PHP warnings

src/www/ui/search.php
input in search page `File size is ≥` and `File size is ≤` was not checked, if actually numeric
=> fix(search): don't allow SQL injection, check numeric for SizeMin and SizeMax

Dockerfile, install/docker-compose.Dockerfile, install/docker-compose.base.yml, install/docker-compose.docker-entrypoint.sh
The modified Dockerfile did not work with the split-up docker-compose
setup. This moves the "complicated" dockerfile to
`install/docker-compose.Dockerfile` and places the old Dockerfile at the
root level.
TODO: merge these dockerfiles again
=> fix(docker): use a simpler Dockerfile for standalone build

src/spdx2/agent/spdx2.php
All three of these agents use the same spdx2 PHP script. The output format is set as a command line argument. Use this argument to set the agent name. This fixes #785 and has the added bonus of showing all three agents in the enabled agents list (Admin -> Scheduler -> Agents).
=> fix(spdx2): set agent name for spdx2, spdx2tv, dep5

src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig
I can't find any reference to spxd anywhere in the repository, so I'm assuming this is a typo.
=> fix(spdx): typo 'spxd2' in document templates

.editorconfig
This helps the code style of the project. Some text editors automatically set settings based on this file, can be used for linting later
Fixes #794
=> chore(editorconfig): add editorconfig to project

src/www/ui/scripts/change-license-common.js
the user is shown an alert dialog, to prevent useless bulk scans
If there is a better way to inform the user about this error, please let me know
Fixes #641
=> fix(bulk-scan): don't schedule bulk scan, if no license is selected by user

src/lib/php/Application/ObligationCsvExport.php, src/lib/php/Application/ObligationCsvImport.php, src/lib/php/BusinessRules/ObligationMap.php, src/lib/php/Plugin/FO_Plugin.php, src/lib/php/common-db.php, src/lib/php/common-ui.php, src/lib/php/services.xml.in, src/www/ui/admin-obligation-file.php, src/www/ui/core-schema.dat, src/www/ui/page/AdminObligationFromCSV.php, src/www/ui/page/AdminObligationToCSV.php, src/www/ui/template/admin_obligation-upload_form.html.twig, src/www/ui/template/include/macros.html.twig
Create two new tables: **obligation_ref** and **obligation_map**.
The table **obligation_ref** contains the topic and text of the obligations.
The table **obligation_map** maps obligation references to licenses.
The combination of an obligation topic (`ob_topic`) and text (`ob_text`)
must be unique. One obligation can be mapped to several licenses.
The license shortnames are used in the UI, only licenses already
available in the **license_ref** table can be used. The UI uses javascript
code for the license selection, the implementation is based on "select2".
CSV export and import functions are available. The license list
is exported as a string with ";" as separator.
=> First implementation of obligations and risks management

src/delagent/agent/delagent.c, src/delagent/agent/delagent.h, src/delagent/agent/util.c, src/delagent/ui/admin-folder-delete.php, src/lib/php/common-folders.php, src/www/ui/page/AdminContentDelete.php
**Delete child folder from command line.** 
Deletion of child folder use to delete all the reference folders as there was no link to its parent.  now use "-p" to indicate the child folders parent.
Also included https://github.com/fossology/fossology/pull/788 after removing a run-time warning
To reproduce issue:
Create a new Folder with Name "TestFolder"
Upload file (in this example test.zip)
Copy test.zip into TestFolder -> test.zip should now exist in the Software Repository and in the folder TestFolder
Delete TestFolder
Expected Behavior: test.zip still exists in the Software Repository, because it was only copied from there in TestFolder before
Actual Behavior: test.zip is gone from the Software Repository
This commit should fix this issue. Testing from more contributors is still …
=> fix(delagent): delete child folder by parent id

src/lib/php/Application/ObligationCsvExport.php, src/lib/php/Application/ObligationCsvImport.php, src/lib/php/Plugin/FO_Plugin.php, src/lib/php/common-db.php, src/lib/php/common-ui.php, src/www/ui/page/AdminObligationFromCSV.php, src/www/ui/page/AdminObligationToCSV.php, src/www/ui/template/include/macros.html.twig
Use correct copyright year for last changes.
Set filename while exporting the obligations CSV.
Allow obligations with no licenses associated.
=> fix(obligations): reintegrate lost changes

Dockerfile, install/docker-compose.Dockerfile
PHP 7 is not yet supported in Fossology
Debian 9 comes with PHP 7.0.14-2 as default
=> fix(docker): use debian 8.8 for images

src/lib/php/Dao/FolderDao.php, src/lib/php/Dao/test/FolderDaoTest.php, src/reuser/ui/reuser-plugin.php, src/reuser/ui/template/agent_reuser.html.twig, src/reuser/ui/template/agent_reuser.js.twig, src/reuser/ui/template/reuse-folder.html.twig
This PR enabled the search of all uploads to reuse. No need to specify a specific folder anymore, but it's still possible to do so.
<hr />
=> feat(reuse): search all folders

src/copyright/ui/template/copyrighthist.html.twig
jquery 3.2.0 is already included in the compiled html file
=> fix(jquery): remove old version of jquery from copyright-hist

src/buckets/agent/Makefile
building from source fails on debian 9 with GCC - this PR allows the linking to complete
```
$ make
....
make -s -C buckets
make[2]: Entering directory '/mnt/data/code/fossology/src/buckets'
writing VERSION file for buckets
make[3]: Entering directory '/mnt/data/code/fossology/src/buckets/agent'
make[4]: Entering directory '/mnt/data/code/fossology/src/lib/c'
make[4]: Leaving directory '/mnt/data/code/fossology/src/lib/c'
/usr/bin/ld: validate.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: inits.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: liccache.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when …
```
=> fix(chore): fix debian linker error

src/www/ui/admin-license-file.php
`rf_risk` was being added to the `$row` array as a value, not as an index. This causes an `undefined index` error. This PR does not change any behaviour, as the combo box using this value was defaulting to zero.
Fixes #885.
=> fix(www): Undefined index in admin-license-file.php

.travis.yml, src/testing/docker/default-docker-test.sh, src/testing/docker/docker-compose-test.sh
Currently travis does the `make`-step to often. For example when the dockerized setup is tested and the setup on the host can be ignored.
This PR refactors the `.travis.yml` file to improve build times and to prevent tests from failing due to unrelated stuff.
- The tests **.1** to **.3** do no longer do `make`
- The test for PHP 7.1 was added as `allowed-failues` but not as real matrix entry, this was changed => test-.17
- The docker tests now check whether the scheduler is running and responding
=> fix(travis): do not build multiple times

.dockerignore
The problem is that FOSSology looks into `.git` in the make step to get the current version. Without the git folder the agent table looks like:
and FOSSology can not handle agent-changes correctly.
Note: adding the git folder to the docker container **increases the container size dramatically (see https://github.com/fossology/fossology/pull/888)** and the `.git` folder might contain unpublished or confidential information (e.g. the fetched content of a private repository). It would be good to switch to some other way of building the container, e.g.
- use a multistep buildscript, which includes git only in the first run but ecludes it for the second run which does `make install`
- use a more complicated script which
1) builds a base image
2) runs that base image and bind-mounts the source …
=> fix(docker): `.git` should not be excluded via dockerignore

src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig
This PR just changes the versions in the templates. The templates are currently SPDX2.1 compatible.
=> faet(spdx2): bump output version from 2.0 to 2.1

src/spdx2/agent/spdx2utils.php, src/spdx2/agent_tests/Unit/spdx2utilTest.php
When generating an SPDX file, make sure all non-standard licenses conform to the SPDX standard naming convention. This partially solves #855 by ensuring generated files are valid even if (future) checks fail when licenses are created.
This change also flattens the `addPrefixOnDemand` function, as there were a number of unnecessary if/else blocks.
Example sanitizing:
`abc+123` -> `LicenseRef-abc-123`
`to do?` -> `LicenseRef-to-do-`
`this+that_more+` -> `LicenseRef-this-that_more+`
`name.with.dots.` -> `LicenseRef-name.with.dots.`
=> feat(spdx2): strip invalid characters from non-spdx-compatible licenses

src/copyright/ui/CopyrightView.php, src/copyright/ui/HistogramBase.php, src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/email-hist.php, src/copyright/ui/template/emailhist_tables.html.twig, src/copyright/ui/template/histTable.js.twig, src/lib/php/Dao/CopyrightDao.php
This PR adds a new table with deactivated statements to all views of Copyright, the result looks like:
and
To make the `Email/URL/Author` more readable this adds tabs which look like:
(there is a slight css problem, i.e. the `Undo` is black and not blue. That will be fixed by https://github.com/fossology/fossology/pull/904)
=> feat(copyright): also show deactivated copyrights/urls/authors/... in the UI

src/spdx2/agent/spdx2.php, src/spdx2/agent/template/dep5-copyright-document.twig, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig
The generated SPDX reported currently does not contain the optional field `name`, containing the clear name, for extracted license infos.
=> feat(spdx2): add name field to extracted license info

src/lib/php/BusinessRules/ClearingDecisionProcessor.php, src/lib/php/BusinessRules/test/ClearingDecisionProcessorTest.php, src/lib/php/Dao/ClearingDao.php
**To Reproduce Issue:**
-> Install **Master** and upload a package.
-> From file tree view of uploaded component, Click on edit and add a license from any folder.
-> Now remove the added license from the same folder.
-> Removed license still exist in edited license column.
Now repeat the same steps in **contrib/fixRemoveEditLicenseTreeView**
=> fix(treeView): removed license through edit, still exists

debian/rules, install/scripts/php-conf-fix.sh, pbconf/Vagrantfile, pbconf/fossology.pb, pbconf/fossology/deb/changelog, pbconf/fossology/deb/control, pbconf/fossology/deb/copyright, pbconf/fossology/deb/fossology-common.README.Debian, pbconf/fossology/deb/fossology-web.postinst, pbconf/fossology/deb/notes, pbconf/fossology/deb/rules, pbconf/fossology/rpm/fossology.spec, pbconf/pbfilter/debian-9.pbf, pbconf/pbfilter/ubuntu-16.04.pbf, pbconf/pbfilter/ubuntu-16.10.pbf, pbconf/pbfilter/ubuntu-17.04.pbf
- Make packages for the following distributions:
debian 8/9, ubuntu 16.04/16.10/17.04, centos 7 and fedora 25
- Find a compromise around composer using COMPOSER_PHAR variable
- Copy the correct VERSION file in /etc/fossology for spec
- Fix TimeZone computation when links are used
- Adjusting file write attributes for rpm package installation
- Vagrant additions for docker based package building
- Remains to fix: Fedora 26 has a syntax change in dnf makecache (solved
in project-builder.org 0.15.1)
- Fix PHP version usage in install procedure cf #920
Should allow to close #688 and #692 for now (while the composer aspect s far from being ideal)
=> Provides a working build infrastructure

src/www/ui/template/ui-clearing-view_bulk.html.twig
**To Reproduce:**
-> Add a new license or candidate license to fossology database with min 50 characters for shortname.
-> Go to single file view click on bulk recognition.
-> Select license will be out of the box.
=> fix(bulk): separate td for each image and add width for select

src/lib/php/common-container.php
saw the error from the log that the container.php was not accessible and found out that is some installation modes the assigned rights were not sufficient.
Unfortunately the conditions are unclear, because it happened at some time on "some instance". 
It seems to be connected with the generation of the SPDX.
=> fix(lib): container.php access from cache

src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/test/CopyrightDaoTest.php, src/lib/php/Report/XpClearedGetter.php, src/readmeoss/agent/readmeoss.php, src/unifiedreport/agent/unifiedreport.php
Point is that when manually adding a finding by the user in the single file view Web UI on a file where the agent did not find anything ("text finding"), then this finding is not put into the reporting.
These are rare cases, as the usual way is to just correct scanner findings. However, manually added things should be there too.
=> add user findings of copyright and ecc from files with non-agent finding

src/www/ui/template/include/upload.html.twig
- Go to upload from file "Visible for all groups" should be selected as default.
=> feat(upload): set 'visible for all groups' as default for all uploads

src/lib/php/Application/ObligationCsvImport.php, src/www/ui/admin-obligation-file.php
Importing obligations from a CSV file with licenses not available
in the DB leads to a `not-null constrains` Postgres error.
With those changes, the license association first checks for the
availability of the license's shortname before associating the
license with the obligation.
=> CSV import from obligations: improve checks while associating Licenses

src/www/ui/async/AjaxBrowse.php
The browse plugin `ui-browse.php` does not require login to be used, but the
ajax backend `AjaxBrowse.php` required it.
The problem was caused due to the migration of the parent class `FO_Plugin` to
`DefaultPlugin` in the `AjaxBrowse.php`. In `FO_Plugin` is by default no login
required, this logic is flipped in the newer implementation `DefaultPlugin`.
closes #994
=> fix(browse): ajax browse required login

.travis.yml
1.  Removed PHP 5.5 tests as PHP5.5 is no longer supported by PHP Group. [More info](https://secure.php.net/supported-versions.php)
2.  Use phpunit from composer downloads.
3.  Update phpunit version requirements for different PHP version.
4.  Fixed a few typos.
Signed-off-by: Gaurav Mishra <mishra.gaurav@siemens.com>
=> fix(phptestcase): Remove PHP 5.5 test case from travis

src/www/ui/page/UploadSrvPage.php, src/www/ui/template/upload_srv.html.twig
This fix issue #959 
Now the users can change the name of upload manually(optional).
=> fix(uploadSrvPage): Added feature so that users can update the name of upload manually

src/composer.json, src/lib/php/Dao/UploadDao.php, src/reuser/agent/ReuserAgent.php, src/reuser/agent/reuser.php, src/reuser/agent_tests/Functional/schedulerTest.php, src/reuser/ui/agent-reuser.php, src/reuser/ui/reuser-plugin.php
Fixed failing testcases and warnings(phpunit) in reuser for debian OS. 
**ERRORS**
`PHP Notice:  Array to string conversion in /builds/fossology/fossologyng/src/lib/php/Db/Driver/Postgres.php on line 72
dropdb: database removal failed: ERROR:  database "reusersched" is being accessed by other users
DETAIL:  There is 1 other session using the database.
1) Fossology\Reuser\Test\SchedulerTest::testReuserRealScanWithARepoClearingEnhanced
pg_execute(): Query failed: ERROR:  invalid input syntax for integer: "Array"
`
=> fix(reuser): remove warnings and errors with testcases for reuse

src/nomos/agent/STRINGS.in, src/nomos/agent/parse.c, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/UnclassifiedLicense/cygwinRef.txt
Includes files having text "licensed under the term" as unclassified license(example below license text).
/* binmode.c
This file is part of Cygwin.
This software is a copyrighted work licensed under the terms of the
Cygwin license.  Please consult the file "CYGWIN_LICENSE" for
details. */
#include "winlean.h"
#include <sys/fcntl.h>
#include <sys/cygwin.h>
extern int _fmode;
=> feat(nomos): extend unclassified license detection

src/www/ui/admin-license-file.php, src/www/ui/css/fossology.css, src/www/ui/popup-license.php, src/www/ui/template/admin_license-upload_form.html.twig, src/www/ui/template/advice_license-edit.html.twig, src/www/ui/template/popup_license.html.twig, src/www/ui/template/riskLevel_select.js.twig
This feature adds a colour mapping for the risk level of a license in the UI. (See issue https://github.com/fossology/fossology/issues/878)
* When adding or updating a license, the dropdown for the risk level is colour encoded:
* In the license detail view of the license browser the risk level is shown by coloured rectangles:
* The colours can be specified globally in `fossology.css`.
=> feat(ui): Colour mapping for risk level in the ui.

src/www/ui/search.php
This fix issue #985 
It displays the total number of files that match the search criteria 
Also, the message about the UI so that users are not confused why indentation is there in the search results.
=> fix(search.php): Fix the number of files matching the search criteria

src/reuser/agent/ReuserAgent.php
copying the missing events to be consistent on the license identifier state in the reused package.
Issue :
1. upload a package upload-A, 
2. cleared the component upload-A(with bulk),
3. reuse the component for upload-B.
4. In upload-B file decided with Bulk,(after reuse) 
clicking "submit" on those the file, will change the license identifier state.
=> fix(reuser): copy events for reuse

src/unifiedreport/agent/unifiedreport.php
In report sometime main license is appearing twice, and one without any file name in file column.
steps to reproduce : 
1. scan a package, 
2. package should have one file with one license-identifier
3. Select that license-identifier as global license.
4. add a new text for the license identifier.
result : (2 entries in main-license section) 
License text without file name
License text with file name.
=> fix(unifiedreport): Global license appears twice in Main license section

src/decider/agent/BulkReuser.php, src/decider/agent/DeciderAgent.php, src/decider/agent_tests/Functional/SchedulerTestRunnerMock.php, src/decider/agent_tests/Functional/schedulerTest.php, src/decider/ui/DeciderAgentPlugin.php, src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/ShowJobsDao.php, src/www/ui/ajax-showjobs.php, src/www/ui/template/ui-showjobs-jobqueue-row.html.twig
To reproduce:
**Install "Master" :** 
- Upload a package (with at least 3 licenses as scanner findings in each file) and Goto single file view.
**Note: I have used fckeditor** 
- Using bulk recognition add license1 and remove license2 and license3.
- Using bulk recognition add license2 and remove license1 and license3.
- Using bulk recognition add license3 and remove license1 and license2.
- Now upload some other version of the package you have uploaded previously.  
- And reuse the bulk decisions. Check the decisions are improper, Because of timestamp.
**Install "contrib/fixBulkOrderingByETA" :**
- Now upload the same package with improper decisions.
- Reuse it with the first package. Now the results should be proper.
=> fix(monkbulk): check the job status when scheduling multiple monkbulks

src/lib/php/Dao/FolderDao.php, src/www/ui/async/AjaxFolderContents.php, src/www/ui/template/admin_content_delete.html.twig, src/www/ui/template/admin_content_move.js.twig
Made a change in query to select every upload on which ununpack agent and adj2nest has finished (which includes zip and non-zip uploads).
**How to test:**
Check #993 
**Additional features:**
1.  Print a message while browsing empty folder in Organize->Uploads->Delete Uploaded File.
2.  Disable the Delete button if a folder is empty.
**How to test:**
1.  Create a new directory.
2.  Goto Organize->Uploads->Delete Uploaded File.
3.  Browse to newly created directory.
4.  A message _"No removable content found"_ should appear instead of empty list.
5.  The Delete button should get disabled.
Closes #993
=> fix(nonzipUpload): Fixed the query to select every upload

README.md
Changed the Travis build status image to show build status of **master** branch only avoiding status of pull requests in README.md.
=> docs(README): Show only master build status

src/www/ui/page/UploadSrvPage.php, src/www/ui/template/upload_srv.html.twig, src/www/ui/template/upload_srv.js.twig
>  Enhancement over #1048
1.  Check if the upload path contains a wild-char and warn the user right-away.
2.  Check for the wild-char at server-side as well.
3.  Prevent unlikely names in uploads and escape special characters.
1.  Goto Upload -> From Server
2.  Enter an file path with the wildchar.
3.  Do not fill the name field for the upload.
4.  The optional name field should become required and user should not be able submit the form.
5.  Repeat the steps above with JavaScript disabled in the browser.
6.  The form can now be submitted but the user must see the server side error if the name is not provided for the upload.
=> feat(serverUpload): Check for wildchar during upload

src/lib/php/Dao/UploadPermissionDao.php
Get Distinct of group id for "visible to all groups" via upload-file. Which was throwing the below error for duplicates.
`[Mon Mar 26 05:37:57.272706 2018] [:error] [pid 10860] [client 10.0.2.2:57156] PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: Fossology\Lib\Dao\UploadPermissionDao::makeAccessibleToAllGroupsOf.insert: INSERT INTO perm_upload (perm, upload_fk, group_fk) SELECT $1 perm, $2 upload_fk, gum.group_fk FROM group_user_member gum LEFT JOIN perm_upload ON perm_upload.group_fk=gum.group_fk AND upload_fk=$2 WHERE perm_upload IS NULL AND gum.user_fk=$3 -- -- Array\n(\n    [0] => 10\n    [1] => 11875\n    [2] => 2\n)\n\n\nERROR:  duplicate key value violates unique constraint "perm_upload_upload_fk_group_fk_key"\nDETAIL:  Key …
=> fix(upload-file): get distinct of groupid to insert in perm upload table

src/www/ui/admin-license-file.php, src/www/ui/template/admin_license-upload_form.html.twig
Steps to test.
User unable to update the license fields from License Administration.
Eg : Updating Risk, is giving error.
This PR fixes the above issue, and user should be able to update the require fields except the license shortname(unique).
=> fix(licenseUpdate): update the license parameters with same shortname

debian/control, install/defconf/fossology.conf.in, install/defconf/samplefooter.txt, install/defconf/sampleheader.txt, src/lib/php/common-sysconfig.php, src/scheduler/agent/Makefile, src/scheduler/agent/database.c, src/scheduler/agent/emailformatter.c, src/scheduler/agent/emailformatter.h, src/scheduler/agent/sqlstatements.h, src/www/ui/admin-config.php, src/www/ui/core-schema.dat, utils/fo-installdeps
**Prerequisite:**
1.  Install heirloom-mailx (BSD mail client, formally known as "nail").
`sudo apt-get install heirloom-mailx`
**Enhancement:**
1.  New AGENTSTATUS macro for list of passed or failed agents.
2.  Complete path of the folder where the package is uploaded.
pls see also: https://github.com/fossology/fossology/wiki/Email-notification-configuration
=> feat(email): Added support for agent status in email

install/scripts/install-json-hpp.sh
Referring to suggestion in #1002.
1.  Updated the version of nlohmann/json from 2.1.1 to 3.1.2 because of several fixes in the library.
=> feat(copyright): New JSON hpp version

src/delagent/agent/util.c
Removed extra drop statements as the temp table is already dropped 4 statements before.
Closes #368
! Merge after #1097
=> fix(delagent): Extra drop statements in test

src/lib/php/common-sysconfig.php, src/scheduler/agent/database.c, src/scheduler/agent/database.h, src/scheduler/agent/job.c, src/scheduler/agent/logging.h, src/scheduler/agent/scheduler.h
1. Check if SMTP variable is set, then only send email otherwise print a notice in log.
2. Separate function to get command (readability, traceability).
3. Check email client's return code.
4. Safe clear for PQresult (SafePQclear) which checks
1. Result is not NULL
2. Clean it
3. Set result to NULL to prevent double-clear
=> fix(email): Prevent scheduler crashes

install/db/licenseref.sql
**License text added for below licenses :**
- 0BSD
- BSD-1-Clause
- MIT-advertising
- MIT-enna
- MIT-feh,
- MITNFA
- mpich2
- MTLL
- Mup
- RSA-Cryptoki
closes #1083
=> feat(licenses): add license test to licenseref.sql from SPDX

src/copyright/agent/database.cc
Improve the query in `queryFileIdsForUpload` function.
Improve the query in `queryFileIdsForUpload` function by dropping additional `agent_fk` check as they are already filtered out during the join.
1.  Upload a huge package (more than 50,000 files) on an existing instance.
1.  The copyright agent will be killed by scheduler due to no heart beat.
1.  Install the branch and upload same package.
1.  The copyright agent will pass as the query time will be reduced.
=> perf(copyright): Improve query for pfile on upload

src/pkgagent/agent/Makefile, src/pkgagent/agent/main.c, src/pkgagent/agent/pkgagent.c, src/pkgagent/agent_tests/Unit/Makefile, src/pkgagent/agent_tests/Unit/testGetMetadata.c
Fix for #1007 . Building fails on Fedora 27 because RPM >= 4.14 has removed the RPM 4.4.x API compatibility.
Used the following defines from the removed rpmlegacy.h:
```
#define headerSprintf(_h, _fmt, _tbltags, _exts, _emsg) \
headerFormat((_h), (_fmt), (_emsg))
#define	tagName		rpmTagGetName
```
edit: Dropped support for RPM 4.4.x and RHEL/CentOS 5.
Compile on Fedora 27.
Should we remove the legacy RPM 4.4.x stuff? RHEL/CentOS 5 are the remaining users of RPM 4.4.x but RHEL is in the Extended Life-cycle Support and CentOS 5 is now EOL.
=> fix(pkgagent): Added support for RPM >= 4.14

src/copyright/ui/template/histTable.js.twig, src/www/ui/scripts/browse.js, src/www/ui/template/browse_file.js.twig, src/www/ui/template/file-browse.js.twig, src/www/ui/template/ui-browse.js.twig, src/www/ui/template/ui-clearing-view.js.twig, src/www/ui/template/ui-job-show.js.twig
Made changes in data table objects after changing datatables from V1.9 to V1.10 in #832
As per [data tables upgrade guide](https://datatables.net/upgrade/1.10-convert)
1.  Removed `sCookiePrefix` parameter as data tables use local cache.
2.  Updated `fnGetData(this)` to `cell(this).data()`.
3.  Updated `fnDraw()` to `draw()`.
4.  Use new object from `DataTable` instead of `dataTable`.
1.  Install current master
1.  Drop-downs in ui-browse does not work
1.  You can not change priorities
1.  Install the fix
*  They should work.
It is recommended to use `DataTable` instead of `dataTable` to use new API. But this new API is not usable by [jquery.dataTables.editable.js](https://github.com/fossology/fossology/blob/master/src/www/ui/scripts/jquery.dataTables.editable.js).
=> fix(dataTables): Update datatable objects to 1.10

src/copyright/agent/copyright.conf
Also Weird copyright statements should be matched in full
Changed regex in copyright.conf
If a copyright statement is there like
Copyright(c) 2018 Michael C. Jaeger
then it is matched by FOSSology like
(c) 2018 Michael C. Jaeger
because a space is missing before the bracket. users apparently find this confusing. it should be the copyright statement in full.
closes #1133
=> fix(copyright): match copyright statements in full

utils/fo-installdeps
Drop support for the following End-of-Life distributions:
| Distribution | Codename | End-of-Life date |
| --- | --- | --- |
| Debian 5 | Lenny | February 2012 |
| Debian 6 | Squeeze | February 2016 |
| Debian 7 | Wheezy | May 2018 |
| Fedora 8 | Werwolf | January 2009 |
| Fedora 9 | Sulphur | July 2009 |
| Fedora 10 | Cambridge | December 2009 |
| Fedora 11 | Leonidas | June 2010 |
| Fedora 12 | Constantine | December 2010 |
| Linux Mint 9 | Isadora | April 2013 |
| Mandriva | * | Dead |
| Ubuntu 8.04 LTS | Hardy Heron | May 2013 |
| Ubuntu 10.04 LTS | Lucid Lynx | April 2015 |
| Ubuntu 11.04 | Natty Narwhal | Octocber 2012 |
| Ubuntu 11.10 | Oneiric Ocelot | May 2013 |
| Ubuntu 12.04 LTS | Precise Pangolin | April 2017 |
| Ubuntu 12.10 | Quantal Quetzal | May 2014 |
| Ubuntu 13.04 | …
=> feat(fo-installdeps): Drop support for End-of-Life distributions.

src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php
The test test_proxy_ftp is flaky, because there are some issues with ftp and required sudo on travis. Since the essential part of the test is already commented out, we should ignore it until there exists a solution for travis.
fix(wget_agent): Ignore test_proxy_ftp, because it is flaky on travis.
fix(wget_agent): Clean up the database only if it is necessary.
=> fix(wget_agent): Ignore test_proxy_ftp, because it is flaky on travis.

src/wget_agent/agent/wget_agent.c, src/wget_agent/agent/wget_agent.h
If the agent fail, generate new parameters with masked password before adding to log.
1.  New function to mask password in parameters.
2.  Generate command in new function `GetVersionControlCommand()`.
1.  Upload a package from version control.
1.  With wrong URL/password.
2.  With wrong URL (no username and password).
2.  Check the log of failed agent.
3.  Log should not contain password.
Closes #540
=> feat(wget_agent): Mask password in log

src/scheduler/agent/defconf/init.d/fossology.in
Signed-off-by: Steve Winslow <swinslow@gmail.com>
Fixes #1171 
This makes the init script for the scheduler agent wait for PostgreSQL to start up.
In the init script, 'postgresql' was added to the Required-Start: and Required-Stop: header lines.
Please note that I have tested this in production, when using the Debian packages for 3.3.0, by manually making this change to `/etc/init.d/fossology`. I've confirmed that this appears to fix the recurring problem in #1171 where the scheduler would fail to start, due to the unavailability of the PostgreSQL database during boot-up.
I have not rebuilt the packages with the change made in this PR, so someone who is familiar with the packages may of course want to do so.
=> fix(scheduler): make init script wait for postgresql on startup

src/www/ui/core-schema.dat
The next value for `nomos_ars_ars_pk_seq` sequence resets at every install to `bucket_ars` instead of `ars_master`. This creates issue while inserting new values in ars child tables.
Fixed the **UPDATE** query for `nomos_ars_ars_pk_seq` sequence.
1.  Install on an existing server and upload a new package.
1.  The ars entries of new scans should be in sequence.
1.  Also, no UNIQUE key conflicts should occur while writing to ARS tables.
Closes #1134
=> fix(ars_seq): Reset ars sequence to ars_master

install/db/dbmigrate_multiple_copyright_decisions.php, src/lib/php/Dao/CopyrightDao.php, src/www/ui/core-schema.dat
Change `ecc_decision` schema to match other Copyright derived tables.
Change column `copyright_decision_pk` => `ecc_decision_pk` in `ecc_decision` table.
1. Open `ecc-view` of a file, no error should be thrown.
1. Make a new ECC decision on a file, no error should be thrown.
Closes #1191
=> fix(ecc-view): Update ecc_decision table to match other schema

src/delagent/mod_deps, src/mimetype/mod_deps, src/pkgagent/mod_deps, src/scheduler/mod_deps, src/ununpack/mod_deps, src/wget_agent/mod_deps, utils/fo-installdeps, utils/prepare-test
fix(fo-installdeps): Allow running without the option '-y'.
fix(fo-installdeps): Install everything on '-y'.
* Run `./utils/fo-installdeps` and check that build and runtime dependencies are installed.
* Run `./utils/fo-installdeps -y` and check that build and runtime dependencies are installed.
Thanks to @GMishx for pointing out this issue.
edit: It resolves #1188.
=> fix(fo-installdeps): Allow running without the option '-y'.

utils/fo-installdeps
* On Trusty and Jessie mbstring is compiled into PHP.
* On Stretch mbstring is a dependency of php-gettext.
But on Xenial it is not compiled into PHP and it is not a dependency of any installed package.
Run the following commands on a fresh Xenial and check that no error occurs:
```
$ cd src
$ composer install
```
Resolves #1186.
=> fix(xenial): Added the missing runtime dependency php7.0-mbstring.

utils/fo-installdeps
Add the missing runtime dependency of boost.
Add the missing boost regex and program options runtime dependencies.
- Install compiled FOSSology on a fresh instance.
- Run `./utils/fo-installdeps -r -y`.
On master, copyright (and sub-agents) fails due to missing boost packages.
Install the fix and run the script again, the issue should be fixed.
Fix #1175
=> fix(deps): Add boost runtime dependency

install/fo-postinstall.in
While installing from Debian packages, the build tends to fail due to incorrect man pages path.
1. Fix the man pages path.
Check #1194
Closes #1194
=> fix(postinstall): Look for compressed man pages

.travis.yml
* Switched the jobs "Syntax Check", "Static Code Analysis" and "Copy/Paste Detector" to sudoless.
Closes #1205
=> fix(travis): Missing phppcd on travis.

src/monk/agent/Makefile, src/monk/agent/cli.c, src/monk/agent/cli.h, src/monk/agent/common.c, src/monk/agent/monk.c, src/monk/agent/monk.h, src/monk/agent/scheduler.c, src/monk/agent/scheduler.h, src/monk/agent/serialize.c, src/monk/agent/serialize.h, src/monk/agent_tests/Functional/cliTest.php, src/monk/agent_tests/Unit/Makefile, src/monk/agent_tests/Unit/run_tests.c, src/monk/agent_tests/Unit/test_serialize.c
For the command line usage of monk, one has to provide the license knowledgebase in some way. Usually this is done by connecting the monk application directly to the fossology database and pulling the licenses from there.
For a lightweight setup this is problematic, since one wants to have as little overhead and dependencies as possible.
For that this PR creates the possibility to serialize the knowledgebase using the monk cli tool. The created file can be used to run monk standalone.
(e.g. in the vagrant vm)
```
$ ./src/monk/agent/monk -s /tmp/monk.knowledgebase
Write knowledgebase to /tmp/monk.knowledgebase
$ sudo /etc/init.d/postgresql stop
* Stopping PostgreSQL 9.3 database server
$ ./src/monk/agent/monk -k /tmp/monk.knowledgebase LICENSE
found diff match between "LICENSE" and …
```
=> feat(monk): allow monk to run standalone

install/db/dbmigrate_copyright-author.php, install/db/resequence_author_table.php, src/copyright/agent/database.cc, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/test/CopyrightDaoTest.php, src/lib/php/Proxy/UploadTreeProxy.php, src/lib/php/Test/testdata.sql, src/www/ui/core-schema.dat
Replace ct_pk with table_pk for all copyright sub-agents
Change `ct_pk` to `tablename_pk`.
edit , delete operations with existing and new uploads.
=> fix(copyright): replace ct_pk with table_pk for all copyright sub-agents

src/copyright/agent/database.cc
The query to fetch pfiles for scanning was taking longer than usual in huge (>40 GB) databases resulting in agent kill due to no heart beat (>10 minutes).
This PR uses prepared statements to fetch the pfiles for scanning.
This result in execution time reduction from 18.691 ms to 5.969 ms (on developer DB of size 29 MB).
Use prepared statements to fetch the pfiles for scanning.
Test on existing FOSSology instances with database > 30 GB. There should be performance improvement in Copyright, ECC and Keyword agents.
=> perf(copyright): Use prepared statements to fetch pfiles

src/cli/fo_monk_license_list.php, src/cli/fo_ninka_license_list.php, src/cli/fo_nomos_license_list.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Dao/test/LicenseDaoTest.php, src/www/ui/ui-license-list.php
If one uses the license-list page, many lines of the following form are generated in the `error.log` of apache:
```
[Fri Aug 24 09:51:01.983633 2018] [:error] [pid 300] [client 10.0.2.2:42804] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/share/fossology/www/ui/ui-license-list.php on line 142, referer: http://localhost:8081/repo/?mod=browse&upload=2&item=2
[Fri Aug 24 09:51:01.983680 2018] [:error] [pid 300] [client 10.0.2.2:42804] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/share/fossology/www/ui/ui-license-list.php on line 142, referer: http://localhost:8081/repo/?mod=browse&upload=2&item=2
[Fri Aug 24 09:51:01.983684 2018] [:error] [pid 300] [client 10.0.2.2:42804] PHP Warning:  Invalid argument supplied for foreach() in …
```
=> fix(license-list): fix handling of getLicensesPerFileNameForAgentId result

Dockerfile
Using slim variant of Debian Jessie to reduce the Docker image size
| [Current size](https://hub.docker.com/r/fossology/fossology/tags/) | [Slim size](https://hub.docker.com/r/gmishx/fossology/tags/) |
| --- | --- |
| ![normal](https://user-images.githubusercontent.com/18077542/43075645-fb49c146-8e9e-11e8-89c3-45c8f9e2f113.png) | ![slim](https://user-images.githubusercontent.com/18077542/43075646-fb74c74c-8e9e-11e8-8006-6514d838afc0.png) |
-  Changed the image label from `debian:8.8` to `debian:jessie-slim` to use the slim variant.
-  The slim variant don't have the man pages, so creating
-  /usr/share/man/man1
-  /usr/share/man/man7
1.  Pull latest docker image, check the image size
```bash
docker pull fossology/fossology:latest
docker image ls
```
2.  Build the new image, check the …
=> perf(Docker): Use Debian Jessie slim variant

.travis.yml, src/cli/tests/test_fo_copyright_list.php, src/composer.json, src/composer.lock, src/nomos/agent_tests/Functional/tests.xml, src/phpunit.xml
The PHP 7.2 tests on travis-ci pass.
* Added support for PHPUnit 6.
* Switched to PHPUnit 6 for PHP 7.1 and PHP 7.2.
* PHP 7.1 and 7.2 tests have to pass.
* Added necessary php extensions to composer.json.
* Added validation step for composer.json in travis-ci.
* Locked some development dependencies for backward compatibility.
* Updated symfony for PHP 7.2 compatibility.
Please check that fossology is working properly because symfony was upgraded.
Fixed #1182.
=> Improved PHP 7.2 Support

install/db/dbmigrate_3.3-3.4.php, install/db/resequence_author_table.php, install/fossinit.php, src/www/ui/core-schema.dat
After renaming the primary column names of `copyright`, `author`, `ecc` and `keyword` table, the migration script was failing.
Check the copyright and author table column name from DB before resequencing the tables.
Also check for tables before applying new constraints (which does not exists in previous versions).
Install fossology and run post install script on existing old setup.
```bash
$ sudo make install
$ sudo install/fo-postinstall
```
Closes #1227
Closes #1209
=> fix(resequence): Check the column name from DB

docker-compose.yml
There are issues with postgresql versions >= 10.
Inspect the logs of `$ docker-compose up` and open the dashboard.
Fixes #1229
=> fix(postgresql): Fixed postgresql version to 9.6 and use a volume for its data.

src/www/ui/admin-dashboard.php
* removed STRCMP and added normal comparison method for PSQL comparison
* removed STRCMP and added normal comparison method for PSQL comparison
Install fossology on machines with different versions of POSTGRESQL and check the dashboard
closes #1229
=> fix(dashboard): change comparison statements for postgres version

debian/control, debian/fossology-web.postinst, debian/rules, utils/fo-installdeps
Added missing php7.2 dependencies for Ubuntu Bionic.
Build debian packages in Ubuntu Bionic (18.04) and install them.
`dpkg-buildpackage -I`
=> fix(debian): Add php7.2 dependencies for Ubuntu Bionic

utils/fo-installdeps
Use find's `execdir` instead of `xargs` to run interactive child shell.
Remove `xarg` from and replace with `execdir`.
1. Run the `sudo utils/fo-installdeps` on fresh machine, the `mod_deps` in agent dirs will not wait for input for `apt-get`.
1. Pull the branch and run `sudo utils/fo-installdeps` on fresh machine, the `mod_deps` will wait for input for `apt-get`.
Fixes #1239
=> fix(installdeps): Run child terminals interactively

src/lib/php/common-agents.php, src/lib/php/common-job.php, src/www/ui/async/ScheduleAgent.php
Earlier, failed agents were not shown under "**Schedule an Analysis**" for a given upload until the agent version changes.
Added new parameter to function `LatestAgentpk` to get only successful results.
On latest master:
1. Upload a package and kill/cancel some running agents to mark them as failed.
1. Go to Jobs » Schedule Agents.
1. The killed agents are not shown for re-scheduling.
Install the branch:
1. Upload a package and kill/cancel some running agents to mark them as failed.
1. Go to Jobs » Schedule Agents.
1. The killed agents will be shown for re-scheduling.
=> fix(agent): Reschedule failed agents

README.md
This PR adds the CII Best Practices badge and drops the unused waffle.io badge
=> chore(README): add best practices badge

src/monk/agent_tests/Functional/cliTest.php
There were some unwanted print in PHP-unit test cases.
Removed unwanted `echo` statement in Monk test cases.
Run phpunit test cases for monk.
`cd src/monk/agent_tests/Functional/ && make test`
No extra print statements should occur.
=> test(monk): Remove unwanted echo from test script

src/lib/php/libschema.php
Remove schema name (public) from definition generated by PostgreSQL to match the definition in `core-schema.dat`
Remove the `"public."` schema (default schema) from definitions generated by PostgreSQL >= 9.
Check #1262
Closes #1262
=> fix(libschema): Remove schema to match PHP strings

src/nomos/agent/CHECKSTR, src/nomos/agent/GENSEARCHDATA, src/nomos/agent/PRECHECK, src/nomos/agent/STRINGS.in, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
After merging #1118, separators in `STRINGS.in` were changed from tab to space.
This resulted in missing checks from `PRECHECK` and `CHECKSTR`.
([Old log](https://travis-ci.org/fossology/fossology/jobs/404417533#L1624) => [Latest master log](https://travis-ci.org/fossology/fossology/jobs/459532025#L1313))
1. Use space as a separator in `PRECHECK` and `GENSEARCHDATA` instead of a tab.
1. Also replace remaining tabs with space in `STRINGS.in`.
Check the new travis log for `PRECHECK`s. (https://travis-ci.org/fossology/fossology/jobs/477241832#L1327)
Maybe [the wiki](https://github.com/fossology/fossology/wiki/Nomos#step-1-add-the-new-signature---stringsin) can also be updated.
=> fix(nomos): Use space as separator

src/scheduler/agent/database.c
After executing the delagent and maintenance agent  the scheduler will crash.
Check the results of the query in case of empty rows.
* Login with fossy user and Upload a package.
* Go to Organize -> Uploads -> Delete uploaded file.
* Delete the uploaded file. and upload a new file.
* Check if the scheduler is running properly through Admin -> Scheduler.
=> fix(scheduler): add check for empty results from query

src/www/ui/template/browse_file.js.twig, src/www/ui/template/include/foot.html.twig
Update the Select2 drop-down whenever the data table is updated in License Browser.
Use the `fnDrawCallback` option of datatable to redraw select2 whenever datatable is drawn.
Check the issue.
Closes #1275
=> fix(filter): Update the filter in license browser

src/nomos/agent/STRINGS.in, src/nomos/agent/parse.c, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/EPL/epl1-pom.xml
Eclipse Public License - v 1.0 was not detected in some cases.
1. Added new entry `_LT_EPL`, `_TITLE_EPL10ref_1` and `_TITLE_EPL20ref_1`.
1. `_LT_EPL` will look for EPL string.
1. `_TITLE_EPL10ref_1` and `_TITLE_EPL20ref_1` will distinguish between versions.
Put the following text in a file and scan using nomos:
```
<licenses>
<license>
<name>Eclipse Public License - v 1.0</name>
<url>http://www.eclipse.org/legal/epl-v10.html</url>
</license>
<license>
<name>GNU Lesser General Public License</name>
<url>http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html</url>
</license>
</licenses>
```
=> fix(nomos): Detect EPL in XMLs

debian/fossology-web.postinst
PHP conf was not updated with all the required changes while installing the Debian packages.
Get the changes done by [php-conf-fix.sh](/fossology/fossology/blob/master/install/scripts/php-conf-fix.sh) and perform the same in [fossology-web.postinst](/fossology/fossology/blob/master/debian/fossology-web.postinst)
1.  Create Debian packages.
2.  Install them on clean machine.
3.  Check if the `php.ini` is updated with the changes.
=> fix(web.postinst): Reflect changes from php-conf-fix

debian/control, utils/fo-installdeps
`php-mbstring` is a required dependency for composer dependencies.
PHPWord requires `php-zip` to be installed as a run time dependency which was missing from Debian control file.
Added `php-mbstring` as a build time dependency.
Also added as runtime dependency for RHEL.
Also added `php-zip` as a dependency for `unifiedreport` for PHP >= 7.0 and added `php5` for Trusty as it do not have `php-zip` as a separate package.
1. On a clean system (Ubuntu >= Xenial or Debian >= Stretch), run `sudo ./utils/fo-installdeps -b` to install build time dependencies.
1. Install composer dependencies.
- On master, it will fail due to missing `php-mbstring`.
1. Checkout the branch and repeat the steps above.
- The install should not fail.
Closes #1119
=> fix(fo-installdeps): Add php-mbstring to build deps

src/maintagent/agent/maintagent.c, src/maintagent/agent/maintagent.h, src/maintagent/agent/process.c, src/maintagent/agent/usage.c, src/maintagent/agent/utils.c, src/maintagent/ui/maintagent.php
Functionality to delete all the orphaned records from fossology database
Removed Orphan records from uploadtree, clearing_event, clearing_decision, clearing_decision_event, obligation_map, obligation_candidate_maps table.
* Upload a package Do clearing for all the files.
* Login to fossology database and delete the uploaded package from upload table.
* Login to fossology UI and add a candidate license and normal license.
* Add this licenses to obligations and delete the added licenses.
* Run maintagent and check if the all the orphaned records deleted from the above tables
=> feat(maintagent): add feature to delete orphaned records from database

src/lib/php/BusinessRules/LicenseMap.php, src/lib/php/BusinessRules/ObligationMap.php, src/lib/php/BusinessRules/test/LicenseMapTest.php, src/www/ui/admin-license-file.php, src/www/ui/template/admin_license-upload_form.html.twig, src/www/ui/template/admin_license_file.html.twig, src/www/ui/template/admin_license_file.js.twig
1. Display the obligations attached to the license next to it in license admin view.
1. Also allow addition and removal of obligations from license edit view.
Show obligations for each license in UI.
1. Add obligations to FOSSology.
1. Add licenses to obligations.
1. Goto Admin -> License Admin -> Select License.
1. Check if the obligations are displayed next to the license.
1. Edit license with obligations.
1. Add / remove obligations to the license.
1. Check if the changes are reflected.
1. Add new license and assign obligations to it.
1. Check if the license is saved with obligations assigned.
This change uses `string_agg` function of PostgreSQL which is available only in 9 and newer versions.
=> feat(license-admin): Show obligations for license

Vagrantfile
Rest API requires Apache's `mod-rewrite` which needs to be enabled explicitly.
Enable `mod-rewrite` for Vagrant.
Build a vagrant container and call the REST API.
Thanks to @maxhbr for pointing this out.
=> fix(Vagrantfile): Enable mod rewrite in vagrant for REST API

utils/freshmeat/trac.php
The word `flase` is an undefined constant, which by default is initialized to its name.
```
php > echo flase;
PHP Warning:  Use of undefined constant flase - assumed 'flase' (this will throw an Error in a future version of PHP) in php shell code on line 1
flase
```
Note that:
```
php > var_dump('flase' == true);
bool(true)
```
Just changed `return flase` to `return false`.
=> fix(trac.php): correct typo `fLAse` instead of `fALse`

src/adj2nest/ui/agent_adj2nest.php, src/cli/cp2foss.php, src/lib/php/common-job.php, src/ununpack/agent/externs.h, src/ununpack/agent/ununpack.c, src/ununpack/agent/ununpack_globals.h, src/ununpack/agent/utils.c, src/ununpack/ui/agent-unpack.php, src/www/ui/page/UploadFilePage.php, src/www/ui/page/UploadPageBase.php, src/www/ui/page/UploadSrvPage.php, src/www/ui/page/UploadUrlPage.php, src/www/ui/page/UploadVcsPage.php, src/www/ui/template/include/upload.html.twig
Implement ignore scm data when scanning an upload (see #1251)
1. Add a new column scm in upload table
1. Add a new option to enable this feature when adding a new upload. 
1. Add a new function in ununpack/agent/utils.c to test SCM data file (see SCM_REGEX constant to search git, svn, TFS, mercurial).
Add a new upload with scm data files. Enable this new option to not scanning SCM data files.
This is a duplicate of  #1264 to resolve multiple commits problem
Closes #1251
=> feat(scm): ignore scm data when scanning

src/maintagent/agent/process.c
Do not delete the global decisions while running the maintagent agent for orphan records.
Changed the query that deletes the global license identification. added the check for global license.
* Upload a package A to fossology.
* Do some clearing with the global decision i.e "Apply decision to all future occurrences of this file".
* Upload the package A(duplicate) again.
* Delete the The package A(original).
* Now go to admin-> Maintenance and Run all Maintenance jobs.
* Go to package A(duplicate) and check the clearing decisions.
* All the global decisions applied should exists.
closes #1291
=> fix(maintagent): do not delete the global decisions

src/www/ui/api/Middlewares/FossologyInitMiddleware.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/index.php
Currently, some plugins are getting missed if user calls REST API without maintaining the cookies.
The plugins which require access more than `READ` on were unloaded as the call was made before setting the `$_SESSION` for a given user.
This PR creates a new middleware to handle this issue and loads the plugins again once the authentication is done for the user.
1. Create a new middleware (`FossologyInitMiddleware`) to load and unload plugins.
1. Rename middleware `RestAuthHelper` => `RestAuthMiddleware`.
Check endpoints mentioned in #1287 
Closes #1287
=> fix(restApi): Fix for missing plugins

.travis.yml, Dockerfile, debian/control, src/nomos/agent/Makefile, src/nomos/agent/Makefile.sa, src/nomos/agent/json_writer.c, src/nomos/agent/json_writer.h, src/nomos/agent/licenses.c, src/nomos/agent/nomos.c, src/nomos/agent/nomos.h, src/nomos/agent_tests/Unit/Makefile, src/nomos/mod_deps
Fix the JSON output while scanning using `-J` flag.
See old output in #953 
The JSON output now following following syntax:
```json
{
"results":[
{
"file": "relative-path-to-file.c",
"licenses":[
"EPL-1.0",
"Apache-2.0"
]
},
{
"file": "absolute-path-to-file-using-l-flag.c",
"licenses":[
"GPL-2.0",
"LGPL-2.1"
]
},
...
]
}
```
1. Run nomos with `-J` flag on a single file
- The result should be a valid JSON.
1. Run nomos with `-J -l` flags on a single file
- The result should be a valid JSON with absolute file path.
1. Run nomos with `-J -d` flags on a directory
- The result should be a valid JSON with results in an array.
1. Run nomos with `-J -l -d` flags on a directory
- The result should be a valid JSON with absolute file path.
1. Run nomos without `-J` flag
- The result should not be …
=> feat(nomos): Fix the JSON output

Dockerfile, Vagrantfile, install/fo-apache.conf, install/fo-postinstall.in
The rewrite string for Debian packaging's apache conf was missing for the REST API.
Added the missing rewrite rule for FOSSology's apache conf file.
1. Build and install the Debian package.
1. Check if the REST API can be used.
=> fix(apache): Add rewrite string to apache conf

Dockerfile, utils/fo-installdeps
Bump docker base image from jessie to stretch, to get rid of the php-5 dependency as suggested on the mailing list by @NicolasToussaint.
test the docker image
=> chore(docker): bump docker base image to stretch

CHANGELOG.md, debian/changelog
FOSSology is now ready for new release 3.5.0. This PR makes the required changes in the changelogs.
=> chore(changelog): Changes for release 3.5.0

src/nomos/agent/STRINGS.in
This corrects a typo in STRINGS.in, which I believe was introduced in [2014](https://github.com/fossology/fossology/commit/f16f6f9fe431b11ba2dfa21a1209bc2ec35a4240).
Renames "foder" to "folder" in the "_LT_SEE_URL" and "_LT_SEE_COPYING_LICENSE_1" string matchers.
=> fix(strings): correct typo

.travis.yml
Update Travis CI configuration
- Remove all deprecated `sudo:` keys in Travis CI `.travis.yml`
- Disable unnecessary addon to speed up tests
- Leverage yaml anchor for phpunit-tests (so we can easily enable phpdbg to speed up phpunit for php v7.0+)
- Enable ccache to speed up tests
- Enable composer cache to speed up tests
- Enable Fast-Finish to retrieve build result faster
- Fix Coveralls execution path (See previous `Could not open input file: src/vendor/bin/coveralls` error in build logs)
- Fix Coveralls output json file not writable issue
- Run PHPUnit via phpdbg to speed up tests (with a output workaround)
Actually, Travis has migrated to the new infra and directly dropped this config, so basically, a passed CI build would be good enough.
It should be easy to find out the build time …
=> Refactor Travis CI configuration

src/cli/cp2foss.php
It would be nice if cp2foss prints out FolderPk as well, since scheduling some agents using POST request requires both UploadPk and FolderPk. 
This is quite convenient if Fossology is used in Continuous Integration process.
Add a print command to print FolderPk.
Upload a file to server using cp2foss command.
=> feat(cp2foss): cp2foss prints out FolderPk as well

src/copyright/mod_deps, src/delagent/mod_deps, src/mimetype/mod_deps, src/nomos/mod_deps, src/pkgagent/mod_deps, src/scheduler/mod_deps, src/ununpack/mod_deps, src/wget_agent/mod_deps, utils/fo-installdeps
Drop distros from `fo-installdeps.sh` which only support php <5.6. They are no longer supported and should not be listed in the script. This especially affects trusty support.
=> chore(fo-installdeps): drop unsupported distros

src/nomos/agent/nomos.h, src/nomos/agent/nomos_regex.c
Nomos crashes when scanning https://github.com/spdx/license-list-data.
Buffer size increased that stores the detected licenses.
Download and scan https://github.com/spdx/license-list-data.
Closes #1337
=> fix(nomos): nomos crash (#1337)

.travis.yml, src/delagent/agent_tests/Unit/testRun.c, src/scheduler/agent/job.c, src/wget_agent/agent_tests/Unit/wget_agent/testDBLoadGold.c
Since Trusty Tahr is reaching its EOL, it is advisable to upgrade systems to Xenial Xerus.
The current builds of FOSSology on Travis were on Trusty, so this PR changes the image to Xenial.
1. Change the `dist` from `trusty` to `xenial`.
1. Remove the old GCC version from tests.
1. Added new GCC versions to tests.
1. Remove PHP 5.6 tests as PHP 7.0 is the default version shipped with Xenial.
Check the travis logs.
=> feat(ci): Run travis jobs on Xenial

src/scheduler/agent/agent.c, src/scheduler/agent/agent.h, src/scheduler/agent/defconf/init.d/fossology.in, src/scheduler/agent/scheduler.c
Currently, the max limit set by agents in their **<agent>.conf** was read and set by scheduler but never checked before scheduling the agent.
This PR checks the same before scheduling the new job/agent.
1. Added one new parameter (`run_count`) to the `meta_agent_t` structure to keep the count of running instances of the agent.
1. This count is increased when the agent is scheduled/resumed and decreased when the agent is killed/paused/finished.
1. Check this `run_count` against the agent's `max_run` before scheduling the job.
1. Reduce the **max** of an agent by editing it's **.conf**
1. Stop the scheduler and schedule the agent from the UI (this is to give buffer for scheduling enough jobs before scheduler picks them up).
1. Start the scheduler and check the running processes.
=> fix(scheduler): Respect max run limit of agents

.travis.yml
Fix #1333
Set shell option pipefail
>  If  set,  the  return value of a pipeline is the value of the last (rightmost)  command  to  exit  with  a non-zero status, or zero if all commands in the pipeline exit successfully.  This  option is disabled by default.
Apply the patch on those should fail but didn't.
=> chore(travis): Set pipefail in Travis CI PHPUnit on PHP 7.0

src/www/ui/css/select2.custom.css, src/www/ui/template/include/upload.html.twig
The box height for "select upload to reuse" in page "upload file" is increased.  Hence giving users access to more number of files before scrolling down.
To make it easy to search and select upload to reuse items in Upload Files Page, the size of upload to reuse window is increased from 200px to 500px.
1. Start Fossology.
2. Go to Upload Files from Menu Option.
3. Scroll down to "Upload To Reuse" select option.
4. The height of the list options is small.
1. Move to the same location.
2. The height of the list options is increased. Thus more options are available on the current display, making it easier to search and find files in the scroll menu.
Closes: #1347 
---
---
=> fix(UI): increased the size of upload to resuse window in upload files

src/reportImport/ui/ReportImportPlugin.php, src/reportImport/ui/template/ReportImportPlugin.html.twig, src/www/ui/template/admin_group_delete.html.twig, src/www/ui/template/admin_group_users.html.twig, src/www/ui/template/admin_license-upload_form.html.twig, src/www/ui/template/admin_upload_edit.html.twig, src/www/ui/template/advice_license-edit.html.twig, src/www/ui/template/components/menu.html.twig, src/www/ui/template/include/macros.html.twig, src/www/ui/template/upload_permissions.html.twig, src/www/ui/template/user_edit.html.twig
Removed the class of select to from macro initialization.
add a advise license and check if the UI looks ok.
=> fix(advicelicense): fix double select of risk in advice license

src/www/ui/async/AjaxShowJobs.php, src/www/ui/ui-download.php
1. FOSSology calls a non-static function defined by monolog in a static way which results in error on PHP5.
1. During the code refactor of jobs page, a variable was not renamed to new name.
1. Replace call to `BrowserConsoleHandler::reset()` by `BrowserConsoleHandler::resetStatic()`.
1. Rename the variable `$job` with `$jobs` in jobs page.
1. Install FOSSology on system with PHP5 and download a report.
1. Check the apache error log.
=> hotfix(download): Fix a call to non-static function

install/db/Makefile, install/db/dbmigrate_3.5-3.6.php, install/fossinit.php, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Db/DbManager.php, src/www/ui/core-schema.dat
This PR adds additional column to copyright/ecc/keyword decision tables to store the hash (MD5) of the text findings. This will help in reducing the duplicates in the tables and also aid in aggregating the entries for PR #1311 .
Add new column, index and unique constraints to copyright/ecc/keyword decision tables.
Install the branch on old instance and check if the installation goes through without causing any issue.
=> chore(decisions): Store SHA256 of text findings

src/www/ui/async/AjaxShowJobs.php, src/www/ui/template/ui-showjobs.js.twig
General fixes after refactoring of showjobs to match old UI.
1. Show message if no jobs to display.
1. Increase the items/sec precision to accommodate big numbers.
1. For upload ETA, do not rely on job, check whole upload.
1. Fix numbers of seconds took to complete a task
1. Check if the `showJobsData` contains the value "There are no jobs to display" and handle the case.
1. Increase the precision of items/sec to accommodate values like `1377.7631` which earlier render to something like `1.4e+3`.
1. Pass the Upload PK to calculate `uploadEta` since the ununpack job can be in different job.
1. If job start time and end time differ in milliseconds, it is no handled by PHP strtotime.
=> fix(showjob): General fix after refactor

src/ununpack/agent/utils.c, src/wget_agent/agent/wget_agent.c
* Due to recent changes, ununpack agent and wget agent were generating following warnings:
```c
utils.c: In function ‘DisplayContainerInfo’:
utils.c:1580:7: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
fscanf(file, "%64s", SHA256);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```c
wget_agent.c: In function ‘DBLoadGold’:
wget_agent.c:117:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
fscanf(file, "%64s", SHA256);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
* Also, if the file path contains any special characters, the call to sha256sum fails.
1. Fix the warnings in ununpack agent and wget agent due to ignored return value of fscanf.
2. Remove unnecessary includes in utils.c
3. Enclose the file …
=> fix(pfile): Fix warnings in ununpack and wget

src/www/ui/async/AjaxShowJobs.php
Check #1385.
Check if the `$allusers` variable is empty before updating the value.
Check #1385.
Closes #1385
=> fix(showjobs): Check empty for allusers before updating

src/copyright/ui/list.php
The copyright list produces pagination links but does not follow them.
This PR fixes it.
Check if the max limit is crossed while generating the output, break the loop.
1. Upload a package with copyright text repeating for more than 50 files and schedule copyright agent.
1. Open the **Copyright Browser** for the upload and check all the files for a given copyright.
- ![image](https://user-images.githubusercontent.com/18077542/60157162-c47b7c00-980b-11e9-8727-ee2ceb59de65.png)
1. Check if the pagination link works.
- ![image](https://user-images.githubusercontent.com/18077542/60157246-f1c82a00-980b-11e9-89da-6fb9c6c11112.png)
1. Check for ECC and Keyword lists as well.
=> fix(copyright): Fix pagination of copyright-list

Makefile.conf
The issue https://github.com/fossology/fossology/issues/1322 shows that the scheduler crashed if fossology was built with a VERSION variable longer than 23 characters.
This PR simply forces the variable down to 23 characters directly in the Makefile.
There might be a way, more desirable, to make it not crash at all, but at least this solution will prevent the unwanted behaviour for the moment.
Simply forcibly truncated the `VERSION`vairable in the file `Makefile.conf`:
`override VERSION:= $(shell echo ${VERSION} | cut -b1-23)`
Build Fossology with: `make VERSION=V2345678901234567890123456789 install` and check that:
- the scheduler does not crash at startup
- the top banner shows the truncated version: `Version: [V2345678901234567890123]`
Describe the steps required to test the changes …
=> Force the VERSION variable to be < 23 chars

src/lib/php/Dao/UserDao.php
Proposition to fix https://github.com/fossology/fossology/issues/1393
Get the `user_desc`from the DB, and display it along the `user_id` in the "Assigned to" dropdown list, on the Browse page.
It shows **Full Name (user_id)**, like it has been done for Issue https://github.com/fossology/fossology/issues/1351
1. Go to the Browse page
1. Click on a list in the "Assigned to" column
=> feat(ui): Show both user description and user name in 'Assigned to' list

src/copyright/ui/HistogramBase.php, src/copyright/ui/TextFindingsAjax.php, src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/copyright-hist.php, src/copyright/ui/email-hist.php, src/copyright/ui/list.php, src/copyright/ui/template/copyrighthist.html.twig, src/copyright/ui/template/copyrighthist_scripts.html.twig, src/copyright/ui/template/copyrighthist_tables.html.twig, src/copyright/ui/template/emailhist_tables.html.twig, src/copyright/ui/template/histTable.js.twig, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/UploadDao.php
Show the text findings done manually by the user in `copyright-hist` view in the UI.
1. Create new functions to create a simple table (without edit capabilities) to show text findings.
1. Create new class to handle ajax call to create such tables.
1. Browse some files for a given upload and add copyright text findings for some files.
1. Browse `mod=copyright-hist` for the same upload.
1. You should get two tabs for **Copyrights** and **Text findings**.
1. **Text findings** tab should show the findings added above.
1. Deactivating the text findings should work.
1. The link to goto file should take you to proper file.
At the same time, other views (URL, ECC, Keywords, etc.) should not be effected.
=> feat(copyright): Show text findings in copyright-hist

debian/fossology-scheduler.lintian-overrides, debian/fossology-scheduler/usr/share/lintian/overrides/fossology-scheduler, src/scheduler/agent/Makefile, src/scheduler/agent/defconf/init.d/fossology.in
This commit adds a weak dependency on postgresql on start.
Fix some warnings be lintian.
1. Implement `force-reload` (required function) in `init.d` script.
1. Include default init-functions for Debian.
1. Add lintian override for `script-in-etc-init.d-not-registered-via-update-rc.d` as it is done by `#DEBHELPER#`.
1. Add a weak dependency on postgresql for start.
Build the package using `debuild`, check the lintian logs.
Closes #1171
Closes #441
=> fix(init.d): Implement missing function

install/db/dbmigrate_3.5-3.6.php, src/ununpack/agent/utils.c, src/wget_agent/agent/wget_agent.c
`pfile_sha256` is still an optional field in DB as it is required only by Software Heritage agent. Removal of all code to check `pfile_sha256` is done in this PR.
1. Fix infinite loop in dbmigrate_3.5-3.6.php
2. Do not check pfile_sha256 in ununpack and wget during insertion as the column is still optional and can be NULL in some cases.
1. With `pfile` table containing all NULL values in `pfile_sha256` column, the fossoloy should still work as before.
1. Upload an old component again.
1. Upload the same component twice.
1. Run `fo-postinstall` on a system where some entries from pfile table does not exists in file system.
- The loop should exit appropriately.
=> fix(pfile): SHA256 is still optional

Makefile.conf, Makefile.process, src/decider/agent/Makefile, src/deciderjob/agent/Makefile, src/readmeoss/agent/Makefile, src/reportImport/agent/Makefile, src/reuser/agent/Makefile, src/spdx2/agent/Makefile, src/unifiedreport/agent/Makefile
After merger of #1348, some artifacts start showing up on the UI failing the twig files as well.
This PR is a hotfix for the issue.
1. Do not add `#!/usr/bin/env php` to every PHP file (this will fail `require()` calls in PHP).
1. Remove `x` flag from PHP files in agent which are not executed directly (it is done by the `fo_wrapper` link in the same dir).
1. Install current master, you will see `#!/usr/bin/env php` all over the UI rendering it useless.
1. Install the branch and check if the issue is resolved.
1. Also check if lintian cries warning for which the fix was introduced in #1348 (see the PR for more info).
=> hotfix(process): Fix the PHP agent installation

Vagrantfile
Update systemd configuration before starting the init.d script,
so that systemd generates the missing fossology.service in time.
Vagrant:
Reload systemd configuration before first startup of fossology
Added a systemctl daemon-reload
vagrant destroy
vagrant up
Fossology now starts correctly. Before it did not.
=> Fix first fossology start failure with vagrant file

src/copyright/ui/Xpview.php
Check issue #1412
1. Check if empty decision type sent for manual copyright findings.
1. Check if empty text finding.
1. Also retain values sent in request for new UI load.
Check issue #1412 
Closes #1412
=> fix(copyright): Check if empty decision sent

src/ojo/agent/OjoUtils.cc, src/ojo/agent/directoryScan.cc, src/ojo/agent/directoryScan.hpp
`libjsoncpp` prior to 0.7.0 does not support `omitEndingLineFeed()` which removes extra `\n` at end.
But since version 1.4.0, `FastWriter` class itself is deprecated. So, till version 1.3.x, remove the `\n` at end explecitly and from 1.4.0 onwards, use `StreamWriterBuilder` class.
Also use boost range iterator since `recursive_directory_iterator` does not have begin and end on version 1.55 (Debian 8).
1. Use `FastWriter` only if json cpp is < 1.4.0, use `StreamWriterBuilder` since 1.4.0.
1. Wrap `recursive_directory_iterator` with `iterator_range`.
1. Build `ojo` on Debian 8
1. Check if the JSON output is correct.
1. Check if the directory scan is working.
=> fix(ojo): Remove call to omitEndingLineFeed on json cpp < 0.7

CHANGELOG.md, debian/changelog
Added CHANGELOG.md and debian/changelog information for 3.6.0-rc2
fix bugs of release 3.6.0.-rc1.
Review the changes in github.
=> chore(changelog): adding 3.6.0-rc2 info to changelog files

src/copyright/ui/template/histTable.js.twig
This enables the user to select 200, 500 and 1000 copyrights to
be displayed in the list on one page.
Add more choices to the amount of lines displayed in the copyright view data tables.
The user can now display up to 1000 table lines on a single page.
This closes issue #1345 
* Specify the lengthMenu item of the datatable object
There is no test needed. This is a standard feature of jQuery data table.
Closes #1345
=> fix(copyright): show more than 100 copyrights on one page

src/lib/php/BusinessRules/AgentLicenseEventProcessor.php, src/www/ui/async/AjaxExplorer.php, src/www/ui/core-schema.dat
Since PR #1314, the number of times `UploadTreeProxy` is materialized is increased (2 per folder in the view). Each call takes significant amount of time depending on the entries in DB.
This PR tires to reduce these calls to only 2 per UI load.
The average amount of time taken to load `?mod=ajax_explorer` for an upload with 10 files is reduced from ~600ms to ~350ms.
1. Create upload view proxy in DB only once with the complete `ItemTreeBounds`.
2. Fix PHP warnings for `AgentLicenseEventProcessor.php` when browsing license for an empty file.
1. Upload a huge package and check the loading time for License Browser table.
1. Install the fix and brows the same package.
- The load time should reduce.
=> fix(ajaxExplorer): Reduce view creation

src/lib/php/services.xml.in, src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/RestHelper.php, src/www/ui/api/Models/Analysis.php, src/www/ui/api/Models/Job.php, src/www/ui/api/documentation/openapi.yaml
The jobs endpoint was not returning the job status which confuses users if the job was finished or not.
This PR also intoduces filtering jobs based on upload id, pagination on jobs and missing ojo analysis to REST API.
1. Add ETA and job status to the job object returned by `/jobs` endpoint.
1. The job ETA is in seconds and can be 0 for completed/failed jobs.
1. The job status can have one of the following values:
- Completed
- Failed
- Queued
- Processing
1. New filter based on upload id in `/jobs` endpoint.
- The filter is passed as query parameter `upload` with the request.
1. Added pagination to the `/jobs` endpoint.
- The request will return total number of pages by `X-Total-Pages` header in response.
- Accept page number from the request headers along with limit.
1. Added missing …
=> feat(api): Return job's ETA and status

debian/control, src/ojo/mod_deps, utils/fo-installdeps, utils/install_composer.sh
Fix the dependencies for Debian Buster (10).
1. Check if all the listed dependencies can be installed without conflicts on all supported distros (at least on stretch and buster).
1. Check if FOSSology can be compiled successfully.
=> fix(deps): Fix dependencies for Debian Buster

src/pkgagent/agent/pkgagent.c
Copy BUFFSIZE-1 and add a 0 termination to the end.
strncpy copies at most n bytes. If there is no 0-termination within these n bytes,
the destination string won't have any. Thus, copy BUFFSIZE-1 and add one in the
end in all occasions.
See the man page strncpy(3)
Closes #1421
=> fix(pkgagent): Avoid possible buffer overrun with strncpy

src/mimetype/agent/mimetype.c
strncpy copies n bytes. If no 0 is within n bytes, the destination
is missing the termination. Add it and only copy BUFFSIZE-1 bytes.
Also, strncpy fills the remaining space with 0, so no memset is
needed.
Above.
Closes #1419
=> fix(mimetype): Fix usage of strncpy, remove memset

src/delagent/agent/util.c
Limit uploadtree_tablename to 1000 characters.
Prevent a possible buffer overflow
Closes #1418 
Limit uploadtree_tablename to 1000 characters.
=> fix(delagent): Fix possible buffer overrun

src/buckets/agent/buckets.h, src/buckets/agent/liccache.c, src/buckets/agent/walk.c
Allocate enough space for sprintf, use strncpy correctly to be sure
to have a 0 at the end of the dest buffer.
Closes #1417
=> fix(buckets): Prevent possible buffer overflow/-run

src/copyright/agent/Makefile, src/copyright/agent/copyright.cc, src/copyright/agent/copyrightUtils.cc, src/copyright/agent/copyrightUtils.hpp, src/copyright/agent/directoryScan.cc, src/copyright/agent/directoryScan.hpp, src/copyright/agent_tests/Unit/Makefile, src/copyright/mod_deps
Provide a new directory flag to allow users to pass a directory for recursive scan like nomos.
Also improve the JSON output.
1. Add a new `-d, --directory` flag to copyright and child agents.
1. Improve the JSON output.
- Earlier, the JSON output just contain the result object and no information about the file itself. Also the result objects were separate for each file eventhough the list of files were passed.
- Now, for each file passed (or picked from directory), there will will be a `file` key denoting the file for which the result is stored and a `results` key holding the agent findings. All these objects will be bounded in a single array as they are result of a single call.
```json
{
"results": [{
"content": "Copyright 2018",
"end": 428,
"start": 381,
"type":"statement"
},{ …
```
=> feat(copyright): New directory scan and better JSON

debian/rules, src/Makefile
Remove Ninka from packaging since ninka is no longer supported on new distros.
1. Remove ninka from Debian rule file.
1. Remove ninka from `src/Makefile`.
Check if ninka is not build and packaged in `.deb` using regular steps.
=> chore(ninka): Remove Ninka packaging from master

src/lib/c/libfossdb.c, src/lib/c/libfossrepo.c
Make sure the dest buffer of snprintf has enough space and use
strncpy correctly to make sure the dest buffer has a terminating 0.
Closes #1416
=> fix(lib/c): Prevent possible buffer overflow/-run

src/www/ui/template/upload_vcs.html.twig
Signed-off-by: Toussaint Nicolas <nicolas1.toussaint@orange.com>
fixes #1485 
Just reorder the VCS in the drop down list so that Git is selected by default.
Choose 'Upload From Version Control System', verify that Git is selected by default.
=> feat(upload_vcs.html.twig) make Git the default VCS rather than SVN

src/cli/fo_nomos_license_list.php
Getting uploadtreeTableName, couldn't find a function named 'GetUploadtreeTableName' but could find 'getUploadtreeTableName', attempting fix by replacing 'G' with 'g'.
=> fix(fo_nomos_license_list.php): change function name

src/www/ui/async/AjaxShowJobs.php
fixes issue #1346 
This pull request changes the three dots(...) in the view full log hyper link to show "display full log" which is more descriptive
changed [this file](https://github.com/fossology/fossology/blob/9d0765c2eda0b72c4a5aaac640322d4f59ffd7f4/src/www/ui/async/AjaxShowJobs.php#L156-L166)
Upload a project as compressed file, allow job to complete, click on job to view details, if log is too long you should see the "Download full log" link instead of "..."
Closes #1346
=> fix(geekyscan): make full job report link more descriptive

src/spdx2/agent/spdx2.php
PR adds user found Copyright entries to SPDX reports
Fixes #1362 
src/spdx2/agent/spdx2.php - read copyright entries from copyright_decision table and add them to result array (merged with scanner results)
1. Add new Copyright in GUI
2. Generate SPDX report
3. Check if previously added copyright can be found on report
=> feat(spdx): add user found copyrights to SPDX reports

src/www/ui/api/Controllers/ReportController.php, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Helper/UploadHelper/HelperToUploadFilePage.php, src/www/ui/api/Helper/UploadHelper/HelperToUploadVcsPage.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/page/UploadPageBase.php, src/www/ui/page/UploadVcsPage.php
Added option allow users to upload packages from VCS.
1. Added content type `application/json` for `POST /uploads` for VCS uploads.
1. VCS JSON includes info of `vcsType`, `vcsUrl`, `vcsName`, `vcsUsername`, `vcsPassword`.
1. Added missing `ignoreScm` input for uploads introduced by #1283.
1. If the upload has first agent as `wget_agent` and does not have `ununpack` started, the the endpoint `/uploads/{id}` returns null on GET request. Now it will return additional information in the message and headers too.
1. Send a POST request to `/uploads` with `application/json` as `Content-Type` header and appropriate values.
1. Also, check the GET request to `/uploads/{id}` with the `wget_agent` agent running.
1. Send a POST request to `/uploads` with `multipart/form-data` as `Content-Type` header …
=> feat(rest): Upload packages from VCS

src/ununpack/agent/traverse.c, src/ununpack/agent/ununpack-disk.c, src/ununpack/agent/ununpack-iso.c, src/ununpack/agent/utils.c
Fix string buffer sizes to be large enough.
Compiled with gcc 8.3.0 without warnings on ubuntu/bionic.
Prevents a buffer overflow. Closes #1423 
Multiplied buffer sizes.
Upgrade vagrant vm to ubuntu/bionic and install gcc-8. Go into directory of ununpack agent and build with
make clean
make
=> fix(ununpack): Increase buffer sizes to prevent overflow

debian/control, src/www/ui/Makefile, src/www/ui/api/Controllers/VersionController.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, utils/fo-installdeps
Provide information about REST API via an endpoint.
Create a new endpoint `/version` to get following information about REST API:
- Version
- Authentication methods allowed
1. Check if the current API version returned by `/version` endpoint matches with `src/www/ui/api/documentation/openapi.yaml`.
1. Check if other endpoints are not effected.
Closes #1474
=> feat(rest): Provide API version as an endpoint

src/www/ui/api/Helper/DbHelper.php
This PR fixes problem with incoherent search results using REST API
Fixes #1481 
src/www/ui/api/Helper/DbHelper.php - call to dbManager.getRows method passes correct parameters (query parameters in array and statementName) to enable running multiple calls from one method with different params
when: using api/v1/search to find file that has multiple occurences in different uploads
before: for files in different uploads, result JSON lists the same upload details (same as first element)
after fix: upload details are correct in result JSON
=> fix(rest): getUploads - invoke getRows with proper parameters 

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/page/UploadFilePage.php, src/www/ui/page/UploadPageBase.php, src/www/ui/page/UploadVcsPage.php
The PR allows user to define the group ID to be used while creating a new upload via REST API.
Depends on #1496 for API version.
1. Read the group ID via header ~`uploadGroupId`~ `groupId`.
1. Pass the group ID in the request object to upload pages.
1. Do a normal upload without group id and check if the upload is done under default group (last chosen by user in UI).
1. Do an upload providing a valid group id and check if the upload is done under the provided group id.
1. Do an upload providing an invalid/inaccessible group id and check if the request fails.
Closes #1468
=> feat(rest): Provide group ID during POST upload

src/decider/agent/DeciderAgent.php, src/decider/ui/DeciderAgentPlugin.php, src/decider/ui/template/agent_decider.html.twig
Auto-Decide all OJO findings and OJO findings where no contradiction with Nomos and Monk.  
* Select a package with All agents selected(at-least Nomos, Monk and OJO ).
* select option " ... scanners matches Ojo findings are no contradiction with other findings"  before you click in upload.
* check if the auto decisions are applied.
=> feat(decider): add auto conclusion for ojo findings

src/lib/php/Dao/LicenseStdCommentDao.php, src/lib/php/Dao/test/LicenseStdCommentDaoTest.php, src/lib/php/Test/testdata.sql, src/lib/php/services.xml.in, src/www/ui/async/AjaxLicenseStdComments.php, src/www/ui/core-schema.dat, src/www/ui/page/AdminLicenseStdComments.php, src/www/ui/scripts/admin-license-std-comments.js, src/www/ui/scripts/change-license-common.js, src/www/ui/template/admin_license_std_comments.html.twig
This feature will allow admins to add some predefined license comments which can be used by users during clearing with the help of a simple drop down in License Comment window.
Admins can navigate to **Admin >> License Admin >> Standard Comments**.
~Currently admins can add **only 7** comments at max to keep the interface simple.~
1. Add new table to hold predefined license comments.
1. Allow users to select these comments with the help of a drop down menu.
1. Insert some comments from the **Admin Standard License Comments** page.
1. Clear some files and add the comments.
1. Try adding comments from the decision table.
1. Try adding comments from the buik table.
1. Add the comments added from the first step should be visible.
1. Added comments should appear in the reports.
**P.S.:** …
=> feat(license): Provide predefined license comments

src/decider/ui/DeciderAgentPlugin.php, src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Models/ScanOptions.php
remove force dependency of nomos and monk for ojo decisions through decider. and add nomos dependency if the user checks nomos scans.
* Upload a package and schedule ojo and decider. without other agents.
=> fix(decider): remove force dependency of nomos and monk for ojo decider

src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/HighlightDao.php, src/lib/php/Proxy/UploadTreeProxy.php, src/www/ui/ui-clearing-view.php
Optimizing some SQL queries.
1. Optimize query to select latest `clearing_decision`.
1. Optimize query to select `highlight_keyword`.
1. Load the clearing status using SQL joins instead of UploadProxyView to increase the loading time for huge DBs.
=> fix(db): Optimize license browse queries

docker-compose.yml
The SW360chores docker compose project uses version 3.5. Bumping the version
here has no negative effects (except for probably old distributions having not a
new enough docker-compose, needs Docker Engine 17.12.0+).
The advantage is, that this allows the deployments to work in sync and one can
start both at the same time e.g. via:
```
./sw360chores.pl --build -- -f path/to/fossology/docker-compose.yml up
```
=> chore(docker-compose): harmonize versions with sw360chores

install/db/Makefile, install/db/dbmigrate_3.6-3.7.php, install/fossinit.php, src/lib/php/Application/ObligationCsvImport.php, src/lib/php/BusinessRules/ObligationMap.php, src/www/ui/admin-obligation-file.php
Associate all candidate licenses with same name to the obligations.
1. Get the list of all licenses which shares the same name `ObligationMap`.
1. Associate all licenses with the given license while creating the obligation map in DB.
1. Create a candidate license in `Group - 1`.
1. Create another candidate license in `Group - 2` with same shortname.
1. Create an obligation using `Group - 1` and associate the candidate license.
1. Edit the same obligation using `Group - 2`. The candidate license will create problems saving the obligation reliably.
Install the branch.
1. Repeat the steps above.
1. Both candidate licenses should be associated with the obligation (no issue while updating the license in UI).
1. Check if there are different entries for the candidate licenses in …
=> fix(obligation): Associate all candidate licenses with same name

src/copyright/ui/template/histTable.js.twig
Wait for bulk replace ajax calls to resolve before reloading the page.
1. Get all the ajax calls in an array while calling `updateRows{{ table.type }}` to update the text.
1. Wait for all ajax calls to be resolved before reloading the page.
1. Run copyright agent on an upload.
1. Goto Copyright Browser and select multiple rows to update the text.
1. Insert the new text in the Replace text box and hit **Mark selected rows for replace** button.
1. Check if the page reloaded only after all calls are solved using the browser console.
1. Make sure no error message popped-up during the operation.
1. Check if all the selected rows are updated.
=> fix(copyright): Wait for ajax calls during bulk replace

src/www/ui/template/user_edit.html.twig, src/www/ui/user-edit.php
Allow users with read-only access to edit their user info.
1. Update the minimum required permission to load `user-edit` page to `Auth::PERM_READ`.
1. Disallow user with permission < 3 (`PERM_WRITE`) to create REST API tokens with Read/Write scopes.
1. Create a new user with read only access.
1. Check if the user can update the password.
1. Check if the user can create REST API tokens
1. The user should not be allowed to make read/write API tokens.
Closes #900
=> fix(admin): Allow read user to edit user

utils/fo-installdeps
Add PHP CLI as a build time dependency as it is required by `utils/preprocess_php`.
Add `php-cli` to build time dependency in `utils/fo-installdeps`.
Build fossology on a fresh instance with steps described in #1150.
Closes #1150
=> fix(build-dep): Add PHP-CLI as build dependency

src/www/ui/change-license-processPost.php, src/www/ui/template/ui-clearing-view_rhs.html.twig, src/www/ui/ui-clearing-view.php
Unable to change the `decision type` for the files which are cleared under `Clearing decision scope : global(Scope) : Apply decision to all future occurrences of this file`.
Example : files with `Clearing decision type` : `To be discussed`  and
`Clearing decision scope : global(Scope) : Apply decision to all future occurrences of this file`
can not be changed to `Clearing decision type` : `To be discussed` with or without
`Clearing decision scope : global(Scope) : Apply decision to all future occurrences of this file`
* Global and local scope of the decision type can be changed
* if applied `Clearing decision scope : global(Scope) : Apply decision to all future occurrences of this file`. the checkbox will be checked.
As described in …
=> fix(ui): decision and scope for licenses

src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Models/User.php, src/www/ui/api/documentation/openapi.yaml
Hide sensitive user information from users list in `/users` endpoint if requesting user is not an admin.
Thank you @deveaud-m for pointing this out.
Depends on #1498 for API version.
1. Check if user is admin or not requesting information about other users, then provide complete information as before.
1. If user is not admin and requesting information about other users, return only user ID, description and username.
1. Create a normal user with no admin access and generate bearer token.
1. Using this bearer token, get list of all users at `/users` endpoint and individual users details using `/users{id}`.
1. Except for the user accessing the endpoint, the information returned should only contain user id, description and username.
1. Generate bearer token for admin user and request same …
=> fix(rest): Hide sensitive user info

src/www/ui/Makefile, src/www/ui/admin-dashboard-general.php, src/www/ui/admin-dashboard-stats.php
New dashboard page added. 
Old dashboard page also relocated to `Dashboards` submenu to keep things grouped together.
For the moment there is a single report on agents usage, however more statistics will come soon.
The idea with the new dashboard was to distinguish the statistics original info dashboard with technical/instance related info.
New `Admin/Dashboards` submenu added.
Old `Admin/Dashboard` moved to `Admin/Dashboards/Overview`.
New `Admin/Dashboards/Statisctics` added as new page.
Open your browser to  `/repo/?mod=dashboard-statistics` to see the new dashboard.
Closes #1502
=> New Dashboard statistics page

src/lib/php/Dao/ClearingDao.php, src/lib/php/Data/AgentRef.php, src/lib/php/Proxy/UploadTreeProxy.php, src/lib/php/Report/LicenseClearedGetter.php, src/lib/php/UI/template/include/base.html.twig, src/spdx2/agent/spdx2.php, src/www/ui/async/AjaxExplorer.php, src/www/ui/async/AjaxFileBrowser.php, src/www/ui/template/browse_file.js.twig, src/www/ui/template/file-browse.js.twig, src/www/ui/template/ui-browse-license_file-list.js.twig, src/www/ui/ui-browse-license.php, src/www/ui/ui-clearing-view.php, src/www/ui/ui-file-browse.php, src/www/ui/ui-license-list-files.php
In the codebase, many places defines a list of agents to fetch the records from DB.
Eventhough they all contain the same value, if someone adds a new agent to fossology, they'll have to find all instance and apply the changes.
This PR moves all such instances to a common base class helping in reduced changes required.
1. Move the array of agents to a common base PHP class.
1. Move the list of agents to base twig file.
1. Check if aggregated license view and file browser view works fine.
1. Check if SPDX agent works fine.
=> chore(lib): Move agent list to common place

src/nomos/agent/parse.c
For files with lengthy lines with out file break nomos is throwing seg fault 
use file with real long line without line break.
=> fix(nomos) : segfault for large offset value

src/nomos/agent/STRINGS.in
FOSSology does not identify the following phrase:
"This document may be reused under a Creative Commons Attribution-ShareAlike
License."
Nomos identifies it as CCPL.
=> fix(nomos) : CC-BY-SA identification

src/lib/php/Application/LicenseCsvExport.php, src/lib/php/Application/LicenseCsvImport.php, src/lib/php/Application/test/LicenseCsvExportTest.php, src/lib/php/Application/test/LicenseCsvImportTest.php, src/lib/php/Db/DbManager.php, src/lib/php/services.xml.in, src/www/ui/page/AdminLicenseFromCSV.php
With the current implementation, if a license already exists in the DB where CSV is being imported, it is skipped altogether. And if the license does not exists, but it's MD5 matches with other license, the other license is updated with new license.
This PR fixes this behavior as following:
1. If the license shortname already exists
1. If the MD5 of new license does not collide with any other license, update the license else print an error.
1. If the license shortname does not exists
1. If the MD5 of the new license collides with any other license, print an error.
1. Otherwise insert it as a new license.
This PR also provides way to differentiate candidate licenses with main licenses by creating additional column called `group` in the exported CSV and checking this column while importing …
=> fix(license-csv): Update license if exists

src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/GPL-2.0-with-code.js, src/ojo/agent/ojoregex.hpp, src/ojo/agent_tests/Functional/regexTest.json
ojo currently had a length limit on license name between 1 and 37.
It is fixed by setting the limit to 3 and 37 as per the licenses in [spdx-license-list-data](https://github.com/spdx/license-list-data/tree/master/html).
1. Patch the license length regex to {3,37}
1. Scan a file with bogus `SPDX-License-Identifier` of length bellow 3.
1. Scan [checkpatch.pl](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/checkpatch.pl?h=v5.5-rc7&id=9f3a89926d6dfc30a4fd1bbcb92cc7b218d3786d) from GNU/Linux Kernel.
=> fix(ojo): Add lower limit to license length

src/lib/php/UI/template/include/foot.html.twig, src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-view.js, src/www/ui/template/browse_file.js.twig, src/www/ui/template/file-browse.js.twig
The dropdown in modal view for bulk option in aggregated license view was not rendering.
This PR uses `dropdownParent` property of `select2` to fix the issue.
1. Change the `dropdownParent` of any `ui-render-select2` element which has a parent class `.modal`.
1. Change the call to `tooltip` class from `$(document)` to `$('img')`.
1. Upload a package and goto aggregated license browser.
1. Select `[Bulk]`.
1. Check if the dropdown renders properly.
1. Check if other occurances of `select2` are not effected.
=> fix(bulk): Fix dropdown bulk on folder level

src/wget_agent/agent/main.c, src/wget_agent/agent/wget_agent.c, src/wget_agent/agent/wget_agent.h, src/wget_agent/agent_tests/Unit/wget_agent/testDBLoadGold.c, src/wget_agent/agent_tests/Unit/wget_agent/testSetEnv.c
Fix wget_agent's obviously possible memory corruption
Closes #1424 
A lot of snprintf/printfs are replaced by asprintf, which allocates memory dynamically and sufficiently.
* Unneeded memset is removed
* Unneeded malloc is removed
* Some pointer checks are introduced
* Some memory leaks are corrected
* New error code for out of memory error
* Some simplifications in program flow
* One minor change in wget_agent.c where rc was used in an error message instead of rc_system
* Lots of new asprintf / free (this most probably needs review!!!)
=> fix(wget_agent): Prevent possible memory corruption

src/www/ui/css/jquery.dataTables.css
Place the DataTables processing message at top of the table as it might be difficult for user to find it and understand something is going on.
1. Change the `top` possition of processing message box to 10% from 50%.
1. Change the `z-index` of message box to `999` to keep it on top.
1. Check the loading on following pages:
1. Browse
1. License Browser
1. File Browser
1. Change concluded License
1. Copyright Browser
=> feat(ui): Place DataTables processing at top

src/delagent/ui/delete-helper.php, src/www/ui/Makefile, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Models/UploadSummary.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/BrowseLicense.php
Get an upload's summart from REST. Following are the contents of the summary:
```json
{
"id": 1245,
"uploadname": "library-2.0.1.tar.gz",
"mainLicense": "MIT,BSD0",
"uniqueLicenses": 10,
"totalLicenses": 41,
"uniqueConcludedLicenses": 2,
"totalConcludedLicenses": 8,
"filesToBeCleared": 20,
"filesCleared": 4,
"clearingStatus": "Open",
"copyrightCount": 25
}
```
1. Provide new endpoint `GET: /api/v1/uploads/{id}/summary`
1. Moved class `ui_browse_license` (file `src/www/ui/ui-browse-license.php`) → class `BrowseLicense` (file `src/www/ui/page/BrowseLicense.php`) under `Fossology\UI\Page` namespace.
1. For a given upload, call the summary endpoint and verify correctness of response.
1. Check if other `/uploads/` enpoints are working.
1. Fetch upload which is not accessible by current user. …
=> feat(rest): Get upload summary

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/page/UploadFilePage.php, src/www/ui/page/UploadPageBase.php, src/www/ui/page/UploadVcsPage.php
This reverts commit b07e1e295289c38d7d87b1812fffa8b9fc8f08e6, reversing changes made to 296aae01b0575a99dad3a3b283edb8e456ca7ab7.
The changes are obsolete because of 6f00ed38e236c8d37e2e6da6940b727d9f4b27cb from #1568.
=> Revert "Merge pull request #1498 from siemens/feat/rest/provide-group-upload"

src/www/ui/api/Helper/AuthHelper.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/documentation/openapi.yaml
PR adds option to provide groupName for REST  API calls, to do stuff in given groupName context (not the one set in DB as user-default group)
Fixes #1529 , while previous PR #1498 will no longer be needed.
REST API accepts additional parameter (groupName) which changes behaviour only for subset of possible paths (please see openapi.yaml file)
RestAuthMiddleware verifies given group existence and user access - if user has no access to given group or group does not exist, error is returned.
In case of positive verification, AuthHelper.updateUserSession method is called with proper paremetrs, to alter and set correct group for specific user session
Try to call REST APi with/without additional groupName parameter to verify if things are done for proper group (passed or not by user), using …
=> feat(rest): Add group context (groupName param) for REST Api calls

src/ojo/agent/Makefile, src/ojo/agent/ojoregex.hpp, src/ojo/agent_tests/Functional/schedulerTest.php, src/ojo/agent_tests/Unit/test_regex.cc
Remove the upper limit from license name as additions of new SPDX licenses will result in rewrite of code.
1. Remove upper limit for license name (lower bound remains same).
1. Add `ojoregex.hpp` as dependency to `$(EXE)` to rebuild whenever regex changes.
1. Added **Dual-License** check in Functional test.
1. Added bad license name check in Unit test.
1. Scan a file with license identifier more than 37 characters in length.
1. Modifying the `regex.hpp` file (using `touch`, or simple modification) should result in rebuild of agent when using `make`.
=> feat(ojo): Remove upper limit from license name

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/ui-license-list.php
Get the result of "License List" page via REST API.
1. Restructured the response of function `createListOfLines` of class `ui-license-list`.
2. Added new endpoint `/uploads/{id}/licenses` to get license list.
1. Send a GET request to `/uploads/{id}/licenses` and check the response.
1. Send the request without agent list which should fail.
1. Send the request with agent which is not scheduled for the upload.
1. Send the request with different values for `containers` query parameter.
1. Send request for unavailable/unaccessible uploads.
**Note:** Depends on #1568 and #1598 for API version.
=> feat(rest): Get the license list for upload

src/decider/ui/DeciderAgentPlugin.php, src/reuser/ui/agent-reuser.php, src/www/ui/page/UploadPageBase.php
If an upload is done with reuse but the new upload has new findings, the reuser simply copied the previous decision ignoring the conflicts.
1. Add scanner dependency to reuser.
2. Add reuser as dependency to decider if monkbulk decisions are being reused.
1. On master branch. upload a package and do clearing (both manual and with monkbulk).
1. From the previous upload, copy a text portion of a file and make it as a new license so monk will add new license for next upload.
1. Install this branch to change the agent IDs to include newly created license.
1. Reupload the package but reusing the previously cleared package.
1. Upload with "bulk phrases from reused packages"
1. Upload without "bulk phrases from reused packages"
1. Check if files with new license findings (new license added in …
=> fix(reuser): Run decider after reuser

src/lib/php/Dao/ClearingDao.php, src/lib/php/Proxy/UploadTreeProxy.php
Clearing decisions were filtered based on user's group irrespective if it is global or not.
This PR changes the logic and checks for the group only for local decisions (per file).
1. Fix the condition in `ClearingDao`.
1. Fix the condition in `UploadTreeProxy`.
1. Create two users (User1 and User2) and 2 groups:
a. User1 to Group1
b. User2 to Group2
1. Perform some clearing on an upload with User1.
- Add both local and global decisions.
1. Login from User2 and check following:
a. Local decisions should not be visible to User2.
b. Global decisions should be visible to User2.
=> fix(lib): Check group on local decision only

install/defconf/fossology.conf.in, src/lib/php/common-auth.php, src/www/ui/core-auth.php
Partially fixes #1273 
This PR introduces external authentication, delegated to Apache.
Apache can be configured to perform any kind of authentication, and places relevent information (login, user name, email), etc. in environment variables.
- on first login, the user's account is automatically created
- then a session is opened for the user.
Optionally, all logins may be lower cased.
Further possible improvements:
1. Make the configuration available in the GUI
1. Configure the default list of agents for each newly created user
1. Add the 'logout' feature (logout is ineffective in this version)
- Added configuration options in `fossology.conf.in`
- In `src/lib/php/common-auth.php` : new function to check external authentication validity
- In `src/www/ui/core-auth.php` : check …
=> feat(auth): Add external authentification feature

.gitignore, utils/FossologyUnicodeClean.cc, utils/FossologyUnicodeClean.hpp, utils/Makefile
Old PostgreSQL with text collation `SQL-ASCII` will have some non-printable characters captured by copyright agent. While migrating to a new PostgreSQL DB with collation `UTF-8`, values in copyright table will cause a failure since they are not UTF-8 compatible.
This program will help to remove such characters from dump created by `pg_dump` and thus, it can be safely imported on new DB.
1. Created a new CPP program to remove non UTF-8 characters from a file or a stream.
1. On a database with `SQL-ASCII` collation, upload a package (tested with [Nuget.Client](https://github.com/NuGet/NuGet.Client) and run copyright agent.
1. Dump the database using `pg_dump` and import on a DB with `UTF-8` collation.
1. Import will fail reporting invalid characters.
1. Use the program to remove such non …
=> feat(migrate): Program to make file UTF-8 compatible

.gitignore, Makefile.conf, install/Makefile
Enable fossology site on source install.
1. Check if the default location for Debian based distro exists, then
install conf file Debian style. Otherwise check for RedHat directory
and install RedHat style.
1. Do a clean install of FOSSology from source on Debian and RedHat
based Linux Distros.
1. Check if FOSSology (`http://localhost/repo`) is enabled.
Closes #182
=> fix(apache): Enable fossology on source install

utils/fo-installdeps
There were few missing fedora dependencies that were missing.
Pull fedora docker image and try executing fo-installdeps
Fixes: #1601
=> fix(fo-installdeps): Missing Fedora dependecies 

src/www/ui/page/AdminLicenseCandidate.php
If the license text in ```advice license``` already existed in a ```main license```, clicking ```verify as a new license```  showed a blank page.
This is a fix for issue #1507 
An error message is shown if the above case occurs.
Closes #1507
Closes #938
=> fix(AdviceLicense): Show error message on failure

src/copyright/agent/regexConfProvider.cc
The copyright agent looks for the config file in the `following` directory 
` /usr/local/share/fossology//mods-enabled/copyright/agent/copyright.conf
`
which doesn't exists, it should look for the config file in:
`/usr/local/share/fossology/copyright
`
Fixes #1298
=> Feat(Copyright): Fixed the checking of config file in wrong folder

.travis.yml
Fix travis warnings.
``` console
$ travis lint
Warnings for .travis.yml:
[x] [warn] on jobs.include: key addon is not known, but addons is, using addons
[x] [warn] on jobs.include.deploy: deprecated key: skip_cleanup (not supported in dpl v2, use cleanup)
```
1. Fix warnings given by travis.
1. Change deprecated keys for [dplv2](https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release)
Check the travis logs.
https://travis-ci.org/fossology/fossology/builds/660574926/config
=> fix(travis): Fix build config warnings

src/www/ui/api/Controllers/AuthController.php, src/www/ui/api/Helper/AuthHelper.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/async/AjaxManageToken.php, src/www/ui/user-edit.php
Removed hostname from JWT token as requested in #1512
1. Removed hostname from all token related functions
1. Removed hostname check while authenticating with token.
1. Generate a new token from UI and REST API
- Inspect it using jwt.io and verify if `iss` and `aud` claims are not in the token.
1. Use old token to access FOSSology (with `iss` and `aud`)
- Should work without any issue
1. Use new token to access FOSSology (without `iss` and `aud`)
- Should work without any issue
Closes #1512
=> fix(rest): Remove hostname from JWT

src/spdx2/agent/template/spdx2-file.xml.twig
Fix comments in SPDX RDF export by adding a closing `>` for `<![CDATA]`. Closes #1692. 
Add a closing tag to the template file.
Go to conf-page of an upload and enable "Show SPDX license comments" and export SPDX RDF of the upload. `<spdx:licenseComments>` for files should now be valid xml.
=> fix(spdx-rdf-report): Fix comments in export.

src/www/ui/core-schema.dat
Update the core-schema.dat to match the output of schema-export tool.
This will help in prevention of additional column recreation in DB.
1. `src/www/ui/core-schema.dat`: Update the schema with `src/cli/schema-export`
1. Dump the output of following SQL
```sql
SELECT
table_name AS table, ordinal_position AS ordinal, column_name,
udt_name AS type, character_maximum_length AS modifier,
CASE is_nullable WHEN 'YES' THEN false WHEN 'NO' THEN true END AS notnull,
column_default AS default,
col_description(table_name::regclass, ordinal_position) AS description
FROM information_schema.columns
WHERE table_schema = 'public'
ORDER BY ordinal_position;
```
2. Install the branch and run `fo-postinstall`.
3. Dump the output of the SQL again.
1. If no schema change was done recently, the ordinal number …
=> fix(schema): Match schema with schema export

src/delagent/agent/util.c, src/maintagent/agent/process.c, src/www/ui/async/AjaxShowJobs.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-showjobs.js.twig, src/www/ui/ui-browse.php
While deleting a upload, due to constraint `upload_pfile_fk_fkey`, the tuple from `upload` table also get dropped. This causes issues with the job table as they hold the `upload_fk` which causes issue for new uploads if the `upload_upload_pk_seq` is reset.
This commit drops that constraint, retaining the upload_pk and marks the upload as deleted using the `expire_action` and `expire_date` columns.
Since the upload link is removed from `foldercontents` table, no other changes were required. The commit also adds a filter to `removeUploads()` for maintenance agent so that it does not drop the tuple.
1. Remove the `upload_pfile_fk_fkey` constraint.
1. Mark upload as deleted using `expire_action` and `expire_date` columns in delagent.
1. Update `removeUploads()` of maintagent so it does not …
=> fix(delete): Do not remove upload_pk

.travis.yml
There was a syntax fix with #1656 for new travis.
The dpl v2 has few keyword changes from dpl v1 like `_` changed to `-`. Also, the tag `skip_cleanup` is replaced with `cleanup`.
This change was done 1:1 in #1656 but the logic of value is flipped with removal of `skip`.
1. Change the value of `cleanup` to `false` as we want to keep the built docs by doxygen.
1. Keep the `skip_cleanup` tag since we've not explicitly opted in for dplv2.
=> fix(travis): Fix page deploy stage

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php
The entry for `upload_clearing` are missing for new uploads.
Generate the entry for `upload_clearing` using `UploadBrowseProxy` class on every upload related endpoint.
1. Upload a file using REST API or UI.
1. Fetch the `/uploads/<id>/summary` without opening `Browse` page in UI.
1. Also, fetch from a different group from REST API.
Closes #1620
=> fix(rest): Get upload summary without UI

src/www/ui/page/AdminLicenseCandidate.php
Fix white page showing when **merge** is clicked, when advice license and a main license have the same license text.
An error message stating `the license text already exists` is shown if the above case occurs.
=> fix(AdviceLicense):show error message on failed merge

src/wget_agent/agent/wget_agent.c, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/page/UploadVcsPage.php, src/www/ui/template/upload_vcs.html.twig
Fixes #1390 
This change adds possibility to indicate specific git branch when uploading source code for analysis using both GUI and Rest API.
When no branch is passed, standard master branch clone is performed as before
`src/wget_agent/agent/wget_agent.c `- changes in agent to pass additional argument to shell command
`src/www/ui/api/Helper/UploadHelper.php` - changes to handle additional parameter in RestApi call and pass it to agent
`src/www/ui/page/UploadVcsPage.php` - changes in upload agent to handle additional request parameter from restApi and GUI
`src/www/ui/template/upload_vcs.html.twig` - changes in twig template to acquire brach parameter from GUI user
RestAPI - try to pass `vcsBranch` param in RestApi call to clone branch specified
GUI - pass (or not) specific branch when …
=> feat(upload): Add possibility to upload specific Git branch

src/copyright/agent/copyright.conf, src/copyright/agent_tests/Unit/test_scanners.cc
Allow Fossology's copyright agent to detect authors from ROS catkin package manifest files as per [official spec](http://wiki.ros.org/catkin/package.xml)
1. Add new regex for detecting authors from <author> tags to the file:
`src/copyright/agent/copyright.conf`
2. Add new test data to check the above regex to the file : 
`src/copyright/agent_tests/Unit/test_scanners.cc`
Build and run the unittests for the copyright agent in `src/copyright/agent_tests/Unit`
```
src/copyright/agent_tests/Unit$ make
src/copyright/agent_tests/Unit$ ./test_copyright 
```
**Result** : all tests should pass
1. Use the following contents as "package.xml"
```xml
<package format="2">
<name>foo_core</name>
<version>1.2.4</version>
<description>
This package provides foo capability.
</description> …
```
=> feat(copyright): Enable agent to read authors from ROS catkin package manifest files as per spec

src/lib/php/libschema.php, src/www/ui/core-schema.dat
While installing FOSSology on PostgreSQL 12, following error was thrown:
```
PHP Warning:  pg_prepare(): Query failed: ERROR:  column attrdef.adsrc does not exist
LINE 7:         attrdef.adsrc AS default,
^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 60
[2019-12-19 16:00:22] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column attrdef.adsrc does not exist LINE 7:         attrdef.adsrc AS default,                 ^ [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: SELECT class.relname AS table,
attr.attnum AS ordinal,
attr.attname AS column_name,
type.typname AS type,
attr.atttypmod-4 AS modifier,
attr.attnotnull AS notnull,
attrdef.adsrc AS default,
col_description(attr.attrelid, attr.attnum) AS description
FROM …
```
=> fix(libschema): Schema fix for PostgreSQL 12

src/unifiedreport/agent/reportSummary.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/ui-report-conf.php
The unified report has a **Department** field under **Clearing Information** section. This field was hard coded with the value **FOSSology Generation** in the code and thus the user has to manually edit the file.
The commit adds a new column `ri_department` in `report_info` table to make this field editable from UI itself.
1. Add a new column `ri_department` in `report_info`.
1. Add labels to check boxes in Report Config page.
1. Check if the installation does not break reports in old uploads.
1. Check if updating the department in Report Conf page results in updated value in Unified Report.
=> fix(unifiedreport): Get department from config

src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Models/Upload.php, src/www/ui/api/documentation/openapi.yaml
This patch extends the REST API model `Upoad` with the SHA1 sum of the uploaded file.
A new fields is available in the `Upload` schema: `string filesha1`
I tested the changes on a local docker-based instance performing a REST call on the `/uploads/` endpoints.
I couldn't find any unit tests for the REST API, are some available? 
Closing #1698
=> feat(rest): extend upload model with filesha1

src/maintagent/agent/process.c, src/www/ui/ui-browse.php
The PR #1707 included changes which changed the behavior of `expire_action` column of `upload` table. A new check was added to check if the upload was deleted. The check looks for `'d'` in expire_action column of upload table. The default value for the column in NULL which fails the check of `!= 'd'` in Postgres.
This commits fixes the check by additional check of column being NULL.
Change the check of `expire_action` being not equal to `d` to `expire_action IS NULL OR expire_action != 'd'`.
1. Check if you can open **Browse** page (`?mod=browse`) for an upload.
1. Check if you can open **Browse** page for a deleted upload.
=> fix(upload): Fix the check for expire_action

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Helper/UploadHelper/HelperToUploadSrvPage.php, src/www/ui/api/Helper/UploadHelper/HelperToUploadUrlPage.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/page/UploadSrvPage.php, src/www/ui/page/UploadUrlPage.php
Provided option to allow user to upload from URL or server from REST API.
1. New parameter `uploadType` to define uploading from URL/VCS/Server.
1. Two new schema `components/schemas/UrlUpload` and `components/schemas/ServerUpload`
1. Check if upload from URL works with all parameters.
1. Check if upload from Server works with all parameters.
1. Check if upload from File works.
1. Check if upload from VCS works even when `uploadType` is not provided (for backward compatibility).
1. Check if an error is thrown for invalid value in `uploadType`.
Depends on #1699 for API version.
Closes #1562
=> feat(rest): Upload from URL and server

src/spdx2/agent/template/spdx2-package.xml.twig
Fix SPDX RDF export to comply with the SPDX spec.
Remove unnecessary `<spdx:licenseConcluded>` from SPDX template to comply with the spec.
Export an SPDX RDF report. The unnecessary tag should be gone.
Changes this:
```xml
<spdx:licenseConcluded>
<spdx:DisjunctiveLicenseSet>
</spdx:DisjunctiveLicenseSet>
</spdx:licenseConcluded>
<spdx:licenseComments><![CDATA[
licenseInfoInFile determined by Scanners:
- nomos ("3.7.0-170-g012cd4da2".012cd4)
- monk ("3.7.0-170-g012cd4da2".012cd4)
]]>
</spdx:licenseComments>
<spdx:licenseConcluded rdf:resource="http://spdx.org/rdf/terms#noassertion" />
```
into this:
```xml
<spdx:licenseConcluded>
<spdx:DisjunctiveLicenseSet>
</spdx:DisjunctiveLicenseSet>
</spdx:licenseConcluded>
<spdx:licenseComments><![CDATA[
licenseInfoInFile determined by Scanners:
- …
```
=> fix(spdx): fix spdx-rdf export.

src/nomos/agent/json_writer.c, src/nomos/agent/json_writer.h, src/nomos/agent/licenses.c, src/nomos/agent/nomos.c, src/nomos/agent/nomos.h, src/nomos/agent/nomos_utils.h
Optimize the JSON output of directory scan for nomos by printing the result objects one by one instead of creating a huge chunk of single result object.
It helps in reducing the memory consumption while creating the JSON also the first output will appear much faster than earlier.
Also, fix a memory leak in `unescapePathSeparator()`.
Removed the use of additional temp file to store the scan results before being converted to JSON. This makes the output appear even faster.
~1. Print JSON objects one by one in `parseTempJson()`.~
1. Fix the calculation of result string in `unescapePathSeparator()`.
1. Removed `writeToTemp()`, `writeToStdOut()` and `parseTempJson()`, replaced all with `writeJson()`.
1. Run nomos with and without `-J` flag on a single file.
1. Run nomos with and without `-J` …
=> feat(nomos): Optimize JSON output

src/maintagent/agent/maintagent.c, src/maintagent/agent/maintagent.h, src/maintagent/agent/process.c, src/maintagent/agent/usage.c, src/maintagent/agent/utils.c, src/maintagent/ui/maintagent.php, src/www/ui/async/AjaxShowJobs.php
Remove job log files created by agents for the uploads which were deleted.
1. Added new function `removeOrphanedLogFiles()` with flag `-L`.
1. List the `jobqueue` entries for uploads where Delete action has been performed and remove all associated log files.
1. The removed file locations gets replaced with `removed`.
1. Upload some package with binary files (images, etc.) which will cause monk to create log.
1. Delete the upload (`delagent` will also create a log file).
1. Save the `jobqueue.job_log` entries for the upload for verification.
1. Run the maintenance agent with relevant options.
1. Check if the `jobqueue.job_log` entries have been updated to `removed`.
1. Check if the previously saved files are removed from FS.
Closes #292
=> feat(maintenance): Remove orphan log files

src/lib/php/UI/template/components/menu.html.twig, src/www/ui/template/user_edit.html.twig, src/www/ui/user-edit.php
Add feature to update default group for a user from user edit form. This will be helpful while creating a new user.
Read #1353 for more info.
**Note:** Only admins will be able to update this value.
1. Add new field `default_group_fk` to **Edit User Account** page.
1. Create a new user.
2. Assign few groups to the newly created user.
3. Edit the new user and change the default group.
4. Login as the new user and check if the default group is updated for the user.
- Check if the non-admin users do not see the field.
Closes #1353
=> feat(groups): Update default group for user

src/lib/php/UI/template/components/login-form.html.twig, src/lib/php/common-folders.php, src/lib/php/common-ui.php, src/reportImport/ui/ReportImportPlugin.php, src/reuser/ui/reuser-plugin.php, src/www/ui/admin-dashboard-general.php, src/www/ui/admin-upload-edit.php, src/www/ui/async/AjaxBrowse.php, src/www/ui/async/AjaxFolderContents.php, src/www/ui/async/AjaxShowJobs.php, src/www/ui/core-auth.php, src/www/ui/template/upload_permissions.html.twig
This pull request adds the capability to convert the timestamps shown in the FOSSology WebUI to the current timezone of the users browser. This makes it easier for the users to track when which action was executed without manually converting the time.
**src/lib/php/UI/template/components/login-form.html.twig** - get the current users timezone during login
**src/lib/php/common-ui.php** - added function "Convert2BrowserTime" to be called wherever in the UI a timestamp is being displayed
**src/www/ui/core-auth.php** - if no timezone is provided by the browser it falls back to the server timezone
The remaining changed files are now calling the function "Convert2BrowserTime" for displaying the timestamps.
After deployment of the application the user logging in to the application should see all …
=> feat(ui): Conversion of timestamps to browser timezone

src/lib/php/common-license-file.php, src/lib/php/common-sysconfig.php, src/www/ui/ui-download.php
Fix proposal for #1304 
This PR is now in initial version, final solution should be confirmed
Now, all read/write users can download source code for uploads they have access to - it is not always desired situation.
Changing line below could not be the best solution as it will also prevent non-admin users from downloading anything else that uses this plugin - for example reports (and we do not want that)
https://github.com/fossology/fossology/blob/b5a389be8ef413fc488b56700ea23bdf3ff9c73a/src/www/ui/ui-download.php#L42
In this PR we simply do not show **Download** buttons when user is not an admin.
I'm aware that it isn't ready to be ths final solution, but I can see 2 options:
- add option in Customize to choose for which access right download button should be shown
- separate somehow (I …
=> feat(download): Limit source code download for admin users only

src/www/ui/template/bulk-history.html.twig
* Add missing class to highlight text for bulk. in case of matched file.
* Upload a package and run bulk for multiple files with different text phrases.
* Check if in each file in bulk history if the matched text is highlighted.
=> fix(bulk): add class to show text highlighted for matched page

src/www/ui/core-schema.dat
Create a PRIMARY KEY index for `license_candidate` table. This will result in significant performance improvement for join of `license_file` table and `license_candidate` for calculating the license histogram in the left side of License Browser page.
1. Create new index `license_candidate_rf_pk_idk` on `license_candidate` table.
On a big FOSSology instance, check the load time of **License Browser** page for a big package before and after creating the index.
The following query is used to create license histogram by `LicenseDao::getLicenseHistogram()`:
```sql
SELECT rf_shortname AS license_shortname, rf_pk, count(*) AS count, count(distinct pfile_ref.pfile_fk) as unique
FROM ( SELECT license_ref.rf_shortname, license_ref.rf_pk, license_file.fl_pk, license_file.agent_fk, …
```
=> perf(license_candidate): Create PRIMARY KEY

src/lib/php/common-ui.php
Under some circumstances, like if the user has old cookie or interacting with REST API, the `$_SESSION` will be missing timezone string. In such cases, use the server timezone instead, otherwise update the timezone as per the value stored in cookie.
1. If the session contains timezone, update the timezone, otherwise leave it to server timezone.
Check #1741
Also, check if the simple workflow of REST API is working.
Closes #1741
=> fix(ui): Use default timezone if not set

src/lib/php/Dao/ShowJobsDao.php, src/www/ui/async/AjaxAllJobStatus.php, src/www/ui/page/AllJobStatus.php, src/www/ui/template/all_job_status.html.twig
Add a new page to show all running/pending jobs on server.
The page also shows current status of scheduler (Running/Stopped).
This will help users to understand the reason if their jobs are stuck.
1. Add new function in `ShowJobsDao.php` to get running and pending jobs per agent.
1. Change the default port on `common-scheduler.php` to `24693` (as per the `fossology.conf`).
1. New async page `AjaxAllJobStatus.php` to get job status and scheduler status.
1. New page `AllJobStatus.php` and template `all_job_status.html.twig` to show the data from `AjaxAllJobStatus.php`.
**Note:**
1. The page is added under Admin >> Dashboards >> All Jobs
1. The page will work **without login** (as no sensitive information is displayed).
1. Check if the new page appears under Admin >> Dashboards >> All Jobs …
=> feat(jobs): Show all running jobs

src/spdx2/agent/spdx2.php
closes #1703 
Path in SPDX files is getting chopped because of which there are few files missing in the report in rare cases.
add parent and enable file path with artifacts.
Please see #1703
=> fix(spdxReport): add missing artifact to file path in spdx reporting

utils/automation/.gitlab-ci.sample.yml, utils/automation/.travis.sample.yml, utils/automation/Dockerfile.ci, utils/automation/fossologyscanner.py, utils/automation/whitelist.sample.json
An idea to provide FOSSology scanners as GitLab runner to do license scanning in a GitLab CI pipeline.
Sample files are provided for .gitlab-ci.yml and whitelist.json under the same folder.
1. A new folder created named `utils/automation` to hold all the relevant files.
1. File `Dockerfile.ci` creates a slim docker image which can then be used by GitLab runners to scan the code.
1. The file `fossologyscanner.py` can be used as an entry point which in turns call other scanners and collect the output from them.
```shell
docker build -t fossology/fossology:scanner -f utils/automation/Dockerfile.ci .
```
Please check the provided `.gitlab-ci.sample.yml` file.
Please check the provided `.travis.sample.yml` file.
```shell
docker run -it -v <path/to/scan>:/project fossology/fossology:runner
cd …
```
=> feat(ci): Use FOSSology scanners CI

src/www/ui/api/Helper/UploadHelper.php
This pull request fixes Bug #1755 
Corrected if statement handling the ignoreScm flag during upload using the api.
Removed "|| ignoreScm" in if statement to properly handle the case of value set to "false".
Run the below Curl command and check the FOSSology UI for .git files in the upload. They should now be present in the files list.
curl -k -s -S -X POST http://localhost:8081/repo/api/v1/uploads
-H "folderId: 1"
-H 'uploadDescription: created by REST'
-H 'public: public' -H 'Content-Type: multipart/form-data'
-H 'ignoreScm: false'
-F 'fileInput=@"time-1.7.tar.gz";type=application/octet-stream'
-H "Authorization: Bearer eyJ0eXAi…"
Closes #1755
=> fix(rest): fixed ignoreScm flag when value is false

install/db/dbmigrate_3.6-3.7.php, src/lib/php/BusinessRules/ObligationMap.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Report/ObligationsGetter.php, src/www/ui/core-schema.dat, src/www/ui/template/admin_obligation-upload_form.html.twig, src/www/ui/ui-report-conf.php
With the current implementation of obligations, the FOSSology stores the license references in the obligation map.
This results in additional efforts required for keeping track of child licenses (a license using different license as conclusion).
This PR attempts to solve the situation by storing (and displaying) only the licenses which are used as conclusion in some license (including self conclusion, which is the default behavior for all licenses). And while generating the unified report, get the obligations associated with the decided license's conclusion.
This will result in reducing the efforts required to attach all child licenses to the obligation.
**Note:** This will not alter candidate licenses as they do not have provision to conclude to other licenses.
1. Display only licenses …
=> fix(obligation): Refer to license conclusions

src/lib/php/Dao/ClearingDao.php, src/lib/php/Report/ClearedGetterCommon.php, src/lib/php/Report/LicenseMainGetter.php, src/lib/php/Report/tests/ClearedGetterCommonTest.php, src/readmeoss/agent/readmeoss.php, src/unifiedreport/agent/unifiedreport.php
Following fixes in library:
1. Default arguments in a function can not be followed by non-default arguments in PHP.
1. Variable not defined in `ClearingDao::getCandidateLicenseCountForCurrentDecisions()`.
1. Define `$params` variable in `ClearingDao::getCandidateLicenseCountForCurrentDecisions()` before use.
1. Change the parameter arrangement in `ClearedGetterCommon::getCleared()`.
Check if unified report and readme oss are working.
=> fix(lib): Correct non-default argument position

src/lib/php/Dao/ShowJobsDao.php, src/www/ui/async/AjaxAllJobStatus.php, src/www/ui/page/AllJobStatus.php
Restrict the All server jobs to read premissions. This will allow admin to configure to allow default user to read the page or not.
Also, restrict the jobs to recent jobs (4 weeks) to prevent processing irrelevant old jobs which do not matter anymore.
1. Change the permission of `AllJobsStatus` and `AjaxAllJobStatus` to read.
1. Use the `nhours` in `ShowJobsDao` to list only recent jobs for `getJobsForAll()`.
1. Check #1749
1. On an old instance, with old pending jobs, check if they do not show up in all jobs page.
Closes #1749
=> chore(alljobs): Restrict to read

src/delagent/agent/delagent.h, src/delagent/agent/util.c
While deleting an upload, the entries from `clearing_decision` and `license_ref_bulk` were not deleted from delagent leaving the DB in inconsistent state until someone runs maintenance agent.
This PR will remove all the corresponding entries from mentioned tables bellow.
1. Remove local clearing entries from `clearing_decision`, `clearing_event` and `clearing_decision_event` tables.
- The global entries will not be removed as they are referenced by pfile.
- And if the pfile is deleted (not referred by any other upload), they will be removed by `clearing_decision_pfile_fk_fkey` constraint.
1. Remove entries from `license_ref_bulk` for deleted `uploadtree_pk`.
1. Upload a package, do some clearing ad then delete the upload.
1. Run `fo_postinstall` simulating a new version install.
1. Upload …
=> fix(delagent): Remove clearing_decision and license_ref_bulk

install/db/dbmigrate_3.7-3.8.php, src/www/ui/ajax-uploads.php, src/www/ui/async/AjaxShowJobs.php, src/www/ui/template/ui-showjobs.js.twig
Show the filename of the deleted upload in Show Job pages and add the author table for UTF migration script.
Fix the color mismatch on show jobs.
1. Show the uploadname if exists in `ui-showjobs.js.twig`
1. Add `author` table to `dbmigrate_3.7-3.8.php`
1. Do not fill job times if empty in `AjaxShowJobs.php`
1. Change the timezone in `ajax-uploads.php` as well.
1. Upload a package and delete it.
1. Under Show Jobs page, the package name should appear with a deleted message.
1. Run a maintenance job.
1. Under Show Jobs page, the view should not break and show maintenance.
1. Kill the scheduler before uploading a package and check if the jobs appear with yellow background.
Closes #1753
Closes #1731
=> feat(showjobs): Show delete file name

src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/UploadDao.php, src/reuser/agent/ReuserAgent.php, src/reuser/agent_tests/Functional/SchedulerTestRunnerMock.php, src/reuser/agent_tests/Functional/schedulerTest.php, src/reuser/ui/agent-reuser.php, src/reuser/ui/template/agent_reuser.html.twig
Deactivated copyrights are not reused when the scanner version changes.
Deactivated copyrights are now reused when `Reuse deactivated copyrights` is selected while uploading the package
or select the option from `Schedule Agents` page on an existing package.  
* Install fossology 3.7.0 upload a package after with `copyright scanner` selection.
* Deactivate false positive copyrights. 
* Install this branch and reused the copyright on the same package or a different version of the package.
* Deactivated copyrights should get copied. 
=> feat(copyright): reuse deactivated copyrights with reuser

install/fossinit.php, src/cli/exportLicenseRefUsingSPDX.php, src/decider/agent_tests/Functional/schedulerTest.php, src/deciderjob/agent_tests/Functional/schedulerTest.php, src/lib/php/Dao/test/LicenseDaoTest.php, src/lib/php/Data/Highlight.php, src/lib/php/Test/TestAbstractDb.php, src/monk/agent_tests/Functional/bulkTest.php, src/monk/agent_tests/Functional/cliTest.php, src/monk/agent_tests/Functional/schedulerTest.php, src/reuser/agent_tests/Functional/schedulerTest.php, src/spdx2/agent_tests/Functional/schedulerTest.php, src/www/ui/core-schema.dat
1. Remove `rf_md5` from `licenseRef.json` as it can be derived from `rf_text`.
2. Remove `rf_pk` from `licenseRef.json` as `rf_shortname` is the correct way to reference a license from DB.
3. Update `rf_md5` whenever `rf_text` updates.
4. Insert `rf_add_date` for new licenses.
5. If a license already exists as candidate, merge it with main `license_ref` before updating.
- On an existing DB:
1. Install the branch and check if the license texts are updated
1. The `rf_md5` is correct (`SELECT rf_shortname, rf_md5, md5(rf_text) AS hash FROM license_ref WHERE rf_md5 != md5(rf_text);`)
1. Check if `license_ref.rf_pk` has not been changed.
- On new DB:
1. Check if all the licenses are updated.
1. The `rf_md5` is correct (`SELECT rf_shortname, rf_md5, md5(rf_text) AS hash FROM license_ref WHERE …
=> fix(licenseRef): Fix import of licenseRef.json

src/nomos/agent/STRINGS.in, src/nomos/agent/parse.c, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/PHP/PHP-2.02.txt
Added a new regex to fix the wrong interpretation of PHP-2.02 license by nomos agent
Try scanning the following file (http://www.php.net/license/2_02.txt) it should be identified as PHP 2.02.
fixes: #1213 
Signed-off-by: Sahil <sjha200000@gmail.com>
=> fix(Nomos): Added a new License signature

src/lib/php/Report/ClearedGetterCommon.php, src/readmeoss/agent/readmeoss.php, src/unifiedreport/agent/unifiedreport.php
In case a same license has been identified in different files with different license text, the report shows only one entry with only one license text.
1. Add the missing `"license"` parameter to `getCleared()`.
1. In a package, identify 3 files with same license (say Public-domain).
1. In all files, change the **License Text** with 3 different text.
1. Generate the Unified report and check for the license.
- It should show 3 entries for all the 3 license texts with different files.
=> fix(report): Don't group results with custom text

src/lib/c/libfossagent.c
There was extra parameter for `queryFileIdsForUpload()` even if the upload tree table is not `uploadtree_a`.
Remove extra parameters from `queryFileIdsForUpload()` if `uploadtreeTableName != uploadtree_a`.
1. Upload a file larger than 500mb (provided in #1737)
1. Reduce the size of uploadtree split from https://github.com/fossology/fossology/blob/b4e3a379a83a3402f0b75bf5198f772b42cd2f7f/src/ununpack/agent/ununpack.c#L272 and upload any file.
Closes #1737
=> fix(lib): Remove extra parameters

src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/CopyrightDao.php
`getItemTreeBounds()` returned default `uploadtree` table causing wrong join with copyright table.
1. Get the correct uploadtree table name and recreate the `$itemTreeBounds` to fix it.
1. As a fail safe, check for `uploadtree` in ClearingDao as well.
=> fix(ClearingDao): Get uploadtree table name

src/lib/php/Dao/ClearingDao.php, src/lib/php/Data/ClearingDecision.php, src/lib/php/Proxy/UploadTreeProxy.php, src/lib/php/Proxy/test/UploadTreeProxyTest.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/async/AjaxExplorer.php, src/www/ui/core-schema.dat, src/www/ui/ui-clearing-view.php
The PR tries to improve the load time of tree view by optimizing some SQL queries, reducing calls to DB and introducing new indexes.
1. Update CTE provided by `ClearingDao::getRelevantDecisionsCte()` to sort and unique only if required and reduce CTE count from 2 to 1 (will benefit PG < 12).
2. Remove `getClearingDecisionsCount()` and `getClearingDecisionsCount()` as they are no longer helpful.
3. Update `UploadTreeProxy::getQueryCondition()` to use simple SORT and DISTINCT instead of WindowAgg.
4. In `AjaxExplorer`, new function `updateFilesToBeCleared()` to cache itemtree bounds which are already calculated to reduce DB reads.
5. Updated index `clearing_decision_event_clearing_fk_idx` to include `clearing_event_fk` making join on cde as `INDEX ONLY SCAN`.
6. New index …
=> perf(ui): Reduce load time for license browser

src/lib/php/Dao/CopyrightDao.php
The `CopyrightDao::updateTable()` can be called by Copyright UI, Reuser (when reusing copyrights) or Clearing Dao (when **irrelevant** decision sent).
The ClearingDao does not send the hash of copyright resulting in a different SQL query. Whereas other methods send the hash and a different SQL query is generated. This causes issue with `prepare()` as the statement name is not updated.
Update statement name in `CopyrightDao::updateTable()` if hash is sent.
1. In an upload, mark some files as **irrelevant**
- It will call `CopyrightDao::updateTable()` without hash and a statement will be prepared.
1. Perform some copyright clearing
- It will call `CopyrightDao::updateTable()` with hash.
1. Upload the same package again and Reuse the older package with **Reuse deactivated copyrights**.
- It …
=> fix(copyrightDao): Change statement in updateTable

install/scripts/install-spdx-tools.sh, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig, src/spdx2/agent_tests/Functional/schedulerTest.php
Signed-off-by: Michael C. Jaeger <michael.c.jaeger@siemens.com>
Changing the spdx templates for SPDX file generation to version tag 2.2
modified:   src/spdx2/agent/template/spdx2-document.xml.twig
modified:   src/spdx2/agent/template/spdx2tv-document.twig
Generate SPDX documents and test them with the SPDx java tool (at version 2.2). Output:
```
lando:Downloads sam$ java -jar spdx-tools-2.2.2-jar-with-dependencies.jar Verify SPDX2_rigel-20190819-master.zip_1602710429-spdx.rdf.txt 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
This SPDX …
```
=> chore(spdx): bump spdx version to 2.2

src/copyright/mod_deps, src/nomos/mod_deps, src/ojo/mod_deps, utils/fo-installdeps
Drop support for Debian Jessie from all dependency scripts.
Part of #1760 
Previous Conversation: #1765
=> update(org): drop debian 8 support

src/ununpack/agent/ununpack.c, src/ununpack/agent/ununpack_globals.h
The mimetype for .deb Debian packages was wrong, added the new mimetype.
Added the new mimetype for `.deb` files (`application/vnd.debian.binary-package`).
Upload a `.deb` package, it should be unpacked.
=> fix(ununpack): Correct the mimetype for deb files

.github/workflows/release-publish.yml
Use GitHub actions to build deb packages on release and attach them to the release.
Currently following builds are implemented:
- Debian Buster
- Debian Stretch
- Ubuntu Xenial
- Ubuntu Bionic
The deb files are archived as `FOSSology-<version>-<os>-<release>.tar.gz`
E.g. **FOSSology-3.9.0-rc2-ubuntu-bionic.tar.gz**
New github workflow file (`.github/workflows/release-publish.yml`).
Check the sample pipeline: https://github.com/GMishx/fossology/actions/runs/303632596
Check the sample release page: https://github.com/GMishx/fossology/releases/tag/3.9.0-rc3
=> feat(cd): Publish release packages with Actions

src/spasht/ui/ui-spasht.php
The data type used to store coordinates was changed from array to an object which was causing advance search to fail.
Check https://github.com/fossology/fossology/pull/1838#issuecomment-734678329 for logs.
Change the data access in `checkAdvanceSearch()`.
1. Search for a package in Spasht tab.
1. Do an advance search for a package in Spasht tab.
1. Schedule Spasht agent.
=> fix(spasht): Fix advance search

src/unifiedreport/agent/reportStatic.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/ui-report-conf.php
Add text boxes for three columns in report conf page, to-write extra notes if needed. 
Columns where the text-area is added.
* Dependency notes.
* Export restrictions by copyright owner.
* Restrictions for use by copyright owner. 
* Generate a unified report after filling the above mentioned columns and check if the extra note added gets displayed.
=> feat(conf): add textarea in conf page for notes

src/www/ui/ui-report-conf.php
Use urlencode and decode for ObTopic in name, so that the brackets will not mix up with obligations.
* Upload a component.
* Create a obligation with brackets '[]' Ex: obligation [Some name]
* Do clearing with license associated obligation.
* go to conf and select obligation and submit.
* check of the results have been stored in database.
=> fix(conf): fix not able to save conf in case of brackets

src/lib/php/Dao/UploadDao.php, src/www/ui/api/Controllers/SearchController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/search-helper.php, src/www/ui/search.php, src/www/ui/template/ui-search.html.twig
This feature adds possibility to search only in specified upload while currently it is possible to do it in all available uploads
Closes: #1280 
Search option for all available uplads only is not very useful when there is more than 3-5 uploads user has access to.
This feature adds possibility to choose in which upload user wants to search in.
List od available uploads for user is dynamically loaded from DB.
- Added option-field on template `src/www/ui/search-helper.php`  filled with all uploads user has access to (plus option to choose to search in All uploads)
- Added method for `src/lib/php/Dao/UploadDao.php` to retrieve all uploads 
- modified `src/www/ui/search-helper.php#GetResults` to filter search results only for selected upload
Search results should be shown only for Upload …
=> feat(search) - possibility to search in selected upload only

src/buckets/ui/ui-buckets.php
Problem described in #1366 
This PR adds Bucket menu entry for license view
src/buckets/ui/ui-buckets.php - added menu entry insert
Bucket link should be visible during browsing upload folders, not only files (mod=license)
Closes #1366
=> feat(gui): Add Bucket link for license view page

src/www/ui/api/Controllers/JobController.php
This pull request fixes bug #1805 .
Set the overall job status to Failed, if any one of the job is Failed.
Corrected the order of job status verification in such a way that Failure status is validated first.
` curl -k -s -S -X GET http://localhost/repo/api/v1/jobs?upload=<id> -H "Authorization: Bearer <TOKEN>"`
Response :
[
{
"id": 3,
"name": "filename",
"queueDate": "2020-10-06 12:17:51.458106+00",
"uploadId": "3",
"userId": "3",
"groupId": "3",
"eta": 0,
"status": "Failed"   ->>>>>> Without this fix Job status is showing as Queued even when ununpack is failed.
}
]
Fixes #1805
=> fix(rest) : Set job status as Failed when any one of the job is failed

src/readmeoss/agent/readmeoss.php
Since the ReadMe_OSS report is a plain text file, it makes sense to unescape the contents. Otherwise the report will contain things like:
Copyright (c) 2000 Contributor &lt;contributor@example.com&gt;
Instead of the desired:
Copyright (c) 2000 Contributor <contributor@example.com>
This closes #1660.
This is fixed by calling `htmlspecialchars_decode()` to reverse the encoding done elsewhere by `htmlspecialchar()`.
1. Import code that contains a copyright statement with angle braces as shown above.
2. Scan code for copyrights.
3. Click the _ReadMe_OSS Generation_ button on the _Browse_ page.
4. View the report to see if it contains angle braces or html escape codes.
=> fix(readmeoss): unescape contents

src/ununpack/agent/ununpack.c, src/wget_agent/agent/main.c
While check `journalctl -xe`, saw
`ununpack[9125]: Libgcrypt warning: missing initialization - please fix the application`
The gcrypt needs to be initialized before using it which was missing from the agents. See https://www.gnupg.org/documentation/manuals/gcrypt/Initializing-the-library.html
Initialize gcrypt in ununpack and wget using `gcry_check_version`.
1. Install the agent, upload a package.
1. Upload a package using Upload from URL.
1. Check the `sudo journalctl -xe` and check if the above mentioned warning does not exists.
=> fix(ununpack): Initialize gcrypt

src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Dao/LicenseStdCommentDao.php, src/lib/php/Dao/SpashtDao.php, src/lib/php/Util/StringOperation.php, src/lib/php/Util/test/StringOperationTest.php, src/www/ui/admin-license-file.php, src/www/ui/admin-obligation-file.php
At every possible place where user input is taken as text and the input is written to a file (reports), remove non-printable unicode control characters.
1. New function `replaceUnicodeControlChar` is added to `StringOperation` class.
1. In an upload, add some license text and acknowledgements with invalid control characters.
1. Also, add some valid unicode characters like &copy; and text from languages with non-latin script.
1. Check if the invalid characters are removed before inserting the data in DB.
1. Perform same operation on License text update, new license creation, acknowledgement with bulk finding, etc.
Example of test strings:
```
4.	“IDENT”.  some text and it’s
copyrights ©
Agreement.
invals
```
```
There is something below this line.
Do copy with care.
```
```
नमस्ते
你好 …
```
=> feat(utils): Filter inputs for unicode ctrl chars

src/nomos/agent/parse.c, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/Apache/Apache-2.0-nourl.txt
If the source contain words **Apache =SOME= license** and not **license =SOME= Apache**, nomos fails to detect it.
Additional check for such cases added in `parse.c` with test file `Apache-2.0-nourl.txt` (just removal of url and license header made nomos fail in detecting actual license text).
=> feat(nomos): Apache detection

src/lib/php/Dao/FolderDao.php, src/lib/php/Proxy/UploadBrowseProxy.php, src/lib/php/services.xml.in, src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/Controllers/SearchController.php, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/RestHelper.php, src/www/ui/api/documentation/openapi.yaml
This PR allows user to limit uploads results to given folder id, provide an option to list uploads recursively, paginate the results if more than 100 uploads exists (can be controlled with `limit` parameter in header).
The default folder id is the user's root folder id and recursive is set to true.
In the earlier implementation, the uploads listing was limited to the user accessing the endpoint meaning that you can list only the uploads done by you. However, the UI lists the uploads based on group id. The REST API now reflects the same behavior.
The listing of `groupName` parameter is updated in the `openapi.yaml` to reduce the redundancy and add the endpoints which were missing it.
1. Add new parameters `folderId`, `recursive` and `page` to `/uploads` endpoint.
1. List uploads based on …
=> feat(rest): Filter uploads by folder id

src/composer.json, src/composer.lock, src/www/ui/template/admin_license_file.js.twig, src/www/ui/template/ui-browse.html.twig, src/www/ui/ui-browse.php
In twig v1.38.4, the spaces between consecutive prints `{{ }} {{ }}` gets lost.
This issue is however limited to PHP7.4 and it causes issues with reports.
Updated the version to v1.42.5 to fix it.
Check https://github.com/twigphp/Twig/issues/3248
1. Update twig `v1.38.4` => `v1.42.5`
1. Escape obligation name in Admin >> License Admin >> Select License as it can contain special characters like `"<`.
1. Print the current folder name instead of root folder in Browse view.
With PHP7.3 and PHP7.4
1. Check if the folder name appears correctly in Browse page.
1. Generate SPDX tag:value report and check if it looks ok.
Closes #1846
=> fix(twig): Update twig version to preserve spaces

.github/workflows/release-publish.yml
Build the new Ubuntu version packages, Ubuntu Focal 20.04 while building release packages.
Add `ubuntu:focal` to image list in GitHub workflow.
=> feat(cd): Build Focal packages on release

debian/fossology-scheduler/usr/share/lintian/overrides/fossology-scheduler, debian/rules
* Add support to php7.4 ( Focal )
* Add missing homedir making pbuilder lost during build
* Add proper current build  directory for Composer task
Signed-off-by: Helio Chissini de Castro <helio.chissini-de-castro@bmw.de>
=> debian: Improve deb package building

src/copyright/ui/HistogramBase.php, src/copyright/ui/copyright-hist.php, src/copyright/ui/ecc-hist.php, src/copyright/ui/email-hist.php, src/copyright/ui/keyword-hist.php, src/copyright/ui/template/copyrighthist_scripts.html.twig, src/copyright/ui/template/histTable.js.twig
Add feature to search using regex, create placeholders and replace in Copyright and sister UIs. Same feature can be used to search for specific terms and replace.
A test table has been added as well where user can see sample results before comiting to it.
For example, you can search for `Copyright(*) rights reserved(*)` which can match anything like:
```
Copyright 2012-2016 Example Inc, All rights reserved
Copyright 2018 Example Inc, All rights reserved some small text snipit
Copyright 2014-2019 Example Inc, All rights reserved and some random text picked up by the agent
```
And replacement can be done with `Copyright$1 rights reserved` (notice the `$1` placeholder) which will transform all text to:
```
Copyright 2012-2016 Example Inc, All rights reserved
Copyright 2018 Example Inc, All …
```
=> feat(copyright): Search and replace with regex

src/lib/php/Dao/UploadPermissionDao.php, src/lib/php/common-auth.php, src/lib/php/common-sysconfig.php, src/lib/php/tests/test_common_auth.php, src/www/ui/admin-config.php, src/www/ui/css/fossology.css, src/www/ui/template/password-policy-check.js.twig, src/www/ui/template/user_edit.html.twig, src/www/ui/user-add.php, src/www/ui/user-del-helper.php, src/www/ui/user-edit.php
Allow admins to enforce password policies from Customize page. Following options can be chosen to generate policy:
1. Enable/disable policy check.
2. Fixing length of passwords (min and max).
3. Requiring minimum one of lowercase character.
4. Requiring minimum one of uppercase character.
5. Requiring minimum one digit.
6. Requiring minimum one of special characters from a predefined set.
This policy is used to generate RegEx and the password will be checked while creating a new user or editing a user.
The checks are added to the backend as well as frontend.
Also, if password policy is enabled, do not allow empty passwords for new users.
1. `common-auth.php`: Two new functions `generate_password_policy()` and `generate_password_policy_string()` to generate policy regex and string …
=> feat(password): Create password policy

src/www/ui/ajax-notice-files.php
Include uploadId in GetResults function to search for notice file.
* Upload a package with notice file.
* Select notice file as acknowledgement while clearing.
=> fix(ack): add missing uploadid in getresults function

.github/workflows/release-publish.yml, Makefile.conf, utils/fo-debuild, utils/fo-installdeps, utils/fo-mktar, utils/utils.sh
Use the information provided by `git describe --tags` and generate the build version number.
The `git describe --tags` also displays the number of commits since last tags which is used here to get the build number. So let's say, last tag was 3.8.1 and there are 88 commits since then, the version now will be 3.8.1.88.
(See the **Example** in [man git-describe](https://linux.die.net/man/1/git-describe) for info on format)
Also, created a new script `utils/fo-debuild` to generate Debian packages and source tar with option to skip signing of packages with `--no-sign` flag.
1. Get the no. of commits from `git describe --tags` using `sed` and generate build number using it.
1. Fix the `fo-mktar` to consider `.gitignore` and use new version.
1. New script `fo-debuild` to generate Debian …
=> feat(build): Get build version number from git

src/www/ui/async/AjaxExplorer.php, src/www/ui/template/browse_file.js.twig
Total files count added to Files Cleared column.
Column name changed to:
*Files Cleared/NotCleared/Total*
In context of a folder it gives the number of containing files.
Signed-off-by: Bartłomiej Dróżdż <bartlomiej.drozdz@orange.com>
Address the [comment point no 1](https://github.com/fossology/fossology/issues/1775#issuecomment-730518125) in #1775. 
The feature gives user a feedback in number of files in directories in the browser.
src/www/ui/async/AjaxExplorer.php
src/www/ui/template/browse_file.js.twig
Go to License Browser in your upload and you should see the number of files in the firectory in _Files Cleared/NotCleared/Total_ column.
=> feat(browser): total files in license browser view

docker-compose.yml
Use the [Health-check](https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck) feature inside `docker-compose` files to have a quick heath status of the containers when running `docker status`
Proposed health tests are:
- *web* : `test: ["CMD-SHELL", "curl -sSf localhost/repo/api/v1/version || exit 1"]`
- *database* : `test: ["CMD-SHELL", "pg_isready"]`
- *scheduler* : `test: ["CMD-SHELL", "true"]`
- **-> did not find a really useful check here since the container crashes as it becomes unhealthy!**
That's a first shot, tests can be improved in the future.
1. Run Fossology using provided docker-compose file
2. Run `docker container ls -a`
=> (feat) docker services healthchecks in the docker-compose file

.gitignore, src/ununpack/agent/Makefile.sa, src/ununpack/agent/checksum.h, src/ununpack/agent/standalone.c, src/ununpack/agent/standalone.h, src/ununpack/agent/ununpack.h, src/ununpack/agent/utils.c
This PR makes unpack agent as standalone, so it can work independently.
```
src/ununpack/agent/Makefile.sa
src/ununpack/agent/ununpack.c
src/ununpack/agent/ununpack.h
```
1. go to `src/ununpack/agent` folder
2. Build ununpack-standalone : `make -f  Makefile.sa` (this will create ununpack-sa) 
3. `./ununpack-sa <file to unzip>`
4. other options can be used :
-C     :: force continue when unpack tool fails.
-d dir :: specify alternate extraction directory. %U substitutes a unique ID.
Default is the same directory as file (usually not a good idea).
-m #   :: number of CPUs to use (default: 1).
-P     :: prune files: remove links, >1 hard links, zero files, etc.
-R     :: recursively unpack (same as '-r -1')
-r #   :: recurse to a specified depth (0=none/default, -1=infinite)
-X     :: remove …
=> feat(ununpack): standalone

src/www/ui/core-schema.dat
Create indexes for columns `pfile_sha1` and `pfile_sha256` on table `pfile`.
Run and analyze `SELECT * FROM pfile WHERE pfile_sha1 = 'ABC'` and `SELECT * FROM pfile WHERE pfile_sha256 = 'ABC'`. The queries should utilize the indexes.
Closes #1859
=> fix(db): add indexes to pfile on sha1 and sha256

src/cli/fo_usergroup.php, src/cli/tests/test_common.php, src/lib/php/Dao/UserDao.php, src/lib/php/common-auth.php, src/lib/php/common-users.php, src/testing/db/create_test_database.php, src/testing/install/test4migrationinstall/test_common.php, src/testing/install/test4packageinstall/test_common.php, src/www/ui/core-auth.php, src/www/ui/user-add.php, src/www/ui/user-edit.php
Currently fossology uses SHA-1 which is now officially deprecated. 
Also as per the [official website](https://www.php.net/manual/en/function.password-hash.php), the salt option of PASSWORD_BCRYPT has been deprecated as of PHP 7.0.0
Updated password hashing algorithm from SHA1 to PASSWORD_DEFAULT (Use the bcrypt algorithm)
Closes #841
=> refactor(login): updated password hashing algorithm

src/www/ui/user-edit.php
If the default group of a user was not updated in the form request, do not set the `group_fk` key which causes issue with DB update.
Check if `default_group_fk` was sent before updating the `$UserRec['group_fk']` in `src/www/ui/user-edit.php`.
1. Login as a non admin user.
2. Goto Admin > Users > Edit User Account and update a field. Submit the form and the update should be recorded.
3. Login as an admin user.
4. Goto Admin > Users > Edit User Account and update the default group of another user.
=> fix(login): Do not set group_fk if empty

.github/workflows/release-publish.yml
The `created` event type works only if a release was done without making a draft. But `published` type event is raised when a release, pre-release or a draft of a release is published. This will make sure the pipeline runs irrespective of draft state.
For more, read: https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#release
Change the trigger from `created` to `published`.
=> fix(cd): Use published event to build release pkgs

src/lib/php/Dao/PfileDao.php, src/lib/php/Dao/test/PfileDaoTest.php, src/lib/php/Test/testdata.sql, src/www/ui/api/Controllers/FileSearchController.php, src/www/ui/api/Helper/FileHelper.php, src/www/ui/api/Models/Findings.php, src/www/ui/api/documentation/openapi.yaml
Modify REST API's `/filesearch` endpoint to export copyright information in addition to license data. 
Added list of copyright statements to the findings object returned by the API. I'm not super familiar with the copyright aspects of Fossology, so would any feedback on the draft would be very welcome. I'm only querying the `copyright` table, should `copyright_decision` also be queried? 
Query `/filesearch` endpoint with a hash of a source file uploaded. Should return the copyright statements of the file.
=> feat(rest): get copyright info for file hash

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/Models/License.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Add API endpoint `/license` to search for licenses based on their short name.
Add the ability to search for licenses based on their short name. Returns the id, short name, full name and text.
Query `/license` endpoint with header `shortName` set to a license's short name. Should return the license's id, short name, full name and text. Querying with non-existing short name should return a proper error.
=> feat(rest): add license search based on short name

src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Models/Reuser.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml
This PR changes the data type of reuse_group from int to string. Fixes #1801.
The data type of reuse_group and reuseGroup is changed to string. The files affected are [Reuser.php](https://github.com/fossology/fossology/blob/master/src/www/ui/api/Models/Reuser.php), [openapi.yaml](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml) and [JobController.php](https://github.com/fossology/fossology/blob/master/src/www/ui/api/Controllers/JobController.php).
- Upload some files to scan and reuse a resource.
- There should be no console errors.
=> feat(reuse): Change data type of reuse_group from int to string.

src/www/ui/ui-clearing-view.php
Do not add decisions i case of global decision if events wont change.
* Make use of isDecisionWip function to check if decisions have been changed.
* Upload a component X and make global clearing to few files.
* Create another user and Upload component X by new users login.
* Scroll through files which have global clearing decisions.
* Check the history so that new decisions should not be added.
* Do end to end clearing testing, So that other clearing areas shouldn't break.
=> fix(globaldecision): do not add decisions if the events have no change

src/reuser/agent/ReuserAgent.php
Do no process clearing events or files if their pfile id is 0.
1. Add checks to pfile being 0.
2. Add checks to `diff` paths being empty.
Check #1411 and #1763
Closes #1411
Closes #1763
=> fix(reuser): Do not process pfiles with id 0

Dockerfile, RdfXml.php.patch, debian/control, src/Makefile, src/reportImport/reportImport.conf, utils/fo-installdeps
This PR will make reportImport agent special with `NOKILL`!
1. Apply patch to `easyrdf` to read xml files in chunk of 1 Mb.
2. Since the majority of computation time is consumed by the **easyrdf** plugin (specifically `xml_parse()`) which can not controlled by FOSSology, adding special flag `NOKILL` to the _reportImport_ agent.
1. Add patch for easyrdf plugin.
2. Add `NOKILL` to report import.
1. Try to import a large RDF file.
2. Check if Debian package installation works.
3. Check if Docker installation works.
Closes #1136
=> fix(reportImport): Read XML in chunks

src/decider/agent/DeciderAgent.php, src/lib/cpp/libfossAgentDatabaseHandler.cc, src/lib/cpp/libfossAgentDatabaseHandler.hpp, src/lib/php/BusinessRules/LicenseMap.php, src/lib/php/BusinessRules/test/LicenseMapTest.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Proxy/UploadTreeProxy.php, src/lib/php/Proxy/test/UploadTreeProxyTest.php, src/ojo/agent/OjoAgent.cc, src/ojo/agent/OjoAgent.hpp, src/ojo/agent/OjoState.cc, src/ojo/agent/OjoState.hpp, src/ojo/agent/OjoUtils.cc, src/ojo/agent/OjosDatabaseHandler.cc, src/ojo/agent/OjosDatabaseHandler.hpp, src/ojo/agent_tests/Functional/schedulerTest.php, src/reportImport/ui/template/ReportImportPlugin.html.twig, src/www/ui/async/AjaxExplorer.php
Create new OJO licenses as candidate licenses rather than main license as ojo looks for regex and can insert malicious licenses in DB.
Also, the auto decision of ojo findings was set to global which was causing some troubles, this PR also sets it back to local decisions only.
1. Insert new licenses by ojo in candidate table.
2. **Do not make ojo auto decisions as global.**
3. Fix UI and Unified report to show candidate licenses.
4. Fix ojo to not rescan files.
1. Create a sample file with `SPDX-License-Identifier` of a new license.
2. Check if the new license was detected my OJO but ends-up in candidate list.
3. Check if the reported license is shown in all UI views.
4. Check if the reported license is shown in reports.
5. Check if reuser can understand this new candidate license.
6. …
=> fix(ojo): New license as candidate

src/lib/php/Dao/TreeDao.php, src/www/ui/page/BrowseLicense.php, src/www/ui/ui-file-browse.php
Load parent folder while clicking on "License Browser" or "File Browser" from a file level view (Info, Conclusion, Copyright, etc.).
1. Check if loaded on a single file while creating menu for "License Browser" and "File Browser".
a. If yes, then find the parent item id and replace in the URL.
2. Added a new function `TreeDao::getParentOfItem()` to aid.
1. From various views, check if link to "License Browser" and "File Browser" are working.
2. While viewing a single file, the link to "License Browser" and "File Browser" should take to the containing folder.
=> fix(ui): Show parent folder on *Browser views

src/lib/php/Dao/UploadDao.php
`getStatus()` in `UploadDao` currently fetches a random entry. This causes confusion. Updated the function to match `getListOfUploadsOfFolder()` which fetches status based on upload id and group id.
Update `UploadDao::getStatus()` to match the group id as well.
**Note**: Default status returned will be 1 (open).
1. Upload a package from a user which has access to minimum 2 groups.
2. With group 1, change the upload status, to say rejected.
3. With group 2, change the upload status, to say closed.
4. The UI shows correct status to respective groups.
5. From the REST API, fetch the upload summary once with `groupName: group1` and once with `groupName: group2`. The `clearingStatus` should change based on group selected.
6. Fetch the upload summary from a third group with no status changes, …
=> fix(uploadDao): Fetch status based on group id

src/lib/php/Proxy/UploadTreeProxy.php
Fix the query to show result only if license is not a "No_license_found" or is a candidate license.
1. Change query to `WHERE (lr.rf_shortname NOT IN ('No_license_found', 'Void') OR lr.rf_shortname IS NULL) WHERE (lr.rf_shortname NOT IN ('No_license_found', 'Void') OR (lr.rf_pk IS NULL AND lc.rf_pk IS NOT NULL))`
=> fix(UploadTreeProxy): Get if candidate license

src/nomos/agent/json_writer.c
Fix observed race condition in Nomos JSON output caused by `printf` buffering.
Flush stdout after printing. When output is not a terminal, `printf` does not 
flush automatically and this results in overlapping output.
1. Compile Nomos standalone
2. Run JSON output against a directory of files
3. Observe validity of JSON output
This closes #1903
=> fix(nomos): Flush stdout in JSON writer

src/www/ui/api/Models/Group.php, src/www/ui/api/documentation/openapi.yaml
Signed-off-by: Piotr Pszczola <piotr.pszczola@orange.com>
Fixes #1900 
Added Group component to src/www/ui/api/documentation/openapi.yaml
Few naming fixes in src/www/ui/api/Models/Group.php
Swagger integration verification should not show any errors
=> fix(rest): missing Group component in API documentation

install/db/Makefile, install/db/dbmigrate_copyright-event.php, install/fossinit.php, src/cli/tests/test_fo_copyright_list.php, src/copyright/agent_tests/Functional/schedulerTest.php, src/copyright/ui/ajax-copyright-hist.php, src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/test/CopyrightDaoTest.php, src/reuser/agent/ReuserAgent.php, src/www/ui/core-schema.dat
Separate copyright status to another table. for better reuse.  
* Script to migrate old data.
* Create new _event table 
* End-to-end testing of copyrights with reuse.
=> feat(copyright): save deleted copyrights in copyright_event table

src/lib/php/UI/Component/Menu.php
Earlier the documentation page is giving proxy error but now the link has been updated
Updated the link with `https://github.com/fossology/fossology/wiki` on line no 38 in
/src/lib/php/UI/Component/Menu.php
Go to Help>Documentation
Issue Reference
#1941
=> updated the documentation link

install/db/dbcreate.in, install/db/fossologyinit.sql, src/lib/php/Test/fosstestinit.sql, src/lib/php/libschema.php, src/testing/db/TestDbFactory.php, src/testing/db/create_test_database.php, src/testing/db/fosstestinit.sql, src/testing/db/ftdbcreate.sh, src/testing/utils/dbcreate, src/testing/utils/testDBinit.sql, utils/prepare-test
Create the `uuid-ossp` extension as `postgres` user instead of `fossy`.
Create he extension where the `plpgsql` was created as `postgres` user.
On database without `uuid-ossp` extension (< 3.9.0 release).
Install fossology and run fo-postinstall.
The installation should finish without errors and extension `uuid-ossp` should be created.
=> fix(uuid-ossp): Create extension as postgres

docker-compose.yml
Revert the port binding of web container created by docker-compose to 8081 as documented in the README.
Change the port mapping from 8082 to 8081 for web container.
Do `docker-compose up` and check if `http://localhost:8081/repo` opens FOSSology.
Closes #1977
=> fix(docker-compose): Revert container port to 8081

utils/fo-debuild
Ubuntu Xenial is using old version of dpkg-buildpackage which does not understand `--no-sign` and does not create .buildinfo file.
Also, making the tar creation optional with the help of `--no-tar` flag.
1. Replace `--no-sign` flag with `-us -uc` which is backwards compatible.
2. Do not specify all files to move, let `*` glob do it.
3. Add `--no-tar` flag.
Run `./utils/fo-debuild` on supported OS with `--no-sign` flag.
=> fix(build): Make script compatible with Xenial

src/phpunit.xml, src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/Controllers/ReportController.php, src/www/ui/api/Controllers/UploadController.php, src/www/ui_tests/Makefile, src/www/ui_tests/api/Controllers/AuthControllerTest.php, src/www/ui_tests/api/Controllers/FolderControllerTest.php, src/www/ui_tests/api/Controllers/JobControllerTest.php, src/www/ui_tests/api/Controllers/ReportControllerTest.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php, src/www/ui_tests/api/Controllers/UserControllerTest.php, src/www/ui_tests/api/Controllers/VersionControllerTest.php, src/www/ui_tests/api/Helper/AuthHelperTest.php, src/www/ui_tests/api/Helper/DbHelperTest.php, src/www/ui_tests/api/Helper/RestHelperTest.php, src/www/ui_tests/api/Makefile, src/www/ui_tests/api/Models/AnalysisTest.php, src/www/ui_tests/api/Models/DeciderTest.php, src/www/ui_tests/api/Models/FileTest.php, src/www/ui_tests/api/Models/FolderTest.php, src/www/ui_tests/api/Models/InfoTest.php, src/www/ui_tests/api/Models/JobTest.php, src/www/ui_tests/api/Models/ReuserTest.php, src/www/ui_tests/api/Models/SearchResultTest.php, src/www/ui_tests/api/Models/UploadSummaryTest.php, src/www/ui_tests/api/Models/UploadTest.php, src/www/ui_tests/api/Models/UserTest.php, src/www/ui_tests/api/tests.xml
Adding unit test cases for REST API.
1. Some changes are done in `Contollers` to use Helper class to get userID and groupID.
1. Created new folder `src/www/ui_tests/api/` containing all the test cases.
1. Added test suite for REST API to `src/phpunit.xml`.
1. Run `make test-www` or `src/vendor/bin/phpunit -csrc/phpunit.xml --testsuite="Fossology PhpUnit Test Suite"` or check the Travis log.
Partial work on #1590
=> test(rest): Unit test cases for REST API

src/lib/php/Application/LicenseCsvExport.php, src/lib/php/Application/LicenseCsvImport.php, src/lib/php/Application/test/LicenseCsvExportTest.php, src/www/ui/template/admin_license_from_csv.html.twig
Include obligation topic as obligations in exported license CSv file.
Change query accordingly to add the obligation topic.
* Go to Admin -> License Admin -> Select license.
* Click on any license edit where obligations are there.
* Export CSV and check if the CSV have obligations column.
* Do the same for multiple license export.
* Check the license import from newly downloaded CSV.
=> feat(licenseExport): include obligation topic in exported CSV

debian/control, install/defconf/fossology.conf.in, src/scheduler/agent/database.c
For sending email in Ubuntu 20.04, s-nail is used as a dependency by fossology (#1614 ). 
In [S-nail v14.9.6](http://manpages.ubuntu.com/manpages/bionic/man1/s-nail.1.html) `smtp-auth-user` and `smtp-auth-password` flag is replaced by `mta`. Also `-S v15-compat` flag should be added for forward compatibility with s-nail v15
Updated the email command for [s-nail](http://manpages.ubuntu.com/manpages/bionic/man1/s-nail.1.html)
- Pull this branch
- Start PostgreSQL and apache 2
- Build and install from src in ubuntu 20.04
- Upload a file 
- Check if email notification for completion of fossology scan is received
=> fix(email): Update email command for s-nail

src/www/ui/template/user_edit.html.twig, src/www/ui/user-edit.php
* Update session variable on changing the username 
* Only allow the admin to change the username
* If the user provides an empty username then a blank white screen appears due to an internal server error
Closes #1112
Updated `$_SESSION['User']` if `$UserRec['user_name']` does not match `$_SESSION['User']`
1. Go to Admin->Users->Edit user account.
2. Change the value of the username for the current user (with active session).
3. Hit Update Account.
4. Goto Upload->(any page which allows selection of agents)
=> fix(username): update session variable on username change

src/reuser/agent/ReuserAgent.php
Closes #1884
When reusing a component, the agent log was getting printed which is not required.
Used the **exec** command instead of **system**
In the **copyClearingDecisionIfDifferenceIsSmall** function previously the system() command was used. While system executed the task fine it also displayed the output immediately(agent-log) which was unnecessary. I have used the exec function instead which executed the task but does not display the output.
1. Upload a file.
2. Do some clearing.
3. Upload the same file with a higher version and select the enhanced reuse feature which will compare with the previous file.
Previously when a file was uploaded, after doing some clearing uploading the same file with a higher version and using the **reuse** feature was printing the agent logs which are …
=> fix(reuser): removed agent log

src/www/ui/admin-license-file.php, src/www/ui/template/admin_license-upload_form.html.twig
While trying to read wrong license from `?mod=admin_license&rf_pk=<wrong_rf_pk>`, PHP throws error and displays an empty page.
This PR fixes that by showing an error message when the license id is invalid.
1. Add a new Twig variable `error` for license admin.
- If it is empty, show the page normally.
- If it is not empty, show the error message only.
2. Create the required `error` variable in case license ID is invalid.
1. Open `?mod=admin_license&rf_pk=<wrong_rf_pk>`, should show an error message.
2. Edit a valid license, should work as expected.
3. Create a new license, should work as expected.
=> fix(ui): Show error message for invalid license id

src/lib/php/Dao/ClearingDao.php, src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-common.js
When someone marked a whole folder as irrelevant, the `clearing_event`s for the files went missing. This causes data inconsistency while getting the license for those `clearing_decision`s.
1. Use `ClearingDecisionProcessor::makeDecisionFromLastEvents()` to generate `clearing_decision` and `clearing_event`.
2. The functions `markDirectoryAsDecisionTypeIfScannerDetected()` and `markDirectoryAsDecisionTypeIfUserEdited()` were no longer required to be separate and thus replaced with `markDirectoryAsDecisionTypeRec()`.
3. Handle errors in UI script if AJAX call fails.
1. On old branch, upload a package and mark a folder as irrelevant using either `[Edit]` under Actions column or use the checkbox.
2. Check the clearing history for the files inside the folder, the license name will be missing. …
=> fix(decision): Create clearing events for irrelevant folder decisions

src/www/ui/template/ui-export-list.html.twig, src/www/ui/ui-export-list.php
1) Consolidate findings of scanners into one.
2) Consolidate findings per file into per directory
UI at Export Lists is slightly changed. There are three options. 1) raw, 2) per file, 3) per directory.
For 2) and 3), list of licenses at each row on the license list are merged into one.
For 3), list of files that has same result is merged into one row.
The result will be provided both on the browser and downloaded CSV file.
Go to an upload > Export Lists
Select one of option at '5. Consolidate Results?'
Generate list. (You can print it on the browser or download the list.)
=> feat(export) : Consolidating results per file or directories

install/db/dbcreate.in
Sometimes when we stop and start the docker instance.
We get the following error message:
psql: FATAL:  the database system is starting up
ERROR: postgresql isn't running
It doesn't mean that the postgresql is not running.
It means postgresql is preparing to start.
So we might need to check for a while and wait.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
When we stop and start an instance of docker. We sometimes got the following log: 
```
*****************************************************
WARNING: No database host was set and therefore the
internal database without persistency will be used.
THIS IS NOT RECOMENDED FOR PRODUCTIVE USE!
*****************************************************
Starting PostgreSQL 9.6 database server: main.
*** Running postinstall for common …
```
=> feat(dbcreate): retry psql check while starting

src/Makefile, src/www/ui_tests/api/Controllers/UploadControllerTest.php, src/www/ui_tests/api/Models/SearchResultTest.php, src/www/ui_tests/api/Models/UploadSummaryTest.php, src/www/ui_tests/api/Models/UploadTest.php
Add the new "assignee" attribute to "Upload" and "UploadSummary" objects in REST API test cases.
Added new envar `COMPOSER_ALLOW_SUPERUSER` to allow composer 2 to run under root user.
1. Fix REST API test cases.
2. Add `COMPOSER_ALLOW_SUPERUSER` to `composer_install` make target allowing root user to run composer.
Check travis test logs.
=> fix(test): Add new assignee attribute to REST

src/decider/agent/BulkReuser.php, src/lib/php/Dao/LicenseDao.php, src/monk/agent/database.c, src/monk/agent/database.h, src/monk/agent/monkbulk.c, src/monk/agent/monkbulk.h, src/www/ui/change-license-bulk.php, src/www/ui/core-schema.dat, src/www/ui/scripts/change-license-common.js, src/www/ui/template/ui-clearing-view_bulk.html.twig
Allow user to choose if they want to ignore irrelevant files while doing a monkbulk scan or not.
The existing scanner ignores irrelevant files by default but works on pfile. While inserting the data back, this pfile needs to be translated into `uploadtree_pk`. During this translation, if a pfile occurs multiple times and is marked as irrelevant in some places but not in other, will include all `uploadtree_pk` which is undesirable.
This PR fixes that by checking `clearing_decision` while inserting new results as well.
Also, depending on the user's selection of **Ignore Irrelevant files** checkbox, the queries will consider or ignore the `clearing_decision`.
1. Upload a package where same file is copied in multiple folders.
2. Do a normal scan on the upload and mark some of the folders with …
=> feat(monkbulk): Configurable irrelevant file scan

src/lib/php/common-sysconfig.php, src/maintagent/agent/maintagent.c, src/maintagent/agent/maintagent.h, src/maintagent/agent/process.c, src/maintagent/agent/usage.c, src/maintagent/ui/maintagent.php
Created a new job in maintenance agent to clean inactive tokens from database which are expired X days ago.
Closes: #1303 
- Added option to edit Max expired token retention period in Admin > Customize page
- Created option to trigger the new job from CLI by passing an additional parameter
- Option to trigger the job from GUI
- Fixed the broken link of Maintenance agent documentation
- Run the agent from CLI ` sudo src/maintagent/agent/maintagent -t 30 `
- Run the agent from GUI
=> feat(maintagent): add job to remove expired tokens from database

src/lib/c/libfossdbmanager.h, src/lib/cpp/libfossdbQueryResult.hpp, src/lib/cpp/libfossdbmanagerclass.hpp
glib headers may use C++ for some constructs, and they provide 'extern "C"' around the needed sections of there code already. Otherwise compilation may fail like this:
```
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
from /usr/include/glib-2.0/glib/gthread.h:32,
from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
from /usr/include/glib-2.0/glib.h:32,
from ../../../src/lib/c/libfossdbmanager.h:24,
from libfossdbmanagerclass.hpp:23,
from libfossAgentDatabaseHandler.cc:18:
/usr/include/c++/10/type_traits:56:3: error: template with C linkage
56 |   template<typename _Tp, _Tp __v>
|   ^~~~~~~~
```
=> remove wrong 'extern "C"'

src/lib/php/Dao/ClearingDao.php, src/www/ui/ajax-clearing-view.php, src/www/ui/css/fossology.css, src/www/ui/scripts/change-license-common.js
The Modal dialog to select a notice file for acknowledgement does not had max-height. Thus, if an upload contains many NOTICE files, it becomes very hard to scroll. Also, the inner elements of the dialog were draggable, which is not required.
1. Add a scroll bar to notice file selection modal for acknowledgement, done by setting setting the max-height of the dialog to 70% of the viewport.
2. Remove the unnecessary draggable for the inner elements of modal.
3. Add additional UTF-8 checks to license browser.
1. Upload a file with many NOTICE files.
2. Goto license browser and add an acknowledgement.
3. Click on "Select from Notice file".
- The modal dialog should not exceed 70% height of the page.
- The inner elements of the dialog should move with the modal, not separately.
=> fix(ui): Add scroll to NOTICE file modal

.github/workflows/conflict-check.yml
Use GitHub actions to mark PRs with merge conflicts with label "has merge conflicts".
1. Create a new GitHub Action workflow which scans for dirty PRs when a merge to master happens.
Check test runs on fork:
- When a PR becomes dirty (has conflict): https://github.com/GMishx/fossology/runs/2601394675?check_suite_focus=true#step:2:11
- When a PR is already dirty: https://github.com/GMishx/fossology/runs/2601483615?check_suite_focus=true#step:2:12
- Labeled PR: https://github.com/GMishx/fossology/pull/25
=> feat(ci): Mark PRs with conflict with Actions

src/copyright/ui/HistogramBase.php, src/copyright/ui/TextFindingsAjax.php, src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/template/histTable.js.twig, src/spasht/ui/ajax-spasht-copyright-hist.php, src/spasht/ui/template/agent_spasht_ui_tabs.html.twig, src/spasht/ui/template/spasht_histTable.js.twig
Multiple undo option for deactivated copyrights. 
* add a checkbox to select deleted.
* add a new button to submit.
* Upload a package and deactivate some copyrights
* Go to deactivated statements and select multiple statements 
* Click on "Undo selected rows".
Closes #1928
=> feat(copyright): add bulk undo for deactivated copyrights

src/www/ui/scripts/browse.js
Use cookies to remember the assignee filter value on the Browse view.
1. Add new session cookie "assigneeSelected" to hold the filter value.
1. On the browse view, filter the uploads based on assignment information.
2. Open an upload, perform some action and go back to browse.
3. The uploads should still be filtered by the assignee selected.
Closes #1927
=> feat(ui): Remember assignee filter on Browse view

src/copyright/ui/HistogramBase.php, src/spasht/ui/template/agent_spasht_ui_tabs.html.twig, src/www/ui/css/jquery.dataTables.css
Break very long lines with the help of CSS properties.
Created new class `wordbreaktable` which can be applied on tables and apply `word-break` & `overflow-wrap` properties to all `td`s.
Scan an upload with very long copyrights which can not be broken.
I tested it with [Angular-9.1.1](https://github.com/angular/angular/releases/tag/9.1.1). Copyright captures a string with a very long base64 string which breaks the UI.
=> fix(ui): Break long lines in copyright table

src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/list.php, src/lib/php/Dao/CopyrightDao.php, src/reuser/agent/ReuserAgent.php
While editing/fetching the copyrights, the association with uploadtree_pk was not very strong. It caused issue while editing copyrights from a single file view instead of aggregated table view.
This causes problem when same upload has duplicate files. Since `copyright` table holds information of `pfile_fk` and `agent_fk` only, there will be only one entry for a copyright in those files. But if someone made some changes, the `copyright_event` is involved which takes `uploadtree_fk` into account. This caused ambiguity on which copyright to show.
1. Add checks for `uploadtree_fk` while fetching copyrights to get only relevant copyrights.
2. Update the check while inserting edits in `copyright_event` to make sure all `uploadtree_fk` are updated.
1. Upload a package with duplicate files which …
=> fix(copyright): Make check strict

src/nomos/agent/STRINGS.in, src/nomos/agent/parse.c
Improved nomos MPL-2.0 detection
added a regex for MPL-2.0 detection
added the same in the parse.c
use this text to check the PR
```
Eigen is primarily MPL2 licensed. See COPYING.MPL2 and these links:
http://www.mozilla.org/MPL/2.0/
http://www.mozilla.org/MPL/2.0/FAQ.html
Some files contain third-party code under BSD or LGPL licenses, whence the other
COPYING.* files here.
All the LGPL code is either LGPL 2.1-only, or LGPL 2.1-or-later.
For this reason, the COPYING.LGPL file contains the LGPL 2.1 text.
If you want to guarantee that the Eigen code that you are #including is licensed
under the MPL2 and possibly more permissive licenses (like BSD), #define this
preprocessor symbol:
EIGEN_MPL2_ONLY
For example, with most compilers, you …
```
=> fix(nomos): improved nomos MPL-2.0 detection

src/www/ui/scripts/change-license-common.js
Since the license text is read from the "title" of the element, which is already [HTML encoded in PHP](https://github.com/fossology/fossology/blob/84a1897e32cc6556713f6efabd3c9ea3bd0dd4c7/src/www/ui/ajax-clearing-view.php#L282), the textarea should be decoded first.
1. Use jQuery trickery to decode HTML with `htmlDecode()`.
2. Use the decoded value to fill textarea.
1. Edit a license text and add some HTML characters like `&`, `"`, `'`, `<` or `>` in the license text.
2. Submit the decision and edit the same license text again.
- In master branch, the special characters will be shows in HTML &amp; style.
- In this branch, they should be shown in human readable format.
3. Check the above points for bulk license text as well.
=> fix(ui): License text editor

debian/control
Add `php-gd` dependency to Debian `fossology-web` package required by `PhpOffice\PhpSpreadsheet`.
- Build and install debian packages.
- Check if you can export spreadsheet of licenses.
See #1958 for more.
=> fix(debian): Add php-gd package as dependency

src/www/ui/template/ui-clearing-view_bulk.html.twig, src/www/ui/template/ui-clearing-view_rhs.html.twig
Fix the modal box height for small screens.
Change the `max-height` for non-popup modal to fix the content, rather than view-port.
Open single file view and check the modals created for "User decision", "Bulk Recognition" and "Clearing History". The brown background should cover the whole content.
=> fix(ui): Fix the modal height for small screens

src/www/ui/api/Models/Reuser.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Models/ReuserTest.php
Add the missing "Reuse report conf" and "Reuse deactivated copyright" options to the REST API.
Added `reuse_report` and `reuse_copyright` to reuser object in REST API.
Create a new job with REST API using new options.
=> fix(api): Add missing reuser options

.gitignore, src/www/ui/api/Controllers/UserController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UserControllerTest.php
Add `/self` endpoint to `/users` to allow user to get their information.
Currently if non-admin users `GET /users` they get only their info but if admin users do that, they get info about every user which is not helpful in all cases.
1. Add new `/users/self` endpoint.
1. Test if the endpoint returns only one user's info regardless if you are admin or not.
Closes #2017
=> feat(rest): Add /users/self endpoint

src/lib/php/Dao/LicenseDao.php, src/phpunit-bootstrap.php, src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Models/License.php, src/www/ui/api/Models/Obligation.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/FolderControllerTest.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php, src/www/ui_tests/api/Models/LicenseTest.php, src/www/ui_tests/api/Models/ObligationTest.php, src/www/ui_tests/api/Models/ScanOptionsTest.php
Added new POST and PATCH endpoints to `/license` for creating and editing licenses from REST API.
The GET to `/license` is also edited. Now, the request without license name will list every license (paginated). Request to `/license/<shortname>` will list just the requested license but will also include the obligations associated to it.
1. Added the POST and PATCH endpoints to `/license`.
2. New model `Obligation`.
3. Added `/license` endpoint for listing all licenses.
4. Update `/license/<shortname>` endpoint to list license obligations.
1. Try to get all the licenses from the `/license` endpoint and check if they matched the DB.
2. Check the pagination feature of the `/license` endpoint.
3. Check the obligation list of a license with `/license/<shortname>` endpoint.
4. Try creating a new …
=> feat(rest): Add POST/PATCH license endpoints

install/defconf/fossology.conf.in, src/www/ui/core-auth.php
When introducing the 'default visibility' feature, the call to `add_user` had not been updated, and therefore the user creating was failing.
I added a configuration entry in `fossology.conf` to configure the default visibility for new user creations, and used it for new user creations.
Configure external configuration, then log in with a user that is not already in the database.
The user should be assigned the "default visibility" that is configured in the `fossology.conf`  file
=> fix(auth): fix call to add_user() when login from external auth

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Filter licenses based on query from `/license` endpoint. Possible values:
- `?kind=all`
+ Get all licenses
+ Default option
- `?kind=candidate`
+ Get only candidate licenses
- `?kind=main`
+ Get only main licenses
1. Added new query parameter `kind` to `/license` endpoint.
1. List of licenses with and without `?kind=all` should be same from endpoint.
2. List candidate licenses with `?kind=candidate`.
3. List main licenses with `?kind=main`.
Closes #2045
=> feat(rest): Filter licenses by kind

src/ojo/agent/OjoAgent.cc, src/ojo/agent/OjoAgent.hpp, src/ojo/agent/OjoUtils.cc, src/ojo/agent/OjosDatabaseHandler.cc, src/ojo/agent/OjosDatabaseHandler.hpp
With the new audit information added for `license_candidate` table, add `rf_user_fk_created` and `rf_user_fk_modified` from ojo while creating new candidate license.
Add the user id for `rf_user_fk_created` and `rf_user_fk_modified` while creating new candidate license.
1. Create dummy package with `SPDX-License-Identifier` where the license name does not exists in main license table.
2. Ojo should create new candidate license for the file.
3. Edit the license and check the "User Created" and "User Modified" fields.
=> fix(ojo): Set candidate license creator

src/copyright/ui/copyright-hist.php
Changing copyright browser menu text and tool-tip text from `copyright agent/user findings` to `copyright`.
Signed-off-by: Sarita Singh <saritasingh.0425@gmail.com>
- Install copyright and www agent
- Upload a file and check `Copyright Browser`
=> fix(copyright):Change menu text of copyright page

.gitpod.Dockerfile, .gitpod.yml, README.md, install/db/Makefile, install/db/dbcreate.in, install/db/gitpod-fossologyinit.sql, install/defconf/fossology.conf.in, utils/gitpod-install.sh
Initial commit for [gitpod.io](https://gitpod.io) integration.
- Way to do simple `make install`.
- The base image is tagged to `latest`, does not have specific tag for `focal`.
- Didn't check the behavior of `make test`.
- Since gitpod stores contents under `/workspace/` only, the FOSSology needs to be installed under it.
+ To implement this, following paths needed to be changes: `PREFIX`, `INITDIR`, `REPODIR`, `LOCALSTATEDIR`, `APACHE2_SITE_DIR`, `SYSCONFDIR`, `PROJECTUSER` and `PROJECTGROUP`.
- Changing the group of user in gitpod is difficult so FOSSology and DB are installed/setup under `gitpod:gitpod`.
- New aliases:
+ `fossrun` : Runs scheduler in shell, not as daemon
+ `fossinstallclean` : Runs `make clean` and then `make install` with all the appropriate path changes. Followed …
=> feat(gitpod): Inital contribution

debian/fossology-scheduler.logrotate, pbconf/fossology/deb/fossology-scheduler.logrotate
Send the `SIGHUP` to scheduler after log rotation to reload config in-turn closing old log file and opening the new file created by `logrotate`.
The other option will be to use `copytruncate` flag which requires no signal generation but might cause loss of logs written during the rotation.
1. Add `postrotate/endscript` to logrotate config to send `SIGHUP`.
1. Add `su fossy fossy` as the log files by default are generated under `fossy` user and not `root`.
1. Install the logrotate file (or install fossology as deb package).
1. Wait for the log to rotate (or change the rotation condition and trigger manual rotation).
1. Check if scheduler works after rotation.
1. Check if scheduler writes to the new log file.
**Note:** Please check the behaviour of SIGHUP if there are some agents in running …
=> fix(logrotate): Send SIGHUP

.github/workflows/release-publish.yml, .travis.yml, Makefile.conf, Vagrantfile, src/copyright/mod_deps, src/lib/php/Dao/LicenseDao.php, src/lib/php/Util/StringOperation.php, src/mimetype/agent_tests/Functional/cliParamsTest4Mimetype.php, src/nomos/mod_deps, src/ojo/mod_deps, src/ununpack/agent_tests/Functional/cliParamsTest4UnunpackNormal.php, utils/fo-debuild, utils/fo-installdeps, utils/utils.sh
Drop support for Ubuntu Xenial as it [reached its EOL](https://help.ubuntu.com/community/EOL#Ubuntu_16.04_Xenial_Xerus). This means upgrading Travis jobs and Vagrant box too.
Also, there is an interesting observation that git does not print tag information in the format introduced in #1768 if the tag is on current commit. This causes Debian builds to fail.
The solution is to make format more flexible and add additional 0 revision.
This PR also updates the Vagrant box from Ubuntu Xenial to Ubuntu Focal!
1. Drop support for Ubuntu Xenial.
2. Update Travis jobs from Xenial to Bionic
- Not update to Focal due to limited PHP support.
- See supported versions for Bionic: https://docs.travis-ci.com/user/reference/bionic/#php-support
- See supported versions for Focal: …
=> chore(os): Drop xenial support for eol

src/lib/php/Data/Spasht/Coordinate.php, src/lib/php/Data/Spasht/DefinitionSummary.php, src/spasht/ui/template/agent_spasht.js.twig, src/spasht/ui/template/show_definitions.html.twig, src/spasht/ui/template/show_details_table.html.twig, src/spasht/ui/ui-spasht.php
Display scores from ClearlyDefined in Spahst configuration.
The effective is only considered here. Can be extended to tool scores.
1. Update the Coordinate object to hold score information.
2. Update the DefinitionSummary ro hold score information.
3. Filter search results based on scores (desc) by default.
4. Update show_definitions and show_details tables with score.
1. Upload a package and goto "Spasht" configuration page.
2. Search for package and check the score in the results.
- They should be available on the result and details table.
Closes #1964
=> feat(spasht): Show effective score

src/unifiedreport/agent/unifiedreport.php, src/unifiedreport/ui/agent-foreport.php
By default, unified report saves traceback URL in `jq_cmd_args`. For UI jobs, it will be `http://localhost/repo/` (or as server's location).
If the report is generated from REST API, it gets changed to `http://localhost/repo/api/v1/report`
This URL is then used to populate the "Fossology Upload" field in unified report.
Add filters to remove everything after `api/` from the traceback URL while generating jobs and report.
1. Add filter to remove `api/.*` from URL while generating job.
2. Add the same filter while generating report.
1. Before installing branch, create a unified report from UI and check the "Fossology Upload" field.
2. Create a unified report from REST API and check the "Fossology Upload" field.
3. Install the branch and generate report from REST API and check the "Fossology …
=> fix(unifiedreport): Fix upload link for API

.github/workflows/docker-build.yml, .github/workflows/release-publish.yml
Since [free auto builds are no longer available on Docker Hub](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/), use GitHub Actions to build the image and push to Docker Hub.
1. Added new build workflow for builds on push to master and release which will build the "fossology/fossology:latest" and "fossology/fossology:scanner" images.
2. Modify release workflow to add build steps for "fossology/fossology:<release_version>" images.
Check the build logs from: https://github.com/GMishx/fossology/runs/3277301909?check_suite_focus=true#logs
Since builds are using QEMU and Buildx, there is a posibility to compile fossology for other architectures as well. I did [a trial with linux/arm64](https://github.com/GMishx/fossology/runs/3263935510?check_suite_focus=true#logs) but it was …
=> ci(actions): Build Docker images in Actions

Dockerfile
Recently, docker build has been failing with that error message:
```
INFO[0357] Running: [/bin/sh -c mkdir /usr/share/man/man1 /usr/share/man/man7  && DEBIAN_FRONTEND=noninteractive apt-get update  && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends       curl       lsb-release       sudo       cron       python       python3       python3-yaml       python3-psycopg2       python3-requests  && DEBIAN_FRONTEND=noninteractive /fossology/utils/fo-installdeps --offline --runtime -y  && DEBIAN_FRONTEND=noninteractive apt-get purge -y lsb-release  && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y  && rm -rf /var/lib/apt/lists/*] 
mkdir: cannot create directory '/usr/share/man/man1': File exists
mkdir: cannot …
```
=> fix (build): do not fail is /usr/share/man* folders already exist

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Provide 4 new filters while listing uploads:
- `name`
+ Allow filter uploads based on name and description.
+ *Example:* `?name=foss`
- `status`
+ Filter uploads with status as `Open`, `InProgress`, `Closed`, `Rejected`.
- `assignee`
+ Filter uploads assigned to someone.
+ Expects username as the value not the numerical userid.
+ Special value `-me-` (for self) and `-unassigned-` (for unassigned).
- `since`
+ Uploads which are done since the given date (`YYYY-MM-DD`).
+ Note, the check is `>=`.
All the filters, along with `folderId` can be combined to get desired result. For example "All uploads in folder 4 which are assigned to me, have word "python" in description, are in progress and uploaded after 1st Feb" can be fetched with
`GET …
=> feat(rest): Filter uploads with 4 new parameters

src/www/ui/api/Controllers/AuthController.php, src/www/ui_tests/api/Controllers/AuthControllerTest.php, src/www/ui_tests/api/Models/AnalysisTest.php, src/www/ui_tests/api/Models/UserTest.php
`AuthController` class went missing since PR #2064
Added it back and adjuster few test cases.
1. Added `AuthController` back.
2. Fix API test cases.
1. Try to create a new token from API.
2. Send a CORS pre-flight (`OPTIONS` request).
=> hotfix(api): Add missing auth controller

src/unifiedreport/agent/reportSummary.php, src/unifiedreport/agent/unifiedreport.php
* Assigned to information from browse page was missing in report.
*  Renamed "Prepared by" to "Report Created by"
* New row in OSS Component Clearing report table, Analyzed by to capture Assigned to information.
* Generate unified report with different assigned to information. 
* Check  Analyzed by row.
=> feat(unifiedreport): include assigned to in component clearing section

src/lib/php/UI/template/include/upload.html.twig
Fix the template issue for upload page.
Fix syntax error in upload page form.
1. Upload a file with description, check in browse page, the description will be missing.
2. Install the fix and repeat steps above, the description should be there.
=> fix(upload): Fix upload description input

.github/workflows/static-checks.yml
As the current api linter is not working, updated the OpenAPI linter from outdated repo to actual repo of `@stoplightio/spectral-action`
Change linter action.
See the Actions log.
=> fix(ci): Update OpenAPI lint

src/www/ui/user-edit.php
Currently, the username field for non-admin users are disabled. It cause any update request to fail.
Added a check if field is empty and user is non-admin, update it with with user id from session.
1. Login as admin user, goto Admin > Users > Edit User Account and update some field.
2. Login as non-admin user, goto same page and edit some fields (like password).
=> fix(login): Allow non-admin user to update

src/www/ui/api/documentation/openapi.yaml
Here, a tiny typo slipt through:
https://github.com/fossology/fossology/blob/107d44e2c125d8234291b49e8aab50e8198f77e5/src/www/ui/api/documentation/openapi.yaml#L1690
The PR fixes `reuse_uplod` to `reuse_uplod`
=> fix(rest): fix typo in openapi.yaml, s/reuse_uplod/reuse_upload/

.github/workflows/release-publish.yml
For release package builds, do not fail the complete build if one matrix item fails.
See https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error
Add `continue-on-error: true` for `release-build` step.
=> chore(cd): Continue release build on failure

src/reportImport/agent/ReportImportSink.php
Fix `LicenseDao` interfaces in report import agent.
Fix calls to following functions:
- `insertUploadLicense()`
- `updateCandidate()`
- `insertClearingEvent()`
1. Clear an upload with new licenses not available in test server.
2. Export SPDX RDF report.
3. Import the report in test server.
Check:
=> fix(reportImport): Fix interfaces in report import

src/nomos/agent/STRINGS.in, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/See-file/ContainerRuntimeLoaderTest.php
While looking out for files with `See-file.LICENSE` regex, look for "view" as an alternative for "see".
For example, "please view the LICENSE file" and "please see the LICENSE file" to be matched.
Change the regex for SEE_FILE with `(see|view)` instead of `see`.
Scan a file which contains wordings like "please view the license file for usage".
Tested with https://github.com/twigphp/Twig/tree/v1.38.4
=> feat(nomos): See file regex to include view

src/nomos/agent/STRINGS.in, src/nomos/agent/parse.c
Added new pattern `_LT_SEE_URL_ref2` to identify strings using following regex:
`licen[cs]e.{0,30}(https?|ftp).{0,60}\/licen[cs]es?`
It will match strings like
"// License: https://github.com/my-project/LICENSE"
New pattern `_LT_SEE_URL_ref2` added for `See-URL`.
Scan a package with interesting lines.
Tested with https://github.com/zzzprojects/html-agility-pack
=> feat(nomos): New see-url pattern

pbconf/fossology/rpm/fossology.spec, src/spdx2/Makefile, src/spdx2/agent/Makefile, src/spdx2/agent/spdx2.php, src/spdx2/agent/template/spdx2csv-document.twig, src/spdx2/agent/template/spdx2csv-file.twig, src/spdx2/agent/template/spdx2csv-package.twig, src/spdx2/spdx2csv.conf, src/spdx2/ui/Makefile, src/spdx2/ui/SpdxTwoCommaSeparatedValuesAgentPlugin.php, src/spdx2/ui/SpdxTwoGeneratorUi.php, src/www/ui/async/AjaxShowJobs.php
Add a new CSV Report type.
The following fields are exported:
- FileName
- SPDXID
- LicenseConcluded
- LicenseComment
- LicenseInfoInFile
- FileCopyrightText
- A new report entry was added to the drop-down action list
- A new `SpdxTwoCommaSeparatedValuesAgentPlugin` was introduced, see `src/spdx2/ui/SpdxTwoCommaSeparatedValuesAgentPlugin.php`
1. Trigger new scan
2. Browse to new upload, open Action dorp down action list, choose `Export CSV Report`
```
FileName,SPDXID,LicenseConcluded,LicenseComment,LicenseInfoInFile,FileCopyrightText
PackageName: clementine-player-master.tar.gz - PackageFileName: clementine-player-master.tar.gz
clementine-player-master.tar.gz/clementine-player-master.tar/3rdparty/libmygpo-qt/qjsonwrapper/Json.cpp,SPDXRef-item1125366,"MIT",,"MIT","Copyright 2014, Uwe L. …
```
=> feat(reports): Add new CSV report type

src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-common.js, src/www/ui/scripts/change-license-view.js, src/www/ui/template/ui-clearing-view_bulk.html.twig, src/www/ui/template/ui-clearing-view_rhs.html.twig
Fix bulk modal to go full screen with a selectable background.
1. Revert changes to modal.
2. Add new event listener `shown.bs.modal` to update CSS properties of modal.
3. Update `draggable` function to not update width for `#bulkModal`.
1. Open a file for clearing.
2. Open the bulk modal.
1. The background text from file should still be selectable.
2. Adding new license should work as expected with select 2 search bar.
3. Other child modals like "License text" should work as expected.
3. On folder view, open bulk modal from `[Bulk]` link.
- Everything should work as mentioned in point 2.
=> fix(ui): Fix bulk modal with selectable bg

src/www/ui/api/documentation/openapi.yaml, src/www/ui/ui-download.php
Set the `Content-Type` headers while downloading reports.
Currently the header is missing causing issues with REST API clients.
Check if report is docx or spdx and set `Content-Type` header to `application/vnd.openxmlformats-officedocument.wordprocessingml.document` or `application/xml` respectively. For other reports, set header to `text/plain`.
Generate reports from UI and REST API and check for `Content-Type` header.
Closes #1767
=> fix(report): Set content type header

Makefile.conf, src/www/ui/api/Controllers/InfoController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Controllers/InfoControllerTest.php
﻿Export version information about the server on REST API. Information includes:
- Version
- Branch Name
- Commit Hash
- Commit Date
- Build Date
The date stored in VERSION file is also changed to include timezone in `+hh:mm` format to avoid confusion with abbreveated timezones. PHP for some reason confuses `IST` and reports `Europe/Istanbul` (TRT), not `Asia/Kolkata`.
1. Added new object `fossology` to `/info` endpoint with all the information.
2. Update `WriteVERSIONFile` function to use `%:z` timezone format.
1. Install the branch and check if the UI shows new timezone format.
2. Call `/info` endpoint and check if the response contains all the required fields.
=> feat(rest): Provide server version on REST api

src/decider/agent_tests/Functional/schedulerTest.php, src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/test/ClearingDaoTest.php, src/www/ui/async/AjaxExplorer.php, src/www/ui/ui-clearing-view.php
Refactor following functions into one (isDecisionCheck).
* isDecisionWip
* isDecisionTBD
* isDecisionDnu
* isDecisionIrrelevant
* getClearingType
* add new functions where ever required.
* Apply some decisions as do not use and to be discussed and check clearing status color in treeview.
* Test if global decisions were getting applied to file with WIP decision.
=> refactor(clearingDao): add few functions to a single one

src/www/ui/template/browse_file.js.twig
Signed-off-by: Rohit Pandey <rohit.pandey4900@gmail.com>
Added "ALL" option license browser table for #2110 
Added a new "ALL" option
1. Go to license browser table
2. For table length select ALL
3. You will see all the licenses
closing #2110 
=> feat(lbtablelength):Added all for license browser table

src/lib/php/UI/template/include/upload.html.twig, src/reuser/ui/template/agent_reuser.html.twig, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/page/UploadFilePage.php, src/www/ui/template/upload_file.html.twig, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Allow users to upload multiple files from "Upload from file" page.
Currently only description can be changed per upload file. Rest of the fields are considered common for all files.
Reuser options are disabled if more than 1 file is being uploaded.
More suggestions are welcome.
1. Change file input to array `[]`.
2. Change description input for file upload as array `[]`.
3. Modify REST API to mimic multifile upload.
1. Upload a single file and set the description.
2. Upload multiple files and set their respective descriptions.
Closes #2006
=> feat(upload): allow multifile upload from UI

src/lib/php/Dao/UserDao.php, src/www/ui/api/Helper/AuthHelper.php, src/www/ui/core-auth.php, src/www/ui/core-schema.dat, src/www/ui/page/AdminGroupUsers.php, src/www/ui/template/user_edit.html.twig, src/www/ui/user-edit.php
There are two GDPR related features in this PR:
**Deactivate users:**  
New user status to prevent users from logging in (or using existing tokens) without removing the account altogether.
This is handy to block account left unused for a long time, or block users (for ex. because they left the company) while keeping decision history as it is.  
If user is logged in wile being deactivated, s·he is not kicked out
**Store the "last connection date" for each user as a timestamp in the database**  
This is necessary to detect accounts left unused for some time. As simple SQL script can then list all users who have not connected for 6 months for example.
**Future features**  
- Another *anonymized* user status might be handy to keep the users in the database while allowing the removal of their …
=> feat(gdpr) deactivate users + Store last cnx timestamp

src/lib/php/Dao/ClearingDao.php
Add statement name incase of global and without-global to fix reuse.
Add Statement-name.
* Upload a component.
* Add global and local decisions.
* Upload the same component again and reuse the decisions.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2164"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(global): add statement name for global query to fix reuser

src/www/ui/ui-browse.php
Redirect user from browse view to license browser if upload contains single file.
See #496 for details.
In `ui-browse`, check if given item is a file and parent of the upload contains only 1 file. Then redirect to the license browser view.
1. Upload a single file (not compressed).
2. Click on the file name in job view.
- Should be redirected to License browser.
3. Upload a compressed file.
4. Click on the file name in job view.
- Normal browse view should be displayed.
- Navigating though the upload should have no effect.
Closes #496
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2160"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(browse): redirect to license view if empty

src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-common.js, src/www/ui/scripts/change-license-view.js, src/www/ui/template/ui-clearing-view_bulk.html.twig
Signed-off-by: rohitpandey49 <rohit.pandey4900@gmail.com>
Added 'Clean Text' button in license text field for #2108 
Added 'Clean Text' button
1. Go to change concluded license
2. Click on license text field
closing #2108 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2161"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(dev-ctbutton): Added clean text button at license text field

src/clixml/agent/clixml.php, src/clixml/agent/template/clixml-file.xml.twig, src/clixml/ui/CliXmlGeneratorUi.php, src/lib/php/Dao/SpashtDao.php, src/lib/php/Data/Package/ComponentType.php, src/lib/php/Util/PurlOperations.php, src/spasht/ui/ui-spasht.php, src/spdx2/agent/spdx2.php, src/spdx2/agent/template/spdx2-package.xml.twig, src/spdx2/agent/template/spdx2tv-package.twig, src/unifiedreport/agent/reportSummary.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/ui-report-conf.php
Read package information (called "Component Id") and type of information from report conf page. Possible values are "purl, maven, npm, nuget and pypi". If the information is a [purl](https://github.com/package-url/purl-spec), it can be parsed to extract coordinates for Spasht agent.
The information is also presented in CLI, Unified report and SPDX RDF & Tag/Value reports.
1. New columns `ri_component_type` and `ri_component_id` in `report_info` table.
2. New class `PurlOperations` to parse pURLs to extract ClearlyDefined coordinates.
3. New class `ComponentType` as an enum.
3. New field `ExternalRef` in SPDX reports.
4. New field `ComponentId` in CLI report.
5. New field `Component Id` in Unified report.
1. Upload a component.
2. Edit the report conf for the component and add component …
=> feat(report): accept package URL

src/www/ui/api/Helper/AuthHelper.php, src/www/ui/api/Helper/UploadHelper.php
Fix REST API for file upload.
1. Rename the variable `$symfonyFile` to `$uploadedFile`.
2. Check if DB row exists before looking for value in AuthHelper.
Create uploads from file and VCS.
Closes #2178 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2179"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> hotfix(rest): fix file upload

src/www/ui/api/Helper/AuthHelper.php
Fix token scope for OAuth. Change it to `read` or `write` based on `r` and `w` values from DB, respectively.
Change `r` to `read` and `w` to `write` for OAuth scope.
1. Add OAuth client with read/write scope and use it for REST API authentication.
2. Create a request which is not `GET`.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2184"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> hotfix(rest): fix scope for oauth

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper/HelperToUploadFilePage.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Removed unnecessary subindex to return full uploadId instead of first digit only
When uploading a package from URL via the API, the uploadId in the response is not complete, but only the first digit. This is caused by an unnecessary "subindex", which was removed. Maybe this issue was created with a change in the database structure.
Removed subindex for array $uploadResponse.
This can easily be tested by checking the response for an API call as described in https://www.fossology.org/get-started/basic-rest-api-calls/ under "Upload a package".
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(api): Return full uploadId

src/www/ui/api/documentation/openapi.yaml
Typo error in `openapi.yaml` file. 
- heathInfo -> healthinfo
This closes the issue ( https://github.com/fossology/fossology/issues/2185)
Closes #2185 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(openapi.yaml): OpenAPI Description: Fixed typo in HeathInfo

src/nomos/agent/STRINGS.in, src/nomos/agent/parse.c
Added a new regex to match ‘BSD-4-Clause-Shortened’(https://spdx.org/licenses/BSD-4-Clause-Shortened.html)  license by nomos agent
Try scanning the following file (https://github.com/sages-pl/example-helloworld-c/blob/master/print-enc.c) it should have license "‘BSD-4-Clause-Shortened’" 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(nomos): add 'BSD-4-Clause-Shortened' license

src/nomos/agent/STRINGS.in, src/nomos/agent/parse.c
Improved nomos GPL detection(fix false alarm)
Use the follow test to check this PR (Should not be detected as GPL license)
```
/* From $OpenBSD: if_enc.h,v 1.8 2001/06/25 05:14:00 angelos Exp $ */
/*
* The authors of this code are John Ioannidis (ji@tla.org),
* Angelos D. Keromytis (kermit@csd.uch.gr) and
* Niels Provos (provos@physnet.uni-hamburg.de).
*
* This code was written by John Ioannidis for BSD/OS in Athens, Greece,
* in November 1995.
*
* Ported to OpenBSD and NetBSD, with additional transforms, in December 1996,
* by Angelos D. Keromytis.
*
* Additional transforms and features in 1997 and 1998 by Angelos D. Keromytis
* and Niels Provos.
*
* Copyright (C) 1995, 1996, 1997, 1998 by John Ioannidis, Angelos D. Keromytis
* and Niels Provos.
* Copyright (c) 2001, Angelos D. …
```
=>  fix(nomos): Improved nomos GPL detection

src/lib/php/common-sysconfig.php
Fixes issue #2188
`src/lib/php/common-sysconfig.php ` - conf_value for CorsOrigins changed from 'localhost:3000' to 'http://localhost:3000'
- Repopulate db
- Attempt to log in using fossologyUI
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2195"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(API): Fixes FossologyUI CORS error for localhost

src/lib/php/common-sysconfig.php, src/www/ui/api/Helper/AuthHelper.php
Closes #2204
- `src/lib/php/common-sysconfig.php` - Added `OidcClientIdClaim` to system configuration
- `src/www/ui/api/Helper/AuthHelper.php` - Replaced `client_id` with `$SysConf['SYSCONFIG']['OidcClientIdClaim']`
- Repopulate db
- Go to "Admin > Customize" in Fossology and edit OIDC Client Id Claim
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2205"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(rest): Allows client ID claim to be configurable

src/lib/php/common-sysconfig.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php
The header 'Access-Control-Allow-Credentials' is used to expose credentials from JavaScript from other domains as well ([reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials)) which is not required for the application. By removing the header from CORS middleware, the allowed origin can be marked as '*'.
1. Remove the `Access-Control-Allow-Credentials` header from REST middleware.
2. Set default value for `Access-Control-Allow-Origin` as `*`.
1. Install the new branch and install the [FOSSologyUI project](https://github.com/fossology/FOSSologyUI).
2. Setup the correct endpoint in `.env` (`localhost/repo/api/v1`).
3. Test if using UI causes any CORS issues.
Closes https://github.com/fossology/FOSSologyUI/issues/202
<a …
=> fix(rest): fix CORS issue

install/db/Makefile, install/db/dbmigrate_3.7-3.8.php, install/db/dbmigrate_4.0-4.1.php, install/db/instance_uuid.php, install/fossinit.php, src/copyright/ui/ajax-copyright-hist.php, src/lib/php/Dao/CopyrightDao.php
Do not update the hash of copyrights where content is empty in `3.7-3.8` migration.
Empty/NULL content and hash are used to denote no copyrights found situations.
The migration script updates the hash which causes multiple collisions due to same hash.
(Same applies for ecc/keyword/author).
Add new migration script `dbmigrate_4.0-4.1.php` to revert content and hash to `NULL` if the hash was updated to `md5('')`.
1. Update 3.7-3.8 script to exclude copyright where content is NULL or empty.
2. Add new script 4.0-4.1 to update content and hash of copyright where hash was `md5('') => d41d8cd98f00b204e9800998ecf8427e`.
3. Updated `ajax-copyright-hist.php` to use `empty()` instead of `!` to detect empty strings.
1. On an existing server with copyright findings, run the installation of master …
=> fix(copyright): do not update empty copyrights

src/composer.json, src/composer.lock, src/lib/php/common-sysconfig.php, src/www/ui/api/Helper/AuthHelper.php, src/www/ui/page/HomePage.php
Explicitly declare algorithm used by JWK key set to prevent token forgery.
Solves [CVE-2021-46743](https://nvd.nist.gov/vuln/detail/CVE-2021-46743).
New parameter `OidcJwkAlgInject` to inject algorithm in jwk key set.
The vulnerability describes possibility of key forging by changing JWT header: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/
The fix is to explicitly declare the algorithm used in signature. Some JWKs provider like 0auth already provide it, others do not. For providers who do not advertise algorithm for the keys, inject them by a value in sysconfig array.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2216"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(jwt): explicitly declare jwk algorithm

Dockerfile, install/fo-install-pythondeps, src/scancode/agent/scancode_wrapper.cc, src/scancode/mod_deps, src/scancode/ui/agent-scancode.php
Move scancode's dependencies from `mod_deps` to `fo-install-pythondeps`.
Also, do not install scancode's UI if executable is not installed on the system.
1. Move Python dependencies of scancode agent to `fo-install-pythondeps`.
2. Rearrange how Python dependencies install to call `pip install` only once.
- See https://github.com/pypa/pip/issues/8063 for the issue (`bin` folder is replaced by each install).
3. Use FOSSology' cache explicitly for scancode (default is `~/.cache` which can resolve to `/root/.cache`).
4. Check if `scancode` executable exists before installing agent's UI.
1. On a clean system, install branch from scratch.
- `scancode` agent and "False Positive Copyright Deactivation" and "False Positive Copyright Deactivation and clutter removal" options of decider agent should …
=> fix(scancode): move python dependencies

src/www/ui/scripts/ui-clearing-view_bulk.js
While adding/removing new license(s) to bulk modal, license text, acknowledgement and comments already entered were removed.
While refreshing the table with new row, restore the values.
1. Update `updateTable()` in `ui-clearing-view_bulk.js` to read existing values while recreating the table.
2. Also, use template string instead of adding strings for the table to make it more presentable.
1. Open a bulk window, add/remove a license.
2. Change the License text, Acknowledgement and Comment to it.
3. Add/remove another license.
- The entered License text, Acknowledgement and Comment should persist.
4. Add/remove another license without making changes to fields.
- "Click to add" should be displayed as usual.
5. Remove add/remove license row.
6. Check the console for warnings/errors.
<a …
=> fix(ui): restore license text for bulk modal

src/clixml/agent/clixml.php, src/lib/php/Dao/SpashtDao.php, src/lib/php/Data/Package/ComponentType.php, src/lib/php/Report/ObligationsGetter.php, src/spdx2/agent/spdx2.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/ui-report-conf.php
Use component id "package-url" instead of purl as recommended value. It is added at index 5 and also is now the default value in database.
For SPDX reports, it is changed back to purl to be conformant with spec.
1. Add new ComponentType::PACKAGEURL
2. Treat ComponentType::PACKAGEURL and ComponentType::PURL same in spasht and SPDX
3. Change default value of 'ri_component_type' from 0 to 5 in 'report_info' table.
1. On existing packages with component ID set to purl, there should be no effect.
2. `purl` should now appear in "Legacy" section of Report Config page.
3. `package-url` should be "Recommended" in Report Config.
4. Changing `purl` to `package-url` in config should have no effect on SPDX reports. Spasht should not throw errors. Only CLIXML should have `package-url` in …
=> chore(component-id): use package-url instead purl

src/www/ui/page/UploadPermissionPage.php
Signed-off-by: Thanvi pendyala [[thanvipendyala194@gmail.com](mailto:thanvipendyala194@gmail.com)]
Fixes #1929 issue. 
Created a new pull request replacing the PR #2190 with the same changes.
This change displays an error when the user tries to change permissions of any uploaded file with reuse permissions when the scheduler is not running.
```src/www/ui/page/UploadPermissionPage.php``` - Added changes to fetch the status of the scheduler and store it.
```src/www/ui/template/upload_permissions.html.twig``` - Added changes to display the status of the scheduler.
1. Upload a package and do some clearing.
2. Change the upload status to "Closed".
3. Create a new group.
4. Kill the scheduler daemon.
5. Go to Admin >> Upload Permissions and find the upload.
6. Add the newly created group with …
=> fix(uploadPermission):introduced error on changing upload permissions

src/www/ui/api/Controllers/UserController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Controllers/UserControllerTest.php
Exposed `default_group` in endpoint `/api/v1/users/self`. Closes #2208. This in regards to the discussion I and @GMishx had on thread [#199](https://github.com/fossology/FOSSologyUI/pull/199#issuecomment-1089839237).
Edited `UserController.php` for exposing key and `openapi.yaml` for updating documentation.
Send GET request to endpoint `/api/v1/users/self`
Closes #2208
Closes #2054
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2209"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(default_group): exposed deafult_group in /users/self

.github/workflows/static-checks.yml
Bump version of spectral-action from 0.8.0 to 0.8.2
It fixes issue with linter for OpenAPI YAML
Check issue https://github.com/stoplightio/spectral-action/issues/634
Bump version of spectral-action from 0.8.0 to 0.8.2
Check CI test logs.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2227"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(ci): update spectral-action to fix ci test

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Added a copyright feat in  `/uploads/{id}/licenses` API .
see #2081 for details.
edited `/uploads/{id}/licenses` endpoint for getting copyright.
- If `license=true` and `copyright=false`  Returns the list of licenses.
- If `license=true` and `copyright=true` Returns the list of licenses and copyrights.
- If `license=false` and `copyright=true` Returns the list of copyrights only. 
Send a get request to `/uploads/{id}/licenses` by changing the `license` and `copyright` param value  and check the response .
Closes #2081 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(API): Created an API end-point for copyright

.github/workflows/docker-build.yml, .github/workflows/docker-test.yml, .github/workflows/release-publish.yml
1. Update dependencies used in GitHub Actions workflows.
2. Fetch all code base while building release packages and Docker images.
1. Update dependencies to latest version where possible for GitHub Actions.
2. Use `fetch-depth` as `0` to pull everything while building release packages and Docker images.
1. Check build logs.
Potentially fixes #2152 and #2206
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2230"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(workflow): update GHA dependencies

src/nomos/agent/nomos.c, src/wget_agent/agent/main.c, src/wget_agent/agent/wget_agent.c
There are many warning suppression mechanisms, I have used `_Pragma()` operator, it works for C99 and above and doesn't cause additional warnings.
See details here: https://nelkinda.com/blog/suppress-warnings-in-gcc-and-clang/#d11e435
Comparison: https://nelkinda.com/blog/suppress-warnings-in-gcc-and-clang/#d11e498
- Suppressed some warnings because theoretically, they won't turn into error. 
- Fixed some code to avoid error
- Checkout this pull-request branch `git fetch upstream pull/1923/head:fix-warnings`
- `git checkout fix-warnings`
- Do a `make clean`
- Run `make` …
=> fix(make): Fix warnings in make for Ubuntu 20.04.2 LTS

src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Controllers/JobControllerTest.php
`/jobs` endpoint only returns the jobs created by the current logged in user rather than giving all the jobs in the database.
- `JobController.php` introduced a function to get the filtered User's job results
- `DbHelper.php` introduced a function with new SQL query to filter out jobs as per UID
- `openapi.yaml` updated the description of the `/jobs` endpoint 
You can use postman or can use the new UI
to visit the `AllRecentJobs` page using different accounts to view different responses.
- In Fossy account
- In different account
Fixes #2253 
PTAL: @GMishx @shaheemazmalmmd @Shruti3004 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2252"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(API): `/jobs` returns only logged in user's jobs

src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/GroupControllerTest.php
Added a new API to delete a user group via a particular id.
1. Added a new function to handle the deletion of the group in `GroupController`.
2. Updated  the main file(`index.php`) by adding a new route `/groups/id`.
3. Updated the `openapi.yaml` file , by introducing a new API.
1. Add a new user group 
2. Keep the new group's Id aside.
3. Call Delete API by passing the Id of the new group in params.
Fixes #2241 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2244"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(API): delete user group

README.md
Signed-off-by: Rohit Pandey <rohit.pandey4900@gmail.com>
In pull request #2274, @GMishx made FOSSology [reuser standard 3](https://reuse.software/spec/) compliant. 
I have added REUSE status badge in `README.md` file.
Included a badge indicating the live status of REUSE.
The REUSE API checks repositories for their compliance with the REUSE best practices. It basically runs the lint command of the REUSE helper tool for the default branch of a project.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2282"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs(reuse): reuse status badge added

src/reuser/ui/agent-reuser.php, src/scancode/ui/agent-scancode.php
Add scancode as a dependency to reuser if it is scheduled to create a
correct job queue.
Check if scancode agent is scheduled and add it to dependency list.
1. Clear an upload with multiple monk bulk jobs.
2. Upload the same package again.
1. Schedule scancode agent on it.
2. Schedule the reuser with "Bulk phrases from reused packages" decider option.
3. In the job queue, reuser should not start untill scancode agent finishes.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2271"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(reuser): add scancode as dependency if sched

install/defconf/Db.conf.in, install/defconf/Db.conf.in.license, install/defconf/fossology.conf.in, install/src-install-apache-example.conf, src/copyright/agent/copyright.conf, src/copyright/agent/ecc.conf
The conf files are not supposed to have any empty lines.
Add comment `#` to empty lines.
1. Compile the tool.
2. Run the `copyright`, `ecc` and `keyword` agents from `src/copyright/agent` folder.
3. Install the tool and run the agents from UI.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(copyright): fix regex conf files

.gitignore, src/copyright/ui/template/copyrighthist.html.twig, src/copyright/ui/template/ui-cp-view.html.twig, src/lib/php/UI/Component/Menu.php, src/lib/php/UI/template/components/menu.html.twig, src/lib/php/UI/template/include/foot.html.twig, src/spasht/ui/template/agent_spasht.html.twig, src/www/ui/core-auth.php, src/www/ui/template/ui-browse.html.twig, src/www/ui/template/ui-export-list.html.twig, src/www/ui/template/ui-report-conf.html.twig
When a user closes the banner message, it should remain closed on all page loads for current session.
1. New JS function `closeBannerForSession()` to close banner if session cookie exists.
2. Adding more files to `.gitignore`
3. Add `jquery.cookie.js` from `foot.html.twig`, eventually removing redundant imports from other places.
1. Goto "Admin >> Customize" and add a new "Banner message".
2. Close the banner message and navigate through FOSSology.
1. The banner should remain closed for all page loads.
3. Navigate other pages which uses cookies for stickiness, and make sure they still work.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2278"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(ui): close banner for a session

src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/GroupControllerTest.php
To check if the user has any group that is possible to be deleted.
1. Added a new function in `GroupController`. to check if the group exists.
2. Updated  the main file(`index.php`) by adding a new route `/groups/has-deletable-group`.
3. Updated the `openapi.yaml` file to introduce a new API.
1. Open and run the project then visit  the url `http://localhost/repo/api/v1/groups/has-deletable-group`
2. Response
The following property in the response body called `available` should be marked as **true** if you have any group that is deletable  , else it will always be marked as **false**.
By default you have group `fossy` , this one is not deletable , the deletable groups are the one you add afterwards.
In other words , by default you don't have …
=> feat(API): list groups that can be deleted

src/lib/php/common-agents.php, src/www/ui/api/Controllers/UserController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/UserHelper.php, src/www/ui/api/Models/User.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/user-edit.php, src/www/ui_tests/api/Controllers/UserControllerTest.php, src/www/ui_tests/api/Helper/DbHelperTest.php, src/www/ui_tests/api/Models/UserTest.php
Signed-off-by : Krishna Mahato <krishhtrishh9304@gmail.com>
Now, there is a PUT route which is available at `/api/v1/users/{id}` that will edit the user details of a given user id. 
- Provide the request body as following ----
- You can expect a response like this
PTAL : @GMishx @Shruti3004 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2256"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
This closes #2257 .
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2262"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Added `users/{id}` PUT route to modify user details

src/www/ui/api/Controllers/UserController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxManageToken.php, src/www/ui/user-edit.php
Signed-off-by : Krishna Mahato <krishhtrishh9304@gmail.com>
The following REST routes have been implemented.
- There is a POST route which is available at `/api/v1/users/tokens` that will Create a new REST API Token. 
- There is a GET route which is available at `/api/v1/users/tokens/{type}` that will Get all the REST API tokens based on the type specified (active | expired). 
- Provide the request body as following ----
- You can expect a response like this
- You can expect a response like this
- type = `active`
- type = `expired`
PTAL : @GMishx @Shruti3004 
This closes #2265 .
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): added `/users/tokens` POST Route  and `/users/tokens/{type}` GET Route

src/www/ui/api/Controllers/UserController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/UserHelper.php, src/www/ui/api/Models/User.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/template/user_add.html.twig, src/www/ui/user-add.php, src/www/ui_tests/api/Controllers/UserControllerTest.php, src/www/ui_tests/api/Helper/DbHelperTest.php
Signed-off-by : Krishna Mahato <krishhtrishh9304@gmail.com>
Now, there is a POST route which is available at `/api/v1/users` that will create a new user.
- Provide the request body as following ----
- You can expect a response like this
PTAL : @GMishx @Shruti3004 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2256"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
This closes #2255 .
=> feat(API): `users/` post route for adding a new user

src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/Controllers/UserController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Models/UserGroupMember.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/GroupControllerTest.php, src/www/ui_tests/api/Controllers/UserControllerTest.php, src/www/ui_tests/api/Helper/DbHelperTest.php
Get all group members with corresponding roles / permissions from the given group via REST API.
1. Added a new function in `GroupController`. to get all  group members.
2. Updated  the main file(`index.php`) by adding a new route `/groups/members/{id}`.
3. Updated the `openapi.yaml` file to introduce a new API.
1. Open and run the project then visit  the url `http://localhost/repo/api/v1/groups/members/{id}`
2. Response
i. **When the group id is given:**
Getting all the users from the group whose id is 14. 
ii. **When the group Id is not given:**
Since the group id is not specified, we are going to pick the default group which is `Default User` instead.
**_Hence our API can handle both situations, Group Id is given, and the group Id is not …
=> feat(API): get group members with corresponding roles

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/UploadPermissionPage.php
Signed-off-by : Krishna Mahato <krishhtrishh9304@gmail.com>
Now, 
- There is a PUT route which is available at `/api/v1/uploads/{id}/permissions` that will Set permissions for a upload in a folder for different groups.
- There is a GET route which is available at `/api/v1/uploads/{id}/perm-groups` that will return all the groups with their respective permissions for a upload.
Here `{id} : is the upload Id`.
- Provide the request body as following ----
- You can expect a response like this
- If your upload exists, you can expect a response like this.
PTAL : @GMishx @Shruti3004 
This closes #2270 .
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2275"><img …
=> feat(api): PUT api to Set permissions for a upload and GET API to fetch respective permissions of groups

src/maintagent/ui/maintagent.php, src/www/ui/api/Controllers/MaintenanceController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/MaintenanceControllerTest.php
A rest API to initiate FOSSology maintenance operations.
1. Added a new controller file and the function to handle the logic in `MaintenanceController`.
2. Updated the file `maintagent.php` to be reusable by the outside callers.
3. Updated  the main file(`index.php`) by adding a new route `POST` `/maintenance`.
4. Updated the `openapi.yaml` file  to introduce a new API.
1. Design a request as follows. 
2. The **options** property should contain the list of the keys whose operations are to be executed.
3. The **logsDate** property is the date from which to remove older gold files from repository (_Free to keep it as null_).
4. The **goldDate** property is the date from which to remove older log files from repository (_Free to keep it as …
=> feat(API): REST-API to initiate FOSSology maintenance

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminLicenseFromCSV.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
The controller function to handle the import of a csv license file.
1. Added a new controller file and the function to handle the logic in `LicenseController`.
2. Updated the file `AdminLicenseFromCSV.php` to be reusable by the outside callers.
3. Updated  the main file(`index.php`) by adding a new route `POST` `/license/import`.
4. Updated the `openapi.yaml` file  to introduce a new API.
1. Design a request as follows. 
2. The **delimiter** property (_Free to keep it as empty_).
3. The **enclosure** property (_Free to keep it as empty_).
4. The **file_input** form-data property. 
3. Run the API.
Fixes #2291
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2292"><img …
=> feat(API): import csv-license file

src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/GroupControllerTest.php
Signed-off-by: dushimsam <dushsam@gmail.com>
An endpoint to add the user to a group as a new member.
1. Added a new controller file and the function to handle the logic in `GroupController`.
2. Updated  the main file(`index.php`) by adding a new route `POST` `/groups/{id}/user`.
Make a POST request on the endpoint to be accessed at ``/groups/{id}/user``
Choose one user who was already a member to act as the sample of the following tests.
Check if he was successfully removed from the group members of that  group.
Great , at this moment it's obviously visible that the member was removed.
This is the core API we are currently testing if it works.
In this response, we can easily see that the member was successfully re-added again to …
=> feat(API): add user to a group.

src/copyright/agent/cleanEntries.cc, src/copyright/agent/copyright.conf, src/copyright/agent/copyscan.cc, src/copyright/agent/copyscan.hpp, src/copyright/ui/CopyrightView.php, src/copyright/ui/HistogramBase.php, src/copyright/ui/Xpview.php, src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/copyright-hist.php, src/copyright/ui/list.php, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/test/CopyrightDaoTest.php, src/lib/php/Report/XpClearedGetter.php, src/lib/php/common-agents.php, src/reso/agent/ResoAgent.php, src/reso/ui/ResoAgentPlugin.php, src/spdx2/agent/spdx2.php, src/www/ui/ui-export-list.php
Signed-off-by: Rohit Pandey <rohit.pandey4900@gmail.com>
As discussed in issue #1592 , implements a part of the REUSE.Software specification, by detecting the `SPDX-FileCopyrightText` keyword from .license suffixed files, and applying the copyright detected by the Copyright agent to the associated file.
1. New regex added to identify SPDX copyright statement.
2. Applied copyright detected in .license file to the associated file.
1. Start new upload - you may want to use example package available here: https://github.com/fossology/fossology/wiki/ReSo-%28REUSE.Software%29#testing
2. Select `REUSE.Software Analysis`  and `Copyright` option.
3. Start Upload
4. Check the copyright applied to associated file of .license file.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pul …
=> feat(copyright): SPDX copyright detection added

src/lib/php/common-sysconfig.php, src/www/ui/page/HomePage.php
1. Allow admin to use either **access token** or **id token** for oidc authentication.
2. Also, allow admin to select the field from `userinfo` endpoint to be used as ID.
- It was primarily set to `email`.
1. Add 2 new configurations "Resource owner id field" and "Token to use from provider" in configuration page.
1. Set the oauth provider (preferably AzureAD).
3. Set the new fields and try to login.
Closes #2229 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2305"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(oidc): allow user to configure token

src/www/ui/api/documentation/openapi.yaml
I've fixed spectral linting warnings/errors related to the `openapi.yaml` file.
Only changes in the `openapi.yaml` spec:
- The `Maintenance` tag was not declared in global tags
- The `required` property for `multipart/form-data` properties needed to be an array, see https://github.com/OAI/OpenAPI-Specification/issues/1954#issuecomment-502946287
With the following spectral ruleset `.spectral.yml`:
```
extends: "spectral:oas"
```
Before this MR:
```sh
$ spectral lint src/www/ui/api/documentation/openapi.yaml
src/www/ui/api/documentation/openapi.yaml
145:11  warning  operation-tag-defined      Operation tags must be defined in global tags.  paths./maintenance.post.tags[0]
2058:28    error  oas3-valid-schema-example  schema is invalid: data/required must be array …
```
=> docs(openapi): fix spectral lint warnings/errors

.github/workflows/release-publish.yml, debian/control, src/copyright/mod_deps, src/lib/c/fossconfig.c, src/lib/php/libschema.php, src/nomos/mod_deps, src/ojo/mod_deps, src/scancode/mod_deps, utils/fo-installdeps
Add support for ubuntu jammy 22.04 for fossology.
added jammy support in installdeps file and corrected a warning.
* Test every functionality of fossology using source install as well as debian install in Ubuntu 22.04
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2300"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(ubuntu): support ubuntu jammy 22.04 for fossology

.github/workflows/docker-build.yml, .github/workflows/release-publish.yml, Dockerfile
Add annotations from Open Container Initiative to Dockerfile https://github.com/opencontainers/image-spec/blob/main/annotations.md
1. Add OCI annotations to `Dockerfile`
2. Add OCI label for Docker Hub images.
Build Docker image and check the image labels.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2325"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(Dockerfile): add OCI annotations

src/unifiedreport/agent/reportStatic.php, src/unifiedreport/agent/unifiedreport.php
replace '\n' with '</w:t>\n<w:br />\n<w:t xml:space=\"preserve\">' to make it compatible with windows and Linux versions.
closes https://github.com/fossology/fossology/issues/2211
see https://github.com/fossology/fossology/issues/2211
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2333"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(unifiedReport): fix line break issue in libre office

src/Makefile, utils/fo-debuild, utils/utils.sh
Prevent duplication of bootstrap folders in `fossology-common` and `fossology-web` Debian packages.
Also, fix regex for `-rc` tag versioning.
While creating Debian packages, `fossology-common` and `fossology-web` both contain files under `/usr/share/fossology/www/ui/css/bootstrap` and `/usr/share/fossology/www/ui/scripts/bootstrap` which causes following warning during installation:
```
Preparing to unpack fossology-common_4.2.0.~rc1-1_amd64.deb ...
Unpacking fossology-common (4.2.0.~rc1-1) over (4.2.0.10~rc1-1) ...
dpkg: error processing archive fossology-common_4.2.0.~rc1-1_amd64.deb (--install):
trying to overwrite '/usr/share/fossology/www/ui/css/bootstrap/bootstrap-grid.css', which is also in package fossology-web 4.2.0.~rc1-1
```
1. In `composer_install` target, check if building …
=> fix(debian): prevent duplication of bootstrap

.github/workflows/build-test.yml, src/www/ui/ui-report-conf.php
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
User was not able to add content with slashes like :  \\xsoftware-1.2.3\\new\\xsoftware.unit.news\\newsforassets\\somemd5.dll to database through conf page.
Get raw content from post escape and write it to database.
* in conf page add \\xsoftware-1.2.3\\new\\xsoftware.unit.news\\newsforassets\\somemd5.dll to any field. slashes should not get vanished. 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2346"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(conf): add escape string and fetch raw content

src/lib/php/Dao/UserDao.php
While using OIDC, if user is matched using `user_email` field, update the username from DB for following checks.
In `getUserAndDefaultGroupByUserName()` make parameter `$userName` as pass-by-reference and update it to `user_name` from DB in case of OAuth.
1. Setup OIDC.
2. Create a user with different username but keep email field to match oidc.
3. Login with the new user using OIDC. The login should succeed.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2349"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(oauth): update username if oauth email matches

src/monk/agent/CMakeLists.txt, src/www/ui/core-schema.dat
1. Fix installation target for monkbulk agent in CMake.
2. Change data type of `jobqueue::jq_cmd_args` to `text` from `varchar(1024)` to allow longer arguments, used by report agents.
In `src/monk/agent/CMakeLists.txt`, fix the component name for monkbulk.
Build packages and check the contents of monk and monkbulk packages.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2359"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(build): fix building of monkbulk package

src/lib/php/common-db.php, src/www/ui/admin-config.php
Fix situations possibly leading to Reflected XSS vulnerability exploitation.
The vulnerabilities have been detected by a Checkmarx scan.
Used `htmlspecialchars` to sanitize data taken from untrusted source shown on html page
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2356"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(security) fix Reflected XSS vulnerability

src/lib/php/Dao/LicenseDao.php
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
Inactive licenses ate still been listed in user decisions and bulk license selection.
Change query to select only active licenses.
* Deactivate some license from license admin.
* It should not appear while adding user decisions and bulk license.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2347"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(licenseRef): show only active licenses in bulk and user decisions

install/db/dbmigrate_2.1-2.2.php, src/lib/php/common-cache.php, src/reportImport/ui/ReportImportAgentPlugin.php, src/www/ui/core-smauth.php, src/www/ui_tests/foss_ui.php
Replaced cryptographically insecure PHP rand() function
with built-in for PHP random_int() with secure pseudo-random number generator
This fixes weak methods of generating pseudo-random values, as detected by a Checkmarx scan of Fossology
Fixes 5 randomness generation in php scripts
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2354"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(security) Replaced cryptographically insecure PHP rand() function

.gitignore, install/scripts/install-spdx-tools.sh, src/composer.json, src/composer.lock, src/lib/php/Data/LicenseRef.php, src/spdx2/CMakeLists.txt, src/spdx2/agent/spdx2.php, src/spdx2/agent/spdx2utils.php, src/spdx2/agent/template/dep5-copyright-document.twig, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2-file.xml.twig, src/spdx2/agent/template/spdx2-package.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig, src/spdx2/agent/template/spdx2tv-file.twig, src/spdx2/agent/template/spdx2tv-package.twig, src/spdx2/agent_tests/Functional/schedulerTest.php, src/www/ui/admin-license-file.php, src/www/ui/page/AdviceLicense.php
Update SPDX RDF and tag:value reports to specification version 2.3.
1. General:
1. Use organization name from "Report Header Text" filed from customize page.
2. Use tool version as `fossology-<version>` where version is build version (e.g. `4.2.1.19`)
3. Fix report creation timestamp to use UTC timezone.
4. Fix verification checksum by excluding parent file from calculation (parent file = uploaded file).
5. Include obligations and acknowledgements in reports.
6. Update license list version to 3.19
2. RDF files:
1. Change extension from `-spdx.rdf` to `.spdx.rdf`
2. Use `xml:base` to reduce URI lengths.
3. If concluded licenses include `Dual-license`, then use `DisjunctiveLicenseSet` (to denote `OR`), otherwise use `ConjunctiveLicenseSet` (to denote `AND`).
4. If there is only one …
=> feat(spdx): update reports to v-2.3

utils/automation/Dockerfile.ci
Add the missing `libxslt` dependency to the `utils/automation/Dockerfile.ci`
Build the runner image
`docker build -f uilts/automation/Dockerfile.ci -t fossology-runner .`
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2374"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(ci): add missing dependency to runner image

src/unifiedreport/agent/reportStatic.php, src/unifiedreport/agent/reportSummary.php, src/unifiedreport/agent/unifiedreport.php
When creating the unified report, the cell get extremely large which holds the component link.
Added fixed width using existing table classes.
* Add large URL into component link column from conf page.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2373"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(unifiedReport): fix table distortion for component link

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminLicenseCandidate.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Signed-off-by: dushimsam <dushsam@gmail.com>
An endpoint to delete admin-license candidate.
1. Added a new controller file and the function to handle the logic in `LicenseController`.
2. Updated the file `AdminLicenseCandidate.php` to be reusable by the outside callers.
3. Updated  the main file(`index.php`) by adding a new route `DELETE` `/license/candidates/{id}`.
4. Updated the `openapi.yaml` file  to introduce a new API.
Make a DELETE request on the endpoint accessed at "/license/candidates/{id}"
In this case, the Admin-license-candidate exists, and the license-candidate will be deleted successfully.
In this case, the Admin-license-candidate doesn't exist, so 404 error will be returned instead.
The request is not coming from the Admin.
This request can only be run by the admin , else …
=> feat(API): delete admin-license candidate

src/www/ui/core-schema.dat
Fix index creation commands to match values from DB, preventing recreation of indexes.
1. Fetch index creation commands from DB.
2. Update `core-schema.dat` with values from DB.
Installing FOSSology on existing setup should not trigger and reindexing.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2385"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(core-schema): fix index to match DB

src/lib/php/Report/ClearedGetterCommon.php, src/lib/php/Report/ObligationsGetter.php, src/unifiedreport/agent/reportStatic.php
fix warnings of unified report agent
Use array_key_exists function to check if the key exist.
* Switch on warnings in your development machine and generate unified report.
* You should not see any warnings in job log.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2372"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(unifiedreport): fix warnings of unified report agent

.github/workflows/build-test.yml, .github/workflows/deploy-pages.yml, .github/workflows/static-checks.yml, src/lib/php/Proxy/UploadTreeProxy.php, src/lib/php/View/HighlightRenderer.php, src/spdx2/agent/template/spdx2-package.xml.twig, src/www/ui/css/highlights.css
1. Since RDF files are XML, putting unescaped text in `<spdx:attributionText>` can cause failures. To prevent, put text in `<![CDATA[ ]]>`
2. Prevent running build-test.yml on pushes other than `master` branch.
3. Add missing keyword other highlight.
4. Update workflows to use checkout v3.
1. Update `<spdx:attributionText>` to use `<![CDATA[ ]]>`.
2. Update `actions/checkout@v2` to `actions/checkout@v3`
3. Prevent dual run of `build-test.yml`
1. Clear an upload with some license.
2. Add an obligation to the license with `&` and `<>` characters in text.
3. Generate SPDX RDF and validate it.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2386"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(spdx-rdf): use CDATA for attributionText

src/copyright/ui/template/ui-xp-view_rhs.html.twig, src/lib/php/Dao/CopyrightDao.php
Made the disabled Manual Copyrights Visible in Current Decision section in `?mod=copyright-view` page.
- Removed `is_enabled` from query to get current decisions data.
- Displayed Options based on whether it is disabled or not.
1. Add a manual copyright
2. Disable the copyright
3. Reload the page
4. Check whether the disabled copyright is visible in Current decisions section.
closes #1344 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2389"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(manualCopyright):Made Disabled Manual Copyrights Visible in UI

src/copyright/ui/HistogramBase.php, src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/template/histTable.js.twig
Added Inverse Search Option to Search in Email/ Url/ Author Page browse table.
- Added Invert checkbox.
- Made addSearchFilter() method to accommodate inverse search parameter.
- Go to Email/ URL/ Author Page.
- Click on invert Search checkbox.
- You will get the inverted Search results.
closes #1387 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2382"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added inverse search in Email/ Url / Author Page

src/reportImport/ui/ReportImportPlugin.php, src/www/ui/api/Controllers/ReportController.php, src/www/ui/api/documentation/openapi.yaml
Signed-off-by: Krishna Mahato <krishhtrishh9304@gmail.com>
There is a new POST route which is available at `/report/import?upload={id}` which will initiate a reportImport job for a given upload.
- Provide the request body as the following. (_Make sure the type is multipart/form-data_)
- You can expect a response like this 
This fixes #2308 .
@GMishx @shaheemazmalmmd @Shruti3004 PTAL.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2317"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(API): `POST report/import?upload={id}` route for initiating a reportImport job for a given upload

src/delagent/ui/Page/AdminUploadDelete.php, src/delagent/ui/delete-file-browse.php, src/www/ui/scripts/browse.js
Added delete file algorithm in Browse Page.
Added delete file algorithm in Browse Page
1. Create new file
2. Go to browse page
3. Go to actions of the corresponding file
4. Select Delete
5. It will add to the job queue,  
Closing #1657 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2381"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
[Screencast from 13-03-23 06:20:32 AM IST.webm](https://user-images.githubusercontent.com/95395832/224585641-1e38db5c-6046-4525-97ad-cef5c0caa717.webm)
=> feat(deleteFileInBrowse):ability to delete file from browser

src/clixml/agent/clixml.php, src/clixml/agent/template/clixml-file.xml.twig, src/lib/php/BusinessRules/LicenseMap.php, src/lib/php/BusinessRules/test/LicenseMapTest.php, src/lib/php/Data/LicenseRef.php, src/lib/php/Report/LicenseMainGetter.php, src/www/ui/admin-license-file.php, src/www/ui/page/AdviceLicense.php
Extract license fullname while generating CLIXML reports and use them to fill the `name` attribute.
1. Extract `name` from `LicenseMainGetter` for main licenses.
2. New function `addLicenseNames()` for license decisions.
3. Change the `name` attribute in twig file.
4. Add new function `LicenseRef::replaceSpaces()` to replace spaces with dash in SPDX ID.
Generate new CLIXML for an upload and check the `name` attribute of `<License>`.
Closes #2399 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2400"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(clixml): use license full name in clixml report

src/lib/php/Application/LicenseCsvExport.php, src/lib/php/Application/LicenseCsvImport.php, src/lib/php/Application/test/LicenseCsvExportTest.php, src/lib/php/Application/test/LicenseCsvImportTest.php, src/www/ui/page/AdminLicenseFromCSV.php
While generating License CSV export, export SPDX ID of license as well.
Also while importing, import SPDX ID as optional column.
1. Export `rf_spdx_id` as `spdx_id`.
2. Import `spdx_id` as optional column.
1. Export a license CSV.
2. Edit the SPDX ID.
3. Import the CSV.
4. License should be updated.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2401"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(licenseCsv): export spdx id in license CSV

src/lib/php/UI/template/components/login-form.html.twig, src/www/ui/template/user_add.html.twig, src/www/ui/template/user_edit.html.twig
Have introduced a toggling eye button beside password which can help us view it while logging in
Introduced an eye button and have handled its working using addEventListener Function in script
It can be tested from the fossology login page
Closing #2392
[Screencast from 16-03-23 03:38:45 PM IST.webm](https://user-images.githubusercontent.com/95395832/225585249-370cbe1e-d255-48a1-b38e-cbd8dfcfa55e.webm)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2393"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(viewPasswordInLogin): Eye button to view Password while logging in

src/decisionexporter/agent/decisionexporter.php, src/decisionimporter/agent/DecisionImporterDataCreator.php, src/decisionimporter/agent/DecisionImporterIdFetcher.php
If an uploadtree is missing from the decision dump, simply ignore it rather than raising an exception.
As this error is not solvable.
For example, if between versions of FOSSology (where dump is created and where it is imported), ununpack decides to extract a new archive type, there will be at least 1 missing uploadtree of the unextracted archive which cannot be found.
Set `new_itemid` for uploadtree to `null` if it is not found.
Closes #2402 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2408"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(import): ignore missing utree in dump import

src/www/ui/api/Controllers/JobController.php
In PR #2287 the upload ID and folder ID got swapped for creating new jobs.
Fix function call to `UploadHelper::handleScheduleAnalysis()` in `JobController`
Schedule agents using REST API.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2411"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(rest): swap upload and folder id to create job

src/www/ui/api/Helper/UploadHelper.php
If no agent has been scheduled on an upload, the `/summary` endpoint throws warnings in logs.
1. Check if the response from `getUploadHist()` contains the required keys.
1. Upload a package (id: 1) and run scanners on it.
2. Upload second package (id: 2) and do not run any scanners on it.
3. Upload a single file, no archive (id: 3) and run scanners on it.
4. Upload a single file (id: 4) and do not run any scanners on it.
On all uploads, do `GET /uploads/{id}/summary` and check Apache error log. There should be no warning like following:
```
PHP Notice:  Undefined index: uniqueLicenseCount in /usr/share/fossology/www/ui/api/Helper/UploadHelper.php on line 608 
PHP Notice:  Undefined index: scannerLicenseCount in /usr/share/fossology/www/ui/api/Helper/UploadHelper.php on line 609 
PHP …
```
=> fix(api): check if hist has required keys

README.md
This is a possible solution to #2432, the link where the badge should point to still needs to be edited, because currently it points to a page which does not exist
The badge was rendered via an SVG, changed to a badge from `image shields`.
`Link still needs to be added`
Badge can be viewed in the README.md of the project.
Might close issue #2432 .
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2433"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(README): Fix broken Travis SVG

src/lib/php/Data/LicenseRef.php, src/lib/php/Util/StringOperation.php, src/spdx2/agent/spdx2.php
When using a custom license text for a license, SPDX creates a new license with md5 at end. This makes the license a LicenseRef. This PR is to make sure, it is a LicenseRef.
1. While creating a custom license, convert it into LicenseRef.
2. In `convertToSpdxId()` make sure to not have `LicenseRef-fossology-LicenseRef-fossology` for licenses.
3. Add polyfill for `str_starts_with()` available in PHP 8+ in `StringOperation::stringStartsWith()`.
1. Clear an upload with a SPDX Listed license like `MIT` and with License ref like `Public-domain`.
2. For both the licenses, add a new decision with custom license text.
3. Check if in the SPDX reports
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2434"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(spdx): create LicenseRef for custom license text

.github/workflows/deploy-pages.yml, .github/workflows/release-publish.yml, Dockerfile, utils/automation/Dockerfile.ci
Update Docker images to use new Debian 11 as base.
1. Update Dockerfile base images to [debian:bullseye-slim](https://hub.docker.com/_/debian/tags?page=1&name=bullseye-slim)
2. Update building and packaging commands from ninja to cmake/cpack
3. Update Document build to use Ubuntu-22.04
Build and run a docker container.
=> feat(docker): update images to Debian 11 (bullseye)

src/lib/php/Dao/LicenseDao.php
In `LicenseDao::getLicenseByCondition()`, set the statement name based on condition.
In `ObligationsGetter::getObligations()`, the function `getLicenseById()` is called without group id and the function is generally called by CLIs. In this special case, the function `getLicenseByCondition()` ends up without the user id and group id.
This results in a prepared statement `Fossology\Lib\Dao\LicenseDao::getLicenseByCondition.rf_pk=$1.group` without group parameter.
Add `.userId` and `.groupId` to statement name based on condition in `LicenseDao::getLicenseByCondition()`.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2437"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(dao): getLicenseByCondition set statement name on condition

install/db/dbmigrate_bulk_license.php, install/fo-install-pythondeps, src/lib/php/Data/AgentRef.php, src/lib/php/UI/template/include/base.html.twig, src/scancode/agent/scancode_dbhandler.cc, src/scancode/agent/scancode_template.html, src/scancode/agent/scancode_utils.cc, src/scancode/agent/scancode_wrapper.cc
1. Fix the `scancode-toolkit` Python dependency to version 31.2.4 to eliminate possible cases of failures.
2. Update scancode code to use modern loops and auto variables.
3. Fix template to handle cases where a single contains multiple copyright and author information.
Run the scancode agent from UI.
Possible fixes for: #2348
Closes #2375
Closes #2329
Closes #2277
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2436"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(scancode): fix the version to 31.2.4

src/decider/agent/BulkReuser.php, src/decider/agent_tests/Functional/schedulerTest.php
Consider folder level bulk while reuse. 
Search for folder uploadtreeID and schedule a bulk scan.
* upload package x.
* schedule a bulk scan for package x for a folder.
* upload package x.1 and reuse bulk decisions from package x.
* bulk should only be applied to folder level.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2448"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(bulkReuse): concider folder level and package level bulk

src/www/ui/user-add.php
the empty email checks and modified other email checks to function with an emtpy email field This fixes issue #2391
Fix "Email can be blank" but is actually required in the add user page.
1. Removed `empty($Email)` check  
2. Modified the other two email checks to not give an error with the email field is empty
Try to add a new user with the email field empty. Previously an error message used to be shown, now it doesn't
This fixes #2391 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2396"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(user-add.php): Fixed email can be blank but required

src/clixml/agent/clixml.php
Fixed the issue on PHP8.1 warning while exporting CLIXML.
1. Install FOSSology on PHP8
2. Upload a package
3. Export CLIXML report
4. Check the agent logs
Fixed #2324 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2417"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(clixml.php): Fixed the issue of PHP 8 Warning

src/www/ui/api/Controllers/InfoController.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/InfoControllerTest.php
This Pull request exposes the `openapi.yaml` file through the new `/openapi` endpoint.
`src/www/ui/api/Controllers/InfoController.php`
`src/www/ui/api/index.php`
use the `/openapi` endpoint in postman.
##Screenshots:
Closes #2452 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2474"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): openapi.yaml exposed through API

src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/ui-view.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to retrieve the contents of a specific file.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/item/{itemId}/view`.
Make a GET request on the endpoint: ``/uploads/{id}/item/{itemId}/view``
Fixes #2454  
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2456"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get the contents of the file

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui_tests/api/Controllers/UploadControllerTest.php
As mentioned in the issue #2404, pagination feature needed to be added to the endpoint "uploads/{id}/license".
Hence, this PR aims to solve the same. 
Additional fields ( i.e. limits and page ) can be passed to UploadController, which calls for UploadHelper. While receiving response from UploadHelper, the response array is modified using `array_slice` according to the needed page and limit fields. 
Also updated the `open-api.yaml` to display the changes.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2430"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
1.) Using an auth token send a get request to `uploads/{id}/license` . This will display all the results.
2.) Include page and limit in the headers of the request. This will display the paginated …
=> feat(api): add pagination to license browser

src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/ui-clearing-view.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to set the clearing decision for a particular item.
1. Introduced a new group of controllers called `uploadTree` for managing different actions on a particular items and with it's corresponding class  `UploadTreeController`.
2. Created the method in `UploadTreeController` for setting the clearing decision for a particular item.
3. Updated  the main file(`index.php`) by adding a new route `PUT` `/uploadtree/{id}/clearing-decision`.
Make a PUT request on the endpoint: ``/uploadtree/{id}/clearing-decision``, with header variables `decisionType` & `globalDecision`
Fixes #2459 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2460"><img …
=> feat(api): set the clearing decision for a particular item

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Added the API to set a specific license as the main license for the given Upload
2. Updated  the main file(`index.php`) by adding a new route `POST` `/uploads/{id}/licenses/main`.
Make a POST request on the endpoint: `/uploads/{id}/licenses/main`.
Fixes #2459   
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2462"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): add the new main license for the upload

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Added the API to delete a specific main license from an upload.
2. Updated  the main file(`index.php`) by adding a new route `DELETE` `/uploads/{id}/licenses/{licenseId}/main`.
Make a DELETE request on the endpoint: `/uploads/{id}/licenses/{licenseId}/main`.
Fixes #2459   
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2463"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Remove a particular main license from an upload

utils/automation/.github-workflow.yml, utils/automation/fossologyscanner.py
Add support of Github actions in `scanner`
* Add logic to execute `scanner` in Github actions
```
- name: Fossology scanner
run: |
docker run --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo \
-e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
-e GITHUB_PULL_REQUEST=${{ github.event.number }} \
fossology/fossology:scanner "/bin/fossologyscanner" nomos ojo
```
Note, `GITHUB_REPOSITORY` and `GITHUB_ACTIONS` are provided by Github action itself, so we do not need to specify it explicitly.
This closes #2450 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2451"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(scanner): support github in scanner

src/www/ui/api/Controllers/CopyrightController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
API to update File copyright is added  in this PR
Send a `PUT` request to the endpoint `/file/upload/{Upload_id}/item/{Item_id}/copyright/{Copyright_hash}`
with a body :
```
{
"content": "New Test copyright text"
}
```
##Screenshots:
- Before sending the API request:
- The API Request:
- After the API request:
closes #2468
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2479"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): API for updating File copyright content

src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to get the what should be the next and the previous item, given the current Item Id.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/items/{itemId}/prev-next`.
Make a GET request on the endpoint: `GET`  `/uploads/{id}/items/{itemId}/prev-next`.
Fixes [#2472](https://github.com/fossology/fossology/issues/2472)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2480"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): API to handle three filters to get prev & next item

src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/Models/BulkHistory.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to a get a list of the bulk history for a particular item.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/items/{itemId}/bulk-history`.
3. Updated the `openapi.yaml` file  to write the new API's documentation.
Make a GET request on the endpoint: `GET` `/uploads/{id}/items/{itemId}/bulk-history`.,
Fixes [#2472](https://github.com/fossology/fossology/issues/2472)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get list of bulk-history API

src/lib/php/Data/DecisionTypes.php, src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/Models/ClearingHistory.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to a get a list of the clearing history for a particular item.
2. Created the method in `UploadTreeController` for retrieve the list of the data.
3. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/items/{itemId}/clearing-history`.
Make a GET request on the endpoint: `GET` `/uploads/{id}/items/{itemId}/clearing-history`.,
Fixes [#2472](https://github.com/fossology/fossology/issues/2472)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2477"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get clearing-history API for an item

src/lib/php/Data/Highlight.php, src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/ui-clearing-view.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to get the index of the keywords and the highlight-entries from the given file's content.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/item/{itemId}/highlight`.
Make a GET request on the endpoint: `/uploads/{id}/item/{itemId}/highlight`
Fixes [#2459](https://github.com/fossology/fossology/issues/2459)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): REST API to get keywords and highlight-entries from content

src/www/ui/api/Controllers/CopyrightController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Restores deleted copyright statements for a file
send a `patch` request to the endpoint `file/upload/{uploadId}/item/{itemid}/copyright{copyrightHash}`
closes #2468
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2486"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): restore deleted copyrights

src/lib/php/Proxy/UploadTreeProxy.php, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Added the API to get retrieve the rows that makes a tree-view from a specific upload and item.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/clearing/progress`.
Make a GET request on the endpoint: `/uploads/{id}/clearing/progress`
UI View:
Corresponding API Object:
Fixes [#2459](https://github.com/fossology/fossology/issues/2459)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2494"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get the clearing-progress info for an upload.

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve the license histogram for a given upload.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/licenses/histogram`.
Make a GET request on the endpoint: `/uploads/{id}/licenses/histogram`.
UI View:
API response:
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2497"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get licenses histogram for an upload

src/lib/php/Dao/CopyrightDao.php, src/www/ui/api/Controllers/CopyrightController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
This API returns the total number of copyrights for a UploadTree
Send a `GET` request to `/file/upload/{UploadId}/item/{ItemId}/totalcopyrights`
##Screenshots
Fixes #2468
@shaheemazmalmmd Please do have a look as this was requested on priority basis.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2488"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): API to return total number of copyrights for a file

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to the retrieve the list of the agents associated with the upload.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/agents`.
Make a GET request on the endpoint: `/uploads/{id}/agents`.
Fixes [#2500](https://github.com/fossology/fossology/issues/2500)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2502"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get all agents for the upload

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Models/UploadSummary.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/page/BrowseLicense.php, src/www/ui_tests/api/Models/UploadSummaryTest.php
Update the current API to for getting the upload's summary to add more information related to licenses.
1. Updated the method `getUploadSummary` in  `UploadController` to make the changes.
2. Updated the `openapi.yaml` file  to introduce a new changes for the API.
Make a GET request on the endpoint: `/uploads/{id}/summary`.
=> feat(api): Update Upload Summary API to add more info

src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxExplorer.php
Added the API to get retrieve the rows that makes a tree-view from a specific upload and item.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/item/{itemId}/tree/view`.
Make a GET request on the endpoint: `/uploads/{id}/item/{itemId}/tree/view`
UI View:
Corresponding API Object:
UI View:
Corresponding API Object:
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2492"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get the license tree-view of the upload and item

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve a list of the edited licenses for a given upload.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/licenses/edited`.
Make a GET request on the endpoint: `/uploads/{id}/licenses/edited`.
**UI View:**
**API response:**
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2495"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2498"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get edited licenses list for an upload

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Added the API to retrieve a list of the licenses' admin acknowledgments.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/licenses/adminacknowlegments`.
Make a GET request on the endpoint:  `/licenses/adminacknowlegments`,
Fixes #2511 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2512"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get all licenses-admin acknowlegments

src/www/ui/api/Controllers/FileInfoController.php, src/www/ui/api/Models/FileInfo.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
API endpoint to get info for a file
Send a get request to `/file/upload/{UploadId}/item/{ItemId}/info`
closes #2493
@shaheemazmalmmd @GMishx 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2496"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): File info API 

src/www/ui/ajax-clearing-view.php, src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/Models/LicenseDecision.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to retrieve a list of license decisions for a particular item.
2. Created the method in `UploadTreeController` for adding the new license on the selected item.
3. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/items/{itemId}/licenses`.
Make a GET request on the endpoint: ``/uploads/{id}/items/{itemId}/licenses``,
Fixes #2459 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get list of license decisions for an item

src/lib/php/BusinessRules/ReuseReportProcessor.php, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxReuseReport.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Added the API to the summary regarding the license reuse summary.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/licenses/reuse`.
Make a GET request on the endpoint: `/uploads/{id}/licenses/reuse`.
**UI View:**
**API response:**
Fixes [#2500](https://github.com/fossology/fossology/issues/2500)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2501"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get licenses reuse summary API

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Models/ScannedLicense.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve a list of the scanned licenses for a given upload.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/licenses/scanned`.
Make a GET request on the endpoint: `/uploads/{id}/licenses/scanned`.
UI View:
API response:
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2495"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get a list of scanned licenses for an upload

src/lib/php/Dao/SysConfigDao.php, src/lib/php/services.xml.in, src/www/ui/api/Controllers/CustomiseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/core-schema.dat
This PR introduces an endpoint to fetch data for the customize page from admin panel 
THIS PR IS WIP and to be updated according to the requirements.
send a `GET` request to `localhost/repo/api/v1/customise`
closes #2519
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2520"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get Customise page data

src/www/ui/ajax-clearing-view.php, src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to handle add, edit, and delete of the license decisions in one request.
2. Created the method in `UploadTreeController` for handling add, edit and delete of the items given in the request body.
3. Updated  the main file(`index.php`) by adding a new route `PUT` `/uploads/{id}/item/{itemId}/licenses`.
Make a PUT request on the endpoint: ``/uploads/{id}/item/{itemId}/licenses``,
Fixes #2459 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Add, edit & delete license decision

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Added the API to add new, edit and toggle admin license acknowledgement.
2. Updated  the main file(`index.php`) by adding a new route `PUT` `/licenses/adminacknowlegments`.
Make a PUT request on the endpoint: ``/licenses/adminacknowlegments``,
Fixes #2511 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2516"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Add, Edit & toggle admin license acknowledgement

install/fo-install-pythondeps
Preserve proxy environments while doing `su` in `fo-install-pythondeps` for `pip install` commands.
Use `--login --whitelist-environment="http_proxy,HTTP_PROXY,https_proxy,HTTPS_PROXY"` flags with `su`.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2571"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(pythondeps): preserve proxy env with su

src/delagent/agent/CMakeLists.txt, src/delagent/agent/util.c, src/delagent/agent_tests/CMakeLists.txt, src/delagent/mod_deps
The password hash stored in the DB are no longer SHA1 but [bcrypt](https://en.wikipedia.org/wiki/Bcrypt). This caused command line of delagent to fail in checking the password, even throw overflow errors.
Use function `crypt()` to check the password from library [libxcrypt](https://salsa.debian.org/md/libxcrypt#readme-for-libxcrypt) which is licensed under [LGPL-2.1-only](https://salsa.debian.org/md/libxcrypt/-/blob/master/COPYING.LIB)
1. Added bcrypt password check along with sha1 in delagent.
1. Should be able to list uploads from delagent (`sudo ./src/delagent/agent/delagent -u --user fossy --password fossy`)
2. The Debian packages should build without issue.
Closes #2026 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2030"><img …
=> fix(delagent): Use bcrypt to check password

src/lib/php/Proxy/UploadTreeProxy.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php
Replace the use of JOINs with `license_ref` and `license_candidate` by getting license ID of 'No_license_found' and 'Void' licenses and filter the IDs directly.
Also, no agent currently scans with candidate license and thus, there should be no candidate license ID in `license_file` table. Thus, we can remove join with `license_candidate` as well.
Removing following join:
```
->  Nested Loop Left Join  (cost=0.85..5.82 rows=1 width=0) (actual time=0.008..0.008 rows=1 loops=3908)
Filter: ((lr.rf_shortname <> ALL ('{No_license_found,Void}'::text[])) OR (lr.rf_pk IS NULL))
Rows Removed by Filter: 1
->  Index Only Scan using lf_pfile_agent_rf_lf_idx on license_file lf  (cost=0.57..3.31 rows=1 width=8) (actual time=0.006..0.006 rows=1 loops=3908)
Index Cond: (pfile_fk = ut.pfile_fk)
Filter: …
```
=> chore(UploadTreeProxy): optimize license file query

src/www/ui/api/Models/ApiVersion.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
This pull request (PR) focuses on enhancing the functionality of the API configuration to accommodate the routes of Version 2.
The i`index.php` file has been revised to facilitate the dynamic base URL, capable of accommodating both V1 and V2 versions of the API. 
The `openapi.yml` file has been updated to incorporate the server URL specific to Version 2 of the API. 
**1. Add this block of code in the `getInfo` method from `InfoController`:**
**2. Call the Version 1 API** 
**3. Call the Version 2 API**
**4. Other Cases**
Fixes #2575 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2576"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(SETUP-V2): Support Multiple Versions (V1 & V2)

src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/change-license-bulk.php, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Added the API to schedule the bulk scan for an item, given relevant information in the request body.
2. Updated  the main file(`index.php`) by adding a new route `POST` `/uploads/{id}/items/{itemId}/bulk-scan`.
3. Updated the `openapi.yaml` file  to write the new API's documentation.
Make a POST request on the endpoint:  `/uploads/{id}/items/{itemId}/bulk-scan`.
This endpoint is expected to return the jobId which corresponds to this bulk scan.
Fixes [#2472](https://github.com/fossology/fossology/issues/2472)
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): REST API to schedule the bulk-scan

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Added the API to retrieve a list of the standard comments.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/licenses/stdcomments`.
Make a GET request on the endpoint:  `/licenses/stdcomments`,
Fixes #2511 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2517"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get all standard comments

src/www/ui/admin-dashboard-stats.php, src/www/ui/api/Controllers/JobController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve the server jobs for the Admin Dashboard overview.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/jobs/dashboard/statistics`.
Make a GET request on the endpoint:  `/jobs/dashboard/statistics`,
Fixes #2523 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2537"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get the summary statistics for all Jobs

.github/workflows/release-publish.yml
Fix following points for the release workflow:
1. Fetch at least last 10 commits before compiling.
2. Change release upload
1. Repository [actions/upload-release-assets](http://github.com/actions/upload-release-assets) is now archived.
2. Use [xresloader/upload-to-github-release](https://github.com/xresloader/upload-to-github-release) instead.
**Fixes**:
1. Closes #2152
2. Closes #2206
3. https://github.com/fossology/fossology/runs/4924129005?check_suite_focus=true#step:11:12
Will setup a fork with updated workflow soon.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2156"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(cd): Fix release workflow for version

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Added the API to add new, edit and toggle standard-license comments.
2. Updated  the main file(`index.php`) by adding a new route `PUT` `/licenses/stdcomments`.
Make a PUT request on the endpoint: ``/licenses/stdcomments``,
Fixes #2511 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2518"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Add, Edit & toggle standard-license comment

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminLicenseCandidate.php
Added the API to verify a given a license as new one or the variant of another existing license.
2. Updated  the main file(`index.php`) by adding a new route `PUT` `/license/verify/{shortname}`.
Make a PUT request on the endpoint:  `/license/verify/{shortname}`,
Fixes #2510 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): verify license as new or variant

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminLicenseCandidate.php
Added the API to merge a given candidate license into another existing one.
2. Updated  the main file(`index.php`) by adding a new route `PUT` `/license/merge/{shortname}`.
Make a PUT request on the endpoint:  `/license/merge/{shortname}`,
Fixes #2510 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2529"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Merge a license into an existing one

src/www/ui/admin-dashboard-general.php, src/www/ui/api/Controllers/OverviewController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve the database contents with corresponding statuses.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/overview/database/contents`.
Make a GET request on the endpoint:  `/overview/database/contents`,
Fixes #2523 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2530"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get the database contents for the dashboard overview

src/www/ui/admin-dashboard-general.php, src/www/ui/api/Controllers/OverviewController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve the disk space usage for the Admin Dashboard overview.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/overview/disk/usage`.
Make a GET request on the endpoint:  `/overview/disk/usage`,
Fixes #2523 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2534"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get disk space usage overview

src/www/ui/admin-dashboard-general.php, src/www/ui/api/Controllers/OverviewController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve the PHP-Info for the Admin Dashboard overview.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/overview/info/php`.
Make a GET request on the endpoint:  `/overview/info/php`,
Fixes #2523 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2535"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get PHP-Info for the Dasbhoard Overview

src/www/ui/api/Controllers/JobController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxAllJobStatus.php
Added the API to retrieve the server jobs for the Admin Dashboard overview.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/jobs/dashboard`.
Make a GET request on the endpoint:  `/jobs/dashboard`,
Fixes #2523 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2536"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get all server jobs for Admin Dashboard

src/monk/ui/oneshot.php, src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminLicenseCandidate.php
Added the API to search and the suggested license from the given reference text.
2. Updated  the main file(`index.php`) by adding a new route `POST` `/license/suggest`.
Make a POST request on the endpoint:  `/license/suggest`,
Fixes #2510 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2524"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Search & suggest license from the reference text

src/www/ui/admin-dashboard-general.php, src/www/ui/api/Controllers/OverviewController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve the database metrics with corresponding statuses.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/overview/database/metrics`.
Make a GET request on the endpoint:  `/overview/database/metrics`,
Fixes #2523 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2532"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get database metrics overview for dashboard

src/www/ui/admin-dashboard-general.php, src/www/ui/api/Controllers/OverviewController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to retrieve the active queries for the Admin Dashboard overview.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/overview/queries/active`.
Make a GET request on the endpoint:  `/overview/queries/active`,
Fixes #2523 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2533"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get active queries for Dashboard overview

src/www/ui/admin-scheduler.php, src/www/ui/api/Controllers/JobController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxAdminScheduler.php
Added the API to retrieve the scheduler options for the given operation.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/jobs/scheduler/operation/{operationName}`.
Make a GET request on the endpoint:  `/jobs/scheduler/operation/{operationName}`,
Fixes #2526 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get scheduler options for a given operation

src/www/ui/admin-dashboard-general.php, src/www/ui/admin-scheduler.php, src/www/ui/api/Controllers/JobController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to run the scheduler of an operation based on the selected option.
2. Updated  the main file(`index.php`) by adding a new route `POST` `/jobs/scheduler/operation/run`.
Make a POST request on the endpoint:  `/jobs/scheduler/operation/run`,
Fixes #2526 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2539"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Run scheduler based on the given operation

src/lib/php/Dao/SysConfigDao.php, src/www/ui/api/Controllers/CustomiseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added update feature for `/customise` endpoint
Send a `PUT` request to `/customise` endpoint with the following body:
```
{
"key": "key_name",
"value":"updated value"
}
```
Closes #2519 
NOTE : MERGE ONLY AFTER MERGING #2520 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2545"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Update customise data

src/lib/php/Dao/UploadDao.php, src/www/ui/admin-dashboard-general.php, src/www/ui/api/Controllers/ConfController.php, src/www/ui/api/Models/Conf.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Implemented endpoint to update the conf data.
Send a `PUT` request to the endpoint `/uploads/{UploadId}/conf` with the following body:
```
{
"key": "reviewed",
"value" : "testakjsbdkahs"
}
```
Closes #2504 
NOTE: PLEASE MERGE #2505 BEFORE MERGING THIS PULL REQUEST
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2549"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Update Conf data endpoint implemented

src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxFolderContents.php
Added the API to retrieve the get a list of removable contents in a folder.
1. Added a new method in  `FolderController` to build the functionality.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/folders/{id}/contents/removable`.
Make a GET request on the endpoint:  `/folders/{id}/contents/removable`.
Fixes #2540 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2551"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get removable folder contents

src/lib/php/Dao/FolderDao.php, src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to unlink the folder contents.
2. Updated  the main file(`index.php`) by adding a new route `PUT` `/folders/contents/{contentId}/unlink`.
Make a PUT request on the endpoint: `/folders/contents/{contentId}/unlink`,
Fixes #2540  
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2552"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Unlink folder contents

src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxFolderContents.php
Added the API to retrieve the get a list of removable contents in a folder.
1. Added a new method in  `FolderController` to build the functionality.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/folders/{id}/contents`.
Make a GET request on the endpoint:  `/folders/{id}/contents`.
Fixes #2554 
cc: @shaheemazmalmmd @GMishx 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2555"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get all contents of a specific folder

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to export licenses' list as a CSV file.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/license/export`.
Make a GET request on the endpoint: `/license/export`,
Fixes #2561  
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2562"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): The REST API to export licenses-list as CSV

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminObligationFromCSV.php
Added the API to import obligation list from a CSV file.
2. Updated  the main file(`index.php`) by adding a new route `POST` `/license/obligation/import-csv`.
Make a POST request on the endpoint: `/license/obligation/import-csv`,
Fixes #2560 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2563"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Import obligation list from CSV

src/buckets/ui/bucket-diff.php, src/nomos/agent_tests/testdata/NomosTestfiles/GPL/nomos-diff-GPLv2.php, src/nomos/ui/nomos-diff.php
test
```
if ($OtherChild and $OtherChild)
```
makes no sense
fix test according to comment:
```
/* If both $Child and $OtherChild are specified,
* reassemble licstr and highlight the differences
*/
```
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2586"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(test): fix wrong test according to comment

src/lib/php/Application/ObligationCsvExport.php, src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/Controllers/ObligationController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Added the API to export Obligations' list as a CSV file.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/license/obligation/export-csv`.
Make a GET request on the endpoint: `/license/obligation/export-csv`,
Fixes #2560 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2574"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Export Obligation list as CSV

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
New API endpoint '/uploads/{id}/topitem' to get top level uploadtree_pk.
New function in `UploadController` to get top item id with `UploadDao::getParentItemBounds()`.
Call the endpoint and validate the id.
=> feat(api): add 'topitem' endpoint to Upload API

src/readmeoss/agent/readmeoss.php, src/testing/lib/fossologyTestCase.php, src/testing/lib/libTestDB.php
You cannot have an optional parameter declared before a required parameter
Remove default value
=> fix(php) Optional parameter declared before required parameter

src/lib/php/common-active.php, src/www/ui/upload-instructions.php
Using ${var} in strings is deprecated
Use {$var} instead
=> fix(php): Using ${var} in strings is deprecated

src/lib/php/common-sysconfig.php, src/unifiedreport/agent/reportStatic.php
support json format for obligationstext in unified report.
* go to customize page 
* Add common obligations in json format
```json
{
"1.a":"All relevant licenses ",
"1.b":"Add all copyrights",
"1.c":"Add all acknowledgements"
}
```
* also for additional obligations and Obligation And Risk Assessment
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(unifiedreport): support json format for rows and also html break

src/testing/lib/TestRun.php, src/testing/lib/fossologyTest.php, src/testing/lib/reportClass.php, src/testing/utils/createUIUsers.php, src/testing/utils/simpleUi-users.php
Function ```split``` was DEPRECATED in PHP 5.3.0, and REMOVED in PHP 7.0.0.
Replace ```split``` by ```explode```.
Partial fix for #2584
=> fix(php): replace deprecated split by explode

src/nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php
PHP 8.2 complains about a syntax error (but PHP 7 does not).
Add missing semicolon at end of file.
=> fix(php): add missing semicolon

utils/freshmeat/Classes/FreshmeatRdfs.php, utils/freshmeat/lib_projxml.h.php, utils/freshmeat/tests/runGp.php
Fix old PHP syntax to be compatible with PHP 8.
Remove ```&``` in ```array_push``` and before ```new```.
=> fix(php): remove & to be compatible with PHP 8

src/cyclonedx/agent/cyclonedx.php, src/lib/php/Data/Clearing/ClearingEvent.php, src/lib/php/Data/License.php, src/lib/php/Data/Report/FileNode.php, src/lib/php/Data/Report/SpdxLicenseInfo.php, src/lib/php/Report/ObligationsGetter.php, src/lib/php/Report/ReportUtils.php, src/spdx2/agent/spdx2.php, src/spdx2/agent/template/listedlicense.xml.twig, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2-file.xml.twig, src/spdx2/agent/template/spdx2-package.xml.twig, src/spdx2/agent/template/spdx2csv-file.twig, src/spdx2/agent/template/spdx2tv-document.twig, src/spdx2/agent/template/spdx2tv-file.twig, src/spdx2/agent/template/spdx2tv-package.twig, src/spdx2/agent_tests/Functional/fo_report.sql, src/www/ui/page/AdminLicenseFromCSV.php, src/www/ui/page/AdminObligationFromCSV.php, src/www/ui/template/admin_license_from_csv.html.twig
If 2 or more licenses share the same SPDX ID, this commit de-duplicates them.
In the same process, change the data structure sent to twig files from arrays to `FileNode` and `SpdxLicenseInfo`.
1. Create 2 new Data structures `FileNode` and `SpdxLicenseInfo`.
2. Use new data structures to send data to SPDX twig files instead of plain arrays.
3. De-Duplicate licenses to each get a unique IRI.
1. First sort licenses by SPDX ID + shortname
2. Check consecutive licenses if they have the same SPDX ID. If yes, then second license is duplicate.
3. Change the license's shortname with `LicenseRef-<shortname>-<md5(text)>` to generate a unique ID.
4. This new ID will then be used as IRI and `<licenseId>` will still point to the SPDX ID.
1. Create variants of a license and give them all same SPDX ID …
=> fix(spdx): de-duplicate licenses with same SPDX ID

src/www/ui/core-schema.dat
With latest master branch, some build produces very long Fossology Version,  longer than 32 chars. This is because in table agent, column agent_rev is too short i.e only 32 characters long.
I have changed 'varchar(32)' in table agent, cloumn agent_rev to 'text' which would easily accomodate longer Fossology version.
closes #2579
=> changed varchar(32) to text

.github/workflows/release-publish.yml
This adds an explicit tag to the `scanner` docker tag on releases, just like the main image, so that people can explicitly version it.
Adds a release build similar to the main build:
https://github.com/fossology/fossology/blob/master/.github/workflows/docker-build.yml#L46-L66
The tag scheme is similar to kaniko's debug tags, which should be picked up by renovate and similar tools. See https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.17.0 for example.
=> chore(ci): tag scanner image on release

src/composer.json, src/composer.json.in, src/composer.lock, src/lib/php/Util/ArrayOperation.php, src/lib/php/Util/test/ArrayOperationTest.php, src/www/CMakeLists.txt, src/www/ui/api/Controllers/AuthController.php, src/www/ui/api/Controllers/InfoController.php, src/www/ui/api/Controllers/UserController.php, src/www/ui/api/Helper/AuthHelper.php, src/www/ui/api/Helper/RestHelper.php, src/www/ui/api/Models/ApiVersion.php, src/www/ui/api/Models/TokenRequest.php, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/api/index.php, src/www/ui/user-edit.php, src/www/ui_tests/api/Controllers/AuthControllerTest.php, src/www/ui_tests/api/Controllers/InfoControllerTest.php, src/www/ui_tests/api/Helper/AuthHelperTest.php, src/www/ui_tests/api/Helper/RestHelperTest.php
Create a new `openapiv2.yaml` file to store the v2 related changes.
The idea is to keep using this file to store the changes related to only v2 migration like camelCasing changes, moving parameters from header to query, etc. Other changes like adding new endpoint need to be updated in both `openapi.yaml` and `openapiv2.yaml`.
Once every endpoint is migrated, the original file `openapi.yaml` can be replaced with this. This will allow to let everyone know v1 is deprecated from that point of time and v2 can be released with version `2.0.0`.
Update the `TokenRequest` component to use camelCasing and update endpoints accordingly.
Remove the deprecated `/version` endpoint.
1. Update `TokenRequest` component to use camelCasing.
2. Create new file `openapiv2.yaml`.
3. Remove deprecated `/version` …
=> feat(api): migrate `/tokens` endpoints to v2

.github/workflows/build-test.yml, .github/workflows/release-publish.yml, .gitpod.Dockerfile, cmake/FoPackaging.cmake, debian/control, pbconf/fossology/deb/control, src/copyright/mod_deps, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/LicenseStdCommentDao.php, src/nomos/mod_deps, src/ojo/mod_deps, src/scancode/mod_deps, src/ununpack/agent/CMakeLists.txt, src/ununpack/agent/ununpack_globals.h, src/ununpack/mod_deps, utils/fo-installdeps
Add support for Debian Bookworm which was released on 2023-06-10.
Note: The package `upx-ucl` used by `ununpack` to extract `upx` files is no longer available on Debian package repositories. It appears to have failing a CI test https://ci.debian.net/packages/u/upx-ucl/
Keeping this PR as a WIP until the package is available. If it takes long, we would have to disable extraction of `upx` files from ununpack agent and go ahead with merge of this PR.
Add packages for `bookworm` in dependency installer scripts.
Build and install FOSSology on Debian Bookworm (12).
Closes #2596
=> feat(os): add support for Debian Bookworm (12)

src/www/ui/api/Controllers/UploadController.php
Default values for 'page' and 'limit' are now correctly assigned within else blocks.
Fix `UploadController`.
Check #2625
Closes #2625
Thanks to @deveaud-m for pointing to the error.
=> fix(api): default values of page and limit

src/lib/php/UI/Component/Menu.php, src/lib/php/UI/template/components/menu.html.twig, src/lib/php/common-sysconfig.php, src/www/ui/async/AjaxAllJobStatus.php, src/www/ui/template/all_job_status.html.twig
Add a button to indicate system load in banner.
also add same in all jobs page.
* Install FOSSology.
* add a banner message.
* You should also be able to see 'CPU/System Load'
=> feat(menu): add new button to indicate system load in banner

src/lib/php/Dao/UploadDao.php, src/lib/php/Dao/test/UploadDaoTest.php, src/lib/php/Data/Upload/UploadEvents.php, src/lib/php/Proxy/UploadBrowseProxy.php, src/lib/php/Proxy/test/UploadBrowseProxyTest.php, src/lib/php/common-ui.php, src/lib/php/services.xml.in, src/www/ui/admin-folder-size.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Models/Upload.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/core-schema.dat, src/www/ui/template/admin-folder-size-form.html.twig, src/www/ui_tests/api/Controllers/UploadControllerTest.php, src/www/ui_tests/api/Helper/DbHelperTest.php, src/www/ui_tests/api/Models/UploadTest.php
Implemented tracking of date-time on which a user was assigned to an upload. Additionally, tracking has been extended to capture the date-time when an upload was closed or rejected. This new feature will enhance monitoring and auditing capabilities.
The values are currently available only on REST endpoints `GET /uploads` and `GET /uploads/{id}`. The duration is displayed in Folder and upload dashboard.
1. Add new table `upload_events` to hold events per upload, timestamp and event type.
2. New class `UploadEvents` to hold different event types.
1. Assign an upload to a user, check if `upload_events` table is updated.
2. Assigning different user should not create new entry in `upload_events`.
3. Close or reject an upload, check if `upload_evens` table is updated.
4. Check if `GET /uploads` …
=> feat(upload): track assignee and closing events

src/lib/php/Data/Report/FileNode.php, src/lib/php/Data/Report/SpdxLicenseInfo.php, src/spdx2/agent/template/spdx2-file.xml.twig
1. Allow `null` values for arrays in `FileNode` class. Type hinting was throwing error for null values.
2. Prevent duplicate license text printing in RDF.
1. Allow `null` values in `FileNode` class.
2. Create new array to track printing of license text in same file.
1. Generate SPDX RDF report of package with no comments, acknowledgements and copyrights.
2. Generate SPDX RDF report of package where at least 1 file has a license finding of SPDX listed license and use same license as conclusion.
- For the file node in report, the license text for this SPDX listed license should only be printed once.
=> fix(spdx2): accept null values for arrays

utils/automation/fossologyscanner.py
The default parameter sets the default value for the `--report` argument. In the original code, it uses `ReportFormat.TEXT`, which is an enum member. However, when the user provides a value, it might be a string, not an enum member. The fix involves using `ReportFormat.TEXT.name` as the default value. This explicitly sets the default value as the string "TEXT" rather than the enum member `ReportFormat.TEXT`
Resolves #2641 
Modified the `default` parameter for the `--report` argument to use strings directly.
* Run the script with various combinations of `--report` values.
* Verify that the default behavior is now correctly set to `TEXT`.
CC- @GMishx
=> fix(action): Ensure proper handeling of enum values in argparse

src/www/ui/api/Controllers/UserController.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/index.php, src/www/ui/user-edit.php
Fix token generation from user-edit page.
1. Fix token generation for user page.
2. Fix error handling in user-edit.php
3. Fix the path `/users/token` to be authenticated.
4. Handle `user_edit` plugin exception in UserController.php
Try to generate new tokens from UI (User edit page) and from rest API (`/users/tokens`).
=> fix(token): fix token generation for user

src/lib/php/Dao/AllDecisionsDao.php
Added the missing space before **'UNION'**  at line 261  in **AllDecisionsDao.php** to correct syntax error 
Closes #2648
=> style(php):Corrected the SQL syntax error in AllDecisionsDao.php

src/www/ui/api/Controllers/CopyrightController.php, src/www/ui/api/Controllers/LicenseController.php
Do not check page number 1 (which is the least value) if response list is empty.
Do not check the page number if there are total 0 pages in response.
1. Query copyrights/emails from a file where there are none.
- The endpoint currently returns 400 saying page should not be > 0 which is wrong and confusing.
- Expected response is empty list.
=> fix(api): do not check page for empty response

cmake/FoPackaging.cmake
Fix PHP dependencies for Debian Bookworm.
Add PHP8.2 dependencies for Debian Bookworm in CMake Packaging script.
Create an install packages for Debian Bookworm (12).
=> fix(deb): fix dependencies for bookworm

src/decisionimporter/agent/DecisionImporterDataCreator.php
This pull request addresses a potential null pointer  issue #2656  in the `createClearingDecisions()` method within `DecisionImporterDataCreator.php`
Closes #2656. 
- Added null pointer that check for the variable `$newCeId` before processing within the foreach loop.
- Inserted `if ($newCeId === null) { continue; }` to ensure the loop skips operations if `$newCeId` is null.
- Tested the updated code by simulating scenarios where `$newCeId` could be null.
- Verified that the loop correctly skips operations and doesn't cause any errors.
/cc @GMishx
=> Fix(php) : Fix null pointer issue in createClearingDecisions()

src/www/ui/api/Controllers/ReportController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml
This PR contains some minor changes to make the cycloneDX sbom report availble via the API. This enables the user to create this report on an automated basis.
* Added the report type to the ReportController of the API
* Added the cyclonedx option to both versions of the openapi specification file. 
Create and analyse an upload and let it create a cyclonedx file e.q. via the https://editor-next.swagger.io/ interface
=> feat(api): make cyclonedx report available via the API

src/www/ui/api/Controllers/UploadController.php
Fix reading of optional query parameters in `UploadController.php`
Read optional parameters with `??` format.
Request `/uploads/{id}/summary`, `/uploads/{id}/licenses/histogram` and `/uploads/{id}/licenses/scanned` with and without the `agentId` parameter.
```
[php:warn] [pid 224455] PHP Warning:  Undefined array key "agentId" in /usr/share/fossology/www/ui/api/Controllers/UploadController.php on line 313
```
=> fix(api): read optional agentId, UploadController

cmake/SetDefaults.cmake, debian/web/postinst, install/fo-postinstall.in
Fix apache error while trying to upgrade from Debian packages.
1. If a2ensite fails on postinstall, disable (delete) the old file first
2. Do not create files in site-enabled, rather in sites-available in `web/postinst`
1. Install Debian packages of older version (before CMake, before 4.3.0).
2. Create new packages of this branch.
3. Install the latest packages. There should be no error from apache.
=> fix(postinstall): check status of a2ensite

src/lib/php/Data/LicenseRef.php, src/lib/php/Data/test/LicenseRefTest.php, src/lib/php/Report/ReportUtils.php
Create 2 consts:
1. `SPDXREF_PREFIX = "LicenseRef-"` to identify any LicenseRef
2. `SPDXREF_PREFIX_FOSSOLOGY = "LicenseRef-fossology-"` to add FOSSology's LicenseRef prefix.
1. Create 1 license with shortname `LicenseA`.
2. Create 1 license with shortname `LicenseRef-LicenseB`.
3. Saving the licenses should create `LicenseRef-fossology-LicenseA` and `LicenseRef-LicenseB`.
=> fix(spdx_ref): use LicenseRef to check ref license

src/www/ui/api/Controllers/FileInfoController.php, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/Models/FileInfo.php, src/www/ui/api/Models/FileLicenses.php, src/www/ui/api/Models/GroupPermission.php, src/www/ui/api/Models/Permissions.php, src/www/ui/api/Models/Upload.php, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php, src/www/ui_tests/api/Models/UploadTest.php
This PR addresses tasks 1, 3, 4, 5, 6, 9, 10, and 11 outlined in issue #2623 
**Common for all: Moved `groupName` variable from headers to query parameters by making a change in  RestAuthMiddleware**
**Task 1: /updoads/{id}, GET:**
- moved `groupName` variable  from headers to query params
- changed the response keys to camelCase
- modified the unit test to accommodate changes  
**Task 3: /updoads/{id}, DELETE:**
-  moved `groupName` variable  from headers to query params
**Task 4: /updoads/{id}, PATCH:**
-  moved `groupName` variable  from headers to query params
**Task 5: /updoads/{id}, PUT:**
-  moved `groupName`, `folderId`, `action` variable  from headers to query params
-  modified the unit test to accommodate changes  
**Task 6: /updoads, GET:** 
- moved `groupName`, `page`, …
=> feat(api): (1) Upgrade Upload APIs to Version 2 

install/CMakeLists.txt
In the previous repository state, configuration files were being overwritten during the installation process, potentially leading to unintended changes. To address this, a new option, `FORCE_CONF_OVERWRITE`, has been introduced. When set to `OFF` (default), the installation process will skip overwriting existing configuration files. Conversely, setting `FORCE_CONF_OVERWRITE` to `ON` will enable overwriting, allowing users to control whether configuration files should be replaced during installation.
* Introduced a new option `FORCE_CONF_OVERWRITE` (default `OFF`) to manage weather user files should be overwritten or not during installation. 
* Implemented a general function to handle installs in CMake. It takes `FILES` (list of files to install with their path), `DEST_DIR` (installation …
=> feat(buildsystem): Introduce FORCE_CONF_OVERWRITE option to control configuration file overwrites

src/ojo/agent/ojoregex.hpp, src/ojo/agent_tests/Unit/test_regex.cc
License names should end with either words, digits or a + symbol.
This prevents creation of licenses such as "MIT."
1. Reduce the min length of licenses from 3 to 2 (there are "GD" and "SL" licenses now).
2. Make sure the license text ends with a word, digit or a "+".
3. Add test case to check scenarios with "MPL-1.1+" and "MIT."
1. Create test files with following kind of license text:
- "SPDX-License-Identifier: GPL-3.0-or-later."
- "SPDX-License-Identifier: GPL-3.0+."
- "SPDX-License-Identifier: GPL-3.0-or-later WITH GCC-exception-3.1."
2. Archive the file and scan with OJO.
3. OJO should find only "GPL-3.0-or-later", "GPL-3.0+" and "GCC-exception-3.1".
=> fix(ojo): ignore extra symbols at end

src/spdx2/agent/template/listedlicense.xml.twig, src/spdx2/agent/template/spdx2-document.xml.twig
Replaced `&` with `&amp;` in the `<rdfs:seeAlso>` tag.
1.) Create a test file with SPDX-License-Identifier: BitTorrent-1.0.
2.) Scan the file with ojo.
3.) Export SPDX RDF report.
Fixes #2688 
CC @GMishx @shaheemazmalmmd
=> fix(spdx): replaced & with &amp;

src/scancode/agent/runscanonfiles.py
When using FOSSology in Docker, the scancode agent fails to scan and throws a `Permission denied: '/root/.cache'` error.
This happens because scancode attempts to create a directory in `/root/.cache` while being initiated by the `fossy` user. To resolve this issue, scancode toolkit introduced various options as mentioned in [CHANGELOG.rst](https://github.com/nexB/scancode-toolkit/blob/66d71661f5ede54cb0f3b36d7663c92a67030299/CHANGELOG.rst#L2009-L2011) and [#2355](https://github.com/nexB/scancode-toolkit/issues/2355).  
Introduced `SCANCODE_CACHE` environment variable in `runscanonfiles.py` file which holds the path to store cache (scancode agent directory in this case) which is accessible by `fossy` user.
* Pull the changes and build the project using `docker compose up --build`.
* Upload …
=> fix(scancode): Fixed failing scancode agent when using FOSSology in Docker

src/scancode/agent/runscanonfiles.py, src/scancode/agent/scancode_wrapper.cc
For scancode findings currently only the ScanCode LicenseDB key is being extracted and reported. I think, this should be changed to use the SPDX ID. The comment before `scanFileWithScancode` (`src/scancode/agent/scancode_wrapper.cc`) already mentions the SPDX ID:
```
* In licenses array:
* key-> license spdx key
[...]
```
but the ScanCode LicenseDB key is being used (key instead of spdx_license_key):
```
keys_to_extract_from_licenses = ['key', 'score', 'name', 'text_url', 'start_line',, 'matched_text']
```
This change extracts and uses `spdx_license_key` from the scancode results instead of `key`.
Upload a package and activate: "ScancodeToolkit, scan for License". The scancode results should be shown with their SPDX ID (e.g. GPL-2.0-or-later instead of gpl-2.0-plus).
=> fix(scancode): Use spdx_license_key instead of key

src/www/ui/api/documentation/openapiv2.yaml
As mentioned in issue #2704, the `openapiv2.yaml` file fails to include all required information when making a v2 post upload request using the `multipart/form-data` content-type. This PR aims to fix this.
In #2634, the documentation was updated for requests with content-type `application/json` to shift parameters from headers to the request body. However, the scenario of `multipart/form-data` content-type request was overlooked. Therefore, this case has been addressed to pass all necessary information for the endpoint.
Load `openapiv2.yaml` file in Swagger-Editor and fire up a `POST` request to `/uploads` endpoint with content-type: `multipart/form-data`. The endpoint will behave as expected. 
CC @GMishx @Akashsah2003
=> fix(api): Modified v2 YML file to accommodate v2 post upload request with multipart/form-data content type

src/lib/php/Report/ReportUtils.php
In `getFilesWithLicensesFromClearings` method of `ReportUtils.php` `getLicenseById` method of `licenseDao` is called without passing `groupId` as an argument. In case of candidate license it is not present in license_ref and when userId is not stored in the session groupId should be used but is currently not used. So `getLicenseById` returns `null`.
`$groupId` is passed in the `getLicenseById` method of licenseDao when it is called in `getFilesWithLicensesFromClearings`.
1.) Create a test file with SPDX-License-Identifier: LicenseRef-123 or any custom license identifier with LicenseRef- prefix.
2.) Scan the file with ojo and clear it.
3.) Export SPDX RDF report.
Fixes #2706 
CC @GMishx @shaheemazmalmmd
=> fix(reportutils): use groupId to get concludedlicense

src/www/ui/api/Middlewares/RestAuthMiddleware.php
In RestAuthMiddleware class, there is some code that excludes some endpoints from authentication ("/version", "/info", "/openapi", "/health") but the problem is that that code simply searches for the corresponing strings (i.e. "/version", "/info", "/openapi", "/health") inside the request path regardless of their position inside the path, so also paths like /uploads/{id}/item/{itemId}/info are excluded from authentication. This implies that when one makes an authenticated request with /uploads/{id}/item/{itemId}/info, authentication gets ignored, user is set to "Default User" and group id is set to 2. Therefore all plugins that do require authentication (including view_info, which is needed to respond to the above-mentioned API call) are not loaded, and this causes a 500 error - "Unable …
=> fix(RestAuthMiddleware): exclude from auth. only the right endpoints

src/www/ui/page/UploadSrvPage.php
When upload files using "Upload" - "From Server" page the "Ignore SCM files" option is always evaluated as disabled. This happens due to the typo in "unpackargs" variable in "src/www/ui/page/UploadSrvPage.php"
1) Variable "unpackArgs" renamed to "unpackargs"
1) Deploy FOSSOlogy instance locally and setup it accordingly
2) Upload some repository using "Upload" - "From Server" page with disabled "Ignore SCM files" option
3) Navigate to "Browse" page and check your uploaded repository content - it should contain ".git" directory
4) Repeat step 2 with enabled "Ignore SCM files" option
5) Navigate to "Browse" page and check your uploaded repository content - it should not contain any ".git*" directories and files
=> fix(ui): 'Ignore SCM files' option is always disabled on upload

src/reportImport/agent/SpdxTwoImportSource.php
Since 4.2.1.45 the ListedLicense tag is being used for exported reports, but is not being parsed when importing a report. This prevents created RDF reports from being re-imported. This patch takes ListedLicense into account when importing an RDF report and treats it the same way as "License".
Take "ListedLicense" into account when importing an RDF report and treat it the same way as "License".
1. Take any FOSSology version >= 4.2.1.45
2. Upload and scan a package
3. Put your license decisions
4. Generate an SPDX RDF report
5. Upload the same package without any action
6. Do "Import Report" for the new upload and use the previously exported RDF report
With the change in this PR the import will work. Without the change the import agent will return success but nothing is being imported. …
=> fix(reportImport): Parse for ListedLicense when importing an RDF report

src/reportImport/agent/ReportImportSink.php
When matching licenses by SPDX ID, an RDF import can fail completely if at least one license can not be matched by SPDX ID. Let's fall back to the ShortName in this case.
The change adds a fallback to ShortName when a license can not be matched by SPDX ID.
1. Take any FOSSology version starting from commit https://github.com/fossology/fossology/commit/d1e1b6e0dde4e37aa62e63b3246fd6b313e3d4d4
2. Choose a package for which you have an existing report
3. To test this change, the report has to contain at least one license statement that cannot be matched by SPDX ID (examples, that failed in my tests are: Public-domain, Dual license, ...)
4. I tested with busybox-1.36.1 and took an existing report from the OSSelot project (https://www.osselot.org/)
5. Upload the same package without any action …
=> fix(reportImport): Adding a fallback to ShortName for RDF imports.

src/lib/php/Report/ObligationsGetter.php, src/www/ui/template/ui-clearing-view_bulk.html.twig
Remove added licenses which are not identified from obligations.
Make default checked for scan only findings to improve the performance. 
* Upload a package add dummy bulk findings
* ex: choose a license which doesnt exist in that package and add with dummy text.
* same license should not appear in reports
=> fix(reports): remove additional licenses in obligation section

src/www/ui/ui-report-conf.php
Deactivated licenses are still appearing in report. as the license names that are stored in report info and license names that we are comparing are different.
* Create a license name "gpl-2.0-with-classpath-exception" and add some obligations.
* Go to conf section and deactivate few obligations.
* Deactivated obligations should not appear in report.
=> fix(conf): unify license names to match in reports

.github/workflows/conflict-check.yml
Explicitely stating required permissions is considered best practice. This case was detected by Poutine, see 
https://github.com/boostsecurityio/poutine/blob/main/docs/content/en/rules/default_permissions_on_risky_events.md.
See above
Run CI
---
:hammer_and_pick: with :heart: by [Siemens](https://opensource.siemens.com/)
=> ci: define permissions for conflict check workflow

src/lib/php/Util/StringOperation.php, src/reportImport/agent/ImportSource.php, src/reportImport/agent/ReportImportAgent.php, src/reportImport/agent/ReportImportDataItem.php, src/reportImport/agent/ReportImportSink.php, src/reportImport/agent/SpdxTwoImportSource.php, src/reportImport/agent/XmlImportSource.php
1. Use EasyRdf to navigate through RDF graph instead of reading it as an associative PHP array. This allows for more flexibility between SPDX versions.
2. Support reading Turtle files as EasyRdf already supports it.
1. Move code in `SpdxTwoImportSource.php` from associative array to EasyRdf object.
1. Test if reports generated from FOSSology can be imported.
2. Test if reports generated from other tools can also be imported.
=> refactor(reportImport): use EasyRdf to read report

src/softwareHeritage/ui/AjaxSHDetailsBrowser.php, src/www/ui/async/AjaxFileBrowser.php
Implemented the search functionality in the `Software Heritage` page and search and filter functionality in the `File Browser` page.
- Added server side logic to implement the functionalities in `AjaxFileBrowser.php` and `AjaxSHDetailsBrowser.php`.
- Type the file/directoru name in the search box to search for it or type `ext:` followed by extension to search for files with the provided extension in software heritage and file browser page.
- Select the license in `filter for scan results` to filter out all files/directories with the selected license.
Fixes #2737 
CC @GMishx @shaheemazmalmmd
=> fix(ui): implemented search in software heritage page and search and filter in file browser page

install/db/fo_mapping_license.php
When upgrading from version < 4.3 to 4.3 or later, obsolete identifiers will be renamed (e.g. GPL-2.0 -> GPL-2.0 only). If a license candidate exists with a shortname identical to the one to which we want to rename (e.g. we have a candidate with the name GPL-2.0-only), edited results and the main license can be lost for existing uploads. This Pull request addresses this issue.
The problem happens, because update_license() is not taking all relevant tables into account (only the license_file table is touched). This can be fixed by updating clearing_event, license_set_bulk and upload_clearing_license as well.
1. Install any FOSSology version < 4.3 (I tested with 4.1)
2. Create a license candidate with the name GPL-2.0-only
3. Upload a package with GPL-2.0 licensed files (I tested with …
=> fix(fo_mapping_license.php): Fix update_license()

src/delagent/agent/delagent.c, src/delagent/agent/delagent.h, src/delagent/agent/util.c
Fix minor errors in delagent.
1. Use default table name as `uploadtree`.
2. Make most of SQL calls logged.
3. Send heartbeat if running from scheduler.
1. Run delagent from CLI using `-U` flag to delete an upload.
2. Try to delete the same upload again.
3. Run delagent from UI.
=> fix(delagent): use uploadtree as default table name

src/lib/php/Report/ReportUtils.php
Since the changes for de-duplication of licenses with the same SPDX ID in commit e01006b21646b4129b61bc72de7015e9714f0c71 , exported reports do not contain entries for files fith 'No_license_found'. These have to be included (and were included before the above mentioned commit).
This commit adjusts the behaviour of addScannerResults() in a way, that files with 'No_license_found' will be reported.
1. Take any FOSSology version starting with commit e01006b21646b4129b61bc72de7015e9714f0c71
2. Upload and clear a package (I've uploaded busybox-1.36.1.tar.bz2 and imported an existing RDF report from the OSSelot project)
3. Create a SPDX TV or RDF export
Without these changes the reports won't contain any entries for all files with 'No_license_found'  as scanner result (for busybox, …
=> fix(ReportUtils): Include files with 'No_license_found' as well

src/www/ui/async/AjaxExplorer.php
createFileDataRow() calls getId() on the return value of getLicenseByShortName() without checking it:
```
$licenseEntriesRest[] = array(
"id" => $this->licenseDao->getLicenseByShortName($shortName, $groupId)->getId(),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"name" => $shortName,
"agents" => $agentEntriesRest,
);
```
In an error condition that would make the UI silently fail / crash.
Make the code more robust and check the return value of getLicenseByShortName() before using it. Only call getId() if a valid license is returned by getLicenseByShortName().
Only the behaviour in an unexpected error condition is changed. No functional changes are expected. No visible changes for the users.
=> fix(AjaxExplorer): Check the return value of getLicenseByShortName()

src/lib/php/Report/LicenseClearedGetter.php
getCachedLicenseRisk() and getCachedLicenseText() do call getRisk() / getText() on $this->licenseCache[$licenseId] without checking the value before.
```
if (!array_key_exists($licenseId, $this->licenseCache)) {
$this->licenseCache[$licenseId] = $this->licenseDao->getLicenseById($licenseId, $groupId);
}
return $this->licenseCache[$licenseId]->getText();
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
In an error condition, this will make a report generation fail with a null pointer dereference.
I propose to check $this->licenseCache[$licenseId] for null before calling getRisk() or getText(). In case $this->licenseCache[$licenseId] is null, we return null to the callers of getCachedLicenseRisk() and getCachedLicenseText(), so they can deal with it.
Only the behaviour in an unexpected error …
=> fix(Report): Check the return value of getLicenseById()

src/cyclonedx/agent/cyclonedx.php, src/spdx2/agent/spdx2.php
Main licenses are obtained using `getLicenseById` method of `licenseDao`. But `groupId` is not passed as an argument so if a candidate license is a main license an error will occur when generating reports for that upload.
- `groupId` is passed in the `getLicenseById` method of licenseDao.
1.) Create a test file with SPDX-License-Identifier: LicenseRef-123 or any custom license identifier with LicenseRef- prefix.
2.) Scan the file with ojo, make it main license and clear it.
3.) Export SPDX tag value report.
Fixes #2752 
CC @GMishx @shaheemazmalmmd
=> fix(report): use groupId to get candidate licenses which are main license

src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/Controllers/UserController.php, src/www/ui/api/Helper/UserHelper.php, src/www/ui/api/Models/Analysis.php, src/www/ui/api/Models/User.php, src/www/ui/api/Models/UserGroupMember.php, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/api/index.php, src/www/ui_tests/api/Controllers/GroupControllerTest.php, src/www/ui_tests/api/Controllers/UserControllerTest.php, src/www/ui_tests/api/Helper/DbHelperTest.php, src/www/ui_tests/api/Models/AnalysisTest.php, src/www/ui_tests/api/Models/UserTest.php
This PR aims to upgrade the `/users` and `/group` endpoints to v2 in accordance with the new upgrade guidelines.
* Completed all tasks mentioned in #2709.
* Updated `openapiv2.yaml` to have all documentation changes.
* Modified models & unit tests to make them version aware.
* Open the `openapiv2.yaml` file in Swagger Editor and test all the updated endpoints for v2 specific responses. All function as intended.
* Execute unit tests, all pass without any issues.
CC @GMishx @shaheemazmalmmd @dushimsam
=> feat(api): Upgrade User & Group APIs to Version 2

.dockerignore, Dockerfile, docker-compose.yml, utils/automation/Dockerfile.ci
Update base image for Docker from Debian Bullseye (11) to Bookworm (12).
Debian 11 will reach its end of initial support on August 14th, 2024.
**BREAKING CHANGE:** Upgrade PostgreSQL image from 9.6 to 16 in Docker Compose. This requires manual export and import of data for upgrade on existing clusters.
See helpful blogs like https://thomasbandt.com/postgres-docker-major-version-upgrade
1. Upgrade base image to Debian Bookworm.
2. Upgrade PostgreSQL image in compose to 16
Build and run FOSSology with Docker and Docker Compose.
=> deps(docker)!: update docker base to Debian 12

src/copyright/ui/ajax-copyright-hist.php, src/lib/php/Dao/CopyrightDao.php, src/www/ui/api/Controllers/CopyrightController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/api/index.php
This PR adds new endpoints to get/delete/restore/update/count user copyright findings via API.
1. Added the following new endpoints
- GET `uploads/{id}/item/{itemId}/user-copyrights` : To retrieve user copyright findings.
- DELETE `uploads/{id}/item/{itemId}/user-copyrights/{hash}` : To deactivate user copyright.
- PATCH `uploads/{id}/item/{itemId}/user-copyrights/{hash}` : To restore deactivated user copyright.
- PUT `uploads/{id}/item/{itemId}/user-copyrights/{hash}` : To update user copyright.
- GET `uploads/{id}/item/{itemId}/totalusercopyrights` : To get the count of user copyright findings.
2. Enhanced controllers, DAOs, and plugins with new methods and adjustments.
3. Updated the `openapi.yaml` & `openapiv2.yaml` files to have the new API's documentation.
Make a `GET` request to …
=> feat(api): New endpoints to get/delete/restore/update user copyright findings

utils/automation/.github-workflow.yml, utils/automation/.gitlab-ci.sample.yml, utils/automation/FoScanner/CliOptions.py, utils/automation/FoScanner/RepoSetup.py, utils/automation/fossologyscanner.py
Add Differential scan using the differential scan argument. Scans the files between two different releases. User provides target release tag value. Script fetches the diff and scans them.
* Modifies script to take tags from user and scan between them.
* Add new cli operation `differential` and cli argument flag `--tags`.
* Modify github workflow and gitlab workflow examples.
* Build new image or test using [this](https://hub.docker.com/layers/rjknightmare/fo-ci-test/diff/images/sha256-8c2825368fdaa866827c4e0cce65cd0e6fda612c98de96bd81142036a3ae8791?context=repo) one: `rjknightmare/fo-ci-test:diff`
* Use workfow files from examples.
* Add env variable called FROM_TAG and TO_TAG with appropriate values in CI settings.
=> feat(differential scans): Add differential scans to CI Scanner

Dockerfile, utils/automation/Dockerfile.ci
Hotfix for scanner image fix.
1. Use build target `ojo_exec` to build ojo binary instead of `ojo` which is a project.
2. Update dependency regex to include words and `+` symbols.
=> hotfix(scanner): fix scanner image build

src/copyright/ui/oneshot.php, src/lib/php/Data/Highlight.php, src/nomos/ui/agent-nomos-once.php, src/www/ui/api/Controllers/OneShotController.php, src/www/ui/api/Models/OneShot.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/api/index.php
This PR introduces three new endpoints to enable one-shot analysis functionality using Nomos, Monk, and copyright scanners:
1. `/uploads/oneshot/nomos` 
2. `/uploads/oneshot/monk`
3. `/uploads/oneshot/ceu`
- Added new `OneShotController` to handle all one shot analysis requests.
- Added new `OneShot` model to provide responses.
- Changed respective `oneshot.php` files to accommodate requests.
- Modified `openapiv2.yaml` and `openapi.yaml` files for documentation changes.
Create a `txt` file containing license, copyright, email, and URL details. Transmit them through the endpoints to check the outcomes. You can also validate them through a comprehensive upload.
tracked by #2503
closes #2503 
CC @GMishx @shaheemazmalmmd @dushimsam @soham4abc
=> feat(api): Added OneShot analysis endpoints for license & copyright

src/spdx2/agent/spdx2.php
The intention of deduplicateLicenseList() is de-duplicating licenses with the same SPDX ID. Duplicates are marked by adding a LicenseRef prefix and adding the MD5 hash of the license text to the shortname. Currently the sanity check for adding the prefix doesn't seem to be correct and LicenseRef might not be added. As a result duplicate licenses can end up in a generated report.
The current sanity check before adding the LicenseRef prefix doesn't seem to be correct:
```
if (! StringOperation::stringStartsWith(
$localList[$i + 1]->getLicenseObj()->getSpdxId(),
^^^^^^^^^^^^
LicenseRef::SPDXREF_PREFIX)) {
$newShortName = LicenseRef::SPDXREF_PREFIX .
$localList[$i + 1]->getLicenseObj()->getShortName();
```
The sanity check has to call getShortName() instead of getSpdxId():
```
if (! …
```
=> fix(spdx2): Mark duplicates correctly with LicenseRef prefix

src/reportImport/agent/ReportImportAgent.php
Fix #1868 
Fixed `if statement` which currently always equals to `true` and therefore never used the hash values for importing the report.  This caused the import to fail if the uploaded package name differs from the name used inside the `.rdf` file.
Adjusted `if statement` to check correctly if `$pfilesByFilename` is not null and has entries. 
Use a package (e.g. https://github.com/Open-Source-Compliance/package-analysis/tree/main/analysed-packages/dart-lang/characters/version-1.2.0), download the source and upload it to fossology. Before uploading it, change the name of the file so fossology has a different upload name than the package. Now import a report file `.rdf` and the files should be correctly concluded.
=> Fix issue 1868: SPDX import does not conclude licenses based on hash values but on file name

utils/automation/FoScanner/FormatResults.py, utils/automation/FoScanner/RepoSetup.py, utils/automation/FoScanner/Scanners.py, utils/automation/fossologyscanner.py
Add line numbers for the copyright and keyword scanners for diff scans
- Introduced a new class FormatResult to handle adding line numbers to the output of the scanners
- Modified existing print results functionality to include the line number results.
- Add new functions in main script `fossologyscanner.py` to format the results of scanners
- Add a new class `ScanResultList`, which inherits from `ScanResult` to hold full content from the scan results
- Refactored the scanner module functions to include 'whole` flags for spitting complete info.
- Build the docker image from the `Dockerfile.ci` located at `utils/automation` directory.
- Set up a Github Actions workflow in any of your repositories with this [example](https://github.com/fossology/fossology/blob/master/utils/automation/.github …
=> feat(automation) : Add line numbers to keyword and copyright scanners

src/lib/php/Dao/JobDao.php, src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Models/Job.php, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/async/AjaxShowJobs.php, src/www/ui_tests/api/Controllers/JobControllerTest.php, src/www/ui_tests/api/Models/JobTest.php
This PR aims to modify and enhance `/jobs` and related endpoints to contain more useful information.
1. For every distinct job, the `/jobs` endpoint now includes all the associated child jobs along with their detailed information.
2. The job status of each parent job is confined to its child job scope exclusively. If any other child job fails for the same upload, it won't affect the status of current job.
3. Modified `openapiv2.yml` and `openapi.yml` files to reflect documentation changes.
Make a 'GET' request to any of `/jobs`, `/jobs/id`, `/jobs/all` or `/jobs?upload=<id>` to view the modifications.
Tracked by #2514
fixes #1301 
fixes #1800 
fixes #1972 
closes #2514 
CC @GMishx @shaheemazmalmmd @dushimsam @soham4abc
=> feat(api): modify /jobs and related endpoints

.github/workflows/docker-test.yml, src/testing/docker/test-cluster.sh, src/testing/docker/test-standalone.sh
Use `docker compose` (v1) instead of `docker-compose` as it is deprecated by Ubuntu and Windows Runners.
Please refer to this [discussion](https://github.com/orgs/community/discussions/116610) and this [issue](https://github.com/actions/runner-images/issues/9557)
=> hotfix(docker_test): Use docker compose (v2) instead of docker-compose (v1)

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/Controllers/ObligationController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/api/index.php
JSON format for export and import of licenses and obligations was introduced in #2734. This PR aims to expose the same over REST APIs.
- Added controller functions and routes.
- Modified the corresponding V1 and V2 documentation. 
1. Send a `GET` request to `/license/export-json` to test the license export functionality in JSON format.
2. Send a `GET` request to `/obligations/export-json` to test the obligation export functionality in JSON format.
3. Send a `POST` request to `/license/import-json` along with JSON file to import licenses.
4. Send a `POST` request to `/obligations/import-json` along with JSON file to import obligations.
CC @GMishx @shaheemazmalmmd @dushimsam @soham4abc
=> feat(api): JSON format export/import of licenses and obligations via APIs

CMakeLists.txt
Ignore Anaconda paths as Python is not used in the build process and if defined, interferes with package finding.
Ignore conda paths from search path if defined.
1. Setup anaconda environment.
2. Setup CMake and build project.
=> chore(cmake): ignore anaconda paths

src/decisionimporter/agent/DecisionImporterDataCreator.php
This fixes an error that happened when importing a FOSSology dump from other machine. On the receiving side data was uploaded from a Git repository without running any agents. The dump contained no copyright/ECC/IPRA data. Yet it kept failing with the "No agent 'copyright' exists on server." and similar errors until I manually ran the three agents on the upload.
Bail out in the nothing-to-do case.
1. Have two FOSSsology instances - sending and receiving
2. On the sending side have an upload with decisions but no Copyright/ECC/IPRA data. Export a FOSSology dump of it.
3. On the receiving side upload the same data using the From Version Control System option. Select NO optional analysis and no options below that
4. On the receiving side import the previously created dump
Original result: …
=> fix(import): Do not require an agent if the report has no related data

src/decisionimporter/agent/DecisionImporterDataCreator.php, src/www/ui/scripts/admin-license-acknowledgements.js, src/www/ui/scripts/admin-license-std-comments.js, src/www/ui/template/admin_license_compatibility_rules.js.twig
Data Tables in License Acknowledgement , Standard comments and Compatibility were not showing the last entry on the current page.
Add calling last page on adding new row.
1. Open Acknowledgements Standard comments page, License Admin > Compatibility.
2. Add entries more than current page limit.
3. The data table should show the last entry on the page (Jumps to new page if the current length \> the page limit)
Closes #2841
=> fix(ui): DataTables Pagination Showing Last Additions

src/lib/php/UI/template/include/upload.html.twig, src/reuser/ui/agent-reuser.php, src/reuser/ui/template/agent_reuser.html.twig, src/reuser/ui/template/agent_reuser.js.twig, src/reuser/ui/template/reuse-folder.html.twig, src/www/ui/page/UploadFilePage.php, src/www/ui/template/upload_file.html.twig
When a multi file upload is done, This pull request looks into how to handle the reuse information regarding each of the upload.
In case of multi file upload, provide a modal to select reuse options for each upload. Multi file upload modal data and the mapping.
1. Reuse Information Modal is created
2. Mapping of each upload to reuse information
1. Open FOSSology User Interface.
2. Move to Upload From File Page
3. Select Multiple Files to Upload
4. Move to (Optional Reuse) --\> Should open a Reuse Modal
5. Select convenient uploads for reuse, Also select reuseMode options
6. Click Upload
=> feat(ui): multi upload support for reuse

src/www/ui_tests/api/Models/AnalysisTest.php, src/www/ui_tests/api/Models/ApiVersionTest.php, src/www/ui_tests/api/Models/BulkHistoryTest.php, src/www/ui_tests/api/Models/FolderTest.php, src/www/ui_tests/api/Models/GroupPermissionsTest.php, src/www/ui_tests/api/Models/GroupTest.php, src/www/ui_tests/api/Models/JobTest.php, src/www/ui_tests/api/Models/ScanCodeTest.php, src/www/ui_tests/api/Models/UploadTest.php, src/www/ui_tests/api/Models/UserGroupMemberTest.php
This pull request introduces more  test cases for the models as reported in issue [#2791](https://github.com/fossology/fossology/issues/2791)
The following models are covered:
- ScanCode
- Upload
- Folder
- Group
- Group permissions
- ApiVersion
- Analysis
- BulkHistory
- Job
- UserGroupMember
- UploadSummary
**Enhanced existing test cases:**  Worked on the  current test suite to improve the coverage.
**Added new test cases:** Introduced additional tests to  validate all methods and member variables.
- Navigate to the ui_tests/api/models directory.
- Execute each test case individually.
- Verify that all tests pass without any errors or failures.
CC @GMishx  @shaheemazmalmmd @soham4abc @dushimsam
=> test(models): added more unit tests for group,job,scancode.etc

src/www/ui_tests/api/Controllers/FolderControllerTest.php, src/www/ui_tests/api/Controllers/GroupControllerTest.php, src/www/ui_tests/api/Controllers/InfoControllerTest.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php, src/www/ui_tests/api/Controllers/MaintenanceControllerTest.php, src/www/ui_tests/api/Controllers/UploadControllerTest.php, src/www/ui_tests/api/Controllers/UserControllerTest.php
This pull request adds versioning in some test cases enabling them to run on both version 1 and 2 as requested in issue [#2788](https://github.com/fossology/fossology/issues/2788)
- Go and run all test cases; they pass with no issues.
CC @shaheemazmalmmd @soham4abc @dushimsam @GMishx
=> test(api): upgraded controller test cases to support v2 standards

src/lib/php/Dao/AgentDao.php, src/lib/php/Dao/test/AgentDaoTest.php, src/lib/php/Dao/test/LicenseDaoTest.php, src/lib/php/Dao/test/PfileDaoTest.php, src/lib/php/Dao/test/ShowJobsDaoTest.php, src/lib/php/Dao/test/UploadPermissionDaoTest.php, src/lib/php/common-container.php
This pull request introduces integration tests for UploadDao, PfileDao, showJobsDao and  UploadPermissionsDao
- Improved the current test cases
- Introduced additional test cases
- Added documentation on test cases
- All tests pass with no issues.
Corresponding  [issue](https://github.com/fossology/fossology/issues/2820)
CC: @GMishx , @shaheemazmalmmd , @dushimsam , @soham4abc
=> test(DAOs): Add more integration tests for uploadDao, PfileDao, showJobsDao and Upload permissionsDao.

src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui_tests/api/Controllers/JobControllerTest.php
Added the option to filter for statuses and sort the results for the following endpoints:
`/jobs` endpoint 
`/jobs/all` endpoint 
Also removed some duplicated code and cleaned up code a bit.
* `JobController.php` Added status and sort queries for api v1 and v2 for the `/jobs` and `/jobs/all` endpoints. Cleaned up code a bit, removed now unused functions.
* `DbHelper.php`Added filter for status and sorting options, removed duplicated code, implemented new cte sql statement for getting the status along with the jobs to avoid getting the status for each job separately with a loop inside the `JobController.php` .
* `openapi.yaml` and `openapiv2.yaml`  added the `status` and `sort` options to the `/jobs` and `/jobs/all` endpoints
* `JobControllerTest.php` Removed no longer needed test, …
=> feat(api): Added sort and status filter options to jobs endpoint

src/composer.json, src/composer.json.in, src/composer.lock
1. Update the version of phpoffice/phpspreadsheet to 1.29.2 which is vulnerability free.
2. The updated version needed php 7.4^, which again checked and supported by Ubuntu/Debian LTS ---> 7.4.3 to be precise.
3. Update lock file with the dependency changes.
1. Update Platform php version to 7.4.3, which is min supported version from Debian and Ubuntu LTS
2. Update phpoffice/phpspreadsheet version --> 1.29.2
1. Install fossology
2. Export unified report
=> fix(composer): update phpoffice/phpspreadsheet without XSS vulnerability

src/monk/agent/database.c
Fix(monk): Filter bulk scan files by agent for current upload
This change resolves an issue where files with valid license findings
from a recent scan could be mistakenly filtered out due to older entries
in the `license_file` table.
https://github.com/fossology/fossology/issues/2799
CC: @shaheemazmalmmd @GMishx
=> Fix(monk): Filter bulk scan files by agent for current upload

src/clixml/agent/clixml.php, src/cyclonedx/agent/cyclonedx.php, src/lib/php/Dao/ShowJobsDao.php, src/lib/php/Report/ReportUtils.php, src/readmeoss/agent/readmeoss.php, src/spdx2/agent/spdx2.php, src/unifiedreport/agent/unifiedreport.php, src/www/ui/async/AjaxShowJobs.php
Remove datetime from report names.
Merging this PR will remove the datatime from the report names in fossology.
| Original Filename                                                                                  | Formatted Filename                                                                   |
|----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
| `CLIXML_cfitsio_4.0.0-1-ubuntu-combined.tar.bz2_2024-10-24_15:45:54.xml`                           | `CLIXML_cfitsio_4.0.0-1-ubuntu-combined.tar.bz2.xml`                                         |
| `cfitsio_4.0.0-1-ubuntu-combined.tar.bz2_clearing_report_Thu_Oct_24_10_2024_03_50_41.docx`         | …
=> refactor(report): Remove datetime from report names

src/www/ui/page/UploadFilePage.php
This pull request addresses potential issues where the description or file input name could be undefined or null. The changes ensure that the application doesn't encounter errors related to count() or undefined variables when handling the $descriptions and $uploadedFiles inputs.
- Changed file -> src/www/ui/page/UploadFilePage.php
- Modified get call for descriptions:
```
$descriptions = $request->get(self::DESCRIPTION_INPUT_NAME), []);
```
- Modified get call for uploaded files:
```
$uploadedFiles = $request->files->get(self::FILE_INPUT_NAME, []);
```
- The empty [ ] parameter ensures that if the DESCRIPTION_INPUT_NAME or FILE_INPUT_NAME is missing or null in the request, the result will default to an empty array, avoiding errors when calling count() or processing files.
- Go to Upload …
=> fix: Internal Server Error in upload from file page

.gitignore, utils/automation/FoScanner/CliOptions.py, utils/automation/FoScanner/FormatResults.py, utils/automation/ScanDeps/Downloader.py, utils/automation/ScanDeps/Parsers.py, utils/automation/ScanDeps/__init__.py, utils/automation/fossologyscanner.py
Add feature to download and scan dependencies in CI. Add new CLI arguments `scan-only-deps` and `--sbom-path`.
Python Packages on PyPI are supported for now. Packages can be scanned independently in a seperate mode using `scan-only-deps`.
- Add new CLI argument `scan-only-deps` and `--sbom-path`
- Add Parsers and Downloaders for Parsing SBOM file and Downloading Dependencies locally.
- packages are downloaded locally depending on registry type (PyPI, NPM etc).
- They can be scanned independently or in repo mode along with the whole directory.
- `Repo` mode overrides the `scan-only-deps` mode.
- Build new image.
- Scan using
-  `fossologyscanner nomos ojo scan-only-deps --sbom-path <path_to_sbom_file>` for scanning only dependencies.
- `fossologyscanner nomos ojo repo --sbom-path …
=> feat(Dependecy Scan): Add Python Dependency Scan

src/decider/agent/DeciderAgent.php, src/scheduler/agent/agent.c
fix(decider): parse multiple arguments correctly
- Add multiple arguments parsing in scheduler
- fix decider agent to correctly read string argument
CC: @GMishx @shaheemazmalmmd @Kaushl2208
=> fix(decider): parse multiple arguments correctly

src/lib/php/Application/LicenseCsvImport.php, src/lib/php/Plugin/DefaultPlugin.php, src/lib/php/Plugin/test/DefaultPluginTest.php, src/lib/php/Util/HttpUtils.php, src/lib/php/common-sysconfig.php, src/softwareHeritage/agent/softwareHeritageAgent.php, src/www/ui/page/AdminLicenseFromCSV.php, src/www/ui/template/admin_license_from_licensedb.html.twig
Fossology needs a functionality to pull license data from LicenseDB. Functionality to make sure FOSSology has all the new/updated licenses from licenseDB (if reqd).
1. Configuration variable like: LicenseDB URL, LicenseDB Base URL, License Pull Endpoint, Auth Token and Sleep time.
2. A check to make sure if the variables are set then render `Import` button page else Rendering the old CSV and JSON Import page.
3. All variables set will be used for `health` check to make sure the connection with LicenseDB is working.
4. Then license import will be called:
a. Going throught the pulled JSON, if license is present in FOSSology DB log it with `License X exists with id(y)`
b. Else make a new entry in the Table for new license
5. An Agent level Log for PHP agents is introduced to write all the …
=> Feat: Licenses import from LicenseDB

src/www/ui/page/AdminLicenseFromCSV.php
fix(licensedb): remove redundant usage of LicenseDBSleep
CC: @Kaushl2208 @GMishx @shaheemazmalmmd
=>  fix(licensedb): remove redundant usage of LicenseDBSleep

src/reportImport/agent/ReportImportAgent.php
Up to now it (still) has been possible to import SPDX version 2.2 based documents. With the merge of the changes for SPDX version 3.0 (b35ba4784ebe9f8bd7a435a27478805efc2ac2a8) the import of SPDX 2.2 is not possible anymore due to an explicit check for version 2.3. Since there so was no change to the relevant import code in this commit, there shouldn't be any reason to disallow the import of SPDX 2.2.
Check for SPDX version 2.2 OR SPDX version 2.3 when importing an SPDX RDF report.
Take any version after commit b35ba4784ebe9f8bd7a435a27478805efc2ac2a8 and try to import an SPDX RDF file, stating specVersion 2.2. Nothing will be imported. With this change, the import will work.
=> fix(reportImport): (Re-)enable import of SPDX 2.2 documents

src/www/ui/api/Helper/DbHelper.php
Fixed a bug of the previous PR #2870 from me. This caused jobs to be displayed as "queued" if the do not have any item inside the `jobqueue` table.
* `DbHelper.php`: Changed the `join statement` from `left` to `right` to make sure only jobs with at least one queue item are displayed as queued.
=> fix(api): Jobs no longer displayed wrongly as queued

src/lib/php/libschema.php
FOSSology Release 4.1.0 had some Schema changes in "Agent" Table. Which now when migration to other versions raises some conflicts regarding : `cannot alter the column used by a view or a rule`
While running migrations: Steps to Drop Views and Constraint before applying changes are now in place.
1. Install FOSSology version 4.1.0
2. Upload and Run some agents.
3. Install the new version of FOSSology 4.5.0, Run Install scripts.
4. Connect to `fossology` DB  , Describe table `agent`. Column `agent_rev` should be of `text` type now.
=> fix(db): Name change Conflict in View/Table

src/lib/php/libschema.php
Due to data persistence from older versions, There are few views and columns that are creating problems with the migrations. 
1. Dropping Views Logic --> Drop view if either table or column doesnt exist
2. The SQL statement was giving all the views (System or User), which system views are not supposed to be deleted.
1. Install old version of fossology (3.0.0)
3. Do some clearing and some operations
4. Install the latest release version(with the same Database as 3.0.0)
Was successfully able to migrate.
CC: @GMishx @shaheemazmalmmd
=> fix(db): Migration Was failing due to Old views and Tables

Dockerfile
Add missing `libyaml-cpp` dependency in `Dockerfile`
- Build and Run the Docker Image (Master Branch)
- Upload a Component and Run the Compatibility Agent. The agent should fail.
- Switch to the Feature Branch.
- Rebuild and Run the Updated Docker Image.
- Upload a Component and Run the Compatibility Agent. The agent should pass.
=> fix(docker): add missing dependency

Dockerfile, src/compatibility/mod_deps
`libjsoncpp24` is the package that was not supported in `debian-bookworm`. Fix the correct name of the package in different debian codenames.
1. Fix correct version of a dependency in `debian-bookworm`
2. Fix flag `--build` should be `--buildtime`
3. Remove the explicit installation of the runtime dependency `libyaml-cpp0.7`
- Build and Run the Docker Image (Master Branch).
- Upload a Component and Run the Compatibility Agent. The agent should fail.
- Switch to the Feature Branch.
- Rebuild and Run the Updated Docker Image.
- Upload a Component and Run the Compatibility Agent. The agent should pass.
cc @shaheemazmalmmd @its-sushant @GMishx 
CLOSES: #2986
=> fix(docker): Runtime dependency not found for compatibility

docker-compose.yml
In this pull request I have removed The version attribute in docker-compose.yml as it is deprecated and no longer required with the latest Docker Compose. Removing it aligns with current best practices and prevents warnings.
Changed docker-compose.yml removing the version attribute
In your local FOSSology instance, trying running docker compose up with this commit.
Fixes: [issue#3004](https://github.com/fossology/fossology/issues/3004)
=> chore(docker): Removed version attribute from docker-compose.yml

src/lib/php/Application/ObligationCsvImport.php, src/lib/php/Util/HttpUtils.php, src/lib/php/common-sysconfig.php, src/www/ui/page/AdminLicenseFromCSV.php, src/www/ui/page/AdminObligationFromCSV.php, src/www/ui/template/admin_license_from_licensedb.html.twig
As LicenseDB is ready and hosted, Fossology needed a way to import Obligations From LicenseDB. Importing Licenses was already present.
1. Added Obligation endpoint customization
2. Added logic to do http req and fetch the obligations
3. Added a logic if the Data coming is empty and How to handle that logic
1. Set configuration Variables, If licenseDB URL is there and others are not: A simple warning message will be shown on the screen.
2. Get Auth Token from LicenseDB login API and update the LicenseDBToken. 
3. Import button will not be active if connection to LicenseDB was not successfull.
4. If LicenseDB is up and health is okay, Then Import button is enabled, Just press Import:
CC: @GMishx @shaheemazmalmmd
=> feat(import): Import Obligations From LicenseDB

src/www/ui/page/AdminObligationFromCSV.php
Undefined variable `LicenseDBSleep` throwing PHP Warnings 
Removed the Undefined Variable
1. Build and Install the Branch
2. Run fo-postinstall
3. Check apache error.log should be no warnings
CC: @shaheemazmalmmd
=> fix(adminObligationsImport): undefined variable throwing warning

.github/workflows/static-checks.yml
Action for DCO check earlier was limited to work on Pull Requests Only. The check was also needed for push to `main` branch as well.
Updated the older action `tisonkun/actions-dco@v1.1`  ---> `christophebedard/dco-check@0.5.0`
Which allows the check on both PRs and Merge Commits.
1. Static Checks Stage on the main branch should not fail
CC: @GMishx
=> fix(ci): dco check not running on push event on main

src/copyright/ui/HistogramBase.php
Show copyright if only scancode data is available
Allow copyright page to show copyright data even thought only scancode findings are present.
- Upload a new component to fossology.
- Run only scancode copyright agent.
- Navigate to copyright result page of the component.
- Should show the scancode data.
=> fix(ui): show copyright if only scancode data is available

src/www/ui/template/ui-browse.js.twig
Fixes comment rendering issue in the upload browse table
- Improves comment truncation logic in DataTables
- Ensures consistent comment display across table updates
- Allows user to see truncated comments with hovering of the comment cell in a title box.
Modified ui-browse.js.twig in order properly truncate comments in the browse table in the browse tab.
[Screencast from 05-03-25 05:51:23 PM IST.webm](https://github.com/user-attachments/assets/82047dc3-5538-4747-a53f-f321409bec09)
- Login to your FOSSology instance
- upload a file using the upload tab
- navigate to browse section using the navigation bar
- first try adding a comment which is less than 40 characters long, The comment should be completely visible.
- Then try adding a comment which is more than 40 characters long, the …
=> fix(browse): Resolve comment truncation inconsistency in DataTables

src/www/ui/api/Controllers/UploadTreeController.php
Fix the list of allowed query parameters in `/uploads/{id}/item/{itemId}/tree/view`
1. Added missing `page` and `limit` to the list of allowed query parameters.
2. Rearranged the check for parameters before usage.
Fire `GET /uploads/{id}/item/{itemId}/tree/view?page=2&limit=3&flatten=true`
and verify that all query parameters are processed correctly without errors.
=> fix(api): fix /tree/view endpoint parameter check

src/www/ui/template/upload_file.html.twig
This pull request Fixes #2900 .  The current popover warning has several issues, such as inconsistent positioning, lack of visibility, and unclear actions for users.
The proposed solution replaces the popover with a centered, responsive modal dialog that:
Clearly displays duplicate files and their details (file name, upload date).
Provides actionable buttons:
"Continue Anyway": Proceeds with the upload.
"Clear Selection": Resets the file selection.
Enhances user experience with better visibility, accessibility, and mobile responsiveness.
Upload a new file: No warning modal should appear.
Upload an existing file: The warning modal should appear with duplicate file details and action buttons.
Test "Continue Anyway" and "Clear Selection" buttons to ensure they work as expected.
Verify …
=> fix(UI): improve duplicate file warning

src/www/ui/api/Models/Analysis.php, src/www/ui/api/Models/ApiVersion.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui_tests/api/Models/AnalysisTest.php, src/www/ui_tests/api/Models/ApiVersionTest.php, src/www/ui_tests/api/Models/ScanOptionsTest.php, src/www/ui_tests/api/Models/UserTest.php
Currently, several scanner agents cannot be enabled through the JSON configuration file despite being listed in the configuration. The affected agents are:
- SCANOSS
- IPRA
- OJO
- pkgagent
- Software Heritage
While these agents appear as `true` in the JSON configuration, they do not execute during job runs, making the configuration ineffective.
Updated Analysis.php and ScanOptions.php to support all agents.
1. Analysis.php: Modified logic to ensure compatibility with all agents.
2. ScanOptions.php: Adjusted configurations to align with the changes in Analysis.php, also modified to be compatible with both version 1 of rest API as well as version 2 of rest API.
These updates enhance agent support and improve overall system robustness.
1. Open any endpoint tester.
2. Test for POST request …
=> fix(api): enable JSON configuration support for external scanner agents

src/scanoss/agent/main.c
This PR adds  proxy support for scanoss agent. The agent sets environment variable https_proxy with any value defined on http_proxy or https_proxy variables defined on fossology.conf file. The following configurations are supported:
- http_proxy = http://\<host>:\<port>
- http_proxy = http://\<user>:\<password>@\<host>:\<port>
Followed guidelines from wget agent and added routines to set the environment variables
1. Open fossology.conf file
2. Uncomment and set the right proxy addeess:port on http_proxy or https_proxy. Depending on the proxy configuration, potentially need to set up the credentials.
3. Reload scheduler configuration
=> feat(scanoss): Adds proxy support

src/copyright/agent/copyright.conf
Fixes #1813 
the issue where the Copyright agent mistakenly detects  **"é + space"** as the copyright symbol **"©"**.
Added a **negative lookbehind** (`(?<!\xC3)\xA9`) to ensure that **A9 is not matched when come after C3** 
`"Votre compte a été suspendu"`  **Should NOT be detected as copyright**
=> fix(copyright): preventing 'é' from being detected as ©

src/wget_agent/agent/wget_agent.c
This PR introduces an option to improve debugging logs by allowing users to see detailed error messages instead of suppressing them. The change removes forced output redirection (`>/dev/null 2>&1`), which was hiding important failure details for SVN and Git commands.
- Updated `GetVersionControlCommand` function to allow visibility of command execution logs.
- Removed the forced suppression of errors (`>/dev/null 2>&1`) when debugging mode is enabled.
- Ensured error messages are correctly displayed for troubleshooting version control issues.
1. Build and deploy the modified code.
2. Attempt to use **SVN** or **Git** with incorrect credentials or an incorrect repository URL.
3. Verify that error messages are now displayed in logs instead of being hidden.
4. Check if the debugging output …
=> feat(debug): Enable more debugging logs for version control commands

src/decider/ui/DeciderAgentPlugin.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Models/Decider.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui_tests/api/Models/DeciderTest.php
Add options to schedule copyright false positive deactivation and declutter options from decider agent.
1. Add missing key `concludeLicenseType` in `openapiv2.yaml`
2. Add new options `copyrightDeactivation` and `copyrightClutterRemoval` allowing user to run the experimental copyright declutter agent.
3. Since the decider is experimental and might not be installed, use `deciderAgentPlugin->isSpacyInstalled()` to first check if agent is installed before sending request to agent from REST API.
Schedule the decider agent with various options from REST API.
=> feat(rest): add option to schedule copyrightfp

src/lib/php/Util/DownloadUtil.php, src/www/ui/page/AdminAllLicenseToCSV.php, src/www/ui/page/AdminAllLicenseToJSON.php, src/www/ui/page/AdminLicenseToCSV.php, src/www/ui/page/AdminLicenseToJSON.php, src/www/ui/page/AdminLicenseToYAML.php, src/www/ui/page/AdminObligationToCSV.php, src/www/ui/page/AdminObligationToJSON.php
Add confirmation dialog before downloading export files to improve user experience.
- Add confirmation dialog before initiating downloads
- Implement for license-admin CSV exports
- Improve UX for new users
- Test across multiple browsers
1. Login to fossology server
2. Navigate to admin/license-admin/csv-export-all
3. Click on export
4. Verify that a confirmation dialog appears before download starts
Fixes #2913
=> feat(ui): add confirmation dialog for export downloads

src/www/ui/scripts/admin-license-acknowledgements.js, src/www/ui/scripts/admin-license-std-comments.js
In the **Admin Standard License Comments** section, searching by the 'Name' column was not functioning correctly. The search only worked for the Comment column but ignored the Name input field. This issue occurred because DataTables was trying to search using the full HTML string of the input field instead of its actual value.The column is easily searchable because it is ```<textarea>```.
This fix ensures that when a search is performed, DataTables extracts the value of the input field inside the Name column instead of the raw HTML, allowing proper filtering.
- Modified the DataTable configuration to properly extract the value from the **input field** in the "Name" column.
- Used ```render``` function to ensure searching works by returning the input field value instead of its HTML …
=> Fix: Search Not Working for 'Name' Column in Admin Standard License Comments

src/copyright/agent/copyright.conf
This PR updates the regex configurations in the copyright agent to exclude URLs and email addresses associated with test domains (example.com, example.net, and example.org) and specific TLDs (test, invalid). This enhancement improves the quality of the data by filtering out irrelevant entries.
- Added negative lookbehind assertions to exclude example domains (`example.com`, `example.net`, `example.org`).
- Updated TLD pattern to exclude test TLDs (`test`, `invalid`).
1. Update the `src/copyright/agent/copyright.conf` file with the new configurations.
2. Run the copyright agent on test data that includes URLs and email addresses from `example.com`, `example.net`, `example.org`, `test`, and `invalid`.
3. Verify that the agent does not report URLs or email addresses from these domains and …
=> Fix: Ignore URLs/E-mail Addresses in Example Domains and Specific TLDs #228

src/lib/php/Exceptions/HttpClientException.php, src/lib/php/Util/HttpUtils.php, src/www/ui/page/AdminLicenseFromCSV.php, src/www/ui/page/AdminObligationFromCSV.php
License and Obligation Pull feature from LicenseDB was not handling the exceptions better:
In case of anything other than `status=200`, it was showing generic mesg which is difficult to debug and handle.
Introduce switch cases for multiple `status_codes`.
In files:
1. AdminObligationFromCSV.php
2. AdminLicenseFromCSV.php
1. Setup LicenseDB server.
2. Give details of the server in `Admin > Customize`, Fille these customize information: ![image](https://github.com/user-attachments/assets/893b0a6b-7e8f-4dcf-b981-c10e6db3d3fb)
3. Play around these information, To get several Response codes from server like 404, 500, 401 etc.
4. Go to `Admin > License Admin > License Import` Check various Outputs given.
=> Fix: LicenseDB Pull mechanism Error Handling Improvement

src/clixml/agent/clixml.php
CLIXml Report generation faces issues while encountering Licenses with same SPDX-ID.
Main License and Other License Comparison now depends on `licenseId` rather than `SPDX-ID`, SPDX-ID being not unique.
1. Create a new license with a SPDX-ID that is common with some other license, E.g. `BSD-3-CLAUSE` common for licenses like: `BSD-3-CLAUSE` and `BSD-3-CLAUSE (Google Inc).
2. Upload a component
3. Do some clearing on the component, Mark one license as main license (preferrable whose spdx-id has been takes common for created license)
4. Download CLI-XML Report, Only the main license marked should be `global`
E.g.
PS: Other reports I have seen, Doesnt incorporate the same logic.(spdx, unified)
CC: @shaheemazmalmmd @its-sushant This needs rigorous testing :)
=> fix(report): CLIXml Report Showing Incorrect License Type

src/www/ui/template/upload_file.html.twig
fix tooltip for reuse modal in file upload from file page
=> fix(ui): fix tooltip for reuse modal in file upload page

src/decider/ui/DeciderAgentPlugin.php, src/reuser/ui/agent-reuser.php, src/reuser/ui/reuser-plugin.php, src/reuser/ui/template/agent_reuser.js.twig, src/scancode/ui/agent-scancode.php, src/www/ui/agent-add.php, src/www/ui/template/agent_adder.html.twig
A wait callback function was added to load the `tools.js` file in the one of the bug fix : #3038 , Due to the wait function some other functionalities required by Upload Schedule Reuse, the folder loading feature was disabled. As mentioned in this issue: #3047 
1. Introduced a Script loading function which loads the required `tools.js` before the rendering of footer.
2. Removed the wait and loading of the `tools.js` directly into `agent_adder.html.twig`
1. Upload a component
2. Select reuse options (Select an already uploaded package for reuse in specific folder, Enhanced reuse (slower), Reuse main license/s) (The folderselector should not be disabled now)
3. Select another component as the upload to reuse
4. Start the upload and Check the scheduled jobs
5. Also Check for `Jobs > Schedule …
=> fix(jsload) : Reuser agent not being scheduled

src/www/ui/template/ui-view-info.html.twig, src/www/ui/ui-view-info.php
This PR fixes the issue #1704 
This PR addresses the issue where package metadata, particularly in Debian source packages, is being displayed with double-encoded HTML entities. For example, angle brackets were showing as `&amp;lt;` and `&amp;gt;` instead of their proper representation.
- Removed all `htmlentities()` calls in the `ShowPackageInfo()` function
- this prevents double-encoding of metadata that's already encoded when stored or retrieved from the database
- Affects display of RPM, Debian binary, and Debian source package metadata
=> Fix(pkgagenterror): pkgagent printing html encoded characters

src/lib/php/tests/test_common_menu.php
This PR **fixes and modernizes** the FOSSology agent tests as part of **Issue #2084**, aligning them with the **new CMake-based build system**.
Many **FOSSology agent tests** were written **over a decade ago** and have not been significantly updated.  
Since the **CMake migration** requires a cleaner and more efficient testing setup, this PR focuses on:
- **Fixing outdated test logic**
- **Modernizing PHPUnit tests**
- **Ensuring better compatibility with the new build system**
- **Removing unnecessary workarounds that were needed for older configurations**
---
- **Refactored `test_common_menu.php`** to align with **modern PHPUnit best practices**.
- **Fixed namespace resolution for the `menu` class** (resolving "Class not found" error).
- **Replaced deprecated assertion methods**:
- Used …
=> fix(agent-tests): modernize PHPUnit test for common-menu.php

src/lib/c/libfossscheduler.c, src/nomos/agent/nomos_utils.c
This pull request addresses **issue #1299** by preventing the `nomos` CLI from attempting to read the `Db.conf` file when a database connection is not required. Specifically, the CLI no longer tries to open a DB connection when displaying the help message (`-h` flag), which previously caused a permission error.
- Introduced a global flag `should_connect_to_db` in `libfossscheduler.c` to control whether a database connection should be initiated.
- Modified the `Usage()` function in `nomos.utils.c` to set `should_connect_to_db = 0` when the help command (`-h`) is used.
- Updated the `fo_scheduler_connect_conf()` function to respect this flag, ensuring the database connection is only attempted when necessary.
---
1. **Display Help Message (`-h`):**  
Run the following command to verify that …
=> fix: prevent nomos CLI from connecting to DB when not required (#1299)

src/lib/c/libfossrepo.c, src/lib/c/libfossscheduler.h, src/nomos/agent/nomos_utils.c, src/nomos/agent/standalone.c, src/ununpack/agent/standalone.c
Define `should_connect_to_db` for standalone agents.
Also ignore some of the wrong warnings.
Define `should_connect_to_db` in `standalone.c`
Build nomossa and ununpacksa agents.
See: https://github.com/fossology/fossology/actions/runs/15320904127/job/43104247330#step:8:4962
=> fix(nomossa): define should_connect_to_db

.github/workflows/static-checks.yml
Fix DCO check to ignore only dependabot user, making it more specific.
Original ignore was added in #3073
=> fix(dco): ignore dependabot user only

.github/workflows/static-checks.yml
Static Check for DCO is failing due to regex issue.
Updated exclusion of dependabot commits from DCO
Static Checks should run
Closes #3075
=> fix(ci) : static check for dco failing

install/fo-install-pythondeps, src/compatibility/mod_deps, src/copyright/mod_deps, src/delagent/mod_deps, src/mimetype/mod_deps, src/nomos/mod_deps, src/ojo/mod_deps, src/pkgagent/mod_deps, src/scancode/mod_deps, src/scanoss/mod_deps, src/scheduler/mod_deps, src/ununpack/mod_deps, src/wget_agent/mod_deps, utils/fo-installdeps, utils/prepare-test
Signed-off-by: Oliver Fendt (ofendt@googlemail.com)
The build from source procedure currently only supports Ubuntu and Debian (in the deb ecosystem). Tuxedo is the distro, which is installed on Tuxedo machines, it is a kind of Ubuntu derivate. I installed Fossology on my Tuxedo machine, it runs Tuxedo OS noble. In order to do that I had to modify the files listed below.
The "OS" is not contained in the name, therefore it is only Tuxedo
adding Tuxedo as option when the distro is checked:
Debian|Ubuntu)
Debian|Ubuntu|Tuxedo)
resp:
Debian|Ubuntu|LinuxMint)
Debian|Ubuntu|LinuxMint|Tuxedo)
Files:
- src/copyright/mod_deps
- src/compatibility/mod_deps
- src/scanoss/mod_deps
- src/ojo/mod_deps
- src/nomos/mod_deps
- src/delagent/mod_deps
- src/scancode/mod_deps
- src/mimetype/mod_deps
- …
=> feat(core): adding support for Tuxedo

src/lib/php/Report/LicenseMainGetter.php, src/spdx/agent/spdx.php
Fixes #3061
… and spdx.php
**Null-check**:  
Checks if `$allLicenseCols` is `null`. This means the code tried to look up a license (using `$originLicenseId`), but there was no matching record in the database.
**Logging**:  
If the license is missing, it writes an error message to the PHP error log, including the license ID that was not found.
**Continue**:  
The `continue;` statement skips the rest of the current loop iteration and moves on to the next license in the list.  
This way, the missing license doesn’t stop the whole process—other licenses will still be processed.
```php
if ($allLicenseCols === null) {
error_log("Error: License ID " . $originLicenseId . " not found in the database.");
continue; // Skip this license and continue with others
}
=> fix: replace exit with proper error handling in LicenseMainGetter.php and spdx.php

src/www/ui/page/AdminObligationFromCSV.php
Import Obligations From CSV functionality was failing due to passing an `array` when a `string` is expected.  Which was creating a issue with internal `nl2br` function (which expects string).  Hence the functionality failed with `Unexpected Type`
`src/www/ui/page/AdminObligationsFromCSV.php`
- Changed handling mechanism of `handleFileUpload` response. 
- Included a basic conditional statement: If return type `array` then use the correct param from the array if `string` then directly assign to `vars["message"]`
1. Use a valid Obligations csv to import
2. Go to Admin > Obligations Admin >Obligations Import
3. Press Upload
4. Obligations should be handled and the Response should be visible.
=> fix(obligations): Import Obligations From CSV failed due bad param passed

src/spdx/agent/spdxutils.php
implodeLicenses() has been changed to be able to deal with Dual-license and custom text. This commit (6d9e289eb79e421266ce20b6f60a0de0dbb262a5) introduced a bug, which breaks the export of SPDXTV reports (handling of AND statements is not done correctly). This change fixes the issue, restoring the original behaviour and keeping the ability of handling Dual-license with custom text.
Move the concatenation of license expressions with an AND statement to the correct position.
=> fix(spdxutils): fix export of spdxtv reports
