fossology/fossology

src/cli/cp2foss.php, src/cli/fo_wrapper.php.in, src/lib/php/common-auth.php
fix #406 and add groupname option to cp2foss
=> fix #406 and add groupname option to cp2foss

src/maintagent/agent/maintagent.c
Changes on maintagent for #251
=> Changes on maintagent for #251

src/lib/php/Application/LicenseCsvExport.php, src/lib/php/Application/LicenseCsvImport.php, src/lib/php/Application/test/LicenseCsvExportTest.php, src/lib/php/Application/test/LicenseCsvImportTest.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Data/License.php, src/lib/php/Data/test/LicenseTest.php, src/lib/php/View/test/HighlightProcessorTest.php, src/www/ui/admin-license-file.php, src/www/ui/core-schema.dat, src/www/ui/page/AdminLicenseCandidate.php, src/www/ui/page/AdviceLicense.php, src/www/ui/popup-license.php, src/www/ui/template/admin_license-upload_form.html.twig, src/www/ui/template/admin_license_candidate-merge.html.twig, src/www/ui/template/advice_license-edit.html.twig, src/www/ui/template/agent_adder.html.twig, src/www/ui/template/include/macros.html.twig, src/www/ui/template/include/upload.html.twig, src/www/ui/template/popup_license.html.twig, src/www/ui/template/ui-clearing-view.js.twig, src/www/ui/ui-license-list-files.php
This feature allows to add a risk level to each license. These risk levels can be used to classify licenses resp. their obligations.
=> adding risk level to licenses

src/copyright/agent_tests/Functional/schedulerTest.php, src/phpunit.xml
* this will also allow travis to run the phpunit tests defined by the copyright agent
=> Add the functional tests from copyright to phpunit.xml

src/spdx2/agent/spdx2.php
This might be needed also for other agents.
With this patch, using the file **apache-openoffice-4.1.2-r1709696-src.zip**, all three spdx agents show `50,937 items`
=> [#560]: repair the calls of `heartbeat`

src/www/ui/page/AdminContentMove.php
* the corresponding php file is `src/www/ui/AdminContentMove.php`
* suggested by @mcjaeger
I am not shure if this shoud be allowed to everyone, but **basic testing** revealed no problems.
=> feat(ui): allow users to move and copy their uploads

src/copyright/agent/copyright.conf
=> fix(copyright): increase maximum length of TLD's

src/lib/php/common-auth.php
=> Fix reading of .fossology.rc for not parsing values

src/www/ui/ui-view.php
Tested on Ubuntu 14.04 docker container running on OS-X 10.10 from revision 87c0413cb000244227858464ba9be6996e34b4b5.
Fixes #615
=> [#615] fix ui-view error reporting

src/www/ui/admin-license-file.php
=> fix(ui): repair prepared statement in `admin-license-file.php`

src/www/ui/user-edit.php
you are either allowed to do this if you are admin or if you are editing your own account
=> feature(ui): add security check to `user-edit.php`

src/www/ui/ajax-showjobs.php, src/www/ui/template/ui-showjobs-jobqueue-row.html.twig
=> fix(ui): #635: add parameter to urls for showjobs

src/wget_agent/agent/wget_agent.c
just add quotes around the arguments of `no_proxy` in line [L354](https://github.com/fossology/fossology/compare/master...maximilianhuber:fix/issue%23298?expand=1#diff-39e61fa734c792befe51b24cedf3dfc9R354) (and whitespace changes).
=> fix(wget_agent): fix issue #298

.travis.yml, README.md, src/composer.json, src/composer.lock, src/phpunit.xml
Add coverage badged from coveralls.io
=> Create xml coverage

src/lib/php/Dao/ClearingDao.php, src/spdx2/agent/spdx2.php, src/spdx2/agent/template/dep5-copyright-document.twig, src/spdx2/agent/template/dep5-copyright-file.twig, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2-file.xml.twig, src/spdx2/agent/template/spdx2-package.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig, src/spdx2/agent/template/spdx2tv-file.twig, src/spdx2/agent/template/spdx2tv-package.twig, src/spdx2/agent_tests/Functional/schedulerTest.php
the used `or` is not the correct operator to combine licenses. The conjunction `and` should have been used.
=> fix(spdx2): fix several bugs in DEP5  and SPDX2 reports

src/www/ui/ui-view-info.php
closes #660
was caused by commit cf2a177f7f731f35e8587bec2e4f1cbe5a251edd
the fix was already suggested in #660 by @rlintu
=> fix(ui): repair issue mentioned in #660

src/delagent/agent/delagent.c, src/delagent/agent/delagent.h, src/delagent/agent/util.c, src/delagent/ui/admin-folder-delete.php, src/delagent/ui/admin-upload-delete.php, src/lib/c/libfossagent.c, src/lib/c/libfossagent.h, src/lib/php/Dao/FolderDao.php, src/spdx2/agent_tests/Functional/fo_report.sql, src/www/ui/admin-folder-delete.php, src/www/ui/core-schema.dat
This PR 
* adds permission handling for directories
* refactors delagent
* repairs permission checking
this will fix #273
see #602 for the discussion on the previous PR concerned with this issue
--
This PR should not be merged yet.
=> Rewrite/refactor delagent and fix #273

src/demomod/agent/Makefile, src/demomod/agent/demomod.c, src/demomod/agent/process.c, src/demomod/ui/demohello.php, src/readmeoss/agent/readmeoss.php, src/readmeoss/agent/version.php.in, src/regexscan/agent/Makefile
The makefiles of the plugins `demomod` and `regexscan` were outdated
=> Fix example plugins

src/www/ui/css/fossology.css, src/www/ui/css/jquery-ui.css, src/www/ui/template/ui-browse.html.twig
Added black color with bold font if selected.
background color of toggle checkbox is maintained same if selected or not
closes #595
=> In Browse section, the name “ Whole folder” Is not clearly visible since it is in white font color

docker-entrypoint.sh
Running docker without external DB did not work, since `docker-entrypoint.sh` was waiting for the (internal) DB before actually starting it. This caused problems with the call
```
docker run -p 8081:80 fossology/fossology
```
was reported by @mcjaeger.
=> fix(Docker): only wait for postgresql if not on localhost

src/lib/php/Application/RepositoryApi.php, src/lib/php/Application/test/RepositoryApiTest.php, src/www/ui/page/AboutPage.php, src/www/ui/template/about.html.twig, utils/fo-installdeps
=> feat(about) Check for latest release if user is admin

src/www/ui/ui-license-list-files.php
1) Added both file counts in ui to indicate users
2) Show all files was not working for special chars in url(like +)
=> fix(ui): Added recent agent_pk in the place of any agent_pk

.travis.yml, src/composer.json
=> chore(php): remove 5.3, set 5.6, add 7.0 to travis-ci

Dockerfile, README.md, docker-entrypoint.sh, install/docker-compose.base.yml, install/docker-compose.yml, install/fo-postinstall.in
- the dockerfile commands were reordered to prevent unnecessary rebuilds
- the repository is now a volume
- the containers run now unpriviledged
- some commands were moved from the entrypoint to the Dockerfile
- the docker-compose file is now `version: 2`
=> chore: refactor dockerfiles

utils/fo-installdeps
=> fix(install): xenial support for postgres

pbconf/fossology.pb, pbconf/fossology/rpm/fossology.spec, pbconf/pbfilter/all.pbf, pbconf/pbfilter/centos-7.pbf, pbconf/pbfilter/debian-6.pbf, pbconf/pbfilter/debian-8.pbf, pbconf/pbfilter/ubuntu-15.10.pbf, pbconf/pbfilter/ubuntu-16.04.pbf, pbconf/pbfilter/ubuntu-16.10.pbf
This is a single proper pull request for project-builder.org patches that were in another PR #731, mixed with composer modifications. I'll close #731 as these composer aspects are now followed up in #739.
=> fix(Project-builder.org): various enhancements

src/www/ui/ajax-showjobs.php
=> fix(www): correct ETA in all job view

README.md
small modifications to the README to update the current status of the project
=> fix(README): update documentation, change releases link to Github

.gitignore
add files to gitignore, which are created during make, make install and by running the php.ini adjustment script
=> chore(gitignore): update gitignore

Dockerfile, install/docker-compose.base.yml
remove 'USER fossy' from Dockerfile, /etc/init.d/postgresql cannot be started without being root
=> fix(docker): change Dockerfile, docker run command

src/www/ui/user-add.php
this change requires email adresses, like usernames to be unique
Fixes #664
=> fix(user-creation): email needs to be unique and required

src/ununpack/agent/ununpack_globals.h
=> fix(unpacking): fix unpacking of mime-type application/java-archive

.gitignore, src/cli/Makefile
fo_monk_licnese_list was incorrectly used instead of fo_monk_license_list
=> Fix a typo

src/www/ui/ui-license-list.php, src/www/ui/ui-view-info.php
ui-license-list and ui-view-info
closes #771
=> fix(www): PHP warnings

src/lib/php/Dao/LicenseDao.php, src/www/ui/page/AdviceLicense.php
Before in the advice_license mod, public notes were not saved at all.
=> fix(advice-licenses): fix public notes not being saved, when creating/editing a license

src/lib/php/Application/RepositoryApi.php
=> fix(about): fix fossology freezing, if api.github not reachable(proxy,downtime)

src/copyright/ui/Xpview.php, src/copyright/ui/template/ui-cp-view.html.twig
resolve error in error-log for browsing ecc
=> fix(ecc): resolved error in apache-errorlog display while handling ecc

.travis.yml, src/testing/docker/default-docker-test.sh, src/testing/docker/docker-compose-test.sh
fossology build into container and run
selenium E2E tests are coming soon
=> chore(travis): add docker test

src/www/ui/page/AdminContentMove.php, src/www/ui/template/admin_content_move.html.twig
this feature is a big time-saver for organizing files
=> feat(organize): allow moving/copying of multiple files/folders at the same time

src/copyright/agent/database.cc, src/copyright/ui/HistogramBase.php, src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/template/histTable.js.twig, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/test/CopyrightDaoTest.php, src/lib/php/Test/testdata.sql, src/spdx2/agent_tests/Functional/fo_report.sql, src/www/ui/core-schema.dat
please execute fo-postinstall for running this pull request code properly
=> feat(copyright&ecc): Add multi delete option to copyright and ecc

.editorconfig
=> chore(editorconfig): change indent_style and size

.travis.yml, src/cli/tests/all_tests.php, src/nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php, src/nomos/agent_tests/testdata/NomosTestfiles/UnclassifiedLicense/ldapbaseauthenticationprovider.inc.php, src/nomos/agent_tests/testdata/NomosTestfiles/Unlicense/bitcoin.php, src/testing/README, src/testing/functional/runTestCleanup.php, src/testing/lib/fossologyTest.php, src/testing/syntax/syntaxtest.sh, src/testing/templates/simpletest/myrun.php, src/testing/templates/simpletest/runtemplate.php, src/testing/utils/fo-runTests.php, src/testing/utils/upload1File.php, src/testing/utils/uploadTestData.php, src/www/ui_tests/BasicTests/runBasicTests.php, src/www/ui_tests/SiteTests/SearchMenuTest.php, src/www/ui_tests/SiteTests/login.php, src/www/ui_tests/SiteTests/runSiteTests.php, src/www/ui_tests/Tweb.php, src/www/ui_tests/VerifyTests/runVerifyTests.php
Fixes #795. A few syntax errors have also been fixed as part of this PR:
- Autoload.php
- bitcoin.php
- fossologyTest.php
Also fixed some typos in testing/README
=> chore(travis): Add PHP syntax checking to Travis

src/www/ui/async/AjaxFolderContents.php
=> feat(organize): add upload datetime and status to move uploads page

src/nomos/agent/STRINGS.in
This PR fixes issue #754. The solution was already suggested in #754 and on the fossology-devel mailinglist by 
as suggested in #754 and by dirkx@... on the mailing list
=> fix(nomos): issue #754, regexp error

src/www/ui/template/advice_license.html.twig
makes it easier to find licenses
=> feat(advice-license): add full text search to advice license

src/www/ui/page/AdminLicenseToCSV.php
Change the CSV filename from a random name to fossology-license-export-(with date).
=> fix(licenseExport): change the filename format of export license

src/www/ui/ajax-clearing-view.php, src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-view.js, src/www/ui/template/ui-clearing-view.js.twig, src/www/ui/template/ui-clearing-view_rhs.html.twig, src/www/ui/ui-clearing-view.php
A new button provided next to bulk recognition. 
To view the clearing history on click when required.
=> feat(clearing): load clearing history in a model on click

src/lib/c/libfossscheduler.c
processed items counting is not thread safe, changed it to use glib atomic integers.
This fixes #650
=> fix(libfoss): make agent processed items counting atomic

src/delagent/agent/util.c
this should fix the travis-ci build failures
=> fix(delagent): remove unused variables

install/easy-install
This uses the instruction in the fossology wiki
https://github.com/fossology/fossology/wiki/Install-from-Source
=> feat(install): provide easy install script

src/Makefile, src/composer.lock, utils/install_composer.sh
* run composer in safe mode: https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md
* update composer lock
* disable quiet mode (sometimes looks like the install process isn't working)
* update composer to 1.4.2
=> chore(composer): composer enhancements

src/www/ui/search.php
Thanks to @AndreasSchirm for the suggestion
=> feat(search): show number of search-results

.travis.yml, src/testing/travis/check-changelog.sh
checks new commits till current master to confirm with the conventional changelog
https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md#user-content-git-commit-conventions
=> chore(travis): enforce changelog

src/www/ui/css/fossology.css, src/www/ui/template/admin_content_move.html.twig
Thanks to @AndreasSchirm for the suggestion
Uses select2, which is already part of Fossology
=> feat(organize): allow searching for folders to copy/move to

src/delagent/ui/DeleteMessages.php, src/delagent/ui/DeleteResponse.php, src/delagent/ui/admin-upload-delete.php
Thanks to @AndreasSchirm for the suggestion
=> feat(delete): allow deletion of multiple uploads

src/delagent/ui/admin-upload-delete.php, src/www/ui/css/fossology.css, src/www/ui/template/include/foot.html.twig, src/www/ui/template/include/upload.html.twig
Thanks to @AndreasSchirm for the suggestion
Uses existing select2 libary
=> feat(delete): add select2 to folder select

src/nomos/agent/STRINGS.in
=> fix(nomos): fix posix incomparible regular expressions

src/spdx2/agent/spdx2.php
The convention is defined under https://spdx.org/spdx-specification-21-web-version#h.3dy6vkm
=> fix(spdx): adhere file naming convention

src/lib/php/Plugin/DefaultPlugin.php, src/lib/php/Plugin/FO_Plugin.php
We should load our own css definitions last this prevents the jquery stuff from overwriting our styles.
=> fix(ui): own css file shoult be loaded last

.travis.yml, src/testing/travis/check-changelog.sh, src/testing/travis/commitlint.config.js
This also fixes the current build problems in travis ci
=> chore(changelog): update to commitlint

install/docker-compose.Dockerfile, install/docker-compose.docker-entrypoint.sh
previously the error log of apache was not shown in the docker-compose log.
=> feat(docker-compose): increase apache verbosity

src/lib/php/Application/ObligationCsvExport.php, src/lib/php/Application/ObligationCsvImport.php, src/lib/php/BusinessRules/ObligationMap.php, src/www/ui/admin-obligation-file.php, src/www/ui/core-schema.dat, src/www/ui/template/admin_obligation-upload_form.html.twig, src/www/ui/template/include/macros.html.twig
* ob_type: type of obligation {Obligation, Restriction, Risk or Right}
* ob_classification: the level of attention the obligation could become (optional)
* ob_modifications: does this obligation concerns modified source code (optional)
* ob_comment: from the obligation admin (optional)
Additionally: add the ability to delete an obligation and throws a confirm dialogue box.
CSV import and export functions are up-to-date with the new schema.
=> feat(obligations): extend database and obligation management with new data:

utils/backup/S3/after, utils/backup/S3/before, utils/backup/S3/fo-backup-s3, utils/backup/S3/fo-restore-s3, utils/backup/S3/install
Wiki page: [S3-Backup](https://github.com/fossology/fossology/wiki/S3-Backup)
=> chore(backup): add s3 backup script

install/db/Makefile, install/db/dbmigrate_multiple_copyright_decisions.php, install/fossinit.php, install/scripts/install-spdx-tools.sh, src/copyright/ui/Xpview.php, src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/template/histTable.js.twig, src/copyright/ui/template/ui-cp-view.html.twig, src/copyright/ui/template/ui-xp-view_rhs.html.twig, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/test/CopyrightDaoTest.php, src/lib/php/Db/DbManager.php, src/lib/php/Db/Driver.php, src/lib/php/Db/Driver/Postgres.php, src/lib/php/Db/Driver/SqliteE.php, src/lib/php/Db/test/DbManagerTest.php, src/www/ui/core-schema.dat
**Note:** the migration script is currently broken. It does not register correctly whether it was already called.
related to #906 and #882
=> feat(copyright): allow to have multiple copyright decisions

src/www/ui/page/AdminLicenseCandidate.php, src/www/ui/template/admin_license_candidate.html.twig
* Delete option added for the candidate license.
* Delete only works when candidate license not in use.
* If the candidate license is in use then show the file paths where this license is used.
=> feat(candidate): add delete feature to candidate licenses

src/www/ui/template/admin_obligation-upload_form.html.twig
=> fix(obligation): select obligation type and classification by default

src/spdx2/agent/spdx2.php, src/spdx2/agent/template/dep5-copyright-document.twig
=> fix(dep5): add missing endif for deb5 document

src/www/ui/css/fossology.css, src/www/ui/page/AdminLicenseCandidate.php
File count not limited but added a scrollbar, if height increases exceeds 200px.( Which approximately display  more than 10 values with scroll bar)
closes #916
=> fix(candidateLicense): add a scrollbar to list of files in popup

src/lib/php/Dao/ClearingDao.php
On successful Testing, this fix should close issue #866 and #826.
=> fix(lib): decision for future occurrence of files

src/www/ui/core-schema.dat
copyright, ecc, clearing_decision, license_file, uploadtree_a
=> feat(schema): add new combined indexes to database tables

src/lib/php/Dao/UserDao.php, src/lib/php/common-parm.php, src/unifiedreport/agent/obligations.php, src/unifiedreport/agent/reportSummary.php, src/unifiedreport/agent/unifiedreport.php, src/unifiedreport/ui/agent-foreport.php
add groupname next to username
correct warnings in obligation
=> feat(unifiedreport): add upload history url to title table

src/lib/php/common-sysconfig.php, src/unifiedreport/agent/reportStatic.php
This fix will update the text from customized section additional and common obligation to report
=> fix(report): rearrange common and additional obligation text for report

src/lib/php/Dao/ClearingDao.php, src/www/ui/change-license-processPost.php, src/www/ui/scripts/change-license-browse.js, src/www/ui/template/change_license_modal.html.twig
.... using the edit functionality
=> feat(treeView): add remove option for irrelevant decisions

src/lib/php/common-agents.php
=> fix(common-agents): add check for empty array and false

src/spdx2/agent/template/spdx2tv-file.twig
This changes the SPDX-tv template as suggested in #963.
=> fix(spdx): make SPDX-rdf and SPDX-tv templates consistent

debian/control, debian/fossology-web.postinst
debian packages to support php7.0
and support for ubuntu 16.04
=> chore(debian) : added support for ubuntu 16.04 and php7.0

src/composer.json, src/composer.lock, src/reuser/agent/ReuserAgent.php, src/reuser/agent/reuser.php, src/reuser/agent_tests/Functional/schedulerTest.php, src/reuser/ui/agent-reuser.php, src/reuser/ui/reuser-plugin.php, src/reuser/ui/template/agent_reuser.html.twig
This will allow user to reuse main license set by the user (with the star icon) from reused packages.
=> feat(reuse): reuse mainLicense

src/wget_agent/agent/wget_agent.c
=> solved issue #988

README.md
Added a documentation for setting up the FOSSology using vagrant.
=> docs(vagrant): add vagrant setup documentation

src/lib/php/common-ui.php
Refactored a spelling mistake of "through"
=> refactor(common-ui): fix spelling mistake

src/delagent/ui/Page/AdminUploadDelete.php, src/lib/php/Dao/FolderDao.php
- Upload a new package "upload-A" in Software Repository
- Create a new folder "Test"
- Make a copy of upload A in Test
- Delete upload A in software repository
- The copied upload should not get deleted
=> feat(deleteUpload): unlink upload in case of multiple upload not delete

src/www/ui/template/browse_file.js.twig
- Upload a package with all agent options selected.
-  Go to file tree view click in checkbox next to "Actions"
- Now click on "MarkAsIrrelevant"
- Check for all the files marked as "irrelevant"
=> feat(treeView): add select all checkbox for mass operations irrelevant

src/lib/php/Dao/ClearingDao.php, src/lib/php/Data/Clearing/AgentClearingEvent.php, src/lib/php/Data/Clearing/ClearingEvent.php, src/lib/php/Data/Clearing/ClearingEventBuilder.php, src/lib/php/Data/Clearing/ClearingLicense.php, src/lib/php/Data/Clearing/ClearingResult.php, src/lib/php/Data/Clearing/test/AgentClearingEventTest.php, src/lib/php/Data/Clearing/test/ClearingResultTest.php, src/lib/php/Data/ClearingDecision.php, src/lib/php/Data/ClearingDecisionBuilder.php, src/lib/php/Data/test/ClearingDecisionBuilderTest.php, src/readmeoss/agent/readmeoss.php, src/spdx2/agent_tests/Functional/fo_report.sql, src/unifiedreport/agent/unifiedreport.php, src/www/ui/ajax-clearing-view.php, src/www/ui/change-license-processPost.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-clearing-view.js.twig
- upload a package and go to single file clearing.
- you should find new acknowledgement TD.
- add new acknowledgement to the file and make it identified.
- Generate READMEOSS and Unified Report.
- check if the acknowledgements exists
=> feat(license): add acknowledgements to license clearing

src/lib/php/libschema.php
**TO REPRODUCE**
- Install master(with fo-postinstall) branch and do some clearing. 
- Now install some other recent branch(any) with fo-postinstall script.
Below error will occur :
=> fix(schema): check for inherits when drop indexes

src/delagent/agent/util.c
**REQUIREMENTS**
* Two same packages with different versions.
**HOW TO TEST**
* On a clean instance 
* Install master and upload package1 (I used zlib-1.2.7)
* On the same instance upload package2 (I used zlib-1.2.8)
* Delete package 1
* Check Browse-view both the packages are getting deleted.
* Now install contrib/delAgentOrphanRecordsUploadTree and repeat the tests.
=> fix(delagent): change query which deletes all files with same pfile

src/copyright/ui/ajax-copyright-hist.php, src/www/ui/async/AjaxExplorer.php, src/www/ui/async/AjaxFileBrowser.php, src/www/ui/ui-browse-license.php, src/www/ui/ui-file-browse.php
=> fix(perm): reading license information and browsing should be allowed with annonymous user

src/lib/php/Application/LicenseCsvImport.php, src/www/ui/template/admin_license_from_csv.html.twig
import licenses in csv format throws error.
=> fix(import-csv): syntax error in importing license-csv

src/www/ui/page/UploadSrvPage.php, src/www/ui/template/upload_srv.html.twig
Fixed incorrect copyright statements in UploadSrvPage.php and upload_srv.html.twig
=> fix(uploadSrv): Copyright statement fix

src/nomos/agent/STRINGS.in
@rlintu please be aware. Related issue: #822
=> Fix regular expression regressions, similar to #879

install/db/Makefile, install/db/dbmigrate_copyright-author.php, install/db/resequence_author_table.php, install/fossinit.php, src/copyright/agent/copyright.cc, src/copyright/agent/database.cc, src/www/ui/core-schema.dat
1.  Get a package with at least one file which contains only author information (email/author/URL) and no copyright statement.
2.  Install master and upload the package.
3.  Upload the same package again (multiple times).
4.  Check the Email/URL/Author tab of the uploaded package. The count of entries in the table will be the multiple of actual occurrence and the number of times the package is uploaded.
1.  Install the fix and run `sudo install/fo-postinstall`.
2.  Repeat the steps above.
3.  The problem will be fixed.
1.  Decouple copyright and author table's index sequence.
Sample test package: [30-seconds-of-code](https://github.com/Chalarangelo/30-seconds-of-code)
=> fix(author): Fix multiple entries in author table

src/www/ui/admin-license-file.php
1.  Get the values from previous POST request if anything goes wrong.
2.  Make the table header sticky while viewing licenses through Admin -> License Admin -> Select License (for modern browsers only).
3.  Create HTML anchors for URL in license while viewing licenses.
1.  Check #1070.
2.  Browse the licenses through Admin -> License Admin -> Select License, while scrolling the page using a modern browser, the header of the table must follow.
3.  Browse the licenses through Admin -> License Admin -> Select License, the URL for each license must appear as a HTML anchor link.
Closes #1070.
=> feat(addLicense): Retain previous request values

src/readmeoss/agent/readmeoss.php
**TO TEST**
- Upload any component and do some license clearing.
- Generate the READMEOSS and check if the license shortname exists above text.
=> feat(readmeoss): add license shortname above the license text

src/cli/schema-export.php, src/lib/php/libschema.php, src/www/ui/core-schema.dat
**HOW TO TEST**
- Run install and fo-postinstall on any existing fossology instance.
- Check for the execution time.
=> fix(schema): check with the table property for current scheme

src/unifiedreport/agent/unifiedreport.php
Removed extra space from the export restrictions message and fix grammar.
=> chore(unifiedreport): Remove extra space

src/lib/php/common-sysconfig.php
Changed the structure of columns and values from plain string to array to ease modification.
=> fix(sysconfig): Change structure of values

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This template will be shown to the user while creating a new issue under the FOSSology repository.
As per the OSS guidelines https://opensource.guide/
=> docs(issue): Issue and PR template for new requests 

src/cli/fo_ninka_license_list.php
replace _monk_ with _ninka_ for fo_ninka_license_list
this fixes issue #1129 
Closes #1129
=> fix typo for ninka script

src/lib/php/Dao/UserDao.php, src/www/ui/page/AdminGroupUsers.php
**Fixes**
1.  If the current user's group is deleted, update the PHP Session.
2.  If a user is removed from it's selected group, select a new valid group.
**How to reproduce:**
1.  Add a user ('user1') to a group (say 'TestGroup1').
2.  Login with the user's ('user1') account and change to newly assigned group (TestGroup1) and logout.
3.  Remove the user from the same group (TestGroup1) from another account.
4.  Login again with the user's ('user1') account, the ajax call will stall.
---
1.  Create a new group ('TestGroup1').
2.  Change current group to 'TestGroup1'.
3.  Goto Admin >> Groups >> Delete Group.
4.  Delete 'TestGroup1'.
5.  Browse another page, the ajax call will stall.
Closes #1003.
=> fix(user): Update user's current group while removing from group

install/docker-compose.Dockerfile, install/fo-postinstall.in
Changes are similiar to #1145
If any command failed, then the fo-postinstall exited with a non-zero exit code.
=> feat(fo-postinstall): Implemented best practices for bash scripts.

src/lib/php/Dao/CopyrightDao.php
fix php fatal Query failed: ERROR:  UNION types bigint and text cannot be matched
install a fresh instance of master and click on single file copyright view
=> fix(copyright): unify same column selection for both queries

.travis.yml
* Removed unused dependencies.
* Removed caching for apt, because travis does not recommend it.
* Refactored matrix build config.
* Use yaml referencing to simplify compiler installation.
=> chore(travis): Simplified travis.yml

CONTRIBUTING.md
Added steps to create a new pull request in FOSSology under CONTRIBUTING.md.
=> docs(contributing): Added steps to create PR

src/copyright/agent/database.cc, src/copyright/ui/Xpview.php, src/copyright/ui/template/ui-xp-view_rhs.html.twig, src/lib/php/Dao/CopyrightDao.php
Fix the decision table primary keys.
Change `copyright_decision_pk` to generic `<table>_pk`.
Make new findings, modify and remove them in
=> fix(decisions): Replace copyright_decision_pk with table_pk

src/unifiedreport/agent/reportStatic.php, src/www/ui/ui-view-info.php
Add textarea for additional notes and general risks in info page. and refactor the code to fix missing <\tr>
Upload any package and goto info page.  and test all the fields in Report Info table.
=> feat(info): change tag from input to textarea

.travis.yml, src/testing/docker/test-cluster.sh, src/testing/docker/test-standalone.sh
* Moved syntax check and static code analysis in separate steps.
* Merged docker tests into one job to build the image only once.
* Removed not working phpunit update.
* Removed already installed packages.
* Split make all test into two steps.
Compare the logs of travis-ci.
=> chore(travis): Removed global environment variables usage.

src/composer.json, src/composer.lock, src/lib/php/Db/test/DbManagerTest.php, src/lib/php/Db/test/ModernDbManagerTest.php, src/phpunit-bootstrap.php
The `composer.lock` is out-of-sync to `composer.json`. Someone has missed to update the `composer.lock` after changing `composer.json`.
* Generated a recent `composer.lock`.
* Updated the development dependencies to the latest versions with support for php 5.6.
* Switched to Mockery::pattern() since Mockery 1.0 removed implicit regex matching.
* Upgraded bootstrapping of Hamcrest
* Run tests or check logs on travis-ci.
* Test fossology.
=> feat(composer): Updated development dependencies.

.dockerignore, Dockerfile, src/testing/docker/test-cluster.sh, src/testing/docker/test-standalone.sh, utils/fo-installdeps
Reduced the compressed size of the docker image from [378 MB](https://hub.docker.com/r/fossology/fossology/tags/) to [269 MB](https://hub.docker.com/r/robertvolkmann/fossology/tags/).
=> feat(docker): Implemented multi-staged build.

src/lib/php/Dao/CopyrightDao.php
refactor copyrightDao check uploadtree table name
Add check for uploadtree table name
edit , delete operations with existing and new uploads. generate all the reports and test
=> feat(copyright): refactor copyrightDao check uploadtree table name

.gitignore, src/deciderjob/agent_tests/Functional/schedulerTest.php, src/lib/php/Dao/FolderDao.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Dao/TreeDao.php, src/lib/php/Db/DbManager.php, src/lib/php/Proxy/LicenseViewProxy.php, src/lib/php/UI/MenuRenderer.php, src/monk/ui/admin-monk-revision.php, src/phpunit.xml, src/reuser/agent/Makefile, src/reuser/agent_tests/Functional/schedulerTest.php
**Description**
* Changes are made to correct PHPCS
* add reuser tests to phpunit
* add comments to public tests
**How to test**
install the branch and run PHPCS and phpunit testcases in your local machine.
=> fix(tests): fix PHPCS and phpunit testcases for deciderjob and reuser

CHANGELOG.md, debian/changelog
Signed-off-by: Michael C. Jaeger <michael.c.jaeger@siemens.com>
Updates to the change log file for building 3.4.0
Changes to the `debian/changelog` file and the Changelog.md in the root project level according to the commit history.
run package build `sudo dpkg-buildpackage -I`
contrib/releaseDocumentation340
=> docs(changelog): updating changelog files for 340

src/unifiedreport/agent/reportStatic.php, src/www/ui/ui-view-info.php
change general assessment tag from text to textarea
changes are done in info page as well as unified report
add some text in general assessment of info page for a package with formatting. test save update. then generate unified report and check the same.
=> feat(info): change general assessment tag from text to textarea

src/delagent/ui/admin-folder-delete.php, src/delagent/ui/template/admin_upload_delete.html.twig, src/lib/php/Plugin/DefaultPlugin.php, src/lib/php/UI/MenuRenderer.php, src/lib/php/common-buckets.php, src/lib/php/services.xml.in, src/reuser/ui/template/reuse-folder.html.twig, src/www/ui/admin-tag-manage.php, src/www/ui/async/AjaxBrowse.php, src/www/ui/scripts/ui-clearing-view_bulk.js, src/www/ui/template/admin-folder-create-form.html.twig, src/www/ui/template/admin-folder-edit-form.html.twig, src/www/ui/template/admin_license-upload_form.html.twig, src/www/ui/template/admin_license_candidate-merge.html.twig, src/www/ui/template/agent_adder.html.twig, src/www/ui/template/browse.html.twig, src/www/ui/template/change_license_modal.html.twig, src/www/ui/template/components/select-folder.html.twig, src/www/ui/template/file-browse.html.twig, src/www/ui/template/include/foot.html.twig, src/www/ui/template/include/macros.html.twig, src/www/ui/template/ui-clearing-view_bulk.html.twig, src/www/ui/template/upload_permissions.html.twig, src/www/ui/template/upload_srv.html.twig, src/www/ui/template/user_edit.html.twig, src/www/ui/user-add.php, src/www/ui/user-del.php
Use select2 library to add search functionality in long drop-downs.
Added new CSS class called `ui-render-select2` to call/apply select2 library on the elements with this class.
Closes #1223
=> feat(select2): Use select2 lib for drop-downs

src/copyright/ui/HistogramBase.php, src/copyright/ui/template/histTable.js.twig
=> feat(copyright): select and replace copyright in bulk mode

docker-compose.yml, docker-entrypoint.sh, install/db/dbmigrate_3.3-3.4.php, install/fo-postinstall.in, install/fossinit.php
Also clean constraints created by #1072 
Added the constraints created by #1072 to the table map.
Fixes #1256
=> fix(constraints): Also clean old constraints

src/delagent/agent/delagent.c, src/delagent/agent/delagent.h, src/delagent/agent/util.c, src/delagent/agent_tests/Unit/testDeleteFolders.c, src/delagent/agent_tests/Unit/testListFolders.c, src/delagent/ui/admin-folder-delete.php
=> fix(delagent): delete existing clearing events using delagent 

src/www/ui/template/ui-view-info.html.twig, src/www/ui/ui-view-info.php
Refactored `info` page to use `twig` templates.
Move all HTML from PHP to twig file.
Closes #1165
=> refactor(view-page): Use Twig templates for info page

src/www/ui/template/ui-view-info.html.twig, src/www/ui/ui-view-info.php
Display following info regarding reused package on info page:
1. Package name
1. SHA1
1. Reused group
1. Reused mode
Show info regarding reused package on info page.
1. Create an upload with reuse option.
1. Check the info page on the new package.
1. Verify the details displayed.
Note: Depends on #1268
=> feat(reused-info): Show reused package in info page

src/dox.c, src/lib/c/libfossology.h, src/lib/cpp/files.cc, src/lib/cpp/files.hpp, src/lib/cpp/libfossAgentDatabaseHandler.cc, src/lib/cpp/libfossAgentDatabaseHandler.hpp, src/lib/cpp/libfossUtils.cc, src/lib/cpp/libfossUtils.hpp, src/lib/cpp/libfossdbQueryResult.cc, src/lib/cpp/libfossdbQueryResult.hpp, src/lib/cpp/libfossdbmanagerclass.cc, src/lib/cpp/libfossdbmanagerclass.hpp, src/lib/cpp/libfossologyCPP.hpp, src/lib/cpp/tests/run_tests.cc, src/lib/cpp/tests/testUtils.hpp, src/lib/cpp/tests/test_fossdbmanagerclass.cc, src/lib/cpp/uniquePtr.hpp
Added doxygen comments for CPP library
Deployed here: https://gmishx.github.io/
=> docs(libcpp): Added doxygen comments for CPP library

.dockerignore
This PR just adds the new lines from `.gitignore` to `.dockerignore`
=> chore(docker): update dockerignore

install/src-install-apache-example.conf, src/composer.json, src/composer.lock, src/lib/php/Exceptions/DuplicateTokenKeyException.php, src/lib/php/Exceptions/DuplicateTokenNameException.php, src/lib/php/common-sysconfig.php, src/lib/php/services.xml.in, src/www/ui/api/Controllers/AuthController.php, src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/Controllers/ReportController.php, src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/AuthHelper.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/RestHelper.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxManageToken.php, src/www/ui/core-schema.dat, src/www/ui/css/access-token.css, src/www/ui/scripts/user-edit.js, src/www/ui/template/user_edit.html.twig, src/www/ui/user-del-helper.php, src/www/ui/user-del.php, src/www/ui/user-edit.php
Use JWT based bearer authentication for REST API instead of insecure basic authentication.
1. Deprecated `/auth` resource to remove basic authentication.
1. Added new resource `/tokens` to allow users to create new bearer tokens.
1. Use JWT for bearer authentication.
1. Max life of token can be modified from `sysconfig` table (Admin > Customize) (defaults to 30 days).
1. Allow user to create tokens with "read only" and "read/write" access (referred as scope of a token).
1. Read tokens can be used only on **GET** methods. Other methods require write access.
1. Whenever a user creates a request to get a new token, a new JWT token is generated in following manner:
1. Create a payload with `iss`, `aud`, `exp`, `nbf`, `jti` and `scope`.
1. `jti` is calculated as token's pk from DB and user's …
=> feat(rest): Use bearer auth instead of basic

CHANGELOG.md, debian/changelog
Please describe the changes in your pull request in few words here.
=> docs(changelog): updating changelog files for 350-rc1

.gitignore
Add ubuntu log files of vagrant to gitignore
=> fix: Add ubuntu log file to gitignore

CHANGELOG.md, debian/changelog
updating changelog files for pre-release 350-rc2.
fix(apache): Add rewrite string to apache conf
fix(git): Add ubuntu log file to gitignore
=> docs(changelog): updating changelog files for 350-rc2

utils/fo-installdeps
this fixes a bug introduced by #1327
=> fix(fo-installdeps): there is a wrong failing default case

src/composer.json, src/composer.lock, src/lib/php/Report/ClearedGetterCommon.php, src/lib/php/Report/LicenseIrrelevantGetter.php, src/lib/php/Report/LicenseMainGetter.php, src/unifiedreport/agent/reportStatic.php, src/unifiedreport/agent/unifiedreport.php
* Separated tables for copyright in to two for scanner findings and user findings.
* Update phpword from v0.13.* to v0.16.*
* fix warnings that appears everytime in unified report job log. 
Fix warnings, and separate copyright tables.  
* Upload a package and do some clearing of license, copyright and ecc.
* Generate unified report, readmeoss and other report formats check for desired output.
* Check the job log of unified report.
```2019-03-28 15:40:13 unifiedreport [0] :: JOB[185].unifiedreport[22603.localhost]: "PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/local/share/fossology/unifiedreport/agent/unifiedreport.php on line 274"
2019-03-28 15:40:13 unifiedreport [0] :: JOB[185].unifiedreport[22603.localhost]: "PHP Stack trace:" …
```
=> feat(unifiedReport): seperate user and scanner findings of copyrights

src/copyright/ui/template/copyrighthist.html.twig, src/copyright/ui/template/histTable.js.twig, src/copyright/ui/template/ui-cp-view.html.twig, src/www/ui/scripts/jquery.dataTables.select.js, src/www/ui/template/admin_license_candidate.html.twig, src/www/ui/template/admin_license_file.html.twig, src/www/ui/template/admin_license_file.js.twig, src/www/ui/template/advice_license.html.twig, src/www/ui/template/browse.html.twig, src/www/ui/template/browse_file.js.twig, src/www/ui/template/browse_license-lic_hist.js.twig, src/www/ui/template/file-browse.html.twig, src/www/ui/template/file-browse.js.twig, src/www/ui/template/ui-browse.html.twig, src/www/ui/template/ui-browse.js.twig, src/www/ui/template/upload_permissions.html.twig
Paging style is changed for all the views where datatable pagination exists
add a new select datatatable plugin to fossology
view all the pages where datatable exists and test pagination.
=> feat(datatable): add select plugin of datatable to change paging

src/composer.json, src/composer.lock, src/lib/php/common-container.php, src/www/ui/api/index.php
Currently the Dependency Injection container used by Slim for REST API is not cached by FOSSology.
Also pinning the Composer dependencies to help making FOSSology more compliant.
1. Cache slim DI container like Symfony container.
1. Pin composer dependencies.
1. Check the general working of FOSSology (for pinning the dependencies).
1. Check the working of REST API (for caching of the container).
=> feat(api): Cache Slim DI container

src/www/ui/async/AjaxExplorer.php
Currently, if an upload contains a folder with only one file in it, the **License Browser** does not show the license findings and decisions.
The UI currently changes the file name if such case occurs.
Now other parameters are also updated at the same time using new function `updateTheFindingsAndDecisions` (reusing the old code).
1. Install current master branch.
1. Upload a package with a folder containing single file.
1. Check the parent folder using the **License Browser**.
- The license findings and decisions will be missing.
1. Install the fix and browse the same upload.
1. It should show the findings.
1. The flat view should not be effected.
1. The other features links ([View][Info][Download][Tag][Edit]) on the right should not be effected.
=> fix(ui): Show license findings for folder with single child

src/lib/php/Report/LicenseIrrelevantGetter.php
Changed the return value for irrelevant files
* upload any package.
* mark some files as irrelevant.
* generated unified report and check for the marked files.
=> fix(unifiedreport): fixed issue with irrelevant file display

src/spdx2/agent/spdx2.php, src/spdx2/agent/template/spdx2-file.xml.twig, src/spdx2/agent/template/spdx2tv-file.twig, src/www/ui/admin-upload-edit.php, src/www/ui/core-schema.dat, src/www/ui/template/admin_upload_edit.html.twig, src/www/ui/template/ui-view-info.html.twig, src/www/ui/ui-view-info.php
Remove dependency from upload table for SPDX license Comments.
* Upload a package one with all agents checked, do some license clearing with license comments.
* Go to info page and select "Show SPDX license comments".
* Download SPDX2 reports and check for the commets.
=> feat(spdx2): SPDX output does not yet show license comments

src/copyright/ui/ajax-copyright-hist.php, src/copyright/ui/template/histTable.js.twig, src/lib/php/Dao/UploadDao.php
handle bad requests and remove PHP notices 
add check for count of parameters before list them into variables
=> fix(copyright): fix php notices in copyright hist view

src/www/ui/page/AdminGroupUsers.php
Resolves #1351  
The new page looks like
=> feat(ui): Add user descripption of available user in group management page

src/www/ui/admin-obligation-file.php, src/www/ui/template/admin_obligation-upload_form.html.twig, src/www/ui/template/include/foot.html.twig
Fix #1300  & #1306 
The smaller size of dropdown UI (Showing Three-dots earlier) was fixed. 
The database was not connected to the Dropdown menu so it was showing default selection while editing. [fixed]
=> fix(obligations): fix UI and connected db to dropdown menu

src/www/ui/admin-license-file.php
If a license has conclusion and report set to some other license and these are updated later to `[self]` from the drop down, the value does not update.
1. Check if the obligation list is send in POST request.
1. Handle the case of conclusion and report separately if value is set to 0.
1. Few prepared statements optimization.
1. On master, create a new license with conclusion and report set to different license.
1. Edit this new license and change conclusion and report to `[self]`.
1. Check the license again, the values are not updated.
1. Install the fix and repeat the same steps.
1. The values should be updated for the license.
=> fix(admin-license-file): Fix update conclusion to self

.gitignore
Added the Visual Studio IDE generated file to gitignore
Modified the `gitignore` in the main file
=> fix(vscode): Add vscode editor file to gitignore

src/www/ui/ui-report-conf.php
closes #1377
Rename array name 
Described here #1377
=> fix(reportConf): include correct array from  to fix report conf

install/db/dbmigrate_3.5-3.6.php
Take 10 % of total records and process.
Install fossology with a old commit before https://github.com/fossology/fossology/pull/1370 
and check if the post install is through.
=> feat(dbmigrate_3.5-3.6): add limit to process number of records

install/Makefile, install/db/Makefile, install/db/dbmigrate_3.5-3.6.php, install/db/dbmigrate_pfile_calculate_sha256.php.in, install/fo-postinstall.in, install/fossinit-common.php, install/fossinit.php, src/www/ui/core-schema.dat
Since calculation of SHA256 for all pfiles is a computation heavy job and requires extra time to run, it is advisable to make it optional during initialization and allow user to run it as a separate job in system.
This PR aims to implement the same.
Since the pfile computation is optional, new flags (`--force-decision`, `--force-pfile`) are added to `fo-postinstall` and `fossinit.php`. Along with the flags, user can set `FOSSPFILE` environment variable to continue the computation of `pfile` checksums (similar to `--force-pfile`).
If non of the options are provided and the total time required by the script is less than 45 minutes, the migration will continue.
Otherwise, a message will be printed on the screen showing the options which can be used to do the migration (forcing using flags, …
=> fix(migration): Make pfile sha calculation separate script

src/lib/php/Dao/FolderDao.php, src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/Models/Folder.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml
1. Copyright agent can not be scheduled from API.
2. Get /users/ always return same result.
3. Add parent folder id to the folder model.
Check following points:
1. Copyright agent can be scheduled from the REST API.
1. /users/ endpoint returns the requested data.
1. /folders/ endpoint returns the parent id (or null for root folder).
=> fix(api): Adhere to specification

src/mimetype/agent_tests/Unit/Makefile, src/monk/agent/Makefile, src/nomos/agent/Makefile, src/pkgagent/agent_tests/Unit/Makefile, src/scheduler/agent_tests/Unit/Makefile, src/ununpack/agent_tests/Unit/Makefile, src/wget_agent/agent_tests/Unit/Makefile
Check #185
Added missing dependency for `libfossology.a`
Check #185
Closes #185
=> fix(build): Fix clean build from all dirs

CHANGELOG.md, debian/changelog
Just adding to `CHANGELOG.md` and `debian/changelog` the necessary information to have the 3.6.0-rc1 information 
Added simple entry to `debian/changelog` and comprehensivepre-release information to the `CHANGELOG-md`
Just look the files, for example if the markdown is correct.
=> Adding changelog files for 3.6.0-rc1 pre-release

src/lib/php/Dao/LicenseDao.php, src/unifiedreport/agent/obligations.php
Include candidate license for obligations in unified report.
refer #1440 
closes #1440
=> feat(unifiedreport): add candidate licenses to the list of obligations

install/db/dbmigrate_3.5-3.6.php
Fix the PHP syntax in dbmigrate_3.5-3.6.php
Remove shorthand array notation for retrieving values.
1. Install FOSSology and run `fo-postinstall`.
=> fix(dbMigrate): Fix PHP syntax error

src/composer.json, src/composer.lock, src/reportImport/agent/ReportImportAgent.php
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
Update easyRDF to a stable version in composer.
change composer.json and replace version of easyRDF.
* Install fossology and check if report import works.
* Check the job log and find no warnings.
=> fix(importReport): update easyRDF to a stable version

CHANGELOG.md, debian/changelog
chore(changelog): add info to changelog files for release 3.6.0
=> chore(changelog): add info to changelog files for release 3.6.0

src/testing/db/c/libfodbreposysconf.c
Use a dynamic approach for string concatenation.
Fix possible buffer overruns with dynamic string allocation.
Closes #1422 
Upgrade vm to ubuntu/bionic and build with gcc-8.3. No warnings should occur.
=> fix(testing/db/c): Prevent buffer overflows

src/Makefile, src/composer.json, src/composer.lock, src/spasht/Makefile, src/spasht/agent/Makefile, src/spasht/agent/spasht.php, src/spasht/agent/version.php, src/spasht/agent/version.php.in, src/spasht/spasht.conf, src/spasht/ui/Makefile, src/spasht/ui/agent-spasht.php, src/spasht/ui/services.php, src/spasht/ui/template/agent_spasht.html.twig, src/spasht/ui/template/agent_spasht_advanceSearch_form.html.twig, src/spasht/ui/template/agent_spasht_search.html.twig, src/spasht/ui/template/show_definitions.html.twig, src/spasht/ui/ui-spasht.php, src/www/ui/core-schema.dat, src/www/ui/css/spasht.css
> #1450 
Updated Core-schema.dat for spasht db
- added advanced search (WIP)
- updated db schema for spasht
`sudo make install`
=> Feat/spasht 1.0

src/www/ui/core-schema.dat, src/www/ui/page/AdminGroupUsers.php, src/www/ui/template/admin_group_delete.html.twig, src/www/ui/template/admin_group_users.html.twig
* Add validation in case of removing all users from group.
* Remove some constraints .
* add notes 
* Create a group. add some users.
* Try Remove all users from that group from "manage group users".
* it should not allow you to remove all users.
=> fix(groups): add validations and remove CONSTRAINTS

src/lib/php/Dao/SpashtDao.php, src/lib/php/services.xml.in, src/spasht/Makefile, src/spasht/agent/Makefile, src/spasht/agent/SpashtAgent.php, src/spasht/agent/spasht.php, src/spasht/ui/Makefile, src/spasht/ui/agent-spasht.php, src/spasht/ui/template/agent_spasht.html.twig, src/spasht/ui/template/agent_spasht.js.twig, src/spasht/ui/template/agent_spasht_advanceSearch_form.html.twig, src/spasht/ui/template/agent_spasht_search.html.twig, src/spasht/ui/template/show_definitions.html.twig, src/spasht/ui/template/show_details_table.html.twig, src/spasht/ui/template/show_uploads_table.html.twig, src/spasht/ui/ui-spasht.php, src/www/ui/core-schema.dat
> #1448 
Updated UI for definition and updated spasht db schema
- Fixed schema fk name
- Integrated spasht db table
- updated UI for schedule agent
- added show details for definitions
- Fixed UI bug
`sudo make install`
=> Feat/spasht 3.0

src/lib/php/Dao/SpashtDao.php, src/spasht/Makefile, src/spasht/agent/Makefile, src/spasht/agent/SpashtAgent.php, src/spasht/agent/spasht, src/spasht/agent/spasht.php, src/spasht/agent/version.php.in, src/spasht/ui/Makefile, src/spasht/ui/agent-spasht.php, src/spasht/ui/template/agent_spasht.js.twig, src/spasht/ui/template/show_definitions.html.twig, src/spasht/ui/template/show_details_table.html.twig, src/spasht/ui/ui-spasht.php, src/www/ui/async/AjaxExplorer.php, src/www/ui/async/AjaxFileBrowser.php, src/www/ui/template/browse_file.js.twig, src/www/ui/template/file-browse.js.twig, src/www/ui/template/ui-browse-license_file-list.js.twig, src/www/ui/ui-browse-license.php, src/www/ui/ui-file-browse.php, src/www/ui/ui-license-list-files.php
> #1451 
Successfully fixed spasht db schema and integrated Licenses
- Fixed Table Issues
- Fixed Current Spasht UI
- Started Agent to fetch the response  from ClearlyDefined harvest endpoint
- Successfully separated Licenses
- Added Spasht 'Sp' to License UI
`sudo make install`
=> Feat/spasht 4.0

debian/control, debian/rules, src/Makefile
Removing ninka information from `debian/control` as well after removing it from `Makefile` by PR #1449
1. Comment information about ninka in `debian/control`.
Build Debian packages and check that the ninka package should not be created.
=> chore(control): Remove ninka from debian/control

src/www/ui/agent-add.php, src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Models/Decider.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml
add feature to schedule ojo decider through rest.
add feature to schedule ojo decider through rest.
Schedule OJO through rest Api
=> feat(rest): add auto conclusion for ojo findings if

src/readmeoss/agent/readmeoss.php
Edited global Licenses are not appearing in the Main Licenses section of the readmeoss report
* Submit another text/edited text for a license in the License text field
* select that particular license as a global license
* generate a readmeoss report
=> fix(readmeoss): added edited global license text in readmeoss

CHANGELOG.md, debian/changelog
Signed-off-by: Michael C. Jaeger <michael.c.jaeger@siemens.com>
adding for 3.7.0-rc1:
* Changelog.md
* debian/changelog
accordingly...
=> chore(release): adding changelog entries for 3.7.0-rc1

src/composer.json, src/composer.lock
update phpword to a latest version https://github.com/PHPOffice/PHPWord/releases
* end-to-end testing for unified report
=> chore(unifiedReport): change phpword to a latest version

debian/control, src/composer.json, src/composer.lock, src/www/ui/api/Controllers/VersionController.php, src/www/ui/api/documentation/openapi.yaml, utils/fo-installdeps
- Remove php-yaml from os level and add it to composer
- Update composer.lock file with latest changes
- Correct failing yaml file
- Remove php-yaml dependency from debian/control file
* build Debian packages and test if the installation works file without errors.
=> chore(installdeps): remove php-yaml from os level and add it to composer

src/lib/php/Report/ClearedGetterCommon.php
=> fix(copyright): only scanner finding copyrights to unifiedreport

CHANGELOG.md, debian/changelog
This is changelog for 3.7.0
added commits in CHANGELOG.md
created entry for debian/changelog
=> chore(release): adding changelog for 3.7.0

CHANGELOG.md
Fix the commits in change-log.
=> fix(CHANGELOG): Fix the changelog

src/lib/php/Dao/ClearingDao.php
Packages without any scanners scheduled tends to fail while opening the
view-license since getLatestSuccessfulAgentIds() returns empty array.
Check if getLatestSuccessfulAgentIds() returns empty array then fix the
SQL accordingly.
1. Upload a package without scheduling any scanner.
1. Browse the package and open a single file.
- The view will fail to load.
1. Install the branch and repeate the steps above.
- The view should load successfully.
1. Add a user decision to any file, the clearing counters on top should
update accordingly.
=> fix(view-license): Browse file without scanner ars

src/copyright/ui/list.php, src/delagent/ui/DeleteMessages.php, src/delagent/ui/DeleteResponse.php, src/delagent/ui/Page/AdminUploadDelete.php, src/www/ui/change-license-processPost.php
Fixed apache error log.
Needs general testing
closes #1544
=> fix(log): fix warnings from apache error log

src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
Include correct license name for last good nomos scan.
Change the license name from CC-by to CC-BY-SA in last good nomos scan.
* Check Travis.
=> fix(nomos):test-cases

src/wget_agent/agent/wget_agent.c
Added as per comment by @maxhbr https://github.com/fossology/fossology/pull/1441#pullrequestreview-283466189
Remove dulpicate code.
=> chore(wget_agent): Remove duplicate code

debian/control, debian/rules, src/fossy-ruleset.xml, src/lib/php/Dao/SoftwareHeritageDao.php, src/softwareHeritage/agent/softwareHeritage.conf, src/softwareHeritage/agent/softwareHeritageAgent.php, src/softwareHeritage/ui/AjaxSHDetailsBrowser.php, src/softwareHeritage/ui/agent-shagent.php, src/softwareHeritage/ui/softwareHeritage-plugin.php, src/softwareHeritage/ui/template/softwareHeritage.html.twig, src/softwareHeritage/ui/template/softwareHeritage.js.twig
Add proxy settings if exists for SHagent.
- add proxy settings for SHagent.
- add SHagent to PHPCS.
- add php-curl dependency to debian.
- fix PHPCS
Install SHagent and test it with proxy enabled.
Depands on https://github.com/fossology/fossology/pull/1401
=> fix(SHagent): add proxy settings, add SH agent to PHPCS

install/db/dbmigrate_3.5-3.6.php, install/db/dbmigrate_3.6-3.7.php, src/lib/php/Dao/UploadDao.php, src/reuser/agent/ReuserAgent.php, src/reuser/ui/agent-reuser.php, src/reuser/ui/template/agent_reuser.html.twig, src/www/ui/ui-view-info.php
Copy all the values of Conf page in the case of reuse.
New option has been provided to reuse conf page.
- Upload package X. 
- Do some clearing and add report configuration values in conf page.
- Upload package X again with reuse option "Reuse report configuration settings".
- Check if the configuration values are copied.
=> feat(reuse): add reuse of report configuration settings

.gitignore, debian/control, debian/rules, src/lib/php/Dao/ClearingDao.php, src/lib/php/common-sysconfig.php, src/spasht/agent/SpashtAgent.php, src/spasht/ui/template/agent_spasht.js.twig, src/spasht/ui/template/agent_spasht_advanceSearch_form.html.twig, src/spasht/ui/template/agent_spasht_search.html.twig, src/spasht/ui/template/agent_spasht_ui_content.html.twig, src/spasht/ui/ui-spasht.php
Made changes to fix bugs, added proxy use, fixed micromenu, added debian control
1. Moved url to Sysconfig
2. Used proxy
3. Updated debian control and rules
4. Fixed bug generated in advance search
5. Fixed Micro menu and Added micromenu
`sudo make install`
=> fix(spasht): micromenu, uri and proxy

src/lib/php/Dao/ShowJobsDao.php, src/lib/php/Dao/SoftwareHeritageDao.php, src/softwareHeritage/agent/softwareHeritageAgent.php, src/www/ui/core-schema.dat
Store status of software heritage results in database.
- Remove SW Heritage agent from calculating ETA.
- Add All licenses found through SW Heritage to a single column in DB.
* Test SW Heritage agent end to end.
=> feat(SWHagent): add status of request to DB

Dockerfile
**Description**
Made a single line update in Dockerfile
**Changes**
Changed `RUN make install clean` to `RUN make clean install clean`
Closes #1633
Signed-off-by: Dinesh <dineshr93@gmail.com>
=> Fix(Dockerfile): make clean install clean

CHANGELOG.md, debian/changelog
Change log added for release  3.8.0-rc1.
=> chore(release): add changelog for 3.8.0-rc1

debian/control
missing `,` after `libicu-dev` failing package build
added , after the package libicu-dev. 
Build the packages
=> fix(package): fix syntax

README.md
The README refers to `COPYING` and `COPYING.LGPL`, neither of which exist.
The README now refers to the correct `LICENSE` file :)
N/A
=> docs(README): Refer to the correct file for the licenses

src/softwareHeritage/agent/softwareHeritageAgent.php
closes #1647 
Add time to reset to agent job log.
* Scan SWH agent with a package more than 120 files and check the job log.
=> feat(SWH): add time to reset if X-RateLimit-Limit reached for SWH agent

.gitignore
Add generated php.ini to .gitignore
=> fix(git) : add php.ini to gitignore

CONTRIBUTING.md
The current Git rebase link was broken. Updated it with the new link. Also, refactored into the latest form of Markdown.
=> docs(contributing.md): Fixed broken link in contributing.md"

src/softwareHeritage/agent/softwareHeritageAgent.php
Catch exception in case of timeout for SWH.
* Upload a package and scan SWH. where there no internet connection. 
* agent should fail writing the error message to job log.
=> feat(SWH): catch exceptions in case of bad response

CHANGELOG.md, README.md, debian/changelog
Changelog for release 3.8.0
Also, added few badges to the README.md
=> chore(release): Changelog for release 3.8.0

src/lib/php/Dao/ClearingDao.php, src/www/ui/ajax-clearing-view.php, src/www/ui/scripts/change-license-common.js, src/www/ui/scripts/change-license-view.js, src/www/ui/template/ui-clearing-view_rhs.html.twig
* check if the candidate license is added to the list 
* if added the show message
* Upload a package X.
* Create a candidate license.
* Add the candidate license to license table in single file view through user decision.
* Check "Apply decision to all future occurrences of this file" option.
=> feat(globalDecision): show warning if the candidate license is added

debian/control, utils/fo-installdeps
as per discussion on #1631 one dependency was missing, So I have added it in fo-installdeps and Debian control file
Fixes: #1631
=> fix(fo-installdeps): added a missing dependency

src/copyright/ui/agent-copyright.php, src/copyright/ui/agent-ecc.php, src/copyright/ui/agent-keyword.php, src/monk/ui/agent-monk.php, src/nomos/ui/agent-nomos.php, src/ojo/ui/agent-ojos.php
=> fix(SCM): fix warnings in apache log if SCM is not selected

CHANGELOG.md, debian/changelog
Making hot fix release to bring fixes done by #1714
=> chore(release): Changelog for release 3.8.1

src/nomos/agent/standalone.c, src/nomos/agent/standalone.h
closes #1724 
Included the declaration for the below in standalone.h
and definition in standalone.c 
Build nomossa, and scan a source file/directory for license finding
=> fix(nomos-standalone): included changes for the PR #1600

src/spasht/ui/template/agent_spasht_search.html.twig, src/spasht/ui/ui-spasht.php
Fix Spasht search value. Removed file extension name.
Spasht search  recommendation was having file extension. Removed file extension from the spasht search box.
`sudo make install-spasht`
=>  fix(spasht-ui): Removed extension from the spasht search

src/spdx2/agent/spdx2.php
The SPDX agents introduce duplicate copyrights in the report. This occurs because the `agent_fk` is not filtered while fetching the results from DB.
1. Filter `agent_fk` while fetching the copyrights in `addCopyrightResults()`.
Check #1742
~~### Todo~~
~~Try to use functions from `lib/php/Report` to create uniformity of output from all report generating agents.~~
Closes #1742
=> fix(spdx): Fix duplicate copyrights

src/deciderjob/agent/DeciderJobAgent.php, src/lib/php/Auth/Auth.php, src/lib/php/Dao/ClearingDao.php, src/lib/php/Plugin/FO_Plugin.php, src/lib/php/common-users.php, src/www/ui/ajax-clearing-view.php, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/ui-report-conf.php, src/www/ui/user-add.php, src/www/ui/user-edit.php
add a new role for all the users. add option to mark all decisions to global from conf page.
* upload a package from user 1.
* clear all the files with local decision.
* go-to user settings from admin user change the role of user1 to clearing admin.
* go-to conf page of uploaded package.
* click on decision settings and select option mark all decisions as clobal.
* check newly scheduled deciderjob to finish. and check the clearings.
=> feat(conf): change all local clearings to global from conf

src/lib/php/Report/ClearedGetterCommon.php, src/lib/php/Report/LicenseDNUGetter.php, src/lib/php/Report/LicenseIrrelevantGetter.php, src/lib/php/Report/LicenseMainGetter.php, src/lib/php/Report/tests/ClearedGetterCommonTest.php, src/readmeoss/agent/readmeoss.php, src/unifiedreport/agent/unifiedreport.php
* Send the object from actual class and call a new heart function to send heartbeat.
* Do clearing on a large package and generate report.
=> feat(ReportDao): send heartbeat from Dao to keep the agent alive

install/fossinit.php
While installing the fossology, there might be some conflicts while importing licenses. This PR tries to catch them and print them in a neat format instead of throwing an exception.
1. Store all failed modifications and print them in a log format.
2. While merging candidate license, check if the same license exists:
a. Same shortname and md5, then delete the candidate and update it's references with main license.
b. If the same license exists but with different shortname or md5, skip it.
1. Add a new candidate license with shortname and license text which exists in main license list.
1. Add a new candidate license with a new shortname (exists in `licenseRef.json` but not in `license_ref`) but same license text which exists in main license list.
1. Add a new candidate license with same …
=> fix(licenseref): handle errors license errors

install/fossinit.php
Fix typo in `array_map` call.
Fix position of `)` in `fossinit.php`
=> fix(licenseRef): Fix type in array_map

debian/control, src/copyright/mod_deps, src/nomos/mod_deps, src/ojo/mod_deps, utils/fo-installdeps
Added Ubuntu 20.04 support 
Fixes #1823
Part of #1760
Previous Conversation: #1765
=> update(org): added focal-fossa support

src/softwareHeritage/agent/softwareHeritageAgent.php
1. Provide User-Agent from Guzzle as "fossology/version" to help identify origin of request.
1. Lowercase the SHA256 to prevent redirects.
1. Create client only once.
1. Add `User-Agent` header to GuzzleHttp client as "fossology/<version>"
1. Lowercase checksum in `getSoftwareHeritageLicense()`.
1. Check if Software Heritage agent works.
Partial fix for #1834
Closes #1835
=> fix(swh): Update User-Agent, lowecase SHA256

CHANGELOG.md, debian/changelog
Change log updates for release 3.9.0
=> chor(release): Release changelog for 3.9.0

src/www/ui/ajax-notice-files.php, src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-common.js, src/www/ui/template/ui-clearing-view.html.twig, src/www/ui/template/ui-clearing-view_bulk.html.twig
* Search for "NOTICE" file in a given upload.
* Load the notice file in a dialog.
* Remove Plain-modal in clearing page and add jquery UI-modal.
See #1465
Closes #1465
=> Import notice file content into acknowledgement

.travis.yml, src/composer.json, src/composer.lock, src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2-file.xml.twig, src/spdx2/agent/template/spdx2-package.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig, src/spdx2/agent_tests/Functional/schedulerTest.php, src/www/ui/page/UploadVcsPage.php, src/www/ui/upload-instructions.php
upgraded php version to 7.0.8
Part of #1760
Previous Conversation: #1765
=> update(org): upgraded php version to php7

src/lib/php/Dao/UploadDao.php, src/unifiedreport/agent/reportStatic.php, src/unifiedreport/agent/unifiedreport.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/ui-report-conf.php
Checkbox to include/exclude tables in Unified Report.
* Add table with headings in text field and checkbox.
* Include/exclude by enable/disable checkbox.
* Edit headings from text field.
* Upload a package.
* Go to conf page and un-check headings and submit.
* Download unified report. unchecked tables under headings shouldn't exists.
* Change heading name and see if the changes appear in report.
=> feat(conf): make unified report configurable

src/composer.json, src/composer.lock
Due to #1830 , API calls were getting affected and returning Internal Server Error (500)
logs:
`web_1        | [Mon Dec 21 15:37:37.655055 2020] [:error] [pid 19] [client 172.19.0.1:34084] PHP Fatal error:  Interface 'Interop\\Container\\ContainerInterface' not found in /usr/local/share/fossology/vendor/flexsounds/slim-symfony-di-container/src/ContainerBuilder.php on line 21`
Added container-interop/container-interop dependency 
spin up the environment by `docker-compose up --build` and query ` /repo/api/v1/version`
Desired Output: 
Fixes: #1850
=> fix(API): added container-interop/container-interop dependency for resolving Internal Server Error (500)

src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/Models/Group.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
This PR adds functionality to get list of groups and greate new group using Rest API
Created: 
src/www/ui/api/Controllers/GroupController.php 
src/www/ui/api/Models/Group.php
Modified:
src/www/ui/api/index.php 
src/www/ui/api/documentation/openapi.yaml 
Trying to get groups (/groups GET )and create group using Rest API (/groups POST)
=> feat(rest): get groups and create group functionality

src/reuser/ui/template/agent_reuser.html.twig
This closes https://github.com/fossology/fossology/issues/1876
Signed-off-by: Pawan Kumar Meena <Pawank1804@gmail.com>
=> fix(reuser): updated misleading UI label

README.md
Updated Readme.md
- Added link of fossology YouTube channel 
- Fixed broken links
- Added link of a test instance
- Fixed typos
- Fixed grammatical errors
Closes #1878 
Closes #1840
=> docs(README): fixed broken links, typos, and grammatical errors

CONTRIBUTING.md
Updated CONTRIBUTING.md
* Updated the link of submitting patches from https://www.kernel.org/doc/Documentation/SubmittingPatches to https://www.kernel.org/doc/Documentation/process/submitting-patches.rst
* Fixed typos
=> docs(CONTRIBUTING.md): Fixed broken link and typos

.github/workflows/deploy-pages.yml, .travis.yml
Migrate API docs generation and deployment to GitHub Actions from Travis CI.
- Added new workflow script for GitHub Actions: pages-deploy.yml
- Removed pages deployment from Travis CI: .travis.yml
- Modified pages-deployment script for GHA: pages-deploy.sh
Check the current deployment at http://avinal.space/checkdeployment/
Fixes part of #1913
=> feat(CI): Migrate API docs generation and deployment to GitHub Actions

.github/workflows/deploy-pages.yml, .github/workflows/static-checks.yml, .travis.yml
This PR migrates the following Checks and Analysis to GitHub Actions from Travis CI
- Syntax Checks
- Static Code Analysis
- Copy/Paste Detector
- PHP Codesniffer
- Added new workflow configuration for static checks and analysis: static-checks.yml
- Removed static checks and analysis from Travis CI configuration: .travis.yml
NA - can only be tested after merging, however, a test run is available here: https://github.com/avinal/fossology/actions/runs/648349454 …
=> feat(CI): Migrate Static Checks and Analysis to GitHub Actions from Travis CI

src/www/ui/template/upload_instructions.html.twig
Closes #1950 
Uploads>instructions>scheduler docmentation
=> fix(ui): updated the link of scheduler documentation

.github/workflows/deploy-pages.yml
Build the fossology.github.io pages on every merge to master or release.
Add build trigger `release` to `deploy-pages` workflow.
=> fix(actions): Build pages on release

install/db/dbmigrate_copyright-event.php
add a transaction and change limit and offset to equations.
* In a large instance test migration of copyright_event
=> perf(migration): remove offset to make the query faster

.travis.yml, src/lib/c/sqlCopy.c, src/monk/agent/_squareVisitor.h.post, src/nomos/agent/doctorBuffer_utils.c, src/nomos/agent/nomos.c, src/nomos/agent/nomos.h, src/nomos/agent/nomos_regex.c, src/nomos/agent/nomos_regex.h, src/nomos/agent/nomos_utils.c, src/nomos/agent/nomos_utils.h, src/scheduler/agent/event.c, src/wget_agent/agent/wget_agent.c
Fix warning and errors reported by GCC-10 which will be shipped by next Debian release (https://packages.debian.org/bullseye/gcc)
Nomos and monk: Make shared variables are extern
Others: Fix string warnings
Build fossology on various GCC versions.
=> fix(gcc-10): Fix errors and warnings

src/lib/php/Dao/UploadDao.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Models/Upload.php, src/www/ui/api/Models/UploadSummary.php, src/www/ui/api/documentation/openapi.yaml
Added uploads asssignee id to REST API
added assginee id to Upload Model and UploadSummay Model 
Try using the following endpoints:
/uploads
/uploads/{id}
/uploads/{id}/summary
Closes #1896
=> feat(rest): Add assignee id to fossology API

src/lib/php/Plugin/DefaultPlugin.php, src/lib/php/Plugin/FO_Plugin.php, src/lib/php/UI/template/include/base.html.twig, src/www/ui/css/fossology.css, src/www/ui/template/admin_obligation-upload_form.html.twig, src/www/ui/template/popup_license.html.twig, src/www/ui/template/ui-clearing-view_bulk.html.twig
Closes #1911 
Fixed Html errors, css errors and add the viewport meta tag
View the page source code after applying the patch
=> fix(UI): fix html errors, css errors and add viewport meta tag

src/lib/php/Report/LicenseClearedGetter.php
Do not merge entries if two licenses have same acknowledgements.
1. Overridden `ClearedGetterCommon::getCleared()` in `LicenseClearedGetter`.
2. Added new function `LicenseClearedGetter::groupStatementsSpecial()` to merge entries if only acknowledgements or comments are requested. Use the `ClearedGetterCommon::groupStatements()` otherwise.
- The merge is done taking **license_name.acknowledgement** or **license_name.comment** as a unique key.
1. In a package identify one file with **License1** and add **Acknowledgement1** as acknowledgement.
2. In other file, identify **License2** and add **Acknowledgement1** as acknowledgement.
3. Add an identification **License1** and add **Comment1** as comment.
4. Add another identification **License2** and add **Comment1** as comment.
5. Add some …
=> fix(report): Do not merge ack text

src/www/ui/template/ui-browse.html.twig, src/www/ui/template/ui-browse.js.twig, src/www/ui/ui-browse.php
add a simple search to get folder in browse page.
a input box to capture text and a jquery function to search.
* create large set of folders using fossology and search for particular folder.
=> feat(browse): add a simple search to get folder

CONTRIBUTING.md, README.md, src/buckets/ui/admin-bucket-pool.php, src/dox.c, src/lib/php/Auth/Auth.php, src/wget_agent/agent/wget_agent.c, src/www/ui/core-init.php, utils/fo-cleanold
Did a detailed analysis of all the links in FOSSology repo and the https://fossology.github.io/ website and fixed 10+ broken links.
Also attaching the details of other unresolved broken links mainly because http://archive15.fossology.org is down but thanks to the [Wayback Machine](https://web.archive.org/) that we can still have a look at http://archive15.fossology.org website past page and can update our current wiki.
Updated links to point to correct URL
1. URL: https://fossology.github.io/dd/d7d/classFossology_1_1Lib_1_1Dao_1_1UserDao.html#aab18027a15a3a29ecd05d275d48c02d1
Delete a group (for constraint, see http://www.fossology.org/projects/fossology/wiki/GroupsPerms )
Possible alternatives: https://github.com/fossology/fossology/wiki/Access-Control 
But it does not have much …
=> fix(links): fix broken links

src/lib/php/common-sysconfig.php, src/www/ui/api/Controllers/AuthController.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php, src/www/ui/api/index.php
`$this->options('', AuthController::class . ':optionsVerification');`
added the options request in /src/www/ui/api/index.php
added the optionsVerification request in /src/www/ui/api/Controllers/AuthController.php
`if(stristr($request->getMethod(), "options") !== false)`
setup the condition in /src/www/ui/api/Middlewares/RestAuthMiddleware.php
Closes #1938
=> feat(restAPI): Added options request and verification function

.travis.yml, src/composer.json, src/composer.lock, src/www/ui/template/ui-export-list.html.twig, src/www/ui/ui-export-list.php, utils/fo-installdeps
Export list in Spreadsheet
UI at Export Lists is slightly changed. There are three options. 
1) don't download license list (default)
2) download license list in CSV
3) download license list in Spreadsheet
Go to an upload > Export Lists
Select one of option at '5. Download License List after creation?'
Generate list.
=> feat(export): Download results in spreadsheet (xlsx)

install/db/dbmigrate_copyright-event.php
General improvements to copyright migration 
thanks @GMishx 
* change function from queryonce to getsinglerow.
* add where clause to update query.
* continue if some table had already migrated.
* copyright migration test.
=> feat(migration): general improvements for copyright migration

src/lib/php/common-job.php
Fix the dependency list datatype for CLI tools.
Change dependency list from string to array type.
Check #1973 
Closes #1973
=> fix(cli): Dependency exception

CHANGELOG.md, debian/changelog
add release changelog for 3.11.0-rc1
=> feat(changelog): add release changelog for 3.11.0-rc1

src/www/ui/api/Controllers/AuthController.php, src/www/ui/api/Middlewares/RestAuthMiddleware.php
Added the `Access-Control-Expose-Headers`.
closes #2041 
- Created the global variable for Allowed headers in `common-sysconfig.php`.
- Added the `Access-Control-Expose-Headers` property in `AuthController.php`.
=> feat(expose-headers): added the expose headers option

.gitignore, src/Makefile, src/decider/agent/DeciderAgent.php, src/decider/ui/template/agent_decider.html.twig, src/fossy-ruleset.xml, src/lib/php/Data/AgentRef.php, src/lib/php/UI/template/include/base.html.twig, src/reso/Makefile, src/reso/agent/Makefile, src/reso/agent/ResoAgent.php, src/reso/agent/reso.php, src/reso/agent/version.php.in, src/reso/reso.conf, src/reso/ui/Makefile, src/reso/ui/ResoAgentPlugin.php, src/www/ui/api/Models/Analysis.php, src/www/ui/api/Models/Decider.php, src/www/ui/api/Models/ScanOptions.php, src/www/ui/api/documentation/openapi.yaml
Replaces PR: https://github.com/fossology/fossology/pull/2029
Fixes #1833
=> feat(reso): new agent for REUSE.Software standard

CHANGELOG.md, debian/changelog
=> feat(changelog) add changelog for 3.11.0-rc2

debian/control, debian/rules
Adding reso package to debian package build.
adding reso packages to debian package build.
debain/rules
debian/control
Install the debain packages
and check for option to schedule the reso agent
=> fix(rules) : adding debian package for reso agent

install/db/dbmigrate_copyright-event.php
* Add current count as lowerUploadtreeId When uploadtreeId is empty.
see #2053 
Closes #2053
=> fix(migration): check if uploadtree is empty

CHANGELOG.md, debian/changelog
Changelog for new release 3.11.0
=> feat(changelog): add changelog for release 3.11.0

src/lib/php/Report/ClearedGetterCommon.php
This changes will help to capture the different short-names with same text in the report. 
install this branch,
add a short-name with same license text and different short-names.
=> fix(report): same license text for different shortname

src/www/ui/page/UploadVcsPage.php
Upload from version control system was not working for parameterize
agent like reuser or decider. This commit will fix the same.
Signed-off-by: Sarita Singh <saritasingh.0425@gmail.com>
-  Upload from Version control system
-  Schedule a parameterize agent like decider and check Jobs
-  decider will be scheduled along with it's dependencies
=> fix(ui/uploadVcsPage):Fix upload from VCS for parameterize agent

src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/Controllers/UploadController.php
Added the check for if page is 0 in the headers. Closes #2079
Added the condition in `UploadController.php` and `LicenseController.php`
Fetch data from `/uploads` and `/licenses`.
=> fix(rest): fixed the pagination in apis

CONTRIBUTING.md, README.md
I created a mess squashing commits in #1944 so created this new branch.
All credits go to @Piyussshh
The changes are taken from #1944, with no modifications done other than squashing the commits.
=> docs: Updated README.md and CONTRIBUTING.md

.github/workflows/test-checks.yml, src/cli/exportLicenseRefUsingSPDX.php, src/monk/agent_tests/Functional/bulkTest.php, src/scheduler/agent_tests/Functional/Functional.py, src/spdx2/agent_tests/Functional/fo_report.sql, src/unifiedreport/agent_tests/Functional/fo_report.sql, src/www/ui_tests/api/Controllers/InfoControllerTest.php, utils/prepare-test
Run unit test cases in CI on GitHub Actions.
1. Add new workflow in GitHub Actions to run CI jobs.
2. Fix breaking test cases.
Check the CI (https://github.com/fossology/fossology/runs/4046522342?check_suite_focus=true)
**Note:** The CI is currently breaking because of OpenAPI test cases and has been fixed in #2112
=> added github-ci

src/maintagent/agent/maintagent.h, src/maintagent/agent/process.c, src/maintagent/agent/utils.c, src/maintagent/ui/maintagent.php
Implement `deleteOrphanGold()` by recursively finding files under gold folder and comparing them against `pfile` table.
**Update**: Implement `removeOrphanedFiles()` reusing `deleteOrphanGold()` logic.
*Note:* Sending upper case SHA1 and MD5 to postgres uses `bpchar` datatype compared to using PG's `UPPER()` with `text` datatype, resulting in excution time of 0.027 ms vs 25125.819 ms respectively on PG 13.3
1. Implement function `deleteOrphanGold()`
2. Implement function `removeOrphanedFiles()`
3. New functions `strtoupper()`, `recurseDir()`, `checkPFileExists()`, `deleteRepoFile()` in utils.c
1. Copy some additional files in gold repo
2. Run the maintenance agent with the "Remove orphaned gold files." flag
3. Check if the additional files got removed.
4. Remove from files from …
=> feat(maintagent): Implement deleteOrphanGold fn

src/maintagent/agent/maintagent.c, src/maintagent/agent/maintagent.h, src/maintagent/agent/process.c, src/maintagent/agent/utils.c, src/maintagent/ui/maintagent.php
Depends on #2091
Remove gold files older than a given date from repository.
The date is read from UI in HTML form and provided to agent with new `-o` flag allowing the value to be changed from CLI easily.
The script makes sure the pfile is not used by any new upload before removing it.
1. New function `deleteOldGold()`
2. Apply bootstrap classes to /repo/?mod=maintagent page.
1. Goto Admin > Maintenance.
2. Check if option "Remove older gold files from repository." exists.
3. Schedule the agent from UI.
4. Schedule the agent from command line.
- Try giving it invalid dates.
=> feat(maintagent): Remove old gold files

src/maintagent/agent/maintagent.c, src/maintagent/agent/maintagent.h, src/maintagent/agent/process.c, src/maintagent/agent/usage.c, src/maintagent/ui/maintagent.php
Depends on #2093
Remove FOSSology job log files older than a given date.
1. Added new function `removeOldLogFiles()`
2. New option `-l #` for maintenance agent.
1. Run the maintenance agent with "Remove older log files from repository." and give an appropriate date.
2. Check under `/srv/fossology/repository/logs` if files older than given date in step 1 exists.
3. Run the agent from command line and check if it is working.
4. On command line, try giving date in invalid format and check if the agent fails with appropriate message.
=> feat(maintagent): Remove old log files

src/lib/php/UI/FolderNav.php, src/www/ui/async/AjaxBrowse.php, src/www/ui/css/jquery.treeview.css, src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-view.js, src/www/ui/template/ui-browse.html.twig, src/www/ui/template/ui-clearing-view.html.twig, src/www/ui/template/ui-clearing-view_bulk.html.twig, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/template/ui-view-info.html.twig, src/www/ui/ui-report-conf.php, src/www/ui/ui-view.php
add line break in upload name if exceeds 20 chars.
* browse page
* single file view page.
* conf page
* info page
* Upload a component with large name.
* Assign to a user with large username.
* check the scroll in single file view.
=> fix(ui): add line break in upload name if exceeds 20 chars

CHANGELOG.md, debian/changelog
Add change log for current release.
* changelog for release 4.0.0
=> feat(changelog): add changelog for release 4.0.0

src/copyright/agent/keyword.conf, src/copyright/agent_tests/Unit/test_scanners.cc
* Add "stolen from" keyword in conf page
* Upload a package where "stolen from" keyword exist.
* Schedule keyword agent and check if the keyword is identified.
=> feat(keyword): add new word 'stolen from' to keyword agent

src/lib/php/UI/template/include/upload.html.twig, src/www/ui/async/AjaxFolderContents.php, src/www/ui/template/upload_file.html.twig
Show warning if user tries to upload duplicate file in a given folder.
1. Update `mod=foldercontents` to accept upload name.
2. Call `foldercontents` when user changes file input.
1. Select a file which already exists in a folder.
- A warning should popup.
2. Select a new file to upload.
- Popup should disappear.
Closes #1966
=> feat(upload): Warning on duplicate upload

src/lib/php/Test/TestPgDb.php, src/reuser/agent_tests/Functional/schedulerTest.php
Fix test cases broken because of #2065
Check GitHub Actions.
=> fix(test): fix test failures caused by sysconfig

src/lib/php/Dao/ClearingDao.php, src/lib/php/Data/DecisionTypes.php, src/lib/php/Proxy/UploadTreeProxy.php, src/lib/php/Report/LicenseNonFunctionalGetter.php, src/lib/php/UI/template/include/macros.html.twig, src/unifiedreport/agent/reportStatic.php, src/unifiedreport/agent/unifiedreport.php, src/www/ui/async/AjaxExplorer.php, src/www/ui/change-license-processPost.php, src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-common.js, src/www/ui/scripts/change-license-view.js, src/www/ui/template/browse.html.twig, src/www/ui/template/browse_file.js.twig, src/www/ui/template/change_license_modal.html.twig, src/www/ui/template/ui-clearing-view_rhs.html.twig
add new decision "non functional" to decision types
* Upload a component.
* Apply Non functional decision from both single file view and tree view.
* Check if the results are attached properly to the files.
* Check unified report for non-functional files and comments.
Closes #1114
=> feat(decisions): add new decision type non-functional

src/cli/tests/test_fo_copyright_list.php, src/clixml/agent/clixml.php, src/lib/c/tests/test_fossscheduler.c, src/lib/php/Application/test/LicenseCsvImportTest.php, src/lib/php/BusinessRules/test/ClearingDecisionFilterTest.php, src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/test/FolderDaoTest.php, src/lib/php/Dao/test/UploadDaoTest.php, src/lib/php/Dao/test/UserDaoTest.php, src/lib/php/Data/Clearing/test/ClearingResultTest.php, src/lib/php/Db/test/DbManagerTest.php, src/lib/php/Plugin/test/DefaultPluginTest.php, src/lib/php/Proxy/test/LatestScannerProxyTest.php, src/lib/php/Proxy/test/UploadBrowseProxyTest.php, src/lib/php/Proxy/test/UploadTreeViewProxyTest.php, src/lib/php/Util/test/ArrayOperationTest.php, src/www/ui_tests/startUpTest.php
Fix test cases for test suite `Fossology PhpUnit Test Suite`.
1. Fix failing test cases.
2. Update deprecated annotation `@expectedException`
Run PHPUnit test cases with `src/vendor/bin/phpunit -csrc/phpunit.xml --testsuite="Fossology PhpUnit Test Suite" --colors=always`
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2163"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(testcase): fix test cases for lib

install/defconf/fossology.conf.in, src/composer.json, src/composer.lock, src/lib/php/Auth/Auth.php, src/lib/php/Dao/UserDao.php, src/lib/php/UI/template/components/login-form.html.twig, src/lib/php/common-sysconfig.php, src/maintagent/agent/process.c, src/www/ui/admin-config.php, src/www/ui/api/Controllers/AuthController.php, src/www/ui/api/Helper/AuthHelper.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/api/Helper/RestHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/async/AjaxManageToken.php, src/www/ui/core-auth.php, src/www/ui/core-schema.dat, src/www/ui/page/HomePage.php, src/www/ui/template/home.html.twig, src/www/ui/template/login.html.twig, src/www/ui/template/user_edit.html.twig, src/www/ui/user-edit.php, src/www/ui_tests/api/Controllers/AuthControllerTest.php, src/www/ui_tests/api/Helper/AuthHelperTest.php
Provide OIDC integration for authentication. Users will be redirected to authentication provider and FOSSology can use the tokens to create a login session.
The login integration uses "Authorization Code" flow of OAuth 2.0 and can be configured using "Customize" page, with ability to read .
The same OAuth provider can be used for REST API authentication as well with "Client Credentials" flow.
The existing token mechanism will still exist and can be configured from `fossology.conf`. A new section `AUTHENTICATION` is added with 2 parameters `provider` and `resttoken`.
Setting `provider` to `external` will prevent logins with username & password. The mechanism for REST authentication can be set by editing `resttoken`.
1. Setup OIDC authentication with FOSSology and check if it works.
2. …
=> feat(rest): oidc based authentication

utils/install_composer.sh
Update version and hash to version2.26
* Install fossology with utils/fo-installdeps
* Check composer version using "**composer about**"
* Check if everything works on UI like report, clearing etc..
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(composer): update composer form 1.9.0 to 2.2.6 version

.github/workflows/docker-test.yml, debian/changelog, src/testing/docker/test-cluster.sh, src/testing/docker/test-standalone.sh
Run Docker test cases in GitHub Actions.
1. Add new workflow docker-test
2. Fix syntax error in `debian/changelog`
Check if Docker test cases run for this pull request.
See https://github.com/fossology/fossology/runs/5476103814?check_suite_focus=true
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2177"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> test(ci): run docker tests in GitHub Actions

debian/control, debian/rules
Add code to generate Debian packages for scancode
* Create and install FOSSology using Debian packages.
* Check of scan-code and copyright feature works.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2197"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(scancode): add scancode to debian packaging

src/pkgagent/ui/agent-pkgagent.php
Fixes #2198
`src/pkgagent/ui/agent-pkgagent.php` - replaced `isset($latestPkgAgent)` with `!empty($latestPkgAgent)`
- Start Fossology service (installed from source)
- Attempt to login with FossologyUI
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(pkgagent): Fixes FossologyUI unexpected token error

src/lib/php/Dao/UploadDao.php
Reuse all columns for `report_info` table when reuser agent is used.
Also, overwrite all entries preventing duplicates.
1. Fetch all columns of `report_info` table from PostgreSQL to be reused
2. Drop `report_info` if it already exists for current upload to replace the values and prevent multiple entries if someone reuse multiple times.
1. Edit Conf section of an upload.
2. Upload new version of the package and run reuser.
- Select "Reuse report configuration settings" while scheduling.
- Check Report Conf section of new upload.
- All values should be copied over.
3. Edit the new upload's Report Conf and run the reuser again.
- Report Conf should have the same values as of reused upload.
4. Logs of Reuser agent should be clean.
<a …
=> fix(reuser): reuse all report columns

src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminGroupUsers.php
Remove a particular user from a specific group.
1. Added a new function in `GroupController`. to implement the core functionality.
2. Updated  the main file(`index.php`) by adding a new route `/groups/{id}/user/{uid}`.
3. Updated the `openapi.yaml` file to introduce a new API.
1. Open and run the project then visit  the url `http://localhost/repo/api/v1/groups/{groupId}/user/{userId}`
2. Response
If the groupId and the UserId exist and the user is part of the group, you should see a response as such.
Else you should see the message `Not a member !` if the user is not a member of the group.
eg:
Fixes #2267
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2269"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(API): remove member from group.

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
New endpoint for getting the copyright information for a specific upload.
send a GET request to `api/v1/uploads/< UPLOAD_ID HERE >/copyrights ` in order to see the response.
Response example (used Nirjas repo) :
```
[
{
"copyright": "Copyright (C) 2020 Ayush Bhardwaj (classicayush@gmail.com), Kaushlendra Pratap (kaushlendrapratap.9837@gmail.com)",
"filePath": [
"Nirjas-master.zip/Nirjas-master/nirjas/languages/php.py",
"Nirjas-master.zip/Nirjas-master/nirjas/languages/c.py",
"Nirjas-master.zip/Nirjas-master/nirjas/languages/matlab.py",
"Nirjas-master.zip/Nirjas-master/nirjas/languages/text.py",
"Nirjas-master.zip/Nirjas-master/nirjas/main.py",
"Nirjas-master.zip/Nirjas-master/nirjas/languages/scala.py",
"Nirjas-master.zip/Nirjas-master/nirjas/languages/c_sharp.py", …
```
=> feat(api): new endpoint for geting copyright details

src/www/ui/api/Controllers/UploadController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/ui-download.php
API endpoint for downloading file using Upload ID
Created a new function in the `UploadController.php` named `uploadDownload()`
use the endpoint `localhost/repo/api/v1/uploads/<UploadID>/download` to get the file as an API response
PTAL @GMishx @shaheemazmalmmd 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2309"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Download file using UploadID

src/www/ui/api/documentation/openapi.yaml
Fixed Open API lint errors that were failing in the tests.
`openapi.yaml`
Check the test results
PTAL @GMishx @shaheemazmalmmd 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2311"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(lint): openapi lint corrected

src/cli/exportLicenseRefUsingSPDX.php
Add/Update licenseRef.json file with new licenses from spdx.org.
Add/Update licenseRef.json file with new licenses from spdx.org.
* Execute postinstall to check if the license had been added.
* Check in the UI for specific licenseName.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2310"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(licenseRef): add/update licenses from spdx.org

src/reportImport/agent/ReportImportAgent.php, src/reportImport/ui/ReportImportPlugin.php
Remove code which checks iseditible two times and fix array warnings.
* Upload findings using rdf file and check if the reportimport runs.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2304"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(reportImport): remove dual check for access and fix array warning

CHANGELOG.md, debian/changelog
Add changes from previous release to current release.
* changelog, debian/changelog
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2326"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(changelog): add changelog for release 4.2.0-rc1

src/www/ui/scripts/change-license-common.js, src/www/ui/template/ui-clearing-view_bulk.html.twig
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
Add div in text model.
* add default comments from admin > license admin > standard comments
* check if this comments can be added through license view. 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(licenseView): fix missing comment select

src/composer.json, src/composer.lock, src/www/ui/api/Helper/AuthHelper.php, src/www/ui/page/HomePage.php
Use new features from [firebase/php-jwt:v6.3.0](https://github.com/firebase/php-jwt/releases) updated in #2331 
1. Use default JWK algorithm while parsing keys rather than injecting them in JSON.
2. Use the `CachedKeySet` to cache JWKs. It will be helpful if JWK keys are rotated.
3. Add new dependency `symfony/cache` for `CachedKeySet`.
Install the new branch and use OpenID Connect to login to FOSSology.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2332"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(php-jwt): use new features from v6.3.0

src/monk/ui/oneshot.php
add intval function to avoid php fatal .
* Go to -> admin -> license admin -> candidates.
* Edit some candidate license and compare.
Credits : @GMishx 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(oneShotMonk): convert value to int to fix php fatal

src/www/ui/user-edit.php
Change query to get tokens above Max expired token retention period.
* set Max expired token retention period from conf.
* go to user edit.
* user shouldn't see tokens before Max expired token retention period.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2337"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(user-edit): make use of retention period to display expired tokens

CHANGELOG.md, debian/changelog
Add release notes for 4.2.1
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(release): add release notes to 4.2.1

.github/workflows/release-publish.yml, cmake/FoPackaging.cmake, src/clixml/ui/CliXmlGeneratorUi.php, src/copyright/agent_tests/Functional/schedulerTest.php, src/deciderjob/agent_tests/Functional/SchedulerTestRunnerCli.php, src/lib/php/UI/MenuRenderer.php, src/www/ui/async/AjaxBrowse.php, utils/prepare-test
1. Fix paths for Debian package builds at release in release-publish.yml
2. Add missing agents `ecc` and `keyword` to FoPackaging.cmake and fix naming of `unifiedreport`. Also, add PHP8.1 dependencies for Ubuntu Jammy.
3. Change repo setup for copyright functional tests.
4. Add folder ID in path for specific agents in MenuRenderer.php
5. Do not run `apt-get` if `cppcheck` is already installed in prepare-test preventing blocking `apt` lock.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2353"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(build): various build fixes

src/www/ui/core-auth.php, src/www/ui/template/ui-showjobs.js.twig
check if the job is running and show [status] where you can check all jobs from dashboard.
* upload a component into fossology.
* check if you can see [status] next to upload name.
* [status] link should take you to all jobs page in dashboard.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2336"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(showjobs): show status link for inprogress jobs

src/lib/php/Dao/LicenseAcknowledgementDao.php, src/lib/php/services.xml.in, src/www/ui/async/AjaxLicenseAcknowledgements.php, src/www/ui/core-schema.dat, src/www/ui/page/AdminLicenseAcknowledgements.php, src/www/ui/scripts/admin-license-acknowledgements.js, src/www/ui/scripts/change-license-common.js, src/www/ui/template/admin_license_acknowledgements.html.twig
add acknowledgements same as license comments.
* go to admin > license admin > acknowledgements
* add new acknowledgement for some license.
* upload a package and go to single file view.
* add acknowledgement using "click to edit"
* check if the acknowledgement is saved and in reports.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(acknowledgements): add new ack dropdown to select saved ack

Vagrantfile, install/easy-install, src/www/ui/core-auth.php
add cmake install scripts in to vagrantfile and easy-install.
* install source using easy-install scripts and build vagrant file.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2360"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(install): cmake changes for easy-install and vagrantfile

src/cli/acme_review.php, src/lib/php/common-folders.php, src/www/ui/acme_review.php
Fixed faulty encoding functions can lead to Cross-Site Scripting (XSS) that can enable an attacker to steal the user's
password, request the user’s credit card information, provide false information, or run malware.
Vulnerability detected with a Checkmarx scan.
Added `ENT_HTML5 | ENT_QUOTES` to `htmlentities` php function, to ensure that all characters are properly encoded on output
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2358"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(security) fix inaproppriate encoding for output context

src/cli/cp2foss.php, src/lib/php/common-repo.php, src/testing/db/cleanup_test_databases.php, src/www/ui/admin-fossdash-config.php, src/www/ui/change-license-processPost.php, utils/runBuild_v2.0.php
Fixes situation where attackers could run arbitrary system-level OS commands on the Fossology server host.
The vulnerabilities were detected with a Checkmarx scan.
Introduced the use of the php function `escapeshellarg` where necessary
=> fix(security) Sanitized  external command parameter

.github/workflows/build-test.yml, .github/workflows/static-checks.yml, src/copyright/agent_tests/Functional/schedulerTest.php, src/lib/php/Db/test/DbManagerTest.php, src/lib/php/Db/test/ModernDbManagerTest.php, src/lib/php/Db/test/SolidDbManagerTest.php, src/lib/php/Html/test/SimpleElementTest.php, src/lib/php/Plugin/test/DefaultPluginTest.php, src/lib/php/Report/tests/ClearedGetterCommonTest.php, src/monk/agent_tests/Functional/bulkTest.php, src/monk/agent_tests/Functional/cliTest.php, src/phpunit.xml, src/spdx2/agent_tests/Unit/spdx2utilTest.php, src/www/ui/api/Controllers/GroupController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/page/AdminGroupUsers.php, src/www/ui_tests/api/Controllers/GroupControllerTest.php
A rest API to change the member's permission in a group.
1. Added a new function to handle the feature in `GroupController`.
2. Updated  the main file(`index.php`) by adding a new route `PUT` `/groups/id`.
1. Choose one existing group.
2. Select one user from the group.
3. Run this API as follows
Pass the Group-Id in the path, and the UserId with NewPermission in Headers.
Fixes #2258
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2244"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2259"><img …
=> feat(API): change group member's permission

src/lib/php/Dao/LicenseDao.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Models/FileLicenses.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/ui-export-list.php
Clearing status parameter for the `/uploads/ID/licenses` endpoint.
Send a licenses request for an upload to see the response.
Fixes #2283
PTAL @GMishx 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2288"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): clearing status

src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Controllers/ReportController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Models/JobQueue.php, src/www/ui/api/Models/ShowJob.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php, src/www/ui/async/AjaxShowJobs.php, src/www/ui_tests/api/Controllers/ReportControllerTest.php
Signed-off-by: Krishna Mahato <krishhtrishh9304@gmail.com>
This development of this PR is in reference to two tasks ---
- P.S.: Here {id} is the upload id.
You can expect a response like this ----
`````
[
{
"jobId": 8,
"jobName": "hotels.json",
"jobQueue": [
{
"jobQueueId": 16,
"jobQueueType": "ununpack",
"startTime": "2022-08-22 14:17:48",
"endTime": "2022-08-22 14:17:48",
"status": "Completed",
"itemsProcessed": 1,
"dependencies": [
null
],
"itemsPerSec": 1,
"canDoActions": true,
"isInProgress": false,
"isReady": true,
"download": ""
},
{
"jobQueueId": 17,
"jobQueueType": "adj2nest",
"startTime": "2022-08-22 14:17:49",
"endTime": "2022-08-22 14:17:49",
"status": "Completed",
"itemsProcessed": 1,
"dependencies": [
"16" …
```
=> feat(API): `/jobs/history?upload={id}` GET route to get the history of all the jobs queued based on an upload

src/clixml/agent/clixml.php, src/clixml/agent/template/clixml-file.xml.twig, src/lib/php/Report/LicenseMainGetter.php
Introduce `LinkScanTool` to `GeneralInformation` (from version 1.6) holding the link to FOSSology upload.
1. Add `<LinkScanTool/>` to `<GeneralInformation/>`
2. Update report format to version 1.6
Generate CLIXML report and check for `<LinkScanTool>` in `<GeneralInformation>`.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2405"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(clixml): introduce LinkScanTool

src/lib/php/UI/template/components/login-form.html.twig, src/www/ui/template/user_add.html.twig, src/www/ui/template/user_edit.html.twig
Reverts fossology/fossology#2393
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Revert "feat(viewPasswordInLogin): Eye button to view Password while logging in"

src/www/ui/page/AdminLicenseCandidate.php
Not able to load admin -> license admin -> candidates page
* Change loop from while to foreach
* Swap variables as required. 
* Check  admin -> license admin -> candidates
* Page should load without error.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2416"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(adminLicensecandidate): replace while loop with foreach

src/clixml/agent/clixml.php, src/lib/php/Report/ClearedGetterCommon.php, src/lib/php/Report/LicenseClearedGetter.php, src/lib/php/Report/LicenseDNUGetter.php, src/lib/php/Report/LicenseMainGetter.php
Add missing acknowledgement fields from report getters.
1. Add missing `acknowledgement` field to `LicenseClearedGetter`.
2. Fix some CLIXML warnings.
Check #2423 
Closes #2423 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2424"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(clixml): add acknowledgement to reports

src/www/ui/api/Models/Hash.php
Fixed the issue of filesearch request with size field returning Invalid key response
Added size to to the list of allowed keys in Hash.php
Create any filesearch request with size field in Json data.
Fixed #2186
=> fix(api): Fixed filesearch request

CHANGELOG.md, debian/changelog
Adding changelog for 4.3.0-rc1
Update changelog files
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2443"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(release): update changelog for 4.3.0-rc1

.github/workflows/release-publish.yml
Fix the release build action by removing old `make` commands.
Remove old `make clean` command.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2444"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(cd): fix release build action

.github/workflows/build-test.yml, .github/workflows/release-publish.yml, .github/workflows/static-checks.yml, src/copyright/mod_deps, src/nomos/mod_deps, src/ojo/mod_deps, src/scancode/agent/scancode_wrapper.cc, src/scancode/mod_deps, src/wget_agent/agent_tests/Unit/wget_agent/testDBLoadGold.c, utils/fo-installdeps
As Ubuntu Bionic Beaver (18.04) is reaching its EOL, dropping the support.
1. Drop dependency install for bionic.
2. Update Github Actions to 20.04 and 22.04
Check Github Actions.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2447"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(os): drop Ubuntu Bionic support

cmake/FoUtilities.cmake, src/composer.json, src/composer.json.in, src/composer.lock, src/scanoss/agent/CMakeLists.txt, src/scanoss/agent/main.c, src/scanoss/agent/snippet_scan.c, src/scanoss/agent/snippet_scan.h, src/scanoss/mod_deps
1. Fix the version in CMake for rc tags.
2. Remove unnecessary dependencies from scanoss.
1. Fix the string append command in CMake.
2. Remove jq with json-c in scanoss
3. Remove not needed dependencies from scanoss
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2445"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(build): remove jq

src/unifiedreport/agent/reportStatic.php, src/www/ui/ui-report-conf.php
In case of single quotes the values are getting doubled after every submit.
replace escaped two single quotes into one.
add single quotes in any cell of conf page and submit.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2446"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(conf): replace two single quotes to one in escaped string

CHANGELOG.md, debian/changelog, src/www/ui/user-add.php
add change log for new release of FOSSology.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2464"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(changlog): add changelog for 4.3.0-rc2

CHANGELOG.md, debian/changelog
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(changelog): add changelog for release 4.3.0

src/decider/agent/copyrightDeactivationClutterRemovalScript.py
Refactored some of the false positive copyright code so that it runs a little faster.
1. Changed the `df.iterrows()` in line 30 to `df.index.to_list()` instead as only the index was needed, so no need to return the entire row as well.
2. Removed two redundant if conditions from line 68 where if no `copyright` is found in the `list_of_copyrights` two if conditions are checked. Afterwards, the two if conditions are performed anyway even when they were not needed.
The code doesn't need testing. Though if the code is run the same output will be produced.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2458"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> refactor(copyright): Refactored some redundant code.

src/copyright/ui/ajax-copyright-hist.php, src/www/ui/api/Controllers/CopyrightController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Copyright info for file is exposed through `/file/upload/{UploadId}/item/{ItemId}/copyrights` endpoint
Send a GET request to `/file/upload/{UploadId}/item/{ItemId}/copyrights` endpoint to see the result.
Closes #2468 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2475"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): copyright info for file

src/www/ui/api/documentation/openapi.yaml
Update REST API version patch number to indicate changes done during GSoC 2023. Future version updates will also consist of changes done over a week.
At the same time, fix documentation issue denoted in #2527
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2531"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(api): update api version

cmake/FoPackaging.cmake
Fix the `.deb` package name for CLIXML to use `_` before package version.
Add `_` before package version for CLIXML.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2541"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(clixml): fix deb package name

src/www/ui/api/Controllers/ConfController.php, src/www/ui/api/Models/Conf.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
This endpoint provides us full conf information as a response for an Upload. 
Send a GET request to `/file/upload/{UploadId}/item/{UploadId}/conf`
Closes #2504
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): conf info for upload

src/www/ui/api/documentation/openapi.yaml
Update API version to denote changes coming from following PRs.
#2506
#2505
#2520
#2509
#2516
Update API version.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2570"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(api): update API version 20230811

src/lib/php/Dao/FolderDao.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/async/AjaxBrowse.php
Refactor two queries.
In browse view and in folder move or copy view.
* Check if all the main licenses load on browse view .
* Delete / Add main licenses and check.
* Check if all the contents of a folder are visible in Organize > Folders > Move or Copy
* Move the contents and check if they are copied perfectly.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2567"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> refactor(browse): use join to fetch data from two tables

README.md
README is missing important information about `docker-compose` cmd which can be very useful for new comers starting out with Fossology .
Added details about  `docker-compose` cmd and refactored some code.
=> docs(README.md): adding more details about `docker-compose` cmd 

src/www/ui/api/documentation/openapi.yaml
Update API version to denote changes coming from following PRs.
#2483
#2517
#2518
#2524
#2528
#2529
#2530
#2532
#2533
#2534
#2535
#2536
#2537
#2538
#2539
#2545
#2549
#2576
Update API version.
=> chore(api): update API version 20230929

src/lib/php/Dao/SysConfigDao.php, src/www/ui/api/Controllers/CustomiseController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Get banner message for all the users.
Send a GET response to `/customise/banner` endpoint.
Fixes #2519 
NOTE: Do not merge this before merging #2520 
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2553"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get banner message

src/lib/php/services.xml.in, src/www/ui/admin-obligation-file.php, src/www/ui/api/Controllers/ObligationController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
API to get the list of the obligations. 
Send `GET` request to `/obligations/list` endpoint.
@GMishx @shaheemazmalmmd Please do have a look.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2559"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): api to get the list of obligations

src/lib/php/BusinessRules/ObligationMap.php, src/www/ui/admin-obligation-file.php, src/www/ui/api/Controllers/ObligationController.php, src/www/ui/api/Models/Obligation.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Get Details of a particular Obligation by requesting it with obligation_id.
Send a `GET` request to `/obligations/{id}` endpoint.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2564"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): get details of a particular obligation using id

src/www/ui/admin-obligation-file.php, src/www/ui/api/Controllers/ObligationController.php, src/www/ui/api/Models/Obligation.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
API endpoint to get all the Obligation details
Send a `GET` Request to `/obligations/all` endpoint.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2565"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Get details of all obligations

src/lib/php/BusinessRules/ObligationMap.php, src/www/ui/admin-obligation-file.php, src/www/ui/api/Controllers/ObligationController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/api/index.php
Delete obligation using obligation ID
Send a `DELETE` request to `obligations/{obligationId}`
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2568"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(api): Delete obligation using id

src/www/ui/api/documentation/openapi.yaml
Update API version after merge of:
#2551
#2552
#2553
#2555
#2562
#2564
#2565
#2563
#2568
#2574
=> chore(api): update API version 20231006

src/www/ui/template/agent_adder.html.twig
Use select2 to search for uploads in  jobs > schedule agents
* Install fossology.
* go to   jobs > schedule agents
* select upload using select 2
* schedule agent and check.
=> feat(schedule agent): add select2 to search for uploads with name

src/buckets/ui/bucket-diff.php, src/buckets/ui/ui-buckets.php, src/buckets/ui/ui-list-bucket-files.php, src/copyright/ui/oneshot.php, src/lib/php/Application/ObligationCsvExport.php, src/lib/php/Dao/FolderDao.php, src/lib/php/Dao/LicenseDao.php, src/lib/php/Dao/ShowJobsDao.php, src/lib/php/Dao/UploadDao.php, src/lib/php/View/HighlightState.php, src/lib/php/common-folders.php, src/lib/php/common-menu.php, src/spasht/ui/ui-spasht.php, src/testing/lib/reportClass.php, src/www/ui/api/Helper/DbHelper.php, src/www/ui/ui-license-list-files.php, src/www/ui/ui-picker.php, utils/freshmeat/Classes/FreshmeatRdfs.php
Do not use array_push() to add one element to the array.
Replace array_push by assignment.
=> fix(php): replace array_push by assignment

src/www/ui/admin-folder-size.php, src/www/ui/template/admin-folder-size-form.html.twig
View size of upload and folder through Admin::Dashboards::Folder/Upload Proportions
* check if the page "Admin::Dashboards::Folder/Upload Proportions" is working properly
=> feat(dashboard): add new page for upload and folder dashboard

src/nomos/agent/generator/STRINGS.in, src/nomos/agent/parse.c, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/CC/perl-XML-Writer.spec, src/nomos/agent_tests/testdata/NomosTestfiles/Nvidia/mix_transformer.py, src/nomos/agent_tests/testdata/NomosTestfiles/See-file/segformer.py
Add more license regex to nomos
Mostly done in parse.c and STRINGS.in to identify licenses.
* Create a file with added license text(regex) 
* Check if nomos is able to identify it.
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(nomos): add more regex to nomos to identify different licenses

src/clixml/agent/clixml.php, src/clixml/agent/template/clixml-file.xml.twig, src/lib/php/Dao/UploadDao.php, src/www/ui/core-schema.dat, src/www/ui/template/ui-report-conf.html.twig, src/www/ui/ui-report-conf.php
support clixml conf for a upload in fossology.
* For a upload make some changes in conf page for CLIXML.
* Generate report and test if the confs reflects or not.
=> feat(conf): support CLIXML conf for a upload

src/decider/agent/BulkReuser.php, src/decisionimporter/agent/DecisionImporterDataCreator.php, src/decisionimporter/agent/FoDecisionData.php, src/lib/php/Dao/AllDecisionsDao.php, src/lib/php/Dao/LicenseDao.php, src/monk/agent/database.c, src/monk/agent/database.h, src/monk/agent/monkbulk.c, src/monk/agent/monkbulk.h, src/www/ui/api/Controllers/UploadTreeController.php, src/www/ui/api/documentation/openapi.yaml, src/www/ui/change-license-bulk.php, src/www/ui/core-schema.dat, src/www/ui/scripts/change-license-common.js, src/www/ui/template/ui-clearing-view_bulk.html.twig, src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
New option for bulk scan instead of scanning whole package you can choose to scan files where a finding exists.
Both UI and backend has been changed.
* scan a package and check if this option works.
=> feat(bulk): checkbox to select scan for findings only

src/www/ui/user-edit.php
Fix `user-edit` page by handling exceptions.
Handle exceptions with REST tokens.
1. Edit user with expired tokens.
2. Edit user with new tokens.
3. The page should load without any errors.
=> fix(user-edit): handle HttpForbiddenException

src/www/ui/user-edit.php
=> fix(user-edit): compare old email and skip email count check

README.md
Update README.md with supported PHP versions.
=> fix(documentation): update README.md with PHP version

src/unifiedreport/agent/reportStatic.php
fix(unifiedreport): replace single quotes with double to fix line breaks
=> fix(unifiedreport): replace single quotes with double to fix line breaks

src/lib/php/Dao/ClearingDao.php, src/lib/php/Dao/CopyrightDao.php, src/lib/php/Dao/UserDao.php, src/lib/php/Dao/test/ClearingDaoTest.php, src/lib/php/Report/XpClearedGetter.php, src/lib/php/common-license-file.php, src/maintagent/ui/maintagent.php, src/scancode/agent/scancode_utils.cc, src/www/ui/async/AjaxFileBrowser.php, src/www/ui/page/BrowseLicense.php
Fix build issue with Debian Buster. It fails on range for loop tagged with `#pragma omp for`.
Change it to normal loop with `i`.
Make some refactoring.
1. Change the parallel range for loop to normal loop.
2. Refactor some lib code.
Build packages on Debian Buster.
=> fix(ci): fix build in Debian Buster

src/spdx2/agent/template/spdx2-document.xml.twig, src/spdx2/agent/template/spdx2tv-document.twig
* Install FOSSology and check if the new licenses got inserted correctly.
=> feat(licenseRef): add new licenses from SPDX

.github/workflows/release-publish.yml
Fix the sleep duration randomization by using environment variables.
See https://github.com/fossology/fossology/actions/runs/6954879978/job/18922549458#step:12:49
See https://github.com/fossology/fossology/actions/runs/6955073773/job/18923142071?pr=2639#step:4:9
=> fix(action): fix the declaration of sleep duration

src/www/ui/ui-view-info.php
Check if ScanOSS agent is installed before loading the data in View page.
Check if the agent `scanoss` is installed and enabled before loading the data in "View" page.
1. Uninstall the ScanOSS agent or install FOSSology with deb packages (ScanOSS does not generate package yet).
2. Upload a file and open the "View" page.
=> fix(view): check if ScanOSS is installed

NOTICES
=> chore(notice): update both notice and notice.spdx files to latest

CHANGELOG.md, debian/changelog
Changelog for new RC. 4.4.0-rc2
=> chore(release): add changelog for 4.4.0-rc2

CHANGELOG.md, debian/changelog
=> chore(release): 4.4.0 release

CHANGELOG.md, debian/changelog
Add commits from #2670 and #2671
=> chore(release): update 4.4.0 changelog

src/lib/php/Application/LicenseCsvExport.php, src/lib/php/Application/LicenseCsvImport.php, src/lib/php/Application/test/LicenseCsvExportTest.php, src/lib/php/BusinessRules/LicenseMap.php, src/www/ui/page/AdminAllLicenseToCSV.php
Add new export for all the licenses with candidates.
* Create Candidate licenses in different groups with few clicking on merge request.
* Generate CSV using "CSV Export Marydone". -> All the main licenses and licenses with merge request should appear.
* Generate CSV using "CSV Export ALL". -> All the main licenses and all candidate licenses with or without merge request should appear.
* Import both with modifying some main and candidate licenses.
* Check the Changes in UI.
=> fix(licenseExport): add all licenses to csv and fix cells

src/lib/php/Report/ObligationsGetter.php
If a license is excluded from obligation list, it is missing in the section 12 of Unified report.
While grouping obligations, recalculate white list of licenses to make sure the excluded licenses still occur in Section 12.
1. In an upload, add a license which has associated obligations.
2. From conf section of the upload, exclude the license.
3. Generate the Unified report and check Section 12, which should contain all licenses with and without obligations.
4. Try again with different combinations like a license having multiple obligations where some are excluded, etc.
=> fix(unifiedreport): excluded obligation license

src/www/ui/api/Controllers/FolderController.php, src/www/ui/api/Controllers/LicenseController.php, src/www/ui/api/Controllers/ObligationController.php, src/www/ui/api/Models/AdminAcknowledgement.php, src/www/ui/api/Models/LicenseCandidate.php, src/www/ui/api/Models/LicenseStandardComment.php, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui/page/AdminLicenseFromCSV.php, src/www/ui/page/AdminObligationFromCSV.php, src/www/ui_tests/api/Controllers/LicenseControllerTest.php
This PR aims to upgrade the `/folder` and `/license` endpoints to v2 in accordance with the new upgrade guidelines.
* Completed all tasks mentioned in #2710.
* Updated `openapiv2.yaml` to have all documentation changes.
* Modified models to make them version aware.
* Open the `openapiv2.yaml` file in Swagger Editor and test all the updated endpoints for v2 specific responses. All function as intended.
* Execute unit tests, all pass without any issues.
CC @GMishx @shaheemazmalmmd @dushimsam
=> feat(api): Upgrade Folder, License & Obligation APIs to Version 2

src/www/ui/api/Controllers/JobController.php, src/www/ui/api/Controllers/ReportController.php, src/www/ui/api/Helper/UploadHelper.php, src/www/ui/api/Models/Analysis.php, src/www/ui/api/Models/Decider.php, src/www/ui/api/Models/Reuser.php, src/www/ui/api/documentation/openapiv2.yaml, src/www/ui_tests/api/Models/AnalysisTest.php, src/www/ui_tests/api/Models/DeciderTest.php, src/www/ui_tests/api/Models/ReuserTest.php
This PR aims to upgrade the `/jobs` and `/report` endpoints to v2 in accordance with the new upgrade guidelines.
* Completed all tasks mentioned in #2724 .
* Updated `openapiv2.yaml` to have all documentation changes.
* Modified models & unit tests to make them version aware.
* Open the `openapiv2.yaml` file in Swagger Editor and test all the updated endpoints for v2 specific responses. All function as intended.
* Execute unit tests, all pass without any issues.
CC @GMishx @shaheemazmalmmd @dushimsam
=> feat(api): Upgrade Jobs & Report APIs to Version 2

src/lib/php/Dao/SysConfigDao.php, src/www/ui/api/Controllers/CopyrightController.php, src/www/ui/api/Controllers/CustomiseController.php, src/www/ui/api/Controllers/SearchController.php, src/www/ui/api/documentation/openapiv2.yaml
This PR aims to upgrade the `/search` , `/copyright`  and `/admin` endpoints to v2 in accordance with the new upgrade guidelines.
* Updated `/search` GET, `/uploads/{id}/item/{itemId}/{xx}` GET, `/customise` GET endpoints.
* Updated `openapiv2.yaml` to have all documentation changes.
* Open the `openapiv2.yaml` file in Swagger Editor and test all the updated endpoints for v2 specific responses. All function as intended.
* Execute unit tests, all pass without any issues.
CC @GMishx @shaheemazmalmmd @dushimsam
=> feat(api): Upgrade Search, Copyright & Admin APIs to Version 2

.github/workflows/release-publish.yml, cmake/FoPackaging.cmake, debian/control, src/copyright/mod_deps, src/decider/ui/template/agent_decider.html.twig, src/nomos/mod_deps, src/ojo/mod_deps, src/scancode/mod_deps, utils/fo-installdeps
Add support for ubuntu jammy 22.04 for fossology.
added noble support in installdeps file and many other.
* Test every functionality of fossology using source install as well as debian install in Ubuntu 24.04
<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2760"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(ubuntu): support ubuntu noble 24.04 for fossology

utils/automation/.github-workflow.yml, utils/automation/FoScanner/CliOptions.py, utils/automation/FoScanner/Utils.py, utils/automation/fossologyscanner.py
Add custom keywords.conf file by setting env varaible in GH Actions or GitlabCI.
* Add `--keyword-conf` CLI argument to fossologyscanner script.
* Script takes the file, validates it, and copies it to desired location checked by scanner.
* Add helper functions to check the validity of input file as the scanner breaks if invalid file is given.
* Modifies GH Actions workflow file to use qemu for cross platform support.
* Take new workflow file for GH Actions. Previous works fine with GitalbCI
* Use [this](https://hub.docker.com/layers/rjknightmare/fo-ci-test/latest/images/sha256-ac72768b8c4383a4aca05a50cd53ae427db9645b42619ad82b53e38b3b876b38?context=repo) test docker image (`rjknightmare/fo-ci-test:latest`) for testing.
* Create a new `keyword.conf` file according to this …
=> feat(automation) : Add custom keyword.conf file

utils/automation/.github-workflow.yml, utils/automation/FoScanner/CliOptions.py, utils/automation/fossologyscanner.py
Read custom allowlist passed by the user and populate the allowlist dict using it. Deprecation warning is printed if project is using whitelist.json.
* Add --allowlist-path CLI argument.
* Add deprecation warning if `whitelist.json` is being used.
Build new docker image using `Dockerfile.ci` file.
CC @GMishx @shaheemazmalmmd @Kaushl2208 @avinal
=> feat(automation): Add custom allowlist.json

src/cli/fo_import_licenses.php, src/lib/php/Application/LicenseCsvExport.php, src/lib/php/Application/LicenseCsvImport.php, src/lib/php/Application/ObligationCsvExport.php, src/lib/php/Application/ObligationCsvImport.php, src/lib/php/Application/test/LicenseCsvImportTest.php, src/www/ui/page/AdminAllLicenseToJSON.php, src/www/ui/page/AdminLicenseFromCSV.php, src/www/ui/page/AdminLicenseToJSON.php, src/www/ui/page/AdminObligationFromCSV.php, src/www/ui/page/AdminObligationToJSON.php, src/www/ui/template/admin_license_from_csv.html.twig
Introduce json format to export and import of licenses and obligations.
* Export licenses through JSON.
* Edit few licenses and import them through same JSON file.
=> feat(licenses): introduce JSON format export and import of licenses and obligations

src/buckets/ui/agent-bucket.php, src/copyright/ui/agent-copyright.php, src/copyright/ui/agent-ecc.php, src/copyright/ui/agent-ipra.php, src/copyright/ui/agent-keyword.php, src/lib/php/common-agents.php, src/mimetype/ui/agent-mimetype.php, src/monk/ui/agent-monk.php, src/nomos/ui/agent-nomos.php, src/ojo/ui/agent-ojos.php, src/pkgagent/ui/agent-pkgagent.php, src/reso/ui/ResoAgentPlugin.php, src/scanoss/ui/agent-scanoss.php, src/softwareHeritage/ui/agent-shagent.php, src/www/ui/ajax-upload-agents.php
add tooltips and description to individual agents.
* Install fossology and check if tooltip works in all upload pages.
=> feat(upload): add tooltips and description to individual agents

src/nomos/agent/json_writer.c
* Add start, end and len information about scan results to nomos's json output.
* Need to give `-S` flag along with `-J` flag to populate the output.
Add new function in `json_writer.c` to populate info in json output.
Rebuild nomos scanner
=> feat(nomos): Add start, end, len to nomos JSON output.

src/scanoss/agent/main.c, src/scanoss/agent/snippet_scan.c, src/www/ui/ui-view-info.php
Fixes a weird logged error on the upload
- Fixes the error reported on log file
"row number 0 is out of range 0..-1"
- Restore snippet matching view (some external modification on the code leads to not showing the table)
- Removes agent temp folder used on a scan
- Fixed some conditions that could lead to segfault
- Upload https://github.com/fossology/atarashi/ master.
- Schedule SCANOSS agent.
- Go to upload logs
- Check that "row number 0 is out of range 0..-1" does not exist anymore
=> Scanoss qg/2668/row number out of range

cmake/FoPackaging.cmake
Add packaging info for compatibility agent.
Added variables for compatibility agent in cmake.
Create and install debian packages.
=> chore(package): add compatibility agent deb package

src/www/ui/page/AdviceLicense.php, src/www/ui/template/advice_license.html.twig
Add column "Created By" to Candidate Licenses Table.
=> fix(created_by): Add created by column to candidate license table

src/www/ui/scripts/change-license-browse.js, src/www/ui/scripts/change-license-common.js, src/www/ui/template/change_license_modal.html.twig, src/www/ui/template/upload_permissions.html.twig
Add loader to upload permission and edit decision page
Changes are made on two pages to add loader:
- Upload Permission Page
- Edit decision
CC: @GMishx @shaheemazmalmmd
=> fix(ui): Add loader to upload permission and edit decision page

src/scanoss/agent/snippet_scan.c
Add heartbeat to scanoss agent
https://github.com/fossology/fossology/issues/2855
CC: @shaheemazmalmmd
=> fix(scanoss): Add heartbeat to scanoss agent

src/www/ui/template/ui-clearing-view.js.twig
Add exactmatch to license search in add a new license table in license browse page.
CC: @shaheemazmalmmd
=> Fix(ui): Add exactmatch to license search

src/decisionimporter/agent/DecisionImporterDataCreator.php, src/decisionimporter/agent/DecisionImporterIdFetcher.php
Fix decisionimporter agent to handle missing pfiles from FOSSology dump report.
closes #2872 
https://github.com/fossology/fossology/issues/2872
=> fix(decisionimporter): fix agent to handle missing pfile

src/www/ui/change-license-bulk.php, src/www/ui/scripts/change-license-browse.js, src/www/ui/template/browse.html.twig, src/www/ui/template/browse_file.js.twig, src/www/ui/template/change_license_modal.html.twig
make the bulk option available for multiple folders
* Schedule a bulk scan with multiple folders in tree view
=> feat(treeview): make the bulk option availible for multiple folders

src/lib/php/Dao/ShowJobsDao.php, src/lib/php/Dao/test/ShowJobsDaoTest.php
Fixed a wrong pagination for the page `Show Jobs (/repo/?mod=showjobs)` if the currently selected group does not have access to all the uploads of the previous jobs.
This resulted in the following problem:
The issue is that the `totalPages` are always calculated for all `jobs` from last month, but the jobs itself can be much less if the currently selected group does not have access to the uploads of the jobs. Also if the uploads are not accessible, it can result to pages displaying not `maxJobsPerPage` (currently 10), but instead one page can display 4 jobs, the other 10, the next 8 and so on. This is also caused by the fact the upload accessible check is made after getting 10 results from the database.
Also fixed a bug, which caused the jobs are always visible if a specific upload is …
=> Fix(ui): Fixed wrong pagination for 'Show Jobs' page & missing upload accessible check

src/lib/php/Dao/SearchHelperDao.php, src/www/ui/search.php
Refactor Search page to include pagination in both UI and database query.
CC: @shaheemazmalmmd @GMishx
=> refactor(search): refactor search page

.github/dependabot.yml
Add `dependabot.yml` to update docker and github-action dependencies.
Add `dependabot.yml`
=> chore(dependabot): add dependabot.yml

src/lib/php/Dao/CompatibilityDao.php, src/www/ui/page/AdminLicenseCompatibilityRules.php, src/www/ui/template/admin_license_compatibility_rules.html.twig, src/www/ui/template/admin_license_compatibility_rules.js.twig
Add server side pagination to compatibility rule page
CC: @shaheemazmalmmd @GMishx
=> enhancement(ui): add server side pagination to compatibility rule page

utils/automation/FoScanner/CliOptions.py, utils/automation/FoScanner/FormatResults.py, utils/automation/fossologyscanner.py
Add subdirectory Scan feature.
Add new CLI Argument `scan-dir` and `--dir-path`
Build new image and scan using `scan-dir` and `--dir-path` argument (not scanning in repo mode)
CC @GMishx @shaheemazmalmmd @Kaushl2208 @avinal
=> feat(dir_scan): Scan a subdirectory inside CI

CHANGELOG.md, debian/changelog
Changelog for release 4.5.0-rc1
=> feat(changelog): add changelog for release 4.5.0-rc1

src/decider/agent/DeciderAgent.php, src/lib/php/BusinessRules/ClearingDecisionProcessor.php, src/lib/php/Data/Clearing/ClearingEventTypes.php
Conclusion string -> "Auto Concluded"  is added if auto-conclusion is done
on upload
1.  ClearingEventType AUTO is added
2. ClearingEventType AUTO with "Auto Concluded" string
3. makeDecisionFromLastEvents function is updated to check if $autoConcluded flag is true
1. Create new LicenseType "auto concluded" in Admin > Customize
2. Convert a license to "Auto Conclude" type
3. Upload a new file, with auto-conclusion type: "auto concluded"
4. In License Clearing Screen, the file containing license should show something:
=> feat(conclusionString):  Update Conclusion String

cmake/FoPackaging.cmake
=> fix(packaging): add required yaml dependency

utils/automation/Dockerfile.ci, utils/automation/fossologyscanner.py, utils/automation/requirements.txt
Add the ScanDeps package to Dockerfile and add requests package to `requirements.txt`.
Build a new image from the update Dockerfile.ci
fixes #2911 
CC @GMishx
=> fix(scanner): Fix broken Scanner Image

CHANGELOG.md, debian/changelog
=> feat(changelog): add change log for release 4.5

src/lib/php/libschema.php
Drop view SQL query might fail if the view doesnt exist.
dropViews() --> Function runs a drop query, which fails if the view doesnt exist.
CC: @shaheemazmalmmd
=> fix(db): Check on drop view if exists

CHANGELOG.md, debian/changelog
=> feat(changelog): add changelog for release 4.5

.github/workflows/static-checks.yml, commitlint.config.mjs
Added a commit linter, which can follow certain commit guidelines from the community.
1. Added a Lint commit stage
2. Added a config file, which follows few of the requirements with commit guidelines. (more can be added in future)
3. Added DCO check 
cc: @GMishx @shaheemazmalmmd
=> feat(workflow): Commit Linting Stage in Static Checks

src/decisionimporter/agent/DecisionImporterAgent.php
fix(decisionimport): fix incorrect parsing of argument
https://github.com/fossology/fossology/issues/3018
CC: @JanAltenberg @GMishx @shaheemazmalmmd @Kaushl2208
=> fix(decisionimport): fix incorrect parsing of argument

CHANGELOG.md, debian/changelog
=> feat(changelog): add change log for new release 4.5.1

src/www/ui/admin-folder-size.php, src/www/ui/template/admin-folder-size-form.html.twig
Add CSV and JSON export functionality in folder dashboard
=> feat(ui): add CSV and JSON export functionality in folder dashboard

src/lib/php/Dao/UserDao.php, src/www/ui/page/AdminGroupEdit.php, src/www/ui/template/admin_group_edit.html.twig
add option to edit group-name
* Create new groups.
* Edit/rename them using admin > Groups > edit group.
=> feat(group): add option to edit groupname

src/nomos/agent/generator/STRINGS.in, src/nomos/agent/parse.c
Fix regex for LGPL and CC0
CC: @shaheemazmalmmd @GMishx @Kaushl2208
=> fix(nomos): fix regex for LGPL and CC0

src/nomos/agent/generator/STRINGS.in, src/nomos/agent/parse.c, src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan, src/nomos/agent_tests/testdata/NomosTestfiles/AOM/AOM.txt
add and fix footprints for licenses identified by nomos.
=> fix(nomos): fix footprints for licenses

src/reportImport/agent/ReportImportAgent.php, src/reportImport/ui/ReportImportAgentPlugin.php, src/www/ui/admin-folder-size.php
Parse argument correctly for reportimport agent.
Closes: https://github.com/fossology/fossology/issues/3096
CC: @shaheemazmalmmd @GMishx @Kaushl2208 @JanAltenberg
=> fix(reportimport): parse argument correctly

utils/automation/FoScanner/CliOptions.py, utils/automation/FoScanner/FormatResults.py, utils/automation/FoScanner/Packages.py, utils/automation/FoScanner/RepoSetup.py, utils/automation/FoScanner/Scanners.py, utils/automation/FoScanner/SpdxReport.py, utils/automation/FoScanner/Utils.py, utils/automation/ScanDeps/Downloader.py, utils/automation/ScanDeps/Parsers.py, utils/automation/fossologyscanner.py
1. Add missing file to fix #3116
2. Optimize code for better performance.
Closes #3116
Sample run of pipeline: https://github.com/GMishx/snap-to-bucket/actions/runs/16744379992
Reduced the run time of the script from 6m 50s to 3m 25s
=> perf(automation): optimize code for fossologyscanner
